const A=require('node:assert/strict'),D=require('./engine.js'),{Game,stats,slash,blade,body,neutral,CLASSES}=D;
let count=0;function test(n,fn){try{fn();count++;console.log('PASS',n);}catch(e){console.error('FAIL',n,e.stack);process.exitCode=1;}}
const cmd=o=>({...neutral(),...o}),make=o=>{const g=new Game({mode:'local',ai:false,...o});g.start();return g;},tick=(g,n,inputs)=>{for(let i=0;i<n;i++)g.step(1/600,inputs||[cmd(),cmd({aim:Math.PI})]);},sec=(g,t,ins)=>tick(g,Math.ceil(t*600),ins);
function pair(g,d=110){g.fighters[0].x=570;g.fighters[1].x=570+d;}
function active(g,i,angle=0){const f=g.fighters[i];f.attackId=++g.attackCounter;g.setState(f,'active',stats(f).active);f.stateTime=f.duration/2;f.attackAim=angle;f.attackHit=false;}
function specialGame(kind,other='knight',o={}){const g=make({characters:[kind,other],rules:{specials:true},...o});g.fighters[0].specialCharge=g.rules.specialCooldown;return g;}
test('V4 defaults: air dash, 400ms guard, 25% faster class timings',()=>{const r=D.cleanRules();A(r.airDash);A(!r.specials);A.equal(r.parryWindow,400);A.equal(r.dashCount,1);A.equal(r.specialCooldown,15);A.equal(stats('knight').startup,.19/1.25);A.equal(stats('assassin').recovery,.25/1.25);const g=make();g.parry(0);A.equal(g.fighters[0].duration,.4);});
for(const kind of Object.keys(CLASSES))test(kind+' still kills in one visible cut in all directions',()=>{for(let i=0;i<8;i++){const g=make({characters:[kind,'knight']}),[a,b]=g.fighters,angle=i*Math.PI/4,r=stats(a).reach*.92;a.x=640;a.y=400;b.x=a.x+Math.cos(angle)*r;b.y=a.y+Math.sin(angle)*r;active(g,0,angle);g.resolveCombat();A(b.dead,kind+' '+i);A.equal(g.score[0],1);A(!('hp'in a));}});
test('feint accepts whole startup and first 60ms, with no contact',()=>{for(const time of[0,.025,.059]){const g=make({rules:{attackSpeed:.5}}),f=g.fighters[0];g.attack(0);g.setState(f,'active',.2);f.stateTime=time;A(g.parry(0));A.equal(f.state,'feintRecovery');A.equal(slash(f).points.length,0);}const g=make();g.attack(0);g.fighters[0].stateTime=.15;A(g.parry(0));});
test('late feint, completed contact, recovery and cooldown refuse cancellation',()=>{const g=make(),f=g.fighters[0];active(g,0);f.stateTime=.061;A(!g.parry(0));f.stateTime=.02;f.attackHit=true;A(!g.parry(0));g.setState(f,'recovery',.3);A(!g.parry(0));g.setState(f,'idle');g.attack(0);A(g.parry(0));A(!g.attack(0));sec(g,.16);g.attack(0);A(!g.parry(0));});
test('one ground launch consumes the default aerial use',()=>{const g=make(),f=g.fighters[0];f.aim=-Math.PI/2;A(g.dash(0));sec(g,.3,[cmd({aim:-Math.PI/2}),cmd()]);A(!f.grounded);A.equal(f.airDashes,1);A(!g.dash(0));});
test('five consecutive upward dashes consume five charges without recovery between',()=>{const g=make({rules:{dashCount:5}}),f=g.fighters[0];const y=f.y;for(let i=0;i<5;i++){f.aim=-Math.PI/2;A(g.dash(0),i);tick(g,85,[cmd({aim:-Math.PI/2}),cmd()]);if(i<4)A.equal(f.state,'idle');}A(f.y<y-600);A.equal(f.airDashes,5);A.equal(f.dashCharges,0);A(!g.dash(0));});
test('landing resets flight limit but does not replenish dash charges',()=>{const g=make({rules:{dashCount:5,dashCooldown:5000}}),f=g.fighters[0];f.dashCharges=1;f.dashCooldown=5;f.airDashes=5;f.y=609;f.grounded=false;f.vy=500;tick(g,5);A(f.grounded);A.equal(f.airDashes,0);A.equal(f.dashCharges,1);});
test('charges refill one by one; disabling air dash works',()=>{const g=make({rules:{dashCount:3,dashCooldown:200,airDash:false}}),f=g.fighters[0];f.dashCharges=0;f.dashCooldown=.2;sec(g,.21);A.equal(f.dashCharges,1);sec(g,.21);A.equal(f.dashCharges,2);f.grounded=false;A(!g.dash(0));});
test('physical milliseconds apply exactly to recovery, cooldown and stun',()=>{const g=make({rules:{parryWindow:400,parryRecovery:720,dashRecovery:210,dashCooldown:1230,stun:880}}),f=g.fighters[0];g.parry(0);A.equal(f.parryCooldown,1.12);sec(g,.405);A.equal(f.state,'parryRecovery');A.equal(f.duration,.72);g.setState(f,'idle');A(g.dash(0,1));A.equal(f.dashCooldown,1.23);sec(g,.15);A.equal(f.duration,.21);});
test('public limits, arbitrary special recharge and experimental values',()=>{const r=D.cleanRules({gravity:20,jump:0,speed:200,specialCooldown:999});A.equal(r.gravity,5);A.equal(r.jump,.1);A.equal(r.speed,3);A.equal(r.specialCooldown,999);const g=make({experimental:true,rules:{speed:200,attackSpeed:100,gravity:10,dashCount:20,mapSize:10}});A.equal(g.rules.speed,200);A.equal(g.rules.attackSpeed,100);A.equal(g.rules.dashCount,20);A(g.map.platforms.length<400);});
test('special starts empty, recharges in 15s, and resets every round',()=>{const g=make({rules:{specials:true}}),f=g.fighters[0];A(!g.special(0));sec(g,14.9);A(f.specialCharge<15);A(!g.special(0));sec(g,.11);A(g.special(0));g.finish(0,'test');sec(g,1.3);A(g.fighters[0].specialCharge<.2);});
test('specials disabled cannot activate even if charged',()=>{const g=make();g.fighters[0].specialCharge=999;A(!g.special(0));});
test('knight absorbs one lethal strike, then is vulnerable and loses parry',()=>{const g=specialGame('knight'),[a,b]=g.fighters;pair(g);g.special(0);active(g,1,Math.PI);g.resolveCombat();A(!a.dead);A.equal(a.ultMode,'');A.equal(a.parryLock,10);A(!g.parry(0));A.equal(b.attackHit,true);active(g,1,Math.PI);g.resolveCombat();A(a.dead);A.deepEqual(g.score,[0,1]);});
test('shield expiry starts 10s penalty; recharge waits for it',()=>{const g=specialGame('knight'),f=g.fighters[0];g.special(0);sec(g,10.01);A(f.parryLock>9.98);A.equal(f.specialCharge,0);sec(g,10.01);A.equal(f.parryLock,0);A(f.specialCharge>0);A(g.parry(0));});
test('shield does not prevent fatal falls',()=>{const g=specialGame('knight');g.special(0);g.fighters[0].y=g.map.deathY+10;g.fighters[0].grounded=false;sec(g,.2);A(g.fighters[0].dead);});
test('lance special kills through guard',()=>{const g=specialGame('lancer'),[a,b]=g.fighters;pair(g,195);a.aim=0;g.special(0);g.parry(1);sec(g,.4);A(b.dead);A(!g.events.some(e=>e.type==='parry'));});
test('lance special ignores clash; enemy shield absorbs it once',()=>{for(const shield of[false,true]){const g=specialGame('lancer'),[a,b]=g.fighters;pair(g,190);g.special(0);g.setState(a,'ultCharge',1e6);a.attackAim=0;if(shield){b.specialCharge=15;g.special(1);}else active(g,1,Math.PI);g.resolveCombat();A(!g.events.some(e=>e.type==='clash'));A.equal(b.dead,!shield);if(shield){A.equal(b.parryLock,10);A(a.attackHit);}}});
test('lance charge cannot steer, dash, jump or parry; wall stops it',()=>{const g=specialGame('lancer'),f=g.fighters[0];g.fighters[1].y=250;g.special(0);sec(g,.4,[cmd({move:-1,aim:Math.PI}),cmd()]);A.equal(f.state,'ultCharge');A(f.vx>0);A(!g.dash(0)&&!g.parry(0)&&!g.attack(0));sec(g,.3,[cmd({jump:true,jumpHeld:true,move:-1,aim:Math.PI}),cmd()]);A.equal(f.ultMode,'');A(g.events.some(e=>e.type==='chargeStop'));});
test('lance missed charge can run off a map without a wall',()=>{const g=specialGame('lancer','knight',{mapId:'bamboo'});g.fighters[1].y=200;g.special(0);sec(g,1.5);A(g.fighters[0].dead);A.equal(g.score[1],1);});
test('assassin projectile kills at range and removes the held dagger',()=>{const g=specialGame('assassin'),f=g.fighters[0];pair(g,400);g.special(0);sec(g,.21);A.equal(f.ultMode,'unarmed');A(f.dagger);A(!g.attack(0));sec(g,.4);A(g.fighters[1].dead);});
test('projectile parry drops dagger near defender and leaves both alive',()=>{const g=specialGame('assassin');pair(g,330);g.special(0);g.parry(1);sec(g,.45);A(!g.fighters[1].dead);A(g.events.some(e=>e.type==='parry'&&e.projectile));A.equal(g.fighters[0].dagger.mode,'dropped');A(Math.abs(g.fighters[0].dagger.x-g.fighters[1].x)<45);});
test('unarmed assassin can parry, dash and kick but cannot attack',()=>{const g=specialGame('assassin'),f=g.fighters[0];g.special(0);sec(g,.45);A.equal(f.state,'idle');A(!g.attack(0));A(g.parry(0));g.setState(f,'idle');A(g.dash(0,1));f.dashRemaining=0;g.setState(f,'idle');A(g.kick(0));});
test('dagger pickup restores attack; lost dagger returns after two seconds',()=>{const g=specialGame('assassin'),f=g.fighters[0];f.ultMode='unarmed';f.dagger={x:-10,y:100,vx:-100,vy:0,mode:'flying',time:0,safe:{x:500,y:605},pickup:0};g.updateDaggers(.01);A.equal(f.dagger.mode,'lost');g.updateDaggers(1.99);A.equal(f.dagger.mode,'lost');g.updateDaggers(.02);A.equal(f.dagger.mode,'dropped');f.x=f.dagger.x;f.y=f.dagger.y+5;g.updateDaggers(.21);A.equal(f.dagger,null);A.equal(f.ultMode,'');A(g.attack(0));});
test('swordsman charged attack kills through parry',()=>{const g=specialGame('swordsman');pair(g,150);g.special(0);g.attack(0);g.parry(1);sec(g,.3);A(g.fighters[1].dead);});
test('swordsman whiff and clash consume power and block parry for 10s',()=>{for(const clash of[false,true]){const g=specialGame('swordsman'),f=g.fighters[0];g.special(0);g.attack(0);sec(g,.2);A.equal(f.ultMode,'edgeStrike');if(clash){pair(g,215);active(g,1,Math.PI);g.resolveCombat();A(g.events.some(e=>e.type==='clash'));}else sec(g,.13);A.equal(f.ultMode,'');A(f.parryLock>9.9);A(!g.parry(0));}});
test('startup feint preserves armed sword; active feint spends its strike',()=>{const g=specialGame('swordsman'),f=g.fighters[0];g.special(0);g.attack(0);g.parry(0);A.equal(f.ultMode,'edge');sec(g,.5);g.attack(0);sec(g,.2);A(g.parry(0));A.equal(f.ultMode,'');A.equal(f.parryLock,10);});
test('reaper size and real reach grow, shrink, then normalize',()=>{const g=specialGame('reaper'),f=g.fighters[0],base=stats(f).reach;g.special(0);A.equal(stats(f).reach,base*1.4);A.equal(stats(f).length,CLASSES.reaper.length*1.4);sec(g,10.01);A.equal(f.ultMode,'reaperWeak');A.equal(stats(f).reach,base*.6);A.equal(f.specialCharge,0);sec(g,10.01);A.equal(f.ultMode,'');A.equal(stats(f).reach,base);A(f.specialCharge>0);});
for(const kind of Object.keys(CLASSES))test(kind+' special snapshots resume deterministically',()=>{const a=specialGame(kind,'knight',{mapId:'tower',rules:{specials:true,dashCount:5,specialCooldown:.3}}),b=make();a.special(0);sec(a,.1);A(b.loadSnapshot(a.snapshot()));for(let i=0;i<1900;i++){const ins=[cmd({move:i<150?1:0,aim:i%300/300,attack:i%211===0,dash:i%307===0,special:i%499===0}),cmd({aim:Math.PI,parry:i%200===0})];a.step(1/600,ins);b.step(1/600,ins);}A.deepEqual(a.snapshot(),b.snapshot());});
test('admin changing map/classes/rules preserves score and resets hazards',()=>{const g=make();g.score=[2,3];g.adminApply({action:'apply',mapId:'tower',characters:['reaper','assassin'],rules:{speed:200,attackSpeed:100,specials:true,specialCooldown:.5},positions:[{x:500,y:600},{}]});A.equal(g.mapId,'tower');A.equal(g.rules.speed,200);A.deepEqual(g.score,[2,3]);A.equal(g.fighters[0].kind,'reaper');A.equal(g.fighters[0].x,500);g.adminApply({action:'refill'});A.equal(g.fighters[0].specialCharge,.5);const h=make();h.loadSnapshot(g.snapshot());A.equal(h.rules.speed,200);});
test('regular direction guard, clash and input buffer still work',()=>{const g=make();pair(g);g.parry(1);active(g,0);g.resolveCombat();A(g.events.some(e=>e.type==='parry'));const h=make();pair(h,190);active(h,0);active(h,1,Math.PI);h.resolveCombat();A(h.events.some(e=>e.type==='clash'));const j=make(),f=j.fighters[0];j.setState(f,'recovery',.3);f.stateTime=.24;j.step(1/600,[cmd({attack:true}),cmd()]);A.equal(f.state,'recovery');tick(j,40);A.equal(f.state,'startup');});
test('dagger thrown next to walls stays outside and can be recovered',()=>{const g=specialGame('assassin','knight',{mapId:'ruins'}),f=g.fighters[0];f.x=464;f.y=620;f.attackAim=0;g.throwDagger(f);A(f.dagger.x<480);A.equal(f.dagger.mode,'dropped');sec(g,.5);A.equal(f.dagger,null);A(g.attack(0));});
test('a downward throw over a pit returns to a real platform',()=>{const g=specialGame('assassin','knight',{mapId:'bridge'}),f=g.fighters[0];f.x=455;f.y=300;f.attackAim=Math.PI/2;g.throwDagger(f);const safe={...f.dagger.safe};A(g.map.platforms.some(p=>safe.x>=p.x&&safe.x<=p.x+p.w&&safe.y===p.y-5));f.dagger.mode='lost';g.updateDaggers(2.1);A.equal(f.dagger.mode,'dropped');A.equal(f.dagger.x,safe.x);A.equal(f.dagger.y,safe.y);});
console.log(count+' V4 core checks passed');
