(function(){
'use strict';
const {clamp,lerp,COLORS,blade,stats}=DuelCore,TAU=Math.PI*2;
class DuelRenderer{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.camera={x:640,y:360,zoom:1};this.previousBlades=[[],[]];this.lastRound=0;this.lastTime=0;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;}
 resize(){const b=this.canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.round(b.width*d),h=Math.round(b.height*d);if(w!==this.canvas.width||h!==this.canvas.height){this.canvas.width=w;this.canvas.height=h;}this.scale=Math.min(w/1280,h/720);this.ox=(w-1280*this.scale)/2;this.oy=(h-720*this.scale)/2;this.dpr=d;}
 screenToWorld(x,y){const r=this.canvas.getBoundingClientRect();return{x:((x-r.left)*this.dpr-this.ox)/this.scale/this.camera.zoom+this.camera.x-640/this.camera.zoom,y:((y-r.top)*this.dpr-this.oy)/this.scale/this.camera.zoom+this.camera.y-360/this.camera.zoom};}
 line(a,b,color,width=1){const c=this.ctx;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.strokeStyle=color;c.lineWidth=width;c.stroke();}
 path(pts,fill,stroke,width=1){const c=this.ctx;c.beginPath();pts.forEach((p,i)=>i?c.lineTo(p[0],p[1]):c.moveTo(p[0],p[1]));if(fill){c.closePath();c.fillStyle=fill;c.fill();}if(stroke){c.strokeStyle=stroke;c.lineWidth=width;c.stroke();}}
 ellipse(x,y,rx,ry,color){const c=this.ctx;c.beginPath();c.ellipse(x,y,Math.max(.1,rx),Math.max(.1,ry),0,0,TAU);c.fillStyle=color;c.fill();}
 background(game,t){DuelScenery.draw(this,game,t);}
 platforms(game,t){DuelScenery.platforms(this,game,t);}
 fighter(f,time,w,portrait=false){DuelActors.draw(this,f,time,w,portrait);}
 sword(f,w,t,portrait=false){if(portrait||f.dead)return;const c=this.ctx,shape=DuelCore.slash(f),color=COLORS[f.color]?.hex||'#80b6ae';
  if(shape.points.length){const pts=shape.points.map(p=>[p.x,p.y]);this.path(pts,'#fff8d9');c.save();c.beginPath();pts.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.closePath();c.clip();const gradient=c.createRadialGradient(shape.origin.x,shape.origin.y,stats(f).minRange,shape.origin.x,shape.origin.y,stats(f).reach);gradient.addColorStop(0,color);gradient.addColorStop(.58,color);gradient.addColorStop(.88,'#fff6bb');gradient.addColorStop(1,'#ffffff');c.globalAlpha=.78;c.fillStyle=gradient;c.fillRect(f.x-250,f.y-DuelCore.C.bodyCenter-250,500,500);c.restore();}
  if(f.state==='startup'){const aim=f.attackAim,rad=stats(f).reach,p=clamp(f.stateTime/f.duration,0,1);c.globalAlpha=.25+p*.5;this.line({x:f.x+Math.cos(aim)*30,y:f.y-DuelCore.C.bodyCenter+Math.sin(aim)*30},{x:f.x+Math.cos(aim)*Math.min(rad,53),y:f.y-DuelCore.C.bodyCenter+Math.sin(aim)*Math.min(rad,53)},'#fff2c4',2);c.globalAlpha=1;}
  if(f.state==='parry'){const a=f.guard==='high'?-Math.PI/2:f.guard==='low'?Math.PI/2:f.guardFacing>0?0:Math.PI,remaining=clamp(1-f.stateTime/f.duration,0,1);c.beginPath();c.arc(f.x,f.y-DuelCore.C.bodyCenter,47,a-.66,a+.66);c.strokeStyle='#9e895c88';c.lineWidth=3;c.stroke();c.beginPath();c.arc(f.x,f.y-DuelCore.C.bodyCenter,47,a-.66,a-.66+1.32*remaining);c.strokeStyle='#fff0af';c.lineWidth=3;c.stroke();c.font='9px monospace';c.textAlign='center';c.fillStyle=DuelScenery.THEMES[this.lastTheme]?.dark?'#f4e6bc':'#6e5733';const label=f.guard==='high'?'ALTO':f.guard==='low'?'BAIXO':'NORMAL';c.fillText(label+(f.duration>.3?' · '+Math.max(0,f.duration-f.stateTime).toFixed(1).replace('.',',')+' s':''),f.x,f.y-144);}
  if(!f.dead){c.globalAlpha=.65;this.ellipse(f.x+Math.cos(f.aim)*47,f.y-DuelCore.C.bodyCenter+Math.sin(f.aim)*47,1.8,1.8,color);c.globalAlpha=1;}
 }
 render(game,effects,t){if(this.lastTheme!==game.mapId){this.lastTheme=game.mapId;if(this.canvas.parentElement){this.canvas.parentElement.dataset.theme=game.mapId;this.canvas.parentElement.classList.toggle('dark-arena',!!DuelScenery.THEMES[game.mapId]?.dark);}}this.resize();const c=this.ctx,dt=clamp(t-this.lastTime,0,.05);this.lastTime=t;if(this.lastRound!==game.round){this.previousBlades=[[],[]];this.actorHistory=[];this.lastRound=game.round;}const alive=game.fighters.filter(f=>!f.dead),fs=alive.length?alive:game.fighters,minX=Math.min(...fs.map(f=>f.x))-210,maxX=Math.max(...fs.map(f=>f.x))+210,minY=Math.min(...fs.map(f=>f.y))-235,maxY=Math.max(...fs.map(f=>f.y))+95,z=clamp(Math.min(1280/(maxX-minX),720/(maxY-minY)),.32,1.12),half=640/z,tx=game.map.width<half*2?game.map.width/2:clamp((minX+maxX)/2,half,game.map.width-half),ty=Math.min(game.map.height-210/z,(minY+maxY)/2),smooth=this.snapCamera?1:1-Math.exp(-dt*7);this.camera.zoom=lerp(this.camera.zoom,z,smooth);this.camera.x=lerp(this.camera.x,tx,smooth);this.camera.y=lerp(this.camera.y,ty,smooth);this.snapCamera=false;
  c.setTransform(1,0,0,1,0,0);c.fillStyle='#d7ceba';c.fillRect(0,0,this.canvas.width,this.canvas.height);c.setTransform(this.scale,0,0,this.scale,this.ox,this.oy);this.background(game,t);c.save();c.beginPath();c.rect(0,0,1280,720);c.clip();const shake=this.reduced?0:effects.shake||0;c.translate(640+(Math.random()-.5)*shake,360+(Math.random()-.5)*shake);c.scale(this.camera.zoom,this.camera.zoom);c.translate(-this.camera.x,-this.camera.y);this.platforms(game,t);for(const f of game.fighters){if(!f.grounded&&!f.dead){const surfaces=game.map.platforms.filter(p=>p.y>=f.y&&f.x>=p.x&&f.x<=p.x+p.w).sort((a,b)=>a.y-b.y);if(surfaces.length){const ground=surfaces[0],height=ground.y-f.y;this.ellipse(f.x,ground.y+3,Math.max(9,27-height*.035),3,'#213f331d');}}const w=blade(f);this.fighter(f,t,w);}for(const f of game.fighters)this.sword(f,blade(f),t);for(const p of effects.particles||[]){c.globalAlpha=p.life/p.maxLife;this.line({x:p.x-p.vx*.015,y:p.y-p.vy*.015},p,p.color,p.size);}c.globalAlpha=1;for(const cut of effects.cuts||[]){c.globalAlpha=cut.life/cut.maxLife;this.line({x:cut.x-90,y:cut.y+60},{x:cut.x+90,y:cut.y-60},'#fff5d6',3);}c.globalAlpha=1;c.restore();if(effects.flash){c.fillStyle='#fff2d6';c.globalAlpha=Math.min(.4,effects.flash*2.5);c.fillRect(0,0,1280,720);c.globalAlpha=1;}}
 drawPortrait(canvas,kind,side=0,color,time=0){const old=this.ctx;this.ctx=canvas.getContext('2d');const c=this.ctx;c.clearRect(0,0,canvas.width,canvas.height);c.save();c.imageSmoothingEnabled=false;const f={id:side,kind,color:color||'jade',x:0,y:0,vx:0,vy:0,aim:-.15,facing:1,attackAim:0,state:'idle',stateTime:0,duration:0,grounded:true,anim:0,landing:0,dead:false,dashX:0,dashY:0,move:0};const w=blade(f),pts=[{x:-65,y:-152},{x:35,y:7},...w.segments.flatMap(s=>[s.a,s.b]),...(w.shaft?[w.shaft.a,w.shaft.b]:[])],minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxY=Math.max(...pts.map(p=>p.y)),scale=Math.min((canvas.width-10)/(maxX-minX),(canvas.height-10)/(maxY-minY));c.translate(canvas.width/2-(minX+maxX)/2*scale,canvas.height-5-maxY*scale);c.scale(scale,scale);this.fighter(f,time,w,true);c.restore();this.ctx=old;}
}
window.DuelRenderer=DuelRenderer;
})();
