const fs=require('fs'),p=__dirname+'/shell.html';let s=fs.readFileSync(p,'utf8');function r(a,b){if(!s.includes(a))throw Error('missing '+a);s=s.replace(a,b);}
s=s.replaceAll('um-corte-v43','um-corte-v5').replaceAll('UM-CORTE-V43','UM-CORTE-V5');
r('UM CORTE <em>IV</em><span>V4.3 · AFINADO PARA O DUELO.','UM CORTE <em>V</em><span>V5 · O INSTANTE QUE DECIDE.');
r('esta versão V4.3','esta versão V5');r('id="settings-button" class="quiet">CONTROLES','id="settings-button" class="quiet">OPÇÕES');
r('<button id="settings-button"','<button id="session-button" class="quiet">SESSÃO</button><button id="settings-button"');
r('<div id="rules-grid"',`<div class="chaos-settings"><label for="chaos-mode">MODO CAOS</label><select id="chaos-mode"><option value="off">DESLIGADO</option><option value="normal">CAOS · um modificador por round</option><option value="ultra">CAOS ULTRA · modificadores acumulam</option></select><small>O sorteio é igual para os dois. Suas regras base continuam preservadas. No Ultra, modificadores compatíveis se acumulam até esgotar o conjunto.</small></div><div id="rules-grid"`);
r('<div id="countdown"',`<div id="chaos-active" class="chaos-active" hidden></div><div id="chaos-intro" class="chaos-intro" hidden><span>MODIFICADOR DO ROUND</span><strong id="chaos-title"></strong><small id="chaos-subtitle"></small></div><button id="highlight-button" class="highlight-button" hidden>★ MOMENTO DECISIVO · REVER ÚLTIMO INSTANTE</button><div id="countdown"`);
r('<button id="match-menu"','<button id="match-stats" class="secondary">ESTATÍSTICAS DA SESSÃO</button><button id="match-menu"');
r('<h2>Controles.</h2>','<h2>Seu jogo.</h2>');
r('<div class="binding-head">',`<div class="graphics-settings"><label>QUALIDADE GRÁFICA<select id="graphics-quality"><option value="low">Baixo</option><option value="medium">Médio</option><option value="high">Alto</option></select></label><label class="check"><input id="graphics-shadows" type="checkbox" checked> Sombras</label><small>Alto: iluminação completa e partículas ambientais. Sombras independem da qualidade. Estes ajustes afetam apenas seu visual e ficam salvos neste navegador.</small></div><div class="binding-head">`);
r('<dialog id="special-intro"',`<dialog id="session-stats" class="session-dialog"><div class="menu-heading"><div><span class="eyebrow">SÓ MAIS UMA.</span><h2>Histórias do duelo.</h2></div><button id="session-close" class="secondary">FECHAR</button></div><p class="fine-print">Acumula pelas revanches nesta sessão. Uma nova sala reinicia os registros. Treino e replays não contam.</p><div class="session-head"><span>NA MESMA ARENA</span><b>JOGADOR 1</b><b>JOGADOR 2</b></div><div id="session-values"></div><div id="session-awards"></div><p id="session-empty" class="fine-print">Joguem mais alguns rounds para descobrir os prêmios.</p><button id="session-reset" class="text-button">ZERAR ESTATÍSTICAS E DESTAQUE</button></dialog><dialog id="special-intro"`);
r('<details open><summary>V4.3 · Ajustes, balanceamento e QoL — atual',`<details open><summary>V5 · Impacto, caos e identidade — atual</summary><p>Golpe fatal com hitstop, queda em micro câmera lenta, aproximação da câmera, som seco e breve silêncio. Causas da derrota no instante do impacto; cortes mais vivos mantendo a mesma área real de acerto. Som de passou raspando e assinaturas visuais e sonoras dos especiais.</p><p>Caos sorteia uma regra por round; Ultra acumula modificadores compatíveis. Apresentação antes de 3, 2, 1, lista compacta e sorteios sincronizados no online. O ADMIN edita regras base, com valores efetivos à vista.</p><p>Destaques opcionais guardam o melhor momento da sessão. Estatísticas atravessam revanches, com prêmios entre amigos. Iluminação dinâmica, sombras independentes e qualidade Baixo / Médio / Alto salva no navegador. Novo ferrão do Cavaleiro Vazio. Mapa aleatório sempre por último, inclusive depois de importar e criar arenas.</p></details><details><summary>V4.3 · Ajustes, balanceamento e QoL`);
r('/* RENDERER */','/* LIGHTING */</script><script>/* AUDIO */</script><script>/* SESSION */</script><script>/* RENDERER */');
s=s.replace(/<title>[^<]*<\/title>/,'<title>UM CORTE V · O instante que decide</title>');
fs.writeFileSync(p,s);
