(function(){
'use strict';const $=id=>document.getElementById(id),D=DuelCore,copy=o=>JSON.parse(JSON.stringify(o));
class MapLibrary{
 async init(){this.db=await new Promise((yes,no)=>{const q=indexedDB.open('um-corte-maps',1);q.onupgradeneeded=()=>{q.result.createObjectStore('maps',{keyPath:'id'});q.result.createObjectStore('settings');};q.onsuccess=()=>yes(q.result);q.onerror=()=>no(q.error);});this.directory=null;return await this.request('maps','getAll');}
 request(store,method,...args){return new Promise((yes,no)=>{const tx=this.db.transaction(store,method==='get'||method==='getAll'?'readonly':'readwrite'),q=tx.objectStore(store)[method](...args);let value;q.onsuccess=()=>value=q.result;tx.oncomplete=()=>yes(value);tx.onerror=()=>no(tx.error);tx.onabort=()=>no(tx.error||Error('Falha ao salvar.'));});}
 async save(map){this.cached=false;if(this.db)try{await this.request('maps','put',map);this.cached=true;}catch{}if(this.directory){const permission=await this.directory.requestPermission({mode:'readwrite'});if(permission!=='granted')throw Error('A pasta não foi autorizada; use Exportar para guardar o arquivo.');const file=await this.directory.getFileHandle(map.id+'.umcorte.json',{create:true}),writer=await file.createWritable();await writer.write(JSON.stringify(map,null,2));await writer.close();return true;}return false;}
 async folder(){if(!window.showDirectoryPicker)throw Error('Este navegador não permite escolher pasta. Use Salvar ou Exportar para baixar o arquivo.');this.directory=await showDirectoryPicker({mode:'readwrite',id:'um-corte-maps'});const maps=[];for await(const [name,handle]of this.directory.entries()){if(handle.kind!=='file'||!name.endsWith('.umcorte.json'))continue;try{const file=await handle.getFile();if(file.size>2100000)continue;const map=D.cleanMap(JSON.parse(await file.text()));maps.push(map);if(this.db)await this.request('maps','put',map);}catch{}}return maps;}
}
class DuelMapEditor{
 constructor(hooks){this.hooks=hooks;this.library=new MapLibrary();this.tool='select';this.undo=[];this.redo=[];this.images=new Map();this.testing=false;this.draft=this.blank();this.picked=null;this.drag=null;
  for(const [id,fn]of Object.entries({'editor-close':()=>this.close(),'editor-new':()=>this.load(this.blank()),'editor-open':()=>this.openTemplate(),'editor-save':()=>this.save(),'editor-export':()=>this.export(),'editor-folder':()=>this.folder(),'editor-import':()=>$('editor-file').click(),'editor-test':()=>this.test(),'editor-undo':()=>this.history(false),'editor-redo':()=>this.history(true),'editor-delete':()=>this.remove(),'editor-return':()=>this.back()}))$(id).onclick=()=>Promise.resolve().then(fn).catch(e=>this.status(e.message));
  $('editor-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2100000)throw Error('O mapa deve ter até 2 MB.');const map=D.cleanMap(JSON.parse(await file.text()));await this.cache(map);this.load(map);this.status('Mapa importado. Salve para gravar na pasta ou exporte uma cópia.');}catch(e){this.status(e.message);}e.target.value='';};
  for(const b of document.querySelectorAll('[data-tool]'))b.onclick=()=>{this.tool=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x===b));};
  for(const key of['name','width','height','theme','ground','shade','tint'])$('editor-'+key).onchange=()=>{this.remember();if(['shade','tint'].includes(key))this.draft.background[key]=key==='shade'?+$('editor-'+key).value:$('editor-'+key).value;else this.draft[key]=['width','height'].includes(key)?D.clamp(+$('editor-'+key).value||1280,key==='width'?640:360,key==='width'?3840:2160):$('editor-'+key).value;this.draw();};
  $('editor-weather').onchange=()=>{this.remember();this.draft.weather=$('editor-weather').value;this.draw();};$('editor-grid').onchange=()=>this.draw();const c=$('editor-canvas');c.onpointerdown=e=>this.down(e);c.onpointermove=e=>this.move(e);c.onpointerup=e=>this.up(e);c.onpointercancel=()=>{this.drag=null;this.draw();};c.onkeydown=e=>{if(e.key==='Delete'){e.preventDefault();this.remove();}if(e.ctrlKey&&e.code==='KeyZ'){e.preventDefault();this.history(e.shiftKey);}};$('map-editor').addEventListener('cancel',e=>{e.preventDefault();this.close();});
  for(const[k,v]of Object.entries(DuelScenery.THEMES)){if(['bells','rooftops'].includes(k))continue;const op=document.createElement('option');op.value=k;op.textContent=D.MAPS[k]?.name||k;$('editor-theme').append(op);}
  this.library.init().then(maps=>{for(const data of maps)try{D.registerMap(data);}catch{}this.hooks.changed();this.storage();}).catch(()=>this.status('Armazenamento do navegador indisponível. Você ainda pode exportar e importar arquivos.'));
 }
 blank(){return{format:'um-corte-map',version:1,id:'custom_'+crypto.randomUUID(),custom:true,decor:[],weather:'none',name:'Minha arena',description:'Arena criada no editor.',width:1280,height:720,theme:'dojo',ground:'#687767',platforms:[{x:60,y:610,w:1160,solid:true}],walls:[],spawns:[{x:320,y:610},{x:960,y:610}],background:{layers:[],shade:.2,tint:'#172838'}};}
 status(text){$('editor-status').textContent=text;}
 storage(){$('editor-storage').textContent=this.library.directory?'Pasta: '+this.library.directory.name+' · Salvar grava um .umcorte.json com as imagens.':'Cópia neste navegador + arquivo portátil. Escolha uma pasta para salvar diretamente nela; sem pasta, Salvar baixa um arquivo.';}
 open(){if(!this.hooks.allowed()){this.hooks.message('Saia da sala online antes de abrir o editor.');return;}this.hooks.clear();this.templates();this.controls();$('map-editor').showModal();this.draw();}
 close(){$('map-editor').close();this.hooks.clear();}
 templates(){const el=$('editor-template'),v=el.value;el.replaceChildren();for(const[k,m]of Object.entries(D.MAPS)){const o=document.createElement('option');o.value=k;o.textContent=(m.custom?'MEU MAPA · ':'MODELO · ')+m.name;el.append(o);}if(D.MAPS[v])el.value=v;}
 openTemplate(){const base=D.MAPS[$('editor-template').value];if(!base)return;if(base.custom)this.load(copy(base));else{const map=this.blank();Object.assign(map,{name:base.name+' · cópia',theme:base.theme||$('editor-template').value,decor:copy(base.decor||[]),weather:base.weather||'none',platforms:copy(base.platforms),walls:copy(base.walls||[]),spawns:copy(base.spawns)});map.platforms.forEach(p=>{if(p.motion&&!p.motion.route){p.motion={x:0,y:p.motion.y,period:p.motion.period/2,pause:0,route:true};}});this.load(map);}}
 load(map){this.draft=copy(map);this.picked=null;this.undo=[];this.redo=[];this.controls();this.draw();}
 controls(){this.draft.decor??=[];$('editor-weather').value=this.draft.weather||'none';for(const k of['name','width','height','theme','ground'])$('editor-'+k).value=this.draft[k];for(const k of['shade','tint'])$('editor-'+k).value=this.draft.background[k];this.properties();this.layers();this.storage();}
 remember(){this.undo.push(copy(this.draft));if(this.undo.length>25)this.undo.shift();this.redo=[];}
 history(redo){const from=redo?this.redo:this.undo,to=redo?this.undo:this.redo;if(!from.length)return;to.push(copy(this.draft));this.draft=from.pop();this.picked=null;this.controls();this.draw();}
 piece(){return this.picked?this.draft[this.picked.list][this.picked.index]:null;}
 properties(){const root=$('editor-properties');root.replaceChildren();const p=this.piece();if(!p){root.textContent='Selecione uma peça na arena.';return;}const field=(title,key,value,assign)=>{const label=document.createElement('label');label.textContent=title;const el=document.createElement('input');el.type='number';el.step='any';el.value=value;el.id='piece-'+key;el.onchange=()=>{const n=Number(el.value);if(!Number.isFinite(n))return;this.remember();assign(n);this.draw();};label.append(el);root.append(label);};for(const k of['x','y','w','h'])if(k in p)field(k.toUpperCase(),k,p[k],n=>p[k]=Math.max(0,n));if(p.motion){field('Ponto B · X','endX',p.x+p.motion.x,n=>p.motion.x=n-p.x);field('Ponto B · Y','endY',p.y+p.motion.y,n=>p.motion.y=n-p.y);field('Tempo A → B (s)','period',p.motion.period,n=>p.motion.period=n);field('Pausa nas pontas (s)','pause',p.motion.pause||0,n=>p.motion.pause=n);}if(p.fragile){field('Tempo até cair (s)','delay',p.fragile.delay,n=>p.fragile.delay=n);field('Reaparecer após (s) · 0 = próxima rodada','respawn',p.fragile.respawn,n=>p.fragile.respawn=n);}}
 layers(){const root=$('editor-layers');root.replaceChildren();for(let i=0;i<2;i++){const layer=this.draft.background.layers[i],box=document.createElement('div');box.className='editor-layer';const label=document.createElement('label');label.textContent=i?'Camada próxima':'Camada distante';const file=document.createElement('input');file.type='file';file.accept='image/png,image/jpeg,image/webp';file.id='layer-file-'+i;file.onchange=async()=>{try{if(!file.files[0])return;const image=await this.imageFile(file.files[0]);this.remember();while(this.draft.background.layers.length<=i)this.draft.background.layers.push({image,parallax:.08,opacity:1,fit:'cover'});this.draft.background.layers[i]={image,parallax:i?.18:.06,opacity:1,fit:'cover'};this.layers();this.draw();}catch(e){this.status(e.message);}};label.append(file);box.append(label);if(layer){for(const[key,title,max]of[['parallax','Profundidade',.5],['opacity','Opacidade',1]]){const l=document.createElement('label');l.textContent=title;const el=document.createElement('input');el.type='range';el.min=0;el.max=max;el.step=.01;el.value=layer[key];el.onchange=()=>{this.remember();layer[key]=+el.value;this.draw();};l.append(el);box.append(l);}const fit=document.createElement('select');fit.setAttribute('aria-label','Enquadramento da camada '+(i+1));for(const[v,n]of[['cover','Preencher'],['contain','Mostrar imagem inteira']]){const o=document.createElement('option');o.value=v;o.textContent=n;fit.append(o);}fit.value=layer.fit;fit.onchange=()=>{this.remember();layer.fit=fit.value;this.draw();};box.append(fit);const remove=document.createElement('button');remove.textContent='REMOVER IMAGEM';remove.className='text-button';remove.onclick=()=>{this.remember();this.draft.background.layers.splice(i,1);this.layers();this.draw();};box.append(remove);}root.append(box);}}
 async imageFile(file){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>15000000)throw Error('Escolha PNG, JPEG ou WebP de até 15 MB.');const bmp=await createImageBitmap(file);try{const k=Math.min(1,1600/bmp.width,1000/bmp.height),c=document.createElement('canvas');c.width=Math.max(1,Math.round(bmp.width*k));c.height=Math.max(1,Math.round(bmp.height*k));c.getContext('2d').drawImage(bmp,0,0,c.width,c.height);let result=c.toDataURL('image/webp',.84);if(result.length>900000)result=c.toDataURL('image/webp',.55);if(result.length>900000)throw Error('Imagem muito detalhada. Use uma versão menor para caber no mapa.');return result;}finally{bmp.close();}}
 point(e){const b=$('editor-canvas').getBoundingClientRect(),x=(e.clientX-b.left)/b.width*this.draft.width,y=(e.clientY-b.top)/b.height*this.draft.height,snap=v=>$('editor-grid').checked?Math.round(v/20)*20:Math.round(v);return{x:D.clamp(snap(x),0,this.draft.width),y:D.clamp(snap(y),0,this.draft.height)};}
 hit(pos){for(let i=(this.draft.decor||[]).length-1;i>=0;i--){const p=this.draft.decor[i],d=D.DECOR[p.type];if(Math.abs(pos.x-p.x)<d.w/2+6&&pos.y>=p.y-8&&pos.y<=p.y+d.h)return{list:'decor',index:i};}for(let i=this.draft.platforms.length-1;i>=0;i--){const q=this.draft.platforms[i];if(q.motion){const x=q.x+q.motion.x,y=q.y+q.motion.y;if(pos.x>=x-8&&pos.x<=x+q.w+8&&Math.abs(pos.y-y)<22)return{list:'platforms',index:i,endpoint:true};}}for(let i=0;i<2;i++)if(Math.abs(pos.x-this.draft.spawns[i].x)<22&&pos.y<=this.draft.spawns[i].y+8&&pos.y>=this.draft.spawns[i].y-110)return{list:'spawns',index:i};for(const list of['walls','platforms'])for(let i=this.draft[list].length-1;i>=0;i--){const p=this.draft[list][i];if(pos.x>=p.x&&pos.x<=p.x+p.w&&pos.y>=p.y-8&&pos.y<=p.y+(p.h||22))return{list,index:i};}return null;}
 down(e){if(e.button!==0)return;const pos=this.point(e);if(D.DECOR[this.tool]){if((this.draft.decor||[]).length>=40){this.status('Limite de 40 objetos.');return;}this.remember();this.draft.decor??=[];this.draft.decor.push({...pos,type:this.tool});this.picked={list:'decor',index:this.draft.decor.length-1};this.properties();this.draw();return;}$('editor-canvas').setPointerCapture(e.pointerId);if(this.tool.startsWith('spawn')){this.remember();const i=+this.tool.at(-1);this.draft.spawns[i]=pos;this.picked={list:'spawns',index:i};this.properties();this.draw();return;}if(this.tool==='select'){this.picked=this.hit(pos);if(this.picked){this.remember();this.drag={start:pos,original:copy(this.piece()),moving:true};}this.properties();}else this.drag={start:pos,end:pos,moving:false};this.draw();}
 move(e){if(!this.drag)return;const pos=this.point(e);if(this.drag.moving){const p=this.piece(),o=this.drag.original;if(this.picked.endpoint){p.motion.x=D.clamp(o.motion.x+pos.x-this.drag.start.x,-p.x,this.draft.width-p.x-p.w);p.motion.y=D.clamp(o.motion.y+pos.y-this.drag.start.y,-p.y,this.draft.height-p.y);this.draw();return;}p.x=D.clamp(o.x+pos.x-this.drag.start.x,0,this.draft.width-(p.w||0));p.y=D.clamp(o.y+pos.y-this.drag.start.y,0,this.draft.height-(p.h||0));}else this.drag.end=pos;this.draw();}
 up(){if(!this.drag)return;const d=this.drag;if(!d.moving){this.remember();const end=d.end||d.start,p={x:Math.min(d.start.x,end.x),y:Math.min(d.start.y,end.y),w:Math.max(40,Math.abs(end.x-d.start.x))};p.w=Math.min(p.w,this.draft.width-p.x);if(this.tool==='wall'){p.h=Math.max(40,Math.abs(end.y-d.start.y));this.draft.walls.push(p);this.picked={list:'walls',index:this.draft.walls.length-1};}else{p.solid=this.tool==='ground';if(this.tool==='moving')p.motion={x:0,y:Math.max(-160,-p.y),period:2,pause:.4,route:true};if(this.tool==='fragile')p.fragile={delay:.8,respawn:4};this.draft.platforms.push(p);this.picked={list:'platforms',index:this.draft.platforms.length-1};}}this.drag=null;this.properties();this.draw();}
 remove(){if(!this.picked||this.picked.list==='spawns')return;this.remember();this.draft[this.picked.list].splice(this.picked.index,1);this.picked=null;this.properties();this.draw();}
 draw(){const c=$('editor-canvas'),m=this.draft;c.height=Math.round(c.width*m.height/m.width);c.style.aspectRatio=m.width+'/'+m.height;const ctx=c.getContext('2d'),sx=c.width/m.width,sy=c.height/m.height;ctx.setTransform(1,0,0,1,0,0);const theme=DuelScenery.THEMES[m.theme]||DuelScenery.THEMES.dojo;ctx.fillStyle=theme.sky[0];ctx.fillRect(0,0,c.width,c.height);for(const l of m.background.layers){let img=this.images.get(l.image);if(!img){img=new Image();img.onload=()=>this.draw();img.src=l.image;this.images.set(l.image,img);}if(img.complete&&img.naturalWidth){const k=l.fit==='contain'?Math.min(c.width/img.width,c.height/img.height):Math.max(c.width/img.width,c.height/img.height);ctx.globalAlpha=l.opacity;ctx.drawImage(img,(c.width-img.width*k)/2,(c.height-img.height*k)/2,img.width*k,img.height*k);}}ctx.globalAlpha=m.background.shade;ctx.fillStyle=m.background.tint;ctx.fillRect(0,0,c.width,c.height);ctx.globalAlpha=1;ctx.scale(sx,sy);if($('editor-grid').checked){ctx.strokeStyle='#ffffff12';ctx.lineWidth=1/sx;ctx.beginPath();for(let x=0;x<m.width;x+=20){ctx.moveTo(x,0);ctx.lineTo(x,m.height);}for(let y=0;y<m.height;y+=20){ctx.moveTo(0,y);ctx.lineTo(m.width,y);}ctx.stroke();}
 for(const list of['platforms','walls'])for(let i=0;i<m[list].length;i++){const p=m[list][i],sel=this.picked?.list===list&&this.picked.index===i;ctx.fillStyle=p.fragile?'#b48a63':p.motion?'#6899a7':list==='walls'?'#687688':m.ground;ctx.fillRect(p.x,p.y,p.w,p.h||18);ctx.strokeStyle=sel?'#fff0b6':'#d5d7c0';ctx.lineWidth=sel?3/sx:1/sx;ctx.strokeRect(p.x,p.y,p.w,p.h||18);if(p.fragile){ctx.fillStyle='#211f32';ctx.font='16px monospace';ctx.fillText('⌁',p.x+p.w/2-8,p.y+15);}if(p.motion){const b={x:p.x+p.motion.x,y:p.y+p.motion.y};ctx.setLineDash([9,6]);ctx.beginPath();ctx.moveTo(p.x+p.w/2,p.y);ctx.lineTo(b.x+p.w/2,b.y);ctx.stroke();ctx.strokeRect(b.x,b.y,p.w,18);ctx.setLineDash([]);ctx.fillStyle='#fff0b6';ctx.font='16px monospace';ctx.fillText('B',b.x+p.w/2,b.y-9);}}
 for(let i=0;i<(m.decor||[]).length;i++){const p=m.decor[i],d=D.DECOR[p.type];this.decorRenderer??=new DuelRenderer(c);this.decorRenderer.ctx=ctx;DuelPresentation.prop(this.decorRenderer,p,null,0);if(this.picked?.list==='decor'&&this.picked.index===i){ctx.strokeStyle='#ffc788';ctx.lineWidth=2/sx;ctx.strokeRect(p.x-d.w/2-4,p.y-4,d.w+8,d.h+8);}ctx.font='12px monospace';ctx.fillStyle='#f0d5b4';ctx.fillText(d.name,p.x-d.w/2,p.y-10);}for(let i=0;i<2;i++){const p=m.spawns[i];ctx.fillStyle=i?'#ea977b':'#93d5bc';ctx.fillRect(p.x-12,p.y-80,24,80);ctx.fillRect(p.x-9,p.y-103,18,20);ctx.font='18px monospace';ctx.fillText('P'+(i+1),p.x-12,p.y-115);}if(this.drag&&!this.drag.moving){const a=this.drag.start,b=this.drag.end;ctx.fillStyle='#f0dda944';ctx.fillRect(Math.min(a.x,b.x),Math.min(a.y,b.y),Math.max(40,Math.abs(a.x-b.x)),this.tool==='wall'?Math.max(40,Math.abs(a.y-b.y)):18);}ctx.setTransform(1,0,0,1,0,0);const list=$('editor-warnings');list.replaceChildren();let warnings;try{D.cleanMap(m);warnings=D.mapWarnings(m);}catch(e){warnings=[e.message];}for(const text of warnings){const li=document.createElement('li');li.textContent=text;list.append(li);}$('editor-undo').disabled=!this.undo.length;$('editor-redo').disabled=!this.redo.length;}
 async cache(map){D.registerMap(map);if(this.library.db)try{await this.library.request('maps','put',map);}catch{}this.hooks.changed();this.templates();}
 async save(){const map=D.cleanMap(this.draft);D.registerMap(map);const folder=await this.library.save(map);this.hooks.changed(map.id);this.templates();if(!folder)this.download(map);this.status(folder?'Salvo na pasta '+this.library.directory.name+'.':this.library.cached?'Mapa salvo no navegador e arquivo enviado para Downloads.':'Arquivo enviado para Downloads. A cópia no navegador não pôde ser salva.');}
 download(map){const blob=new Blob([JSON.stringify(map,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=map.id+'.umcorte.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
 export(){this.download(D.cleanMap(this.draft));this.status('Arquivo exportado com geometria e imagens.');}
 async folder(){const maps=await this.library.folder();for(const m of maps)D.registerMap(m);this.hooks.changed();this.templates();this.storage();this.status(maps.length+' mapa(s) carregado(s) da pasta.');}
 test(){const map=D.cleanMap(this.draft);D.registerMap(map);this.hooks.changed();this.close();this.testing=true;$('editor-return').hidden=false;this.hooks.test(map.id);}
 back(){this.testing=false;$('editor-return').hidden=true;this.hooks.back();this.open();}
}
window.DuelMapEditor=DuelMapEditor;
})();
