const A=require('node:assert/strict'),fs=require('fs'),{chromium}=require('C:/Users/Luiz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));try{
 await p.addInitScript(()=>{const original=Math.random;let scene=false;Math.random=()=>{if(!scene&&new Error().stack.includes('new DuelMenuFX')){scene=true;return .05;}return original();};});await p.goto('http://127.0.0.1:4183/um-corte-v6.3.html');await p.waitForFunction(()=>window.duelSnapshot);await p.waitForTimeout(200);A.equal(await p.locator('#title-scene-name').textContent(),'JARDINS SUSPENSOS');await p.screenshot({path:__dirname+'/menu-gardens.png'});
 const images=await p.evaluate(()=>{const c=document.createElement('canvas');c.style='position:fixed;left:0;top:0;width:1280px;height:720px;z-index:-1';document.body.append(c);const r=new DuelRenderer(c),g=new DuelCore.Game({mode:'local',ai:false,mapId:'bamboo',characters:['duelist','staff']});g.start();r.lighting.settings.quality='high';g.fighters[0].x=430;g.fighters[1].x=870;const out={},base={shake:0,particles:[],wallJumps:[],lights:[]};for(const kind of Object.keys(DuelCore.CLASSES))for(const state of['idle','parry','entry','special','finisher']){g.fighters[0].kind=kind;g.fighters[0].ultMode='';g.fighters[0].state=state==='parry'?'parry':state==='special'?'active':'idle';g.fighters[0].stateTime=.04;g.fighters[0].duration=.15;g.fighters[0].attackAim=-Math.PI/4;g.fighters[0].guard='high';g.fighters[0].guardFacing=1;g.phase=state==='entry'?'roundEntry':'playing';g.entryRemaining=.34;if(state==='special')g.fighters[0].ultMode={duelist:'fenceStrike',staff:'sweepStrike',knight:'shield',lancer:'charge',assassin:'unarmed',swordsman:'edge',reaper:'reaperBoost',boxer:'boxerRush'}[kind];const e={...base};if(state==='finisher')e.fatal={finisher:true,winner:0,kind,x:580,y:490,age:.25,angle:-.2};const before=JSON.stringify(g.snapshot());r.render(g,e,.33);if(before!==JSON.stringify(g.snapshot()))throw Error('Visual mutated engine '+kind+state);if(['duelist','staff'].includes(kind)&&['entry','special','finisher'].includes(state))out[kind+'-'+state]=c.toDataURL();}
 r.adminOverlays={body:true,slash:true,parry:true,geometry:true,spawns:true,vectors:true,projectiles:true,timers:true,ai:true};g.fighters[0].kind='duelist';g.fighters[1].state='parry';g.fighters[1].guard='high';r.render(g,{...base,wallJumps:[{x:30,y:470,side:-1,age:.1}]},1);out.diagnostics=c.toDataURL();c.remove();return out;});for(const[n,data]of Object.entries(images))fs.writeFileSync(__dirname+'/'+n+'.png',Buffer.from(data.split(',')[1],'base64'));
 await p.click('#title-play');await p.click('[data-mode="tournament"]');await p.selectOption('#tournament-stages','2');await p.selectOption('#difficulty','easy');await p.click('#rules-details summary');await p.fill('#number-winningScore','1');await p.locator('#number-winningScore').press('Tab');await p.uncheck('#specials-enabled');await p.click('#start');await p.click('#tournament-fight');await p.waitForFunction(()=>duelSnapshot().phase==='playing');
 // ADMIN-only live class exception survives the next tournament bout.
 await p.goto('http://127.0.0.1:4183/um-corte-v6.3-admin.html');await p.click('#title-play');await p.click('[data-mode="tournament"]');await p.selectOption('#tournament-stages','2');await p.selectOption('#difficulty','easy');await p.click('#rules-details summary');await p.fill('#number-winningScore','1');await p.locator('#number-winningScore').press('Tab');await p.uncheck('#specials-enabled');await p.click('#start');
 for(let match=0;match<2;match++){if(match){const s=await p.evaluate(()=>duelSnapshot());A.equal(s.fighters[0].kind,'staff');A(s.fighters[0].admin.invincible);}await p.click('#tournament-fight');await p.waitForFunction(()=>duelSnapshot().phase==='playing');await p.keyboard.press('*');await p.selectOption('#admin-map','bamboo');await p.selectOption('#admin-character-0','staff');await p.fill('#admin-pos-0-x','600');await p.fill('#admin-pos-1-x','700');await p.fill('#admin-pos-0-y','615');await p.fill('#admin-pos-1-y','615');await p.click('#admin-apply');await p.check('#admin-power-0-invincible');await p.fill('#admin-power-0-attackScale','3');await p.click('#admin-actors');await p.click('#admin-close');await p.waitForFunction(()=>duelSnapshot().phase==='playing');const s=await p.evaluate(()=>duelSnapshot()),box=await p.locator('#game').boundingBox(),sc=Math.min(box.width/1280,box.height/720),e=s.fighters[1];await p.mouse.move(box.x+(box.width-1280*sc)/2+((e.x-s.camera.x)*s.camera.zoom+640)*sc,box.y+(box.height-720*sc)/2+((e.y-71-s.camera.y)*s.camera.zoom+360)*sc);await p.keyboard.press('j');await p.waitForFunction(()=>document.getElementById('tournament-screen').open,null,{timeout:12000});}
 A((await p.evaluate(()=>duelSnapshot())).podium);await p.waitForTimeout(5500);A((await p.evaluate(()=>duelSnapshot())).podium);A.equal(await p.locator('#tournament-podium-cards canvas').count(),3);await p.screenshot({path:__dirname+'/podium.png'});await p.click('#tournament-show-ranking');A.equal(await p.locator('#tournament-ranking tr').count(),4);A.equal(await p.locator('#tournament-results').isVisible(),true);A.deepEqual(errors,[]);console.log('PASS all eight presentations preserve engine; new classes, overlays, bright title, full tournament, persistent live ADMIN and podium waits for click');
 }catch(e){console.error(errors);await p.screenshot({path:__dirname+'/visual-failure.png',fullPage:true});console.error(await p.evaluate(()=>duelSnapshot()));throw e;}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
