const {chromium}=require('C:/Users/Luiz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),A=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.setDefaultTimeout(20000);p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4189/'+(process.argv.includes('--admin')?'um-corte-v8-admin.html':'um-corte-v8.html'));await p.locator('#title-play').click();await p.locator('[data-mode="training"]').click();await p.locator('#rules-details summary').click();await p.locator('#specials-enabled').uncheck();await p.locator('#start').click();await p.waitForFunction(()=>duelSnapshot().phase==='playing');await p.keyboard.press('Tab');await p.locator('#legacy-lab').click();
 A.equal(await p.locator('#legacy-catalogue [data-legacy]').count(),115);
 for(const id of ['bow','wingboot','coin','counter','hound','fireball'])await p.locator('#legacy-catalogue [data-legacy="'+id+'"] button').first().click();
 await p.locator('#legacy-search').fill('YAMATO');A.equal(await p.locator('#legacy-catalogue [data-legacy]').count(),1);await p.locator('#legacy-search').fill('');await p.locator('#legacy-lab').click();
 for(const width of[1440,800,390]){await p.setViewportSize({width,height:1000});await p.locator('#legacy-panel').evaluate(e=>e.scrollTop=0);await p.screenshot({path:'outputs/v8-inventory-'+width+'.png'});A(await p.locator('#legacy-panel').evaluate(e=>e.scrollWidth<=e.clientWidth+1),'inventory overflow '+width);}
 await p.setViewportSize({width:1440,height:1000});await p.keyboard.press('Tab');A.equal(await p.locator('#legacy-hud canvas').count(),6);await p.screenshot({path:'outputs/v8-icons-hud.png'});
 await p.reload();await p.locator('#title-play').click();await p.locator('#rules-details summary').click();await p.locator('#specials-enabled').uncheck();await p.selectOption('#legacy-mode','match');await p.locator('#start').click();await p.waitForFunction(()=>document.querySelector('#legacy-draft').open);
 for(const width of[1440,800,390]){await p.setViewportSize({width,height:1000});await p.locator('#legacy-draft').evaluate(e=>e.scrollTop=0);await p.screenshot({path:'outputs/v8-draft-'+width+'.png'});A(await p.locator('#legacy-draft').evaluate(e=>e.scrollWidth<=e.clientWidth+1),'draft overflow '+width);}
 await p.locator('#draft-cards [data-legacy]').last().click();const chosen=await p.locator('#draft-cards .selected').getAttribute('data-legacy');await p.locator('#draft-confirm').click();await p.waitForFunction(()=>duelSnapshot().phase==='playing');A((await p.evaluate(()=>duelSnapshot())).fighters[0].legacy.items.includes(chosen));
 A.deepEqual(errors,[]);console.log('PASS catalogue 115, search, six category additions, inventory 1440/800/390 no horizontal overflow, HUD 6 icons, responsive draft selection confirmed',process.argv.includes('--admin')?'ADMIN':'normal');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
