(function(root){
'use strict';
const SCALE=.9;
const C={scale:SCALE,bodyTop:121*SCALE,bodyBottom:25*SCALE,bodyCenter:79*SCALE,width:1280,height:720,ground:610,radius:17*SCALE,bladeWidth:3*SCALE,winningScore:5,deathY:890,roundPause:1.05};
const CLASSES={
 duelist:{name:'Duelista',weapon:'Rapieira',description:'Precisão e punição. Estocada estreita, passos ágeis e compromisso.',speed:350,startup:.15,active:.10,recovery:.255,reach:164,minRange:29,length:136,sweep:0,dashSpeed:1060},
 staff:{name:'Monge',weapon:'Bastão',description:'Controle de espaço. Arcos amplos, preparação visível e mãos firmes.',speed:305,startup:.28,active:.145,recovery:.405,reach:144,minRange:28,length:128,sweep:3.25,dashSpeed:970},
 boxer:{name:'Pugilista',weapon:'Punhos',description:'O menor alcance. Socos alternados, pés rápidos e contra-golpe explosivo.',speed:378,startup:.119,active:.08925,recovery:.2125,reach:69,minRange:12,length:40,sweep:0,dashSpeed:1100},
 knight:{name:'Cavaleiro',weapon:'Espada',description:'Equilíbrio. Cortes precisos e recuperação confiável.',speed:310,startup:.19,active:.12,recovery:.32,reach:142,minRange:30,length:112,sweep:2.1,dashSpeed:990},
 lancer:{name:'Lanceiro',weapon:'Lança',description:'Controle de distância. Só a ponta fere; aproxime-se para vencê-lo.',speed:290,startup:.23,active:.12,recovery:.39,reach:222,minRange:157,length:194,sweep:0,dashSpeed:930},
 assassin:{name:'Assassino',weapon:'Adaga',description:'Mobilidade e velocidade. Precisa entrar muito perto.',speed:360,startup:.14,active:.105,recovery:.25,reach:92,minRange:28,length:62,sweep:2.2,dashSpeed:1080},
 swordsman:{name:'Espadachim',weapon:'Espada longa',description:'Duas mãos, arco amplo. O alcance cobra comprometimento.',speed:300,startup:.262,active:.15,recovery:.428,reach:187,minRange:34,length:153,sweep:2.55,dashSpeed:970},
 reaper:{name:'Ceifador',weapon:'Foice',description:'A lâmina curva envolve o rival. Dentro do arco há uma abertura.',speed:305,startup:.29,active:.15,recovery:.465,reach:208,minRange:116,length:156,sweep:2.55,dashSpeed:975}
};
for(const s of Object.values(CLASSES)){for(const k of ['reach','minRange','length'])s[k]*=SCALE;}
for(const s of Object.values(CLASSES))Object.assign(s,{parry:.15,parryRecovery:.4,parryCooldown:.55,dash:.14,dashRecovery:.075,dashCooldown:.32,stun:.49});
for(const st of Object.values(CLASSES))for(const key of['startup','active','recovery'])st[key]/=1.25;
const RUNNER={...CLASSES.assassin,name:'Corredor',weapon:'Livre',description:'Só movimento. Precisão em cada salto.',speed:445,dashSpeed:1120,reach:0,minRange:0,length:0,sweep:0};
const COLORS={jade:{name:'Jade',hex:'#367f75'},coral:{name:'Coral',hex:'#b75640'},indigo:{name:'Índigo',hex:'#5a64a7'},gold:{name:'Ouro',hex:'#af842e'},plum:{name:'Ameixa',hex:'#995879'},ice:{name:'Gelo',hex:'#5796b4'}};
Object.assign(COLORS,{ruby:{name:'Rubi',hex:'#b83f60'},teal:{name:'Turquesa',hex:'#168f99'},violet:{name:'Violeta',hex:'#8254ba'},orange:{name:'Âmbar',hex:'#c57528'},rose:{name:'Rosa',hex:'#bf7397'},olive:{name:'Oliva',hex:'#7b873d'},silver:{name:'Prata',hex:'#a4b1ba'},copper:{name:'Cobre',hex:'#996146'},navy:{name:'Safira',hex:'#315ead'},mint:{name:'Menta',hex:'#61ac86'}});
const RULES={attackSpeed:{name:'Velocidade de ataque',min:.1,max:3,step:.01},mapSize:{name:'Tamanho da arena',min:.5,max:3,step:.1},gravity:{name:'Gravidade',min:.1,max:5,step:.05},jump:{name:'Força do pulo',min:.1,max:5,step:.1},speed:{name:'Velocidade de movimento',min:.1,max:3,step:.01},dashDistance:{name:'Distância do dash',min:.1,max:5,step:.1},dashCount:{name:'Dashes consecutivos',min:1,max:5,step:1,unit:'cargas',default:1},dashRecovery:{name:'Recuperação do dash',min:0,max:2000,step:5,unit:'ms',default:75},dashCooldown:{name:'Recarga de cada dash',min:0,max:5000,step:10,unit:'ms',default:320},parryWindow:{name:'Duração do parry',min:50,max:2000,step:10,unit:'ms',default:400},parryRecovery:{name:'Recuperação do parry',min:0,max:3000,step:10,unit:'ms',default:400},stun:{name:'Atordoamento após parry',min:0,max:3000,step:10,unit:'ms',default:490},specialCooldown:{name:'Recarga do especial',min:.1,max:120,step:.1,unit:'s',default:7,unbounded:true}};for(const r of Object.values(RULES))r.numeric=true;
Object.assign(RULES,{boxerWindow:{name:'Pugilista · janela do parry',min:100,max:15000,step:100,unit:'ms',default:5000,numeric:true},boxerRush:{name:'Pugilista · duração da sequência',min:100,max:10000,step:100,unit:'ms',default:2000,numeric:true},boxerPenalty:{name:'Pugilista · bloqueio de dash',min:0,max:15000,step:100,unit:'ms',default:3000,numeric:true},platformSpeed:{name:'Velocidade das plataformas',min:.1,max:5,step:.1,default:1,numeric:true},collapseSpeed:{name:'Tempo para desabar',min:.1,max:5,step:.1,default:1,numeric:true},respawnSpeed:{name:'Tempo para reaparecer',min:.1,max:5,step:.1,default:1,numeric:true}});
Object.assign(RULES,{winningScore:{name:'Pontos para vencer',min:1,max:25,step:1,unit:'pontos',default:5,integer:true,unbounded:true,numeric:true},attackRecovery:{name:'Recuperação dos ataques',min:.1,max:5,step:.1,default:1,numeric:true}});
const DEFAULT_RULES=Object.fromEntries([...Object.entries(RULES).map(([k,v])=>[k,v.default??1]),['airDash',true],['specials',true],['persistSpecial',true],['chaos','off']]);
const COMBAT_KEYS=['attackSpeed','attackRecovery','speed','gravity','jump','dashDistance','dashCount','dashRecovery','dashCooldown','parryWindow','parryRecovery','stun','airDash'];
const combatDefaults=Object.fromEntries(COMBAT_KEYS.map(k=>[k,DEFAULT_RULES[k]]));
const PRESETS={classic:{name:'CLÁSSICO',description:'O ritmo padrão da V7.2.',rules:{...combatDefaults}},turbo:{name:'TURBO',description:'Movimento 1,6× · ataque 1,4× · dash recarrega em 240 ms.',rules:{...combatDefaults,speed:1.6,attackSpeed:1.4,dashCooldown:240}},lowGravity:{name:'BAIXA GRAVIDADE',description:'Gravidade 0,65× · pulo 1,1× · mais espaço para duelos aéreos.',rules:{...combatDefaults,gravity:.65,jump:1.1}},merciless:{name:'SEM PIEDADE',description:'Parry de 180 ms · falha de parry: 500 ms · recuperação dos ataques 1,2×.',rules:{...combatDefaults,parryWindow:180,parryRecovery:500,attackRecovery:1.2}}};
function applyPreset(r,id){return cleanRules({...r,...PRESETS[id]?.rules});}
function detectPreset(r){return Object.keys(PRESETS).find(id=>COMBAT_KEYS.every(k=>r[k]===PRESETS[id].rules[k]))||'custom';}
const MAPS={
 dojo:{name:'Dojo elevado',description:'Chão seguro, plataformas e pilares para saltar pelas paredes.',platforms:[{x:40,y:610,w:1200,solid:true},{x:220,y:405,w:270},{x:790,y:405,w:270}],spawns:[{x:385,y:610},{x:895,y:610}]},
 bridge:{name:'Ponte quebrada',description:'Distância, saltos e vãos fatais. Não recue sem olhar.',platforms:[{x:55,y:590,w:360,solid:true},{x:490,y:525,w:300},{x:865,y:590,w:360,solid:true}],spawns:[{x:290,y:590},{x:990,y:590}]},
 ruins:{name:'Ruínas',description:'Rotas aéreas, paredes e um vão no centro. Cuidado ao recuar.',platforms:[{x:45,y:620,w:460,solid:true},{x:775,y:620,w:460,solid:true},{x:430,y:460,w:420},{x:90,y:400,w:200},{x:990,y:400,w:200},{x:510,y:265,w:260}],spawns:[{x:315,y:620},{x:965,y:620}]},
 bamboo:{name:'Bosque da Lua',description:'Bambu, lanternas e luar. Rotas laterais acima de um chão seguro.',platforms:[{x:40,y:615,w:1200,solid:true},{x:130,y:425,w:235},{x:915,y:425,w:235},{x:420,y:290,w:440}],spawns:[{x:385,y:615},{x:895,y:615}]},
 frost:{name:'Fortaleza Nevada',description:'Torres congeladas e um vão central. Avance pelos bastiões.',platforms:[{x:40,y:610,w:410,solid:true},{x:830,y:610,w:410,solid:true},{x:435,y:450,w:410},{x:110,y:405,w:220},{x:950,y:405,w:220}],spawns:[{x:300,y:610},{x:980,y:610}]},
 forge:{name:'Forja de Cinzas',description:'Correntes sobre lava. Dispute a ilha e as passarelas centrais.',platforms:[{x:45,y:590,w:290,solid:true},{x:945,y:590,w:290,solid:true},{x:485,y:605,w:310,solid:true},{x:305,y:420,w:245},{x:730,y:420,w:245}],spawns:[{x:235,y:590},{x:1045,y:590}]}
};
MAPS.dojo.walls=[{x:55,y:280,w:26,h:330},{x:1199,y:280,w:26,h:330},{x:190,y:390,w:26,h:220},{x:1064,y:390,w:26,h:220}];
MAPS.ruins.walls=[{x:65,y:315,w:28,h:305},{x:1187,y:315,w:28,h:305},{x:480,y:500,w:25,h:120},{x:775,y:500,w:25,h:120}];
MAPS.tower={name:'Torre do Sino',description:'Paredes, pilares e um elevador central. O terreno também se move.',platforms:[{x:50,y:630,w:1180,solid:true},{x:180,y:430,w:240},{x:860,y:430,w:240},{x:470,y:240,w:340},{x:540,y:450,w:200,motion:{y:115,period:5.6}}],walls:[{x:70,y:165,w:35,h:465},{x:1175,y:165,w:35,h:465},{x:340,y:450,w:30,h:180},{x:910,y:450,w:30,h:180}],spawns:[{x:470,y:630},{x:810,y:630}]};
const SKINS={knight:{id:'hollow',name:'Cavaleiro Vazio',reference:'Hollow Knight'},lancer:{id:'katakuri',name:'Doce Comandante',reference:'Katakuri'},assassin:{id:'thorfinn',name:'Filho do Norte',reference:'Thorfinn jovem'},swordsman:{id:'guts',name:'Espadachim Negro',reference:'Guts'},reaper:{id:'kite',name:'Caçador da Lua',reference:'Kite · Crazy Slots Nº 2'},boxer:{id:'yuji',name:'Punho Amaldiçoado',reference:'Yuji Itadori'}};
const cleanSkin=(kind,skin)=>typeof skin==='string'&&SKINS[kind]?.id===skin?skin:'default';
MAPS.sanctuary={name:'Santuário Suspenso',description:'Ruínas nas nuvens. O caminho central desaba; as rotas altas permanecem.',theme:'sanctuary',platforms:[{x:40,y:610,w:250,solid:true},{x:990,y:610,w:250,solid:true},{x:330,y:565,w:160,fragile:{delay:.8,respawn:4}},{x:560,y:540,w:160,fragile:{delay:.8,respawn:4}},{x:790,y:565,w:160,fragile:{delay:.8,respawn:4}},{x:215,y:410,w:200},{x:500,y:335,w:280},{x:865,y:410,w:200}],walls:[],spawns:[{x:175,y:610},{x:1105,y:610}]};
// Map files contain only bounded data. No HTML, scripts, external URLs or SVG assets.
function cleanMap(data){if(!data||typeof data!=='object'||data.format!=='um-corte-map'||data.version!==1)throw Error('Arquivo de mapa incompatível.');const number=(v,min,max)=>{if(!Number.isFinite(v)||v<min||v>max)throw Error('Medida do mapa fora dos limites.');return v;},color=v=>/^#[0-9a-f]{6}$/i.test(v)?v:'#607266';
 const race=data.type==='parkour';if(data.type&&!['duel','parkour'].includes(data.type))throw Error('Tipo de mapa inválido.');const width=number(data.width,640,race?24000:3840),height=number(data.height,360,race?24000:2160),id=String(data.id||'');if(!/^custom_[a-zA-Z0-9_-]{1,60}$/.test(id))throw Error('Identificador de mapa inválido.');if(!Array.isArray(data.platforms)||data.platforms.length>(race?300:80)||!Array.isArray(data.walls)||data.walls.length>(race?200:60)||!Array.isArray(data.spawns)||data.spawns.length!==2)throw Error('Mapa precisa de dois inícios e até 80 plataformas / 60 paredes.');
 const platforms=data.platforms.map(p=>{const q={x:number(p.x,0,width),y:number(p.y,0,height),w:number(p.w,20,width),solid:!!p.solid};if(q.x+q.w>width+1)throw Error('Plataforma fora da arena.');if(p.motion){q.motion={x:number(p.motion.x,-width,width),y:number(p.motion.y,-height,height),period:number(p.motion.period,.4,120),pause:number(p.motion.pause??0,0,30),route:true};if(q.x+q.motion.x<0||q.x+q.motion.x+q.w>width||q.y+q.motion.y<0||q.y+q.motion.y>height)throw Error('Trajeto fora da arena.');}if(p.fragile)q.fragile={delay:number(p.fragile.delay,.1,30),respawn:number(p.fragile.respawn,0,120)};return q;});
 const walls=data.walls.map(w=>{const q={x:number(w.x,0,width),y:number(w.y,0,height),w:number(w.w,12,width),h:number(w.h,12,height)};if(q.x+q.w>width||q.y+q.h>height)throw Error('Parede fora da arena.');return q;});const spawns=data.spawns.map(p=>({x:number(p.x,22,width-22),y:number(p.y,110,height)}));
 const background=data.background||{},layers=(background.layers||[]).slice(0,2).map(l=>{if(typeof l.image!=='string'||l.image.length>900000||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(l.image))throw Error('Fundo inválido: use PNG, JPEG ou WebP.');return{image:l.image,parallax:number(l.parallax??.1,0,.5),opacity:number(l.opacity??1,0,1),fit:l.fit==='contain'?'contain':'cover'};});
 return{format:'um-corte-map',version:1,id,type:race?'parkour':'duel',race:race?cleanRaceMap(data.race,width,height,platforms,walls):undefined,custom:true,name:String(data.name||'Minha arena').slice(0,48),description:String(data.description||'Arena criada no editor.').slice(0,160),width,height,deathY:height+170,decor:cleanDecor(data.decor||[],width,height),weather:WEATHER.includes(data.weather)?data.weather:'none',theme:['dojo','bridge','ruins','bamboo','frost','forge','tower','sanctuary'].includes(data.theme)?data.theme:'dojo',platforms,walls,spawns,ground:color(data.ground),background:{layers,tint:color(background.tint||'#172838'),shade:number(background.shade??.2,0,.85)}};
}
function registerMap(data){const map=cleanMap(data);MAPS[map.id]=map;return map;}
function cleanRaceMap(data,width,height,platforms,walls){
 if(!data||!data.start||!data.finish||!Array.isArray(data.checkpoints)||!data.checkpoints.length||data.checkpoints.length>40)throw Error('Parkour precisa de largada, chegada e 1–40 checkpoints em ordem.');
 const point=p=>{if(!p||!Number.isFinite(p.x)||!Number.isFinite(p.y)||p.x<22||p.x>width-22||p.y<110||p.y>height)throw Error('Ponto do percurso fora do mapa.');return{x:p.x,y:p.y};};
 const supported=p=>platforms.some(q=>p.x>=q.x+12&&p.x<=q.x+q.w-12&&Math.abs(p.y-q.y)<3&&!q.motion&&!q.fragile)||walls.some(w=>p.x>=w.x+12&&p.x<=w.x+w.w-12&&Math.abs(p.y-w.y)<3);
 const start=point(data.start);if(!supported(start))throw Error('A largada precisa de apoio fixo e seguro.');
 const gate=(g,i)=>{const p=point(g);if(i>=0&&g.order!==i+1)throw Error('Checkpoints devem estar numerados em ordem, sem repetição.');if(!supported(p))throw Error('Chegada e checkpoints precisam de apoio fixo e seguro para respawn.');const w=g.w??100,h=g.h??170;if(!Number.isFinite(w)||!Number.isFinite(h)||w<40||w>400||h<80||h>400)throw Error('Tamanho de checkpoint inválido.');return{...p,w,h,...(i>=0?{order:i+1}:{})};};
 const checkpoints=data.checkpoints.map(gate),finish=gate(data.finish,-1),anchors=[start,...checkpoints,finish];
 for(let i=1;i<anchors.length;i++)if(Math.hypot(anchors[i].x-anchors[i-1].x,anchors[i].y-anchors[i-1].y)<80)throw Error('Separe os portais do percurso por pelo menos 80 px.');
 const routes=anchors.slice(1).map((p,i)=>{const nodes=data.routes?.[i];if(!nodes)return[anchors[i],p].map(point);if(!Array.isArray(nodes)||nodes.length<2||nodes.length>100)throw Error('Linha de percurso inválida.');const pts=nodes.map(point);if(Math.hypot(pts[0].x-anchors[i].x,pts[0].y-anchors[i].y)>2||Math.hypot(pts.at(-1).x-p.x,pts.at(-1).y-p.y)>2)throw Error('Cada linha de percurso deve ligar seus dois portais.');return pts;});
 return{start,finish,checkpoints,routes};
}
function mapWarnings(map){const messages=[];for(let i=0;i<2;i++){const p=map.spawns[i];if(map.walls.some(w=>p.x+16>w.x&&p.x-16<w.x+w.w&&p.y-12>w.y&&p.y-112<w.y+w.h))messages.push('Jogador '+(i+1)+' começa dentro de uma parede.');if(!map.platforms.some(q=>p.x>=q.x&&p.x<=q.x+q.w&&Math.abs(p.y-q.y)<6)&&!map.walls.some(w=>p.x>=w.x&&p.x<=w.x+w.w&&Math.abs(p.y-w.y)<6))messages.push('Jogador '+(i+1)+' começa sem apoio direto.');}if(Math.hypot(map.spawns[0].x-map.spawns[1].x,map.spawns[0].y-map.spawns[1].y)<45)messages.push('Os dois inícios estão muito próximos.');return messages;}

const DIFFICULTIES={easy:{name:'Fácil',description:'Mais hesitação e erros. Reação de 260–400 ms.',reaction:[.26,.40],parry:.24,attack:.48},normal:{name:'Normal',description:'Lê distância e aberturas, mas pode ser enganada.',reaction:[.16,.26],parry:.57,attack:.72},adaptive:{name:'Adaptativo',description:'Ajusta defesa, pressão e fintas aos seus hábitos nesta partida.',reaction:[.15,.25],parry:.53,attack:.68},master:{name:'Mestre',description:'Fintas, punições e leitura de trajetória. Percebe ações com atraso e não lê seus comandos.',reaction:[.085,.12],parry:.94,attack:.98},impossible:{name:'Impossível',description:'Prevê golpes e reage quase instantaneamente. Mesmas regras físicas.',reaction:[.005,.018],parry:1,attack:.96}};
const specialKind=f=>root.DuelLegacy?.specialKind(f)||f.kind;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,stats=f=>{const originalSource=(typeof f==='string'?f:f.kind)==='runner'?RUNNER:(CLASSES[typeof f==='string'?f:f.kind]||CLASSES.knight),source=root.DuelLegacy?.weaponStats(f,originalSource)||originalSource,as=typeof f==='object'?(f.admin?.attackScale||1):1,base=as===1?source:{...source,reach:source.reach*as,minRange:source.minRange*as,length:source.length*as,weaponScale:as},scale=typeof f==='object'&&specialKind(f)==='reaper'?(f.ultMode==='reaperBoost'?1.4:f.ultMode==='reaperWeak'?.6:1):1;if(typeof f==='object'&&specialKind(f)==='boxer'&&f.ultMode==='boxerRush')return{...base,startup:.024,active:.04,recovery:0};if(typeof f==='object'&&specialKind(f)==='staff'&&f.ultMode==='sweepStrike')return{...base,startup:.24,active:.21,recovery:.62};return scale===1?base:{...base,reach:base.reach*scale,minRange:base.minRange*scale,length:base.length*scale,weaponScale:as*scale};};
function cleanRules(r={},experimental=false){const o={};for(const[k,v]of Object.entries(RULES)){let n=Number.isFinite(r[k])?r[k]:DEFAULT_RULES[k];n=experimental?Math.max(['dashCount','winningScore'].includes(k)?1:['attackSpeed','mapSize'].includes(k)?.001:0,n):Math.max(v.min,v.unbounded?n:Math.min(v.max,n));o[k]=k==='dashCount'||v.integer?Math.min(Number.MAX_SAFE_INTEGER,Math.floor(n)):n;}o.airDash=r.airDash!==false;o.specials=r.specials!==false;o.persistSpecial=r.persistSpecial!==false;o.chaos=['normal','ultra'].includes(r.chaos)?r.chaos:'off';return o;}
const aimSide=(a,facing=1)=>Math.abs(Math.cos(a))<.0003?facing:Math.cos(a)>0?1:-1;
const neutral=()=>({legado:[],legadoHeld:[],kickHeld:false,move:0,up:false,taunt:false,aim:0,jump:false,jumpHeld:false,down:false,attack:false,attackHeld:false,parry:false,dash:false,kick:false,special:false});
function nearest(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1),0,1);return{x:a.x+dx*t,y:a.y+dy*t};}
const pointSegment=(p,a,b)=>{const n=nearest(p,a,b);return Math.hypot(p.x-n.x,p.y-n.y);};
function segmentDistance(a,b,c,d){const cross=(p,q,r)=>(q.x-p.x)*(r.y-p.y)-(q.y-p.y)*(r.x-p.x),v1=cross(a,b,c),v2=cross(a,b,d),v3=cross(c,d,a),v4=cross(c,d,b);if(v1*v2<0&&v3*v4<0)return 0;return Math.min(pointSegment(a,c,d),pointSegment(b,c,d),pointSegment(c,a,b),pointSegment(d,a,b));}
function guardSector(angle,grounded){const s=Math.sin(angle);return s<-.7071?'high':s>.7071&&!grounded?'low':'normal';}
// Scale both axes of the arena. Large layouts receive intermediate stepping stones
// along existing routes so increasing space never removes the basic jump route.
function sealPathMap(map){if(!map?.path||map.pathEnclosed)return map;const sorted=[...map.walls].sort((a,b)=>a.x-b.x),left=sorted[0],right=sorted.at(-1);if(!left||!right||left===right)return map;const low=left.x+left.w,high=right.x;for(const [w,isLeft]of[[left,true],[right,false]]){w.boundaryBottom=w.y+w.h;w.pathBoundary=true;w.x=isLeft?0:high;w.w=isLeft?low:map.width-high;w.y=-10000000;w.h=w.boundaryBottom-w.y;}for(const p of map.platforms)if(p.wallTop){p.y=p.baseY=-10000000;}map.pathEnclosed=true;return map;}
function makeMap(id,scale=1,source){const base=source||MAPS[id]||MAPS.dojo;scale*=base.type==='parkour'?1:1.5;const platforms=base.platforms.map(p=>({...p,x:p.x*scale,y:p.y*scale,w:p.w*scale}));
 if(scale>1&&!base.custom){const original=[...platforms];for(let i=0;i<original.length;i++)for(let j=i+1;j<original.length;j++){const a=original[i],b=original[j],gap=Math.max(0,Math.max(a.x,b.x)-Math.min(a.x+a.w,b.x+b.w)),rise=Math.abs(a.y-b.y);if(rise<1||rise>240*scale||gap>150*scale||rise<=205&&gap<=180)continue;
  const left=Math.max(a.x,b.x),right=Math.min(a.x+a.w,b.x+b.w),x=right>=left?(left+right)/2:(a.x<b.x?(a.x+a.w+b.x)/2:(b.x+b.w+a.x)/2),steps=Math.min(64,Math.max(Math.ceil(rise/190),Math.ceil(gap/180)));
  for(let n=1;n<steps;n++){const y=lerp(a.y,b.y,n/steps),w=110;if(!platforms.some(p=>Math.abs(p.y-y)<55&&x>=p.x-25&&x<=p.x+p.w+25))platforms.push({x:x-w/2,y,w,step:true});}
 }}
 const walls=(base.walls||[]).map(w=>({x:w.x*scale,y:w.y*scale,w:w.w*scale,h:w.h*scale}));for(const w of walls){platforms.push({x:w.x,y:w.y,w:w.w,solid:true,wallTop:true});if(scale>1)for(let y=w.y+w.h-180;y>w.y+60;y-=Math.max(180,(w.h-240)/64))platforms.push({x:Math.max(0,w.x-65),y,w:w.w+130,wallLedge:true});}for(const p of platforms){p.baseX=p.x;p.baseY=p.y;if(p.motion)p.motion={...p.motion,x:(p.motion.x||0)*scale,y:p.motion.y*scale};if(p.fragile)p.fragile={...p.fragile};p.stage="solid";p.crumbleAt=null;p.goneAt=null;}
 return sealPathMap({...base,walls,platforms,spawns:base.spawns.map(p=>({x:p.x*scale,y:p.y*scale})),width:(base.width||C.width)*scale,height:(base.height||C.height)*scale,deathY:(base.deathY||C.deathY)*scale,scale});
}
function pointInPolygon(p,poly){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a.y>p.y)!==(b.y>p.y)&&p.x<(b.x-a.x)*(p.y-a.y)/(b.y-a.y)+a.x)inside=!inside;}return inside;}
function polygonSegment(poly,a,b,r=0){if(!poly.length)return false;if(pointInPolygon(a,poly)||pointInPolygon(b,poly))return true;return poly.some((p,i)=>segmentDistance(p,poly[(i+1)%poly.length],a,b)<=r);}
function polygonsIntersect(a,b){return a.length&&b.length&&(pointInPolygon(a[0],b)||pointInPolygon(b[0],a)||a.some((p,i)=>polygonSegment(b,p,a[(i+1)%a.length])));}
// The same polygon is filled by the renderer and used by hit, guard and clash tests.
// No separate enlarged hitbox and no damage from the weapon model or its handle.
function body(f){const low=clamp((f.slideRemaining||0)/.12,0,1),center=lerp(C.bodyCenter,27,low),scale=f.admin?.bodyScale||1;return{top:center+(lerp(C.bodyTop,44,low)-center)*scale,bottom:center+(lerp(C.bodyBottom,13,low)-center)*scale,radius:lerp(C.radius,11,low)*scale,center};}
function clipPlane(poly,key,edge,sign){const out=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],da=(a[key]-edge)*sign,db=(b[key]-edge)*sign;if(da>=0)out.push(a);if((da>=0)!==(db>=0)){const t=da/(da-db);out.push({x:lerp(a.x,b.x,t),y:lerp(a.y,b.y,t)});}}return out;}
// Clip rays at physical walls; both rendering and collisions use this contour.
function wallFraction(a,b,w){let lo=0,hi=1;for(const [key,min,max]of[['x',w.x,w.x+w.w],['y',w.y,w.y+w.h]]){const d=b[key]-a[key];if(Math.abs(d)<1e-9){if(a[key]<min||a[key]>max)return 1;continue;}let t=(min-a[key])/d,u=(max-a[key])/d;if(t>u)[t,u]=[u,t];lo=Math.max(lo,t);hi=Math.min(hi,u);if(lo>hi)return 1;}return lo;}
function wallContour(poly,origin,walls,reach){const nearby=walls.filter(w=>Math.hypot(origin.x-clamp(origin.x,w.x,w.x+w.w),origin.y-clamp(origin.y,w.y,w.y+w.h))<=reach);if(!nearby.length)return poly;const rays=nearby.flatMap(w=>[[w.x,w.y],[w.x+w.w,w.y],[w.x,w.y+w.h],[w.x+w.w,w.y+w.h]]).map(([x,y])=>Math.atan2(y-origin.y,x-origin.x));const out=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],dx=b.x-a.x,dy=b.y-a.y,ts=[0];for(const angle of rays)for(const offset of[-1e-6,0,1e-6]){const rx=Math.cos(angle+offset),ry=Math.sin(angle+offset),cross=dx*ry-dy*rx;if(Math.abs(cross)<1e-8)continue;const t=((origin.x-a.x)*ry-(origin.y-a.y)*rx)/cross;if(t>0&&t<1&&(a.x+t*dx-origin.x)*rx+(a.y+t*dy-origin.y)*ry>0)ts.push(t);}ts.sort((x,y)=>x-y);for(const t of ts){const p={x:a.x+dx*t,y:a.y+dy*t},hit=Math.min(1,...nearby.map(w=>wallFraction(origin,p,w)));out.push({x:lerp(origin.x,p.x,hit),y:lerp(origin.y,p.y,hit)});}}return out;}
function slash(f,walls=[],geometry=null){if(f.legacyNoSlash)return{points:[]};if(!['active','ultCharge'].includes(f.state)||f.dead)return{points:[]};const kind=geometry?.kind||root.DuelLegacy?.weaponKind(f)||f.kind,s=geometry?.stats||stats(f),size=geometry?.size||f.admin?.attackScale||1,aim=f.attackAim,origin={x:f.x,y:f.y-(geometry?.center??body(f).center)},at=(x,y)=>({x:origin.x+Math.cos(aim)*x-Math.sin(aim)*y,y:origin.y+Math.sin(aim)*x+Math.cos(aim)*y});let points=[];
 const progress=clamp((f.state==='ultCharge'?.5:f.stateTime/Math.max(.001,f.duration)),0,1),sweep=lerp(-.28,.28,progress)*(Math.cos(aim)>=0?1:-1);
 if((geometry?.technique??root.DuelLegacy?.attackTechnique(f)?.type)==='lunge'){const lo=Math.min(s.minRange,25*size),hi=s.reach*(.82+.18*Math.sin(progress*Math.PI)),half=7*size;points=[[lo,-half*.35],[hi-16*size,-half],[hi,0],[hi-16*size,half],[lo,half*.35]].map(p=>at(...p));}
 else if(kind==='boxer'){const extension=.75+.25*Math.sin(progress*Math.PI),r=s.reach*extension;points=[[12*size,-5*size],[r-10*size,-12*size],[r,-6*size],[r,6*size],[r-10*size,12*size],[12*size,5*size]].map(p=>at(...p));}
 else if(kind==='duelist'){const lo=s.minRange,hi=lerp(s.reach*.86,s.reach,Math.sin(progress*Math.PI)),width=4.5*SCALE*(f.admin?.attackScale||1);points=[[lo,0],[lo+12*size,-width],[hi-17*size,-width],[hi,0],[hi-17*size,width],[lo+12*size,width]].map(p=>at(...p));}
 else if(kind==='staff'&&f.ultMode==='sweepStrike'){origin.y=f.y-13;const reach=s.reach*1.4,half=11*(f.admin?.attackScale||1);points=Array.from({length:40},(_,i)=>{const a=i/40*Math.PI*2;return{x:f.x+Math.cos(a)*reach,y:origin.y+Math.sin(a)*half};});}
 else if(kind==='staff'){const outer=[],inner=[],a0=-1.65+progress*.45,a1=1.65+progress*.45;for(let i=0;i<=24;i++){const a=lerp(a0,a1,i/24),r=s.reach*(.9+.1*Math.sin(i/24*Math.PI));outer.push(at(Math.cos(a)*r,Math.sin(a)*r));inner.push(at(Math.cos(a)*(s.minRange+12*size),Math.sin(a)*(s.minRange+12*size)));}points=[...outer,...inner.reverse()];}
 else if(kind==='lancer'){const lo=s.minRange-7*SCALE*size,hi=lerp(s.reach*.87,s.reach,Math.sin(progress*Math.PI));points=[[lo,0],[lo+12*size,-5*SCALE*size],[hi-18*size,-15*SCALE*size],[hi,0],[hi-18*size,15*SCALE*size],[lo+12*size,5*SCALE*size]].map(p=>at(...p));}
 else{const steps=18,arc=kind==='reaper'?1.2:kind==='swordsman'?1.12:kind==='assassin'?.8:.95,outer=[],inner=[];for(let i=0;i<=steps;i++){const t=i/steps,a=lerp(-arc,arc,t)*(.35+.65*Math.sin(progress*Math.PI))+lerp(-arc*.6,arc*.6,progress)*(Math.cos(aim)>=0?1:-1),r=s.reach*(.83+.17*Math.sin(t*Math.PI)),thickness=(s.reach-s.minRange)*Math.pow(Math.sin(t*Math.PI),.8)*(.55+.45*Math.sin(progress*Math.PI));outer.push(at(Math.cos(a)*r,Math.sin(a)*r));inner.push(at(Math.cos(a)*(r-thickness),Math.sin(a)*(r-thickness)));}points=[...outer,...inner.reverse()];}
 points=wallContour(points,origin,walls,s.reach*(f.ultMode==='sweepStrike'?1.4:1));return{points,origin,aim,progress};
}
function blade(f){
 const kind=root.DuelLegacy?.weaponKind(f)||f.kind,s=stats(f),p=clamp(f.stateTime/Math.max(.001,f.duration),0,1),attack=['startup','active','recovery','ultWindup','ultCharge','throwWindup'].includes(f.state),aim=attack?f.attackAim:f.aim,side=Math.cos(aim)>=0?1:-1;
 let angle=aim+(kind==='assassin'?.45:kind==='reaper'?-.85:kind==='swordsman'?-.7:-.45)*side,extend=0,offset=24*SCALE,start=12*SCALE,end=s.length;
 if(s.sweep){if(f.state==='startup')angle=aim-side*s.sweep*.48*Math.sin(p*Math.PI/2);else if(f.state==='active')angle=aim+side*s.sweep*.46;else if(f.state==='recovery')angle=aim+side*lerp(s.sweep*.46,-.18,1-Math.pow(1-p,3));}
 else{angle=['startup','active','recovery','ultWindup','ultCharge'].includes(f.state)?aim:aim-.35*side;if(f.state==='startup')extend=-20*SCALE*p;else if(f.state==='active')extend=18*SCALE;else if(f.state==='recovery')extend=-20*SCALE*(1-p);start=s.length-44*SCALE;}
 if(f.state==='parry'){const ga=f.guard==='high'?-Math.PI/2:f.guard==='low'?Math.PI/2:(f.guardFacing>0?0:Math.PI);angle=ga+Math.PI/2;offset=0;}
 if(f.state==='feintRecovery')angle=f.attackAim-side*.9*(1-p);
 if(f.state==='stunned')angle=aim+side*1.2;
 const hand={x:f.x+Math.cos(aim)*(offset+extend),y:f.y-body(f).center+Math.sin(aim)*(offset+extend)};
 if(f.state==='parry'){const ga=f.guard==='high'?-Math.PI/2:f.guard==='low'?Math.PI/2:(f.guardFacing>0?0:Math.PI);hand.x=f.x+Math.cos(ga)*37*SCALE-Math.cos(angle)*s.length*.33;hand.y=f.y-body(f).center+Math.sin(ga)*48*SCALE-Math.sin(angle)*s.length*.33;}
 if(kind==='boxer'){const active=f.state==='active',guard=f.state==='parry',ga=f.guard==='high'?-Math.PI/2:f.guard==='low'?Math.PI/2:(f.guardFacing>0?0:Math.PI),a=guard?ga:aim,r=active?s.reach*.86:f.state==='startup'?20:30;hand.x=f.x+Math.cos(a)*r;hand.y=f.y-body(f).center+Math.sin(a)*r;angle=a;start=0;end=9;}
 if(kind==='staff'&&f.ultMode==='sweepStrike'){const wind=f.state==='startup';angle=wind?side*(-1.1+p*.9):Math.sin(p*Math.PI*2)*.16;hand.x=f.x+side*(wind?14:Math.cos(p*Math.PI*2)*22);hand.y=wind?f.y-body(f).center+p*29:f.y-30;}
 const at=(n,l=0)=>({x:hand.x+Math.cos(angle)*n-Math.sin(angle)*l,y:hand.y+Math.sin(angle)*n+Math.cos(angle)*l});
 let segments=[{a:at(start),b:at(end)}],shaft=null;
 if(kind==='lancer')shaft={a:at(-45*SCALE),b:at(start)};
 if(kind==='staff'){shaft={a:at(-s.length*.48),b:at(s.length*.66)};segments=[shaft];}
 if(kind==='duelist')segments=[{a:at(10),b:at(s.length)}];
 if(kind==='reaper'){
  shaft={a:at(-34*SCALE),b:at(s.length)};const pts=[[139,-4],[167,7],[174,29],[166,53],[145,73],[119,84]].map(p=>at(p[0]*SCALE*(s.weaponScale||1),p[1]*SCALE*(s.weaponScale||1)));segments=pts.slice(1).map((p,i)=>({a:pts[i],b:p}));
 }
 return{hand,angle,a:segments[0].a,b:segments[segments.length-1].b,segments,shaft,guard:{a:at(-12*SCALE),b:at(Math.min(120*SCALE,s.length))}};
}
function makeFighter(id,kind,color,spawn){return{id,kind,color,...spawn,vx:0,vy:0,facing:id?-1:1,aim:id?Math.PI:0,attackAim:0,grounded:true,platform:-1,coyote:.085,jumpBuffer:0,airJumps:1,doubleJumpTime:0,jumping:false,airUsed:false,dropTimer:0,move:0,state:'idle',stateTime:0,duration:0,dead:false,deathTime:0,dashCooldown:0,parryCooldown:0,dashX:0,dashY:0,dashRemaining:0,slideRemaining:0,wallSide:0,wallId:-1,lastWall:-1,wallLock:0,wallJumpTime:0,feintCooldown:0,kickCooldown:0,kickHit:false,queued:null,attackId:0,attackHit:false,guard:'normal',guardFacing:id?-1:1,anim:0,landing:0};}
class Game{
 resetSpecial(f){if(f.legacy)delete f.legacy.mirrorSpecial;f.specialCharge=0;f.fenceRemaining=0;f.dashLock=0;f.punch=0;f.ultMode='';f.ultTime=0;f.parryLock=0;f.breakAttackId=0;f.dagger=null;f.ultSide=f.facing;}
 special(id,copyKind=null){const f=this.fighters[id],kind=copyKind||f.kind;if(!this.rules.specials||!this.canAct(f)||!copyKind&&f.specialCharge+1e-6<this.rules.specialCooldown||f.ultMode||f.parryLock>0)return false;if(kind==='staff'&&!f.grounded)return false;if(!copyKind)f.specialCharge=0;f.ultSide=f.facing;f.attackAim=f.aim;f.attackHit=false;
  if(kind==='duelist')f.ultMode='fenceReady';
  if(kind==='staff')f.ultMode='sweepReady';
  if(kind==='boxer'){f.ultMode=this.rules.boxerWindow>0?'boxerGuard':'';f.ultTime=this.rules.boxerWindow/1000;if(!f.ultTime)f.dashLock=this.rules.boxerPenalty/1000;}
  if(kind==='knight'){f.ultMode='shield';f.ultTime=10;}
  if(kind==='reaper'){f.ultMode='reaperBoost';f.ultTime=10;}
  if(kind==='swordsman')f.ultMode='edge';
  if(kind==='lancer'){f.ultMode='charge';f.attackAim=f.ultSide>0?0:Math.PI;this.setState(f,'ultWindup',.3);}
  if(kind==='assassin'){f.ultMode='throw';this.setState(f,'throwWindup',.18);}
  this.emit('special',{id,kind:kind,x:f.x,y:f.y-body(f).center});return true;
 }
 endEdge(f){if(f.ultMode==='edgeStrike'){f.ultMode='';f.parryLock=4;f.breakAttackId=0;this.emit('specialEnd',{id:f.id});}}
 stopCharge(f){if(f.state!=='ultCharge')return;f.ultMode='';f.vx=0;this.setState(f,'ultRecovery',.4);this.emit('chargeStop',{id:f.id,x:f.x,y:f.y-body(f).center});}
 absorb(f,a){if(root.DuelLegacy?.protect(this,f,a))return true;if(f.admin?.invincible){if(a)a.attackHit=true;this.emit('adminAbsorb',{id:f.id});return true;}if(f.ultMode!=='shield')return false;f.ultMode='';f.ultTime=0;f.parryLock=4;if(a)a.attackHit=true;this.hitstop=.07;this.emit('shieldBreak',{id:f.id,x:f.x,y:f.y-body(f).center});return true;}
 lethal(a,d,reason){if(d.dead||this.absorb(d,a))return false;const impact=this.deathInfo(a,d);d.dead=true;d.deathTime=0;this.setState(d,'dead');this.finish(a.id,reason,{x:d.x,y:d.y-body(d).center,...impact});return true;}
 boxerParry(f){if(specialKind(f)==='boxer'&&f.ultMode==='boxerGuard'){f.ultMode=this.rules.boxerRush>0?'boxerRush':'';f.ultTime=this.rules.boxerRush/1000;this.emit('special',{id:f.id,kind:specialKind(f),x:f.x,y:f.y-body(f).center});}}
 tickSpecial(f,dt){if(f.dead)return;f.dashLock=Math.max(0,(f.dashLock||0)-dt);f.parryLock=Math.max(0,(f.parryLock||0)-dt);if(f.ultTime>0){f.ultTime=Math.max(0,f.ultTime-dt);if(!f.ultTime){if(f.ultMode==='boxerGuard'){f.ultMode='';f.dashLock=this.rules.boxerPenalty/1000;}else if(f.ultMode==='boxerRush')f.ultMode='';else if(f.ultMode==='shield'){f.ultMode='';f.parryLock=4;}else if(f.ultMode==='reaperBoost'){f.ultMode='reaperWeak';f.ultTime=10;}else if(f.ultMode==='reaperWeak')f.ultMode='';this.emit('specialEnd',{id:f.id});}}
  root.DuelLegacy?.finishMirrorSpecial(f);if(this.phase==='playing'&&this.rules.specials&&!f.legacy?.mirrorSpecial&&!f.ultMode&&f.parryLock<=0&&f.dashLock<=0)f.specialCharge=Math.min(this.rules.specialCooldown,(f.specialCharge||0)+dt);
 }
 daggerPoint(from,to){const fraction=Math.min(1,...this.map.walls.map(w=>wallFraction(from,to,w))),length=Math.hypot(to.x-from.x,to.y-from.y),t=fraction<1?Math.max(0,fraction-1.1/(length||1)):1;return{x:lerp(from.x,to.x,t),y:lerp(from.y,to.y,t),blocked:fraction<1};}
 daggerSafe(x,y){const points=this.map.platforms.map(p=>({x:clamp(x,p.x+Math.min(8,p.w/2),p.x+p.w-Math.min(8,p.w/2)),y:p.y-5})).filter(p=>!this.map.walls.some(w=>p.x>=w.x&&p.x<=w.x+w.w&&p.y>=w.y&&p.y<=w.y+w.h));points.sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y));return points[0]||{x:this.map.spawns[0].x,y:this.map.spawns[0].y-5};}
 throwDagger(f){const a=f.attackAim,from={x:f.x,y:f.y-body(f).center},p=this.daggerPoint(from,{x:from.x+Math.cos(a)*34,y:from.y+Math.sin(a)*34});f.ultMode='unarmed';f.dagger={x:p.x,y:p.y,vx:p.blocked?0:Math.cos(a)*1350,vy:p.blocked?40:Math.sin(a)*1350,mode:p.blocked?'dropped':'flying',time:0,safe:this.daggerSafe(f.x,f.y),pickup:.25};this.setState(f,'ultRecovery',.24);this.emit('daggerThrow',{id:f.id,x:f.dagger.x,y:f.dagger.y});}
 updateDaggers(dt){for(const owner of this.fighters){const p=owner.dagger;if(!p||owner.dead)continue;if(root.DuelLegacy?.daggerCarry(this,owner,p,dt))continue;const d=this.fighters.find(t=>!t.dead&&t.id!==owner.id&&(!this.pathEncounter||!!t.id!==!!owner.id));if(!d)continue;p.time+=dt;p.pickup=Math.max(0,p.pickup-dt);if(p.mode==='lost'){if(p.time>=2){Object.assign(p,{...p.safe,vx:0,vy:0,mode:'dropped',time:0,pickup:.2});}continue;}
   const from={x:p.x,y:p.y};if(p.mode==='dropped')p.vy+=1980*this.rules.gravity*dt;let to=this.daggerPoint(from,{x:p.x+p.vx*dt,y:p.y+p.vy*dt});if(to.blocked){p.vx=0;p.vy=40;p.mode='dropped';}
   if(root.DuelLegacy?.daggerIntercept(this,owner,p,from,to))continue;
   if(p.mode==='flying'&&!d.dead){const db=body(d),guard=blade(d).guard,hit=segmentDistance(from,to,{x:d.x,y:d.y-db.top},{x:d.x,y:d.y-db.bottom})<=db.radius+5,guardTouch=d.state==='parry'&&segmentDistance(from,to,guard.a,guard.b)<=8,angle=Math.atan2(from.y-(d.y-db.center),from.x-d.x),valid=d.state==='parry'&&(Math.abs(from.x-d.x)<.001||Math.sign(from.x-d.x)===d.guardFacing);
    if((hit||guardTouch)&&valid){d.guardVisual=guardSector(angle,false);d.guardVisualUntil=this.time+.18;p.mode='dropped';to=this.daggerPoint({x:d.x,y:d.y-db.center},{x:d.x+d.guardFacing*22,y:d.y-db.center});p.vx=to.blocked?0:d.guardFacing*65;p.vy=-110;p.pickup=.2;const perfect=d.stateTime<=Math.min(.08,d.duration)+1e-8;this.setState(d,'idle');d.lastPerfect=perfect?this.time:(d.lastPerfect??-100);this.boxerParry(d);d.parryCooldown=Math.min(d.parryCooldown,.18);this.hitstop=.07;this.emit('parry',{id:d.id,x:to.x,y:to.y,projectile:true,perfect,height:d.guardVisual,attackerKind:owner.kind});}
    else if(hit){if(this.absorb(d)){p.mode='dropped';p.vx=0;p.vy=30;}else{this.lethal(owner,d,'A adaga encontrou uma abertura.');}}
   }
   p.x=to.x;p.y=to.y;const supports=this.map.platforms.filter(q=>q.stage!=='gone'&&p.x>=q.x&&p.x<=q.x+q.w&&q.y>=p.y-6).sort((a,b)=>a.y-b.y);if(supports.length)p.safe={x:p.x,y:supports[0].y-5};
   if(p.mode==='dropped'&&p.vy>=0){const q=this.map.platforms.find(q=>q.stage!=='gone'&&p.x>=q.x&&p.x<=q.x+q.w&&from.y<=q.y+5&&p.y>=q.y-5);if(q){p.y=q.y-5;p.vy=0;p.vx=0;p.safe={x:p.x,y:p.y};}}
   if(p.x<0||p.x>this.map.width||p.y>this.map.deathY||p.mode==='flying'&&p.time>3){p.mode='lost';p.time=0;}
   if(p.mode==='dropped'&&p.pickup<=0&&Math.abs(owner.x-p.x)<29&&p.y>=owner.y-body(owner).top-15&&p.y<=owner.y+12){owner.dagger=null;owner.ultMode='';this.emit('daggerPickup',{id:owner.id,x:owner.x,y:owner.y});}
  }}
 adminApply(change){const score=[...this.score],round=this.round;if(change.action==='refill'){for(const f of this.fighters){f.dashCharges=this.rules.dashCount;f.dashCooldown=0;f.parryCooldown=0;f.airDashes=0;this.resetSpecial(f);f.specialCharge=this.rules.specialCooldown;}return;}
  const options={mode:this.mode,ai:this.aiEnabled,difficulty:this.difficulty,characters:change.characters||this.characters,skins:change.skins||this.skins,colors:change.colors||this.colors,mapId:change.mapId||this.mapId,rules:change.rules||this.rules,experimental:true};this.start(options);this.score=score;this.round=round;if(Array.isArray(change.positions))for(let i=0;i<2;i++)for(const k of['x','y'])if(Number.isFinite(change.positions[i]?.[k])){this.fighters[i][k]=change.positions[i][k];this.fighters[i].grounded=false;this.fighters[i].platform=-1;}this.emit('adminReset');const winner=this.score.findIndex((n,i)=>n>=this.rules.winningScore&&n>this.score[1-i]);if(winner>=0&&this.mode!=='training'){this.phase='matchEnd';this.emit('matchEnd',{winner});}
 }

 constructor(o={}){this.random=o.random||Math.random;this.mode='pve';this.difficulty='normal';this.characters=['knight','knight'];this.colors=['jade','coral'];this.skins=['default','default'];this.mapId='dojo';this.rules=cleanRules();this.configure(o);this.events=[];this.time=0;this.round=1;this.score=[0,0];this.phase='title';this.hitstop=0;this.roundTimer=0;this.attackCounter=0;this.lastReason='';this.fallTimer=0;this.habits={attacks:0,parries:0,whiffs:0,jumps:0,retreat:0};this.resetFighters();}
 configure(o={}){if(['day','night'].includes(o.timeOfDay))this.timeOfDay=o.timeOfDay;if(typeof o.roundEntries==='boolean')this.roundEntries=o.roundEntries;if(['pve','local','online','training'].includes(o.mode))this.mode=o.mode;if(DIFFICULTIES[o.difficulty])this.difficulty=o.difficulty;if(o.characters)this.characters=[0,1].map(i=>CLASSES[o.characters[i]]?o.characters[i]:'knight');if(o.skins)this.skins=[0,1].map(i=>cleanSkin(this.characters[i],o.skins[i]));else this.skins=this.skins.map((s,i)=>cleanSkin(this.characters[i],s));if(o.colors)this.colors=[0,1].map(i=>COLORS[o.colors[i]]?o.colors[i]:(i?'coral':'jade'));if(this.colors[0]===this.colors[1])this.colors[1]=Object.keys(COLORS).find(c=>c!==this.colors[0]);if(MAPS[o.mapId])this.mapId=o.mapId;if(typeof o.experimental==='boolean')this.experimental=o.experimental;if(o.rules)this.rules=cleanRules(o.rules,this.experimental);this.aiEnabled=typeof o.ai==='boolean'?o.ai:this.mode==='pve';this.mapSource=o.mapData?cleanMap(o.mapData):MAPS[this.mapId];this.map=makeMap(this.mapId,this.rules.mapSize,this.mapSource);this.routeCache=new Map();}
 resetFighters(preserve=false){const charges=preserve&&this.rules.specials&&this.rules.persistSpecial?this.fighters?.map(f=>f.specialCharge)||[]:[];for(const p of this.map.platforms){p.stage="solid";p.crumbleAt=p.goneAt=null;}this.fighters=[0,1].map(i=>makeFighter(i,this.characters[i],this.colors[i],this.map.spawns[i]));for(const f of this.fighters){f.skin=this.skins[f.id];this.resetSpecial(f);f.specialCharge=clamp(charges[f.id]||0,0,this.rules.specialCooldown);f.dashCharges=this.rules.dashCount;f.airDashes=0;}for(const f of this.fighters)f.platform=this.map.platforms.findIndex(p=>f.x>=p.x&&f.x<=p.x+p.w&&f.y===p.y);this.ai={timer:.3,intent:0,seen:0,reaction:-1,answer:0,attackDelay:.5,jumpDelay:.6,bait:false,navTarget:-1};this.fallTimer=0;}
 start(o){if(o)this.configure(o);this.time=0;this.round=1;this.score=[0,0];this.phase='playing';this.hitstop=0;this.roundTimer=0;this.attackCounter=0;this.lastReason='';this.habits={attacks:0,parries:0,whiffs:0,jumps:0,retreat:0};this.events=[];this.resetFighters();this.emit('start');}
 emit(type,data={}){this.events.push({type,...data});}
 between(a,b){return lerp(a,b,this.random());}
 setState(f,state,duration=0){if(f.state==='active'&&state!=='active')this.endEdge(f);if(['fenceStrike','sweepStrike'].includes(f.ultMode)&&['clash','stunned','recovery','pushed','dead'].includes(state)){if(state==='clash'){state='recovery';duration=.72/this.rules.attackSpeed*this.rules.attackRecovery;}f.ultMode='';f.fenceRemaining=0;}if(['ultCharge','ultWindup','throwWindup'].includes(f.state)&&['stunned','clash','pushed','dead'].includes(state))f.ultMode='';f.state=state;f.stateTime=0;f.duration=duration;if(duration===0&&state==='parry'){f.state='parryRecovery';f.duration=this.rules.parryRecovery/1000;}if(f.duration===0&&['recovery','parryRecovery','dashRecovery','slideRecovery','stunned'].includes(f.state))f.state='idle';if(['stunned','clash','pushed','dead'].includes(state)){f.dashRemaining=0;f.slideRemaining=0;f.queued=null;}}
 canAct(f){return!f.dead&&f.state==='idle'&&this.phase==='playing';}
 attack(id){const f=this.fighters[id];if(f.ultMode==='unarmed'||f.legacy?.effects?.mist>0)return false;if(!this.canAct(f)&&!(['dash','slide'].includes(f.state)&&!f.dead&&this.phase==='playing'))return false;if(specialKind(f)==='staff'&&f.ultMode==='sweepReady'&&!f.grounded)return false;if((root.DuelLegacy?.weaponKind(f)||f.kind)==='boxer')f.punch=1-(f.punch||0);if(f.ultMode==='fenceReady'){f.ultMode='fenceStrike';f.fenceRemaining=.135;f.fenceAngle=f.aim;f.jumpBuffer=0;f.dashRemaining=f.slideRemaining=0;}if(f.ultMode==='sweepReady'){f.ultMode='sweepStrike';f.jumpBuffer=0;f.dashRemaining=f.slideRemaining=0;f.vx=0;}f.attackAim=f.aim;f.attackId=++this.attackCounter;f.attackHit=false;this.setState(f,'startup',stats(f).startup/this.rules.attackSpeed);if(!id)this.habits.attacks++;this.emit('windup',{id});return true;}
 parry(id){const f=this.fighters[id],s=stats(f);if(f.state==='startup'||f.state==='active'&&f.stateTime<=.06&&!f.attackHit)return this.feint(id);if(!this.canAct(f)||f.parryCooldown>0||f.parryLock>0)return false;f.guard='normal';f.guardFacing=aimSide(f.aim,f.facing);f.guardVisual='normal';this.setState(f,'parry',this.rules.parryWindow/1000);f.parryCooldown=(this.rules.parryWindow+this.rules.parryRecovery)/1000;if(!id)this.habits.parries++;this.emit('guard',{id});return true;}
 feint(id){const f=this.fighters[id];if(['fenceStrike','sweepStrike'].includes(f.ultMode))return false;if(f.dead||!(f.state==='startup'||f.state==='active'&&f.stateTime<=.06&&!f.attackHit)||f.feintCooldown>0)return false;this.setState(f,'feintRecovery',.15);f.feintCooldown=.45;f.queued=null;this.emit('feint',{id});return true;}
 kick(id){const f=this.fighters[id];if(!this.canAct(f)||f.kickCooldown>0)return false;f.kickHit=false;f.kickSide=f.facing;f.kickCooldown=.7;this.setState(f,'kickStartup',.16);this.emit('kickWindup',{id});return true;}
 command(id,action,inp){const f=this.fighters[id],ok=action==='dash'?this.dash(id,inp.move,inp.down,inp.up):this[action](id);if(ok){f.queued=null;return true;}if(['recovery','parryRecovery','dashRecovery','slideRecovery','kickRecovery','feintRecovery','stunned','clash','pushed','dash','slide'].includes(f.state)&&f.duration-f.stateTime<=.08)f.queued={action,ttl:.085,move:inp.move,down:inp.down,up:!!inp.up,aim:inp.aim};return false;}
 dash(id,move=0,down=false,up=false){const f=this.fighters[id],s=stats(f);if(f.dashLock>0||!(this.canAct(f)||['dashRecovery','slideRecovery'].includes(f.state)&&f.dashCharges>0)||f.dashRemaining>0||f.dashCharges<1||(!f.grounded&&(!this.rules.airDash||f.airDashes>=this.rules.dashCount)))return false;
  let x=Math.cos(f.aim),y=Math.sin(f.aim);if(Math.abs(move)>.1){const slope=Math.min(Math.PI/3,Math.asin(Math.abs(y)));x=Math.sign(move)*Math.cos(slope);y=Math.sign(y)*Math.sin(slope);}if(f.grounded&&y>0){x=Math.sign(x)||f.facing;y=0;}
  if(!f.grounded){x=Math.abs(move)>.1?Math.sign(move):0;y=(down?1:0)-(up?1:0);if(!x&&!y)x=f.facing;const length=Math.hypot(x,y);x/=length;y/=length;}
  f.groundDashTail=f.grounded?s.dash+this.rules.dashRecovery/1000:0;const slide=down&&f.grounded;if(slide){x=Math.sign(move)||f.facing;y=0;}f.dashX=x;f.dashY=y;f.dashRemaining=slide?.28:s.dash;f.slideRemaining=slide?.42:0;f.airUsed=true;f.airDashes++;f.dashCharges--;if(f.dashCooldown<=0)f.dashCooldown=this.rules.dashCooldown/1000;this.setState(f,slide?'slide':'dash',f.dashRemaining);this.emit(slide?'slide':'dash',{id});return true;
 }
 tickState(f,dt){this.tickSpecial(f,dt);for(const k of['doubleJumpTime','groundDashTail','slideRemaining','wallLock','wallJumpTime','feintCooldown','kickCooldown'])f[k]=Math.max(0,(f[k]||0)-dt);if(f.queued){f.queued.ttl-=dt;if(f.queued.ttl<=0)f.queued=null;}if(f.dashCharges<this.rules.dashCount){f.dashCooldown=Math.max(0,f.dashCooldown-dt);if(f.dashCooldown<=0){f.dashCharges=this.rules.dashCooldown<=0?this.rules.dashCount:Math.min(this.rules.dashCount,f.dashCharges+1);f.dashCooldown=f.dashCharges<this.rules.dashCount?this.rules.dashCooldown/1000:0;}}else f.dashCooldown=0;f.parryCooldown=Math.max(0,f.parryCooldown-dt);f.dropTimer=Math.max(0,f.dropTimer-dt);f.landing=Math.max(0,f.landing-dt);f.stateTime+=dt;
  if(f.dead){f.deathTime+=dt;return;}
  if(f.dashRemaining>0){f.dashRemaining=Math.max(0,f.dashRemaining-dt);if(!f.dashRemaining){f.vx*=.45;f.vy*=.55;if(['dash','slide'].includes(f.state))this.setState(f,f.dashCharges>0?'idle':f.state==='slide'?'slideRecovery':'dashRecovery',f.dashCharges>0?0:this.rules.dashRecovery/1000);}}
  if(f.duration&&f.stateTime>=f.duration){const s=stats(f),old=f.state;if(old==='ultWindup'){this.setState(f,'ultCharge',1e6);f.attackId=++this.attackCounter;f.attackHit=false;this.emit('chargeStart',{id:f.id});}else if(old==='throwWindup'){this.throwDagger(f);}else if(old==='kickStartup'){this.setState(f,'kickActive',.10);}else if(old==='kickActive'){this.setState(f,'kickRecovery',.27);}else if(old==='startup'){this.setState(f,'active',s.active/this.rules.attackSpeed);if(f.ultMode==='edge'){f.ultMode='edgeStrike';f.breakAttackId=f.attackId;}this.emit('swing',{id:f.id});}else if(old==='active'){const recovery=f.ultMode==='fenceStrike'?.62:s.recovery;this.setState(f,'recovery',recovery/this.rules.attackSpeed*this.rules.attackRecovery);if(!f.attackHit){if(!f.id)this.habits.whiffs++;this.emit('whiff',{id:f.id});}}else if(old==='parry'){this.setState(f,'parryRecovery',this.rules.parryRecovery/1000);this.emit('parryMiss',{id:f.id});}else if(old==='dash'){this.setState(f,'dashRecovery',this.rules.dashRecovery/1000);}else this.setState(f,'idle');}
 }
 moveFighter(f,inp,dt){if(f.dead)return;if(root.DuelLegacy?.attackTechnique(f)){inp={...inp,move:0,jump:false,jumpHeld:true};f.jumpBuffer=0;}const s=stats(f),r=root.DuelLegacy?.movementRules(this,f)||this.rules,oldX=f.x,wasGrounded=f.grounded;if(f.grounded&&f.platform>=0){const platform=this.map.platforms[f.platform];if(platform?.stage==='gone'){f.grounded=false;f.platform=-1;}else if(platform?.motion){f.x+=platform.dx||0;f.y+=platform.dy||0;}}const oldY=f.y;
  f.aim=Number.isFinite(inp.aim)?inp.aim:f.aim;f.facing=aimSide(f.aim,f.facing);f.move=clamp(inp.move||0,-1,1);if(f.admin?.fly){const dx=f.move,dy=(inp.down?1:0)-(inp.jumpHeld?1:0),length=Math.max(1,Math.hypot(dx,dy));f.vx=dx/length*s.speed*r.speed*1.5;f.vy=dy/length*s.speed*r.speed*1.5;f.x=clamp(f.x+f.vx*dt,24,this.map.width-24);f.y=clamp(f.y+f.vy*dt,90,this.map.height-10);f.grounded=false;f.platform=-1;f.anim+=Math.abs(f.vx)*dt*.026;return;}if(f.ultMode==='sweepStrike'){inp={...inp,jump:false,jumpHeld:false,move:0};f.move=0;f.vx=0;}if(f.ultMode==='fenceStrike'){inp={...inp,jump:false,jumpHeld:true,move:0};f.move=0;}f.coyote=f.grounded?.085:Math.max(0,f.coyote-dt);f.jumpBuffer=inp.dash||f.dashRemaining>0?0:inp.jump?.09:Math.max(0,f.jumpBuffer-dt);
  if(f.jumpBuffer>0&&!f.grounded&&f.wallSide&&f.wallLock<=0&&(f.wallId!==f.lastWall||f.wallReleased)&&!['stunned','clash','pushed','dead','ultCharge','ultWindup','throwWindup'].includes(f.state)&&f.dashRemaining<=0){const high=inp.up||inp.move*f.wallSide>=0;f.vx=-f.wallSide*(high?280:470);f.vy=-(high?940:810)*r.jump;f.wallLock=.10;f.wallReleased=false;f.wallJumpTime=.23;f.lastWall=f.wallId;f.jumpBuffer=0;f.jumping=true;f.coyote=0;this.emit('wallJump',{id:f.id,side:f.wallSide,x:f.x+f.wallSide*C.radius,y:f.y-body(f).center});}
  if(f.jumpBuffer>0&&f.dashRemaining<=0&&!['dash','slide','stunned','clash','pushed','dead','ultCharge','ultWindup','throwWindup'].includes(f.state)&&this.phase==='playing'&&(f.grounded||f.coyote>0)){
   const platform=this.map.platforms[f.platform];if(inp.down&&platform&&!platform.solid){f.dropTimer=.22;f.y+=3;f.grounded=false;f.coyote=0;}else{f.vy=-940*r.jump;f.grounded=false;f.jumping=true;f.coyote=0;this.emit('jump',{id:f.id});if(!f.id)this.habits.jumps++;}f.jumpBuffer=0;
  }
  if(f.jumpBuffer>0&&!f.grounded&&f.coyote<=0&&f.airJumps>0&&f.dashRemaining<=0&&this.phase==='playing'&&!['dash','slide','stunned','clash','pushed','dead','ultCharge','ultWindup','throwWindup'].includes(f.state)){
   f.airJumps--;f.vy=-875*r.jump;f.vx=clamp(f.vx,-s.speed*r.speed,s.speed*r.speed);f.jumpBuffer=0;f.jumping=true;f.doubleJumpTime=.20;f.fastFalling=false;this.emit('doubleJump',{id:f.id,x:f.x,y:f.y});if(!f.id)this.habits.jumps++;
  }
  if(f.jumping&&!inp.jumpHeld&&f.vy<-250){f.vy*=.48;f.jumping=false;}
  if(root.DuelLegacy?.techniqueVelocity(this,f,dt)){}else if(root.DuelLegacy?.impulseVelocity(this,f,inp,dt)){}else if(f.ultMode==='fenceStrike'&&f.fenceRemaining>0){f.vx=Math.cos(f.fenceAngle)*980;f.vy=Math.sin(f.fenceAngle)*980;f.fenceRemaining=Math.max(0,f.fenceRemaining-dt);if(f.vy<0)f.grounded=false;}else if(f.state==='ultCharge'){f.vx=f.ultSide*2200;f.vy+=1980*r.gravity*dt;}else if(f.dashRemaining>0){f.vx=f.dashX*s.dashSpeed*r.dashDistance*(f.slideRemaining>0?.55:1);f.vy=f.dashY*s.dashSpeed*r.dashDistance;if(f.vy<0)f.grounded=false;}
  else{
   const attacking=['startup','active','recovery'].includes(f.state),locked=['stunned','clash','pushed'].includes(f.state),target=f.move*s.speed*r.speed*(attacking&&f.grounded?.7:1),accel=(f.groundDashTail>0?(f.grounded?3800:1100):['dashRecovery','slideRecovery'].includes(f.state)?3800:f.grounded?(f.move?9800:15000):2600)*(locked?0:1)*(root.DuelLegacy?.friction(this,f)??1);
   if(!locked&&f.wallLock<=0)f.vx+=clamp(target-f.vx,-accel*dt,accel*dt);else if(locked)f.vx*=Math.exp(-5*dt);
   f.vy+=1980*r.gravity*(f.legacy?.effects?.inverted?-1:1)*(inp.down&&f.vy>0?1.7:1)*dt;
  }
  root.DuelLegacy?.flightVelocity(this,f,inp,dt);root.DuelLegacy?.wallClothingVelocity(this,f,inp,dt);f.wallSliding=!f.grounded&&f.wallSide&&f.move*f.wallSide>.1&&f.vy>0&&f.wallLock<=0&&f.dashRemaining<=0&&!['stunned','clash','pushed','ultCharge','ultWindup'].includes(f.state);if(f.wallSliding)f.vy=Math.min(f.vy,155*r.gravity);if(!f.wallSide&&f.wallLock<=0)f.wallReleased=true;f.fastFalling=!!(inp.down&&!f.grounded&&f.vy>0&&!f.wallSliding);
  f.x=f.state==='ultCharge'?f.x+f.vx*dt:clamp(f.x+f.vx*dt,24*SCALE,this.map.width-24*SCALE);f.y+=f.vy*dt;f.grounded=false;f.platform=-1;
  if(f.vy>=0&&!f.legacy?.effects?.phasing){for(let i=0;i<this.map.platforms.length;i++){const p=this.map.platforms[i];if(p.stage==='gone'||f.dropTimer>0&&!p.solid)continue;if(f.x+C.radius*.7>p.x&&f.x-C.radius*.7<p.x+p.w&&oldY<=p.y+.5&&f.y>=p.y){f.y=p.y;f.vy=0;f.grounded=true;f.platform=i;f.jumping=false;if(!wasGrounded){f.landing=.15;if(f.dashRemaining<=0)f.airUsed=false;this.emit('land',{id:f.id});}break;}}}
  if(this.map.path||!f.legacy?.effects?.phasing)this.collideWalls(f,oldX,oldY);
  if(f.grounded){f.airJumps=1+(root.DuelLegacy?.has(f,'wingboot')?1:0);f.lastWall=-1;if(f.dashRemaining<=0){f.airUsed=false;f.airDashes=0;}}
  if(!f.wallSide||f.grounded||inp.move*f.wallSide<=0)f.wallSliding=false;
  f.anim+=Math.abs(f.vx)*dt*.026;
 }
  updatePlatforms(time,carry=true){for(let i=0;i<this.map.platforms.length;i++){const p=this.map.platforms[i];let x=p.baseX,y=p.baseY;if(p.motion){const m=p.motion,t=time*this.rules.platformSpeed;if(m.route){const span=m.period,wait=m.pause||0,cycle=span*2+wait*2,z=t%cycle,a=z<wait?0:z<wait+span?(z-wait)/span:z<wait*2+span?1:1-(z-wait*2-span)/span;x+=m.x*a;y+=m.y*a;}else y+=Math.sin(t*Math.PI*2/m.period)*m.y;}p.dx=carry?x-p.x:0;p.dy=carry?y-p.y:0;p.x=x;p.y=y;
  if(!carry||!p.fragile||this.phase!=='playing')continue;const occupied=this.fighters.some(f=>!f.dead&&f.grounded&&f.platform===i);
  if(p.stage==='solid'&&occupied){p.stage='cracking';p.crumbleAt=time;this.emit('crack',{x:p.x+p.w/2,y:p.y});}
  if(p.stage==='cracking'&&time-p.crumbleAt>=p.fragile.delay*this.rules.collapseSpeed){p.stage='gone';p.goneAt=time;this.routeCache.clear();for(const f of this.fighters)if(f.platform===i){f.grounded=false;f.platform=-1;f.coyote=.06;}this.emit('collapse',{x:p.x+p.w/2,y:p.y});}
  if(p.stage==='gone'&&p.fragile.respawn>0&&time-p.goneAt>=p.fragile.respawn*this.rules.respawnSpeed&&!this.fighters.some(f=>!f.dead&&f.x+20>p.x&&f.x-20<p.x+p.w&&f.y>=p.y-12&&f.y-body(f).top<=p.y+20)){p.stage='solid';p.crumbleAt=p.goneAt=null;this.routeCache.clear();}
 }}

 collideWalls(f,oldX=f.x,oldY=f.y){if(this.map.pathEnclosed){const ws=this.map.walls.filter(w=>w.pathBoundary).sort((a,b)=>a.x-b.x),b=body(f);if(ws.length===2)f.x=clamp(f.x,ws[0].x+ws[0].w+b.radius,ws[1].x-b.radius);}f.wallSide=0;f.wallId=-1;const b=body(f);for(let i=0;i<this.map.walls.length;i++){const w=this.map.walls[i];const crosses=(oldX+b.radius<=w.x&&f.x+b.radius>=w.x)||(oldX-b.radius>=w.x+w.w&&f.x-b.radius<=w.x+w.w);if(!crosses&&(f.x+b.radius<w.x-.001||f.x-b.radius>w.x+w.w+.001)||f.y-b.bottom-b.radius<=w.y||f.y-b.top-b.radius>=w.y+w.h)continue;
   if(oldY-b.top-b.radius>=w.y+w.h&&f.vy<0){f.y=w.y+w.h+b.top+b.radius;f.vy=0;continue;}
   if(w.x+w.w+b.radius>this.map.width-24*SCALE||w.x-b.radius>=24*SCALE&&(oldX<=w.x||f.x<w.x+w.w/2)){f.x=w.x-b.radius;f.wallSide=1;if(f.vx>0)f.vx=0;}else{f.x=w.x+w.w+b.radius;f.wallSide=-1;if(f.vx<0)f.vx=0;}f.wallId=i;if(f.state==='ultCharge')this.stopCharge(f);if(f.dashRemaining>0){f.dashRemaining=0;if(['dash','slide'].includes(f.state))this.setState(f,'dashRecovery',.09);}
  }}
 bodyContact(a,d){return polygonSegment(slash(a,this.map.walls).points,{x:d.x,y:d.y-body(d).top},{x:d.x,y:d.y-body(d).bottom},body(d).radius);}
 incomingSector(a,d){const poly=slash(a,this.map.walls).points,center={x:d.x,y:d.y-C.bodyCenter};let best=center,dist=Infinity;for(let i=0;i<poly.length;i++){const p=nearest(center,poly[i],poly[(i+1)%poly.length]),n=Math.hypot(p.x-center.x,p.y-center.y);if(n<dist){best=p;dist=n;}}const dx=a.x-d.x,dy=a.y-d.y;return{sector:guardSector(Math.atan2(dy,dx),false),side:Math.sign(dx)||1,point:best};}
 resolveCombat(){const[p,e]=this.fighters;if(p.dead||e.dead)return;const ps=slash(p,this.map.walls),es=slash(e,this.map.walls);
  if(p.state!=='ultCharge'&&e.state!=='ultCharge'&&polygonsIntersect(ps.points,es.points)){for(const f of[p,e]){f.attackHit=true;this.setState(f,'clash',.16);f.vx=(f.x<(f===p?e:p).x?-1:1)*170*(root.DuelLegacy?.knockbackScale(f)??1);}this.hitstop=.055;this.emit('clash',{kinds:[p.kind,e.kind],kind:p.kind,x:(p.x+e.x)/2,y:(p.y+e.y)/2-C.bodyCenter});return;}
  const hits=[];for(const[a,d]of[[p,e],[e,p]]){if(!['active','ultCharge'].includes(a.state)||a.attackHit)continue;const body=this.bodyContact(a,d),g=blade(d).guard,guardTouch=d.state==='parry'&&polygonSegment(slash(a,this.map.walls).points,g.a,g.b,C.bladeWidth);if(!body&&!guardTouch){const db=DuelBody(d);if(polygonSegment(slash(a,this.map.walls).points,{x:d.x,y:d.y-db.top},{x:d.x,y:d.y-db.bottom},db.radius+9))a.nearCandidate={id:d.id,x:d.x,y:d.y-db.center};continue;}const incoming=this.incomingSector(a,d);if(a.ultMode==='sweepStrike'){incoming.sector=d.grounded?'normal':'low';incoming.side=Math.sign(a.x-d.x)||a.facing;}const valid=a.state!=='ultCharge'&&!(a.breakAttackId&&a.breakAttackId===a.attackId)&&d.state==='parry'&&(Math.abs(a.x-d.x)<.001||incoming.side===d.guardFacing);
   if(valid){const disarmEligible=root.DuelLegacy?.canDisarm(a)??false;d.guardVisual=incoming.sector;d.guardVisualUntil=this.time+.18;a.attackHit=true;this.setState(a,'stunned',this.rules.stun/1000);a.vx=(a.x<d.x?-1:1)*120*(root.DuelLegacy?.knockbackScale(a)??1);const perfect=d.stateTime<=Math.min(.08,d.duration)+1e-8;this.setState(d,'idle');d.lastPerfect=perfect?this.time:(d.lastPerfect??-100);this.boxerParry(d);d.parryCooldown=Math.min(d.parryCooldown,.22);this.hitstop=.07;this.emit('parry',{id:d.id,attacker:a.id,attackerKind:a.kind,disarmEligible,height:incoming.sector,side:incoming.side,...incoming.point,perfect});return;}if(body){a.attackHit=true;if(!this.absorb(d,a))hits.push([a,d]);}
  }
  if(!hits.length)for(const[a,d]of[[p,e],[e,p]]){if(a.state!=='kickActive'||a.kickHit)continue;const y=a.y-body(a).center+12,from={x:a.x+a.kickSide*18,y},to={x:a.x+a.kickSide*56,y},db=body(d);if(!this.map.walls.some(w=>wallFraction({x:a.x,y},{x:d.x,y},w)<1)&&segmentDistance(from,to,{x:d.x,y:d.y-db.top},{x:d.x,y:d.y-db.bottom})<=db.radius+9){a.kickHit=true;this.setState(d,'pushed',.12);d.vx=a.kickSide*570*(root.DuelLegacy?.knockbackScale(d)??1);d.vy=Math.min(d.vy,-85*(root.DuelLegacy?.knockbackScale(d)??1));d.grounded=false;this.hitstop=.035;this.emit('kick',{id:a.id,x:d.x,y:d.y-db.center});}}
  if(hits.length){const trade=hits.length===2,winner=trade?-1:hits[0][0].id;const impact=this.deathInfo(hits[0][0],hits[0][1]);for(const[,d]of hits){if(d!==hits[0][1])this.deathInfo(hits[1][0],d);d.dead=true;d.deathTime=0;this.setState(d,'dead');}const d=hits[0][1];const reason=trade?'Os dois cortes chegaram juntos.':d.stateBefore==='recovery'?'O golpe errado abriu sua recuperação.':d.stateBefore==='parryRecovery'?'O parry terminou antes de o corte chegar.':d.stateBefore==='parry'?'O corte veio por fora da direção protegida.':d.stateBefore==='dash'?'O dash entrou no alcance do corte.':d.stateBefore==='stunned'?'O parry abriu espaço para o contra-ataque.':'O corte encontrou uma abertura.';this.finish(winner,reason,{x:d.x,y:d.y-C.bodyCenter,trade,...impact,cause:trade?'TROCA':impact.cause});}
 }
 finish(winner,reason,data={}){if(this.phase!=='playing')return;if(winner>=0&&this.mode!=='training')this.score[winner]++;this.phase='roundEnd';this.roundTimer=this.mode==='training'?.6:C.roundPause;this.hitstop=.095;this.lastReason=reason;this.emit('kill',{winner,reason,trade:winner<0,...data});}
 separateBodies(){const[a,b]=this.fighters;if(root.DuelLegacy?.crossing(a)||root.DuelLegacy?.crossing(b)||a.state==='ultCharge'||b.state==='ultCharge'||a.dead||b.dead||a.y-body(a).bottom+body(a).radius<b.y-body(b).top-body(b).radius||b.y-body(b).bottom+body(b).radius<a.y-body(a).top-body(a).radius)return;const dx=b.x-a.x,overlap=35*SCALE-Math.abs(dx);if(overlap>0){const sign=dx>=0?1:-1;a.x=clamp(a.x-overlap*.5*sign,24*SCALE,this.map.width-24*SCALE);b.x=clamp(b.x+overlap*.5*sign,24*SCALE,this.map.width-24*SCALE);if(a.vx*sign>0)a.vx=0;if(b.vx*sign<0)b.vx=0;}}
 getAIPolicy(){const base=DIFFICULTIES[this.difficulty],h=this.habits,total=h.attacks+h.parries+1,confidence=clamp(total/14,0,1);return{...base,attack:clamp(base.attack+(this.difficulty==='adaptive'?Math.min(.12,h.retreat/100):0),0,1),parry:clamp(base.parry+(this.difficulty==='adaptive'?confidence*(h.attacks/total-.4)*.5:0),0,1),bait:this.difficulty==='adaptive'?.14+confidence*h.parries/total*.55:.15,punish:this.difficulty==='easy'?.4:this.difficulty==='adaptive'?.65+Math.min(.3,h.whiffs/total*.4):.85,learned:this.difficulty==='adaptive'&&total>6};}
 nextPlatform(f,goal){const key=f.kind+':'+f.platform+':'+goal;if(this.routeCache.has(key))return this.routeCache.get(key);const ps=this.map.platforms,start=f.platform,cost=ps.map(()=>Infinity),prev=ps.map(()=>-1),open=new Set(ps.map((_,i)=>i).filter(i=>ps[i].stage!=='gone'));cost[start]=0;const speed=stats(f).speed*this.rules.speed,jump=940*this.rules.jump,gravity=1980*this.rules.gravity;
  while(open.size){let i=-1;for(const j of open)if(i<0||cost[j]<cost[i])i=j;if(!Number.isFinite(cost[i])||i===goal)break;open.delete(i);const a=ps[i];for(const j of open){const b=ps[j],rise=a.y-b.y,disc=jump*jump-2*gravity*rise;const extra=875*this.rules.jump,maxRise=(jump*jump+extra*extra)/(2*gravity);if(rise>maxRise*.92)continue;const gap=Math.max(0,Math.max(a.x,b.x)-Math.min(a.x+a.w,b.x+b.w)),flight=disc>=0?(jump+Math.sqrt(disc))/gravity:(jump+extra+Math.sqrt(Math.max(0,extra*extra-2*gravity*(rise-jump*jump/(2*gravity)))))/gravity;if(gap+38>speed*flight*.88)continue;const candidate=cost[i]+gap+Math.abs(rise)*.3+65;if(candidate<cost[j]){cost[j]=candidate;prev[j]=i;}}}
  let next=goal;if(prev[next]<0)next=-1;else while(prev[next]!==start&&prev[next]>=0)next=prev[next];this.routeCache.set(key,next);return next;
 }
 navigateAI(e,p,inp){const ai=this.ai,ps=this.map.platforms,s=stats(e);if(e.grounded){ai.navTarget=-1;if(e.platform<0)return;const goal=p.grounded?p.platform:ps.findIndex(q=>q.stage!=='gone'&&p.y<=q.y+20&&p.x>=q.x&&p.x<=q.x+q.w);if(goal<0||goal===e.platform)return;const next=this.nextPlatform(e,goal);if(next<0)return;const q=ps[next],target=clamp(e.x,q.x+30,q.x+q.w-30),dx=target-e.x,rise=e.y-q.y,disc=(940*this.rules.jump)**2-2*1980*this.rules.gravity*rise;const flight=disc>=0?(940*this.rules.jump+Math.sqrt(disc))/(1980*this.rules.gravity):1.1*this.rules.jump/this.rules.gravity,launch=Math.min(190,s.speed*this.rules.speed*flight*.67);inp.jump=false;inp.down=false;inp.move=Math.abs(dx)>9?Math.sign(dx):0;
   if(rise<-15&&!ps[e.platform].solid&&e.x>q.x+10&&e.x<q.x+q.w-10){inp.down=true;inp.jump=true;inp.jumpHeld=false;ai.navTarget=next;ai.jumpDelay=.25;return true;}
   if(Math.abs(dx)<=launch&&ai.jumpDelay<=0&&!['stunned','clash'].includes(e.state)){inp.jump=true;inp.jumpHeld=true;inp.down=false;ai.navTarget=next;ai.jumpDelay=.25;}else if(Math.abs(dx)<=launch)inp.move=0;return true;
  }else if(ai.navTarget>=0){const q=ps[ai.navTarget];if(!q||e.y>q.y+30&&e.vy>0&&!e.airJumps){ai.navTarget=-1;return;}const target=clamp(p.x,q.x+38,q.x+q.w-38),dx=target-e.x;inp.move=clamp(dx*.025-e.vx*.002,-1,1);inp.jumpHeld=e.vy<0;if(e.airJumps>0&&e.dashRemaining<=0&&ai.jumpDelay<=0&&e.vy>-120&&(e.y>q.y-45||Math.abs(dx)>85)){inp.jump=true;inp.jumpHeld=true;inp.dash=false;inp.down=false;ai.jumpDelay=.3;}return true;}
 }
 updateAI(dt){const p=this.fighters[0],e=this.fighters[1],ai=this.ai,s=stats(e),policy=this.getAIPolicy(),dx=p.x-e.x,dy=p.y-e.y,dist=Math.hypot(dx,dy),toward=Math.sign(dx)||1,impossible=this.difficulty==='impossible';const inp=neutral();inp.aim=Math.atan2(dy,dx);inp.move=ai.intent;inp.jumpHeld=e.vy<0;ai.timer-=dt;ai.attackDelay-=dt;ai.jumpDelay-=dt;
  if(p.dead||e.dead)return inp;
  if(p.state==='startup'&&p.attackId!==ai.seen){ai.seen=p.attackId;ai.reaction=this.between(...policy.reaction);ai.answer=this.random();}
  if(ai.reaction>=0){ai.reaction-=dt;if(ai.reaction<=0&&['startup','active'].includes(p.state)&&dist<stats(p).reach+55&&this.canAct(e)){if(ai.answer<policy.parry){const from=Math.atan2(p.y-e.y,p.x-e.x);inp.aim=from;inp.parry=true;}else if(ai.answer<.92){ai.intent=-toward;inp.move=-toward;inp.dash=this.random()<.3;}ai.reaction=-1;}}
  if(impossible&&this.canAct(e)&&['startup','active'].includes(p.state)){const probe={...p,state:'active',duration:stats(p).active/this.rules.attackSpeed,stateTime:Math.max(0,p.state==='active'?p.stateTime:p.stateTime-p.duration)+.025};if(this.bodyContact(probe,e)){const incoming=this.incomingSector(probe,e);inp.aim=incoming.sector==='high'?-Math.PI/2:incoming.sector==='low'?Math.PI/2:incoming.side>0?0:Math.PI;inp.parry=true;}}
  if(ai.timer<=0){ai.timer=this.between(.09,.19);const roll=this.random(),inRange=dist<s.reach-9&&dist>s.minRange;
   if(inRange&&ai.attackDelay<=0&&p.state!=='parry'&&((['recovery','parryRecovery','stunned'].includes(p.state)&&p.stateTime>(impossible?0:.11)&&roll<policy.punish)||roll<policy.attack)){inp.attack=true;ai.attackDelay=this.between(.38,.85)*(this.difficulty==='easy'?1.4:1);ai.intent=0;}
   else if(dist<s.minRange+15)ai.intent=-toward;
   else if(dist>s.reach-28)ai.intent=toward;
   else if(roll<policy.bait){ai.intent=-toward;ai.bait=true;}
   else ai.intent=roll<.5?0:toward;
   if(ai.bait&&roll>.55){ai.bait=false;ai.intent=toward;}
   if(e.grounded&&ai.jumpDelay<=0&&(dy<-110||(dist<320&&roll<.16))){inp.jump=true;inp.jumpHeld=true;ai.jumpDelay=this.between(.6,1.3);}
   if(e.grounded&&dy>130&&!this.map.platforms[e.platform]?.solid&&Math.abs(dx)<170){inp.down=true;inp.jump=true;}
  }
  inp.move=ai.intent;if(e.ultMode==='boxerRush'&&dist<s.reach+25)inp.attackHeld=true;
  const navigating=(dist>s.reach-15||Math.abs(dy)>85)&&this.navigateAI(e,p,inp);
  if(inp.dash&&!e.grounded){inp.up=Math.sin(inp.aim)<-.4;inp.down=Math.sin(inp.aim)>.4;}
  if(!navigating&&e.grounded&&Math.abs(inp.move)>.1){const edge=e.x+inp.move*65,support=this.map.platforms.some(q=>q.stage!=='gone'&&edge>=q.x&&edge<=q.x+q.w&&Math.abs(q.y-e.y)<35);if(!support){const landing=this.map.platforms.some(q=>(q.x+q.w-e.x)*inp.move>0&&Math.abs(q.x+q.w*.5-e.x)<430&&q.y>e.y-240);if(landing&&ai.jumpDelay<=0){inp.jump=true;inp.jumpHeld=true;ai.jumpDelay=.65;}else inp.move=0;}}
  if(!navigating&&!e.grounded&&e.vy>0){const below=this.map.platforms.filter(q=>q.stage!=='gone'&&q.y>=e.y-10);if(below.length&&!below.some(q=>e.x>q.x+12&&e.x<q.x+q.w-12)){const target=below.reduce((a,b)=>Math.abs(clamp(e.x,a.x+24,a.x+a.w-24)-e.x)<Math.abs(clamp(e.x,b.x+24,b.x+b.w-24)-e.x)?a:b);inp.move=Math.sign(clamp(e.x,target.x+24,target.x+target.w-24)-e.x);}}
  if(e.wallSide&&inp.move*e.wallSide>0&&ai.jumpDelay<=0){inp.jump=true;inp.jumpHeld=true;ai.jumpDelay=.3;}if(p.state==='parry'&&dist<62&&this.canAct(e))inp.kick=true;
  if(this.rules.specials&&this.canAct(e)&&e.specialCharge>=this.rules.specialCooldown&&dist<600&&ai.timer<.03)inp.special=true;if(e.ultMode==='unarmed'&&e.dagger){inp.attack=false;inp.move=Math.sign(e.dagger.safe.x-e.x);if(e.dagger.y<e.y-110&&e.grounded)inp.jump=true;}
  return inp;
 }
 step(dt,inputs=[]){if(!Number.isFinite(dt)||dt<=0)return;if(this.hitstop>0){this.hitstop=Math.max(0,this.hitstop-dt);return;}if(this.phase==='title'||this.phase==='matchEnd')return;this.time+=dt;this.updatePlatforms(this.time);
  if(this.phase==='roundEnd'){for(const f of this.fighters){if(f.dead)f.deathTime+=dt;else{this.tickState(f,dt);f.vx*=Math.exp(-12*dt);f.move=0;}}this.roundTimer-=dt;if(this.roundTimer<=0){const winner=this.score.findIndex((n,i)=>n>=this.rules.winningScore&&n>this.score[1-i]);if(winner>=0&&this.mode!=='training'){this.phase='matchEnd';this.emit('matchEnd',{winner});}else{this.round++;this.phase='playing';this.resetFighters(true);this.emit('round');}}return;}
  const commands=this.fighters.map((f,i)=>this.aiEnabled&&i>0?(root.DuelLegacy?.ai(this,i,dt)||this.updateAI(dt)):inputs[i]||neutral());this.legacyFrame=commands;root.DuelLegacy?.beforeStep(this,commands,dt);if(this.legacyRewind){root.DuelLegacy?.worldStep(this,0);return;}if(this.phase!=='playing')return;this.lastCommands=commands.map(c=>({...c}));if(commands[0].move*(this.fighters[1].x-this.fighters[0].x)<0)this.habits.retreat+=dt;
  for(let i=0;i<this.fighters.length;i++){const f=this.fighters[i],inp=commands[i],actorDt=dt*(root.DuelLegacy?.timeScale(this,f)??1);if(!actorDt)continue;this.tickState(f,actorDt);root.DuelLegacy?.command(this,f,inp,actorDt);if(f.dead)continue;f.aim=Number.isFinite(inp.aim)?inp.aim:f.aim;f.facing=aimSide(f.aim,f.facing);f.stateBefore=f.state;if(f.queued&&this.canAct(f)){const q=f.queued;f.aim=q.aim;this.command(i,q.action,q);f.aim=inp.aim;}if(inp.dash)this.command(i,'dash',inp);if(inp.attack||(inp.attackHeld&&f.ultMode==='boxerRush'&&this.canAct(f)))this.command(i,'attack',inp);if(inp.parry)this.command(i,'parry',inp);if(inp.kick)this.command(i,'kick',inp);if(inp.special)this.command(i,'special',inp);if(Math.abs(inp.move)>.01||inp.jump||inp.attack||inp.parry||inp.dash||inp.kick||inp.special||f.state!=='idle'||!f.grounded)f.tauntTime=0;else if(inp.taunt)f.tauntTime=.9;else f.tauntTime=Math.max(0,(f.tauntTime||0)-dt);this.moveFighter(f,inp,actorDt);root.DuelLegacy?.afterMove(this,f,inp,actorDt);}
  this.separateBodies();for(const f of this.fighters)if(!f.dead&&!f.legacy?.effects?.phasing)this.collideWalls(f);this.resolveCombat();if(this.legacyRewind){root.DuelLegacy?.worldStep(this,0);return;}if(this.phase!=='playing')return;root.DuelLegacy?.worldStep(this,dt);if(this.phase!=='playing')return;this.updateDaggers(dt);if(this.phase!=='playing')return;
  for(const f of this.fighters)if(!f.dead&&(f.y>this.map.deathY||f.legacy?.effects?.inverted&&f.y-body(f).top<-(this.map.deathY-this.map.height))){if(f.admin?.invincible){Object.assign(f,this.map.spawns[f.id?1:0],{vx:0,vy:0,grounded:false,platform:-1});this.emit('adminRescue',{id:f.id});continue;}if(root.DuelLegacy?.fallRescue(this,f))return;this.deathInfo(null,f);this.metrics?.players[f.id]&&(this.metrics.players[f.id].falls++);f.dead=true;f.deathTime=0;this.setState(f,'dead');if(!this.fallTimer)this.fallTimer=.15;}
  if(this.fallTimer){this.fallTimer-=dt;const dead=this.fighters.filter(f=>f.dead);if((this.pathEncounter?this.fighters[0].dead||this.fighters.slice(1).every(f=>f.dead):dead.length===2)||this.fallTimer<=0){const loser=dead[0],winner=dead.length===2?-1:1-loser.id;this.finish(winner,winner<0?'Os dois caíram na mesma janela.':'Queda fora da arena.',{x:loser.x,y:Math.min(loser.y,this.map.height),cause:winner<0?'TROCA':'QUEDA'});}}
 }
 snapshot(){return JSON.parse(JSON.stringify({version:72,timeOfDay:this.timeOfDay||'day',mapData:this.mapSource?.custom?{...this.mapSource,background:{...this.mapSource.background,layers:[]}}:null,platformStates:this.map.platforms.map(p=>({stage:p.stage,crumbleAt:p.crumbleAt,goneAt:p.goneAt})),skins:this.skins,experimental:!!this.experimental,aiEnabled:this.aiEnabled,mode:this.mode,difficulty:this.difficulty,characters:this.characters,colors:this.colors,mapId:this.mapId,rules:this.rules,phase:this.phase,time:this.time,score:this.score,round:this.round,hitstop:this.hitstop,roundTimer:this.roundTimer,attackCounter:this.attackCounter,fallTimer:this.fallTimer,lastReason:this.lastReason,fighters:this.fighters,habits:this.habits,ai:this.ai}));}
 loadSnapshot(s){if(!s||s.version!==72||!Array.isArray(s.fighters)||(s.pathEncounter?s.fighters.length<2||s.fighters.length>4:s.fighters.length!==2))return false;if(s.mapData?.background&&!s.mapData.background.layers.length&&MAPS[s.mapData.id]?.background?.layers?.length)s={...s,mapData:{...s.mapData,background:{...s.mapData.background,layers:MAPS[s.mapData.id].background.layers}}};this.configure({...s,ai:s.aiEnabled});for(const key of['phase','time','score','round','hitstop','roundTimer','attackCounter','fallTimer','lastReason','fighters','habits','ai'])this[key]=JSON.parse(JSON.stringify(s[key]));if(s.platformStates)s.platformStates.forEach((p,i)=>Object.assign(this.map.platforms[i]||{},p));this.updatePlatforms(this.time,false);this.events=[];return true;}
}
const DuelBody=body;
// V5: deterministic round rules and event telemetry. Rendering never changes these values.
const MODES={off:'DESLIGADO',normal:'CAOS',ultra:'CAOS ULTRA'};
const CHAOS=[
 {id:'light',name:'BAIXA GRAVIDADE',group:'gravity',key:'gravity',factor:.6},
 {id:'heavy',name:'PESO DO MUNDO',group:'gravity',key:'gravity',factor:1.5},
 {id:'jump',name:'PULO GIGANTE',group:'jump',key:'jump',factor:1.4},
 {id:'dash',name:'MAIS UM DASH',group:'dash',key:'dashCount',add:1},
 {id:'attack',name:'LÂMINAS VELOZES',group:'attack',key:'attackSpeed',factor:1.3},
 {id:'speed',name:'PÉS LIGEIROS',group:'speed',key:'speed',factor:1.25},
 {id:'arena',name:'SEM ESPAÇO',group:'arena',key:'mapSize',factor:.8},
 {id:'guard',name:'GUARDA PRECISA',group:'guard',key:'parryWindow',factor:.75},
 {id:'recovery',name:'DASH INCANSÁVEL',group:'recovery',key:'dashRecovery',factor:.5},
 {id:'fragile',name:'CHÃO DE VIDRO',group:'platforms'},
 {id:'noSpecial',name:'SÓ NA TÉCNICA',group:'special',key:'specials',value:false},
 {id:'special',name:'PODER IMPACIENTE',group:'special',key:'specialCooldown',factor:.6}
];
const metricPlayer=()=>({rounds:0,attacks:0,whiffs:0,parries:0,parryMisses:0,falls:0,dashDeaths:0,recoveryDeaths:0,clashes:0,specials:0,retreat:0,classes:{}});
const original={};for(const key of['configure','start','resetFighters','step','emit','finish','snapshot','loadSnapshot','adminApply','attack'])original[key]=Game.prototype[key];
Game.prototype.configure=function(o={}){original.configure.call(this,o);if(o.rules)this.baseRules=cleanRules(o.baseRules||o.rules,this.experimental);else this.baseRules??={...this.rules};if(Number.isFinite(o.seed))this.chaosSeed=o.seed>>>0;};
Game.prototype.rebuildRoundRules=function(){this.rules={...this.baseRules};for(const id of this.chaosStack||[]){const m=CHAOS.find(m=>m.id===id);if(!m?.key)continue;this.rules[m.key]=m.value??(m.add?this.rules[m.key]+m.add:this.rules[m.key]*m.factor);}this.map=makeMap(this.mapId,this.rules.mapSize,this.mapSource);this.routeCache=new Map();if(this.chaosStack?.includes('arena'))this.safeArenaSpawns();if(this.chaosStack?.includes('fragile'))for(const p of this.map.platforms){if(!p.solid&&!p.wallTop&&!this.map.spawns.some(s=>s.x>=p.x&&s.x<=p.x+p.w&&Math.abs(s.y-p.y)<8))p.fragile={delay:.65,respawn:3.5};}};

Game.prototype.safeArenaSpawns=function(){const map=this.map,used=[];for(const spawn of map.spawns){const r=C.radius+2,candidates=[];for(const p of map.platforms){if(p.w<r*2||p.fragile)continue;for(const x of[clamp(spawn.x,p.x+r,p.x+p.w-r),p.x+r,p.x+p.w-r,p.x+p.w/2]){const q={x,y:p.y};if(map.walls.some(w=>x+r>w.x&&x-r<w.x+w.w&&q.y-C.bodyBottom+r>w.y&&q.y-C.bodyTop-r<w.y+w.h))continue;if(used.some(a=>Math.abs(a.y-q.y)<C.bodyTop&&Math.abs(a.x-x)<r*2+2))continue;candidates.push(q);}}candidates.sort((a,b)=>Math.hypot(a.x-spawn.x,a.y-spawn.y)-Math.hypot(b.x-spawn.x,b.y-spawn.y));const q=candidates[0];if(q)Object.assign(spawn,q);used.push({...spawn});}};

Game.prototype.rollChaos=function(){const mode=this.baseRules.chaos;if(mode==='off'){this.chaosStack=[];this.chaosNew=null;return;}const used=new Set((this.chaosStack||[]).map(id=>CHAOS.find(m=>m.id===id)?.group));let pool=CHAOS.filter(m=>mode==='ultra'?!used.has(m.group):m.id!==this.chaosNew);if(!this.baseRules.specials)pool=pool.filter(m=>m.group!=='special');if(!this.mapSource.platforms.some(p=>!p.solid&&!this.mapSource.spawns.some(s=>s.x>=p.x&&s.x<=p.x+p.w&&Math.abs(s.y-p.y)<8)))pool=pool.filter(m=>m.id!=='fragile');this.chaosState=((this.chaosState||1)*1664525+1013904223)>>>0;const m=pool[Math.floor(this.chaosState/4294967296*pool.length)];this.chaosNew=m?.id||null;if(mode==='normal')this.chaosStack=[];if(m)this.chaosStack.push(m.id);};
Game.prototype.resetFighters=function(preserve=false){if(!this.v5Started||this.loadingV5)return original.resetFighters.call(this,preserve);const fractions=preserve&&this.baseRules.persistSpecial?this.fighters.map(f=>clamp(f.specialCharge/this.rules.specialCooldown,0,1)):[0,0];this.rollChaos();if(this.baseRules.chaos==='off')this.rules={...this.baseRules};else this.rebuildRoundRules();original.resetFighters.call(this,false);this.fighters.forEach((f,i)=>{f.specialCharge=fractions[i]*this.rules.specialCooldown;this.metrics.players[i].classes[f.kind]=(this.metrics.players[i].classes[f.kind]||0)+1;});this.roundTrace={clash:-100,parry:[-100,-100],near:[-100,-100],attacks:[-100,-100]};this.lastHighlight=null;this.lastImpact=null;this.introRemaining=this.baseRules.chaos==='off'?0:4.1;if(this.introRemaining)this.phase='roundIntro';};
Game.prototype.start=function(o){this.v5Started=false;original.start.call(this,o);this.metrics={players:[metricPlayer(),metricPlayer()],winner:null};this.chaosStack=[];this.chaosNew=null;this.chaosState=this.chaosSeed??((Math.random()*4294967296)>>>0);this.v5Started=true;this.resetFighters();};
Game.prototype.attack=function(id){const ok=original.attack.call(this,id);if(ok)this.fighters[id].nearCandidate=null;return ok;};
Game.prototype.emit=function(type,data={}){const m=this.metrics,t=this.roundTrace,id=data.id;let extra={};if(m){const p=m.players[id];if(type==='windup'&&p){p.attacks++;if(t)t.attacks[id]=this.time;}if(type==='whiff'&&p){p.whiffs++;const f=this.fighters[id],n=f.nearCandidate;if(n){if(t)t.near[n.id]=this.time;original.emit.call(this,'nearMiss',{...n,attacker:id,kind:f.kind});f.nearCandidate=null;}}if(type==='parryMiss'&&p)p.parryMisses++;if(type==='parry'&&p){p.parries++;if(t)t.parry[id]=this.time;}if(type==='special'&&p&&this.fighters[id].ultMode!=='boxerRush')p.specials++;if(type==='clash'){m.players.forEach(p=>p.clashes++);if(t)t.clash=this.time;}if(type==='matchEnd')m.winner=data.winner;}
 if(Number.isInteger(id)&&this.fighters?.[id])extra={kind:this.fighters[id].kind,x:this.fighters[id].x,y:this.fighters[id].y-body(this.fighters[id]).center};original.emit.call(this,type,{...extra,...data});if(['round','roundGo'].includes(type)&&this.phase==='playing'&&this.rules.winningScore>1&&this.score.some(n=>n===this.rules.winningScore-1))original.emit.call(this,'matchPoint');};
Game.prototype.deathInfo=function(a,d){const state=d.state,unblockable=a&&(a.state==='ultCharge'||a.breakAttackId&&a.breakAttackId===a.attackId),cause=state==='recovery'?'ABERTURA':state==='parry'?(unblockable?'GUARDA ROMPIDA':'FORA DA GUARDA'):state==='parryRecovery'?'TARDE DEMAIS':state==='stunned'&&this.time-(this.roundTrace?.parry[1-d.id]??-100)<1.2?'PUNIDO':'CORTE LIMPO';const dash=d.dashRemaining>0||['dash','slide'].includes(state),air=!d.grounded;const p=this.metrics?.players[d.id];if(p){if(dash)p.dashDeaths++;if(state==='recovery')p.recoveryDeaths++;}return{cause,state,dash,air,kind:a?.kind||d.kind,victim:d.id,angle:a?.attackAim||0,contours:a?slash(a,this.map.walls).points.map(p=>({...p})):[]};};
Game.prototype.finish=function(winner,reason,data={}){if(this.phase!=='playing')return;const descriptions={ABERTURA:'O ataque errado deixou sua recuperação aberta.','FORA DA GUARDA':'O golpe veio por fora da direção protegida.','TARDE DEMAIS':'O parry terminou antes do golpe.','GUARDA ROMPIDA':'O especial atravessou sua defesa.',PUNIDO:'O parry abriu espaço para o contra-ataque.',QUEDA:'Queda fora da arena.',TROCA:'Os dois caíram no mesmo instante.'};if(descriptions[data.cause])reason=descriptions[data.cause];const t=this.roundTrace||{attacks:[-100,-100],parry:[-100,-100],near:[-100,-100],clash:-100},decider=this.score.every(n=>n===this.rules.winningScore-1),tags=[];if(winner<0)tags.push('TROCA');if(Math.abs(t.attacks[0]-t.attacks[1])<.13&&this.time-Math.max(...t.attacks)<.65)tags.push('POR UM INSTANTE');if(winner>=0&&this.time-t.parry[winner]<1.2)tags.push('CONTRA-ATAQUE');if(data.dash)tags.push('NO DASH');if(data.air)tags.push('NO AR');if(this.time-t.clash<.9)tags.push('DEPOIS DO CLASH');if(winner>=0&&this.time-t.near[winner]<1.5)tags.push('POR UM FIO');if(decider)tags.push('TUDO OU NADA');this.lastHighlight=tags.length?{tags,weight:tags.length+(decider?4:0)+(winner<0?2:0),round:this.round}:null;if(winner>=0&&this.metrics)this.metrics.players[winner].rounds++;this.lastImpact={...data,cause:data.cause||(winner<0?'TROCA':'CORTE LIMPO')};original.finish.call(this,winner,reason,{...data,highlight:this.lastHighlight,cause:data.cause||(winner<0?'TROCA':'CORTE LIMPO')});};
Game.prototype.step=function(dt,inputs=[]){if(this.phase==='roundIntro'){if(!(dt>0))return;this.introRemaining=Math.max(0,this.introRemaining-dt);if(!this.introRemaining){this.phase='playing';this.emit('roundGo');}return;}if(this.phase==='playing'&&this.hitstop<=0&&dt>0){for(const f of this.fighters)if(!f.dead&&f.vx*((this.fighters[f.id?0:1]?.x??f.x)-f.x)<-20)this.metrics.players[f.id].retreat+=dt;}return original.step.call(this,dt,inputs);};
Game.prototype.snapshot=function(){return{...original.snapshot.call(this),baseRules:{...this.baseRules},chaosStack:[...(this.chaosStack||[])],chaosNew:this.chaosNew??null,chaosState:this.chaosState??1,introRemaining:this.introRemaining||0,metrics:JSON.parse(JSON.stringify(this.metrics||{players:[metricPlayer(),metricPlayer()],winner:null})),roundTrace:JSON.parse(JSON.stringify(this.roundTrace||{})),lastHighlight:this.lastHighlight||null,lastImpact:this.lastImpact||null};};
Game.prototype.loadSnapshot=function(s){if(s?.version!==72)return false;this.loadingV5=true;const ok=original.loadSnapshot.call(this,s);this.loadingV5=false;if(!ok)return false;for(const key of['baseRules','chaosStack','chaosNew','chaosState','introRemaining','metrics','roundTrace','lastHighlight','lastImpact'])this[key]=JSON.parse(JSON.stringify(s[key]));this.v5Started=true;this.rebuildRoundRules();s.platformStates?.forEach((p,i)=>Object.assign(this.map.platforms[i]||{},p));this.updatePlatforms(this.time,false);return true;};
Game.prototype.adminApply=function(change){if(change.action==='refill')return original.adminApply.call(this,change);const saved={metrics:this.metrics,stack:[...this.chaosStack],mode:this.baseRules.chaos,state:this.chaosState,new:this.chaosNew,trace:this.roundTrace};const cfg={...change,rules:change.rules||this.baseRules};this.chaosSeed=saved.state;original.adminApply.call(this,cfg);this.metrics=saved.metrics;this.chaosState=saved.state;if(this.baseRules.chaos===saved.mode){this.chaosStack=saved.stack;this.chaosNew=saved.new;this.rebuildRoundRules();original.resetFighters.call(this,false);if(Array.isArray(change.positions))this.fighters.forEach((f,i)=>{for(const k of['x','y'])if(Number.isFinite(change.positions[i]?.[k])){f[k]=change.positions[i][k];f.grounded=false;f.platform=-1;}});}this.phase=this.score.some((n,i)=>n>=this.rules.winningScore&&n>this.score[1-i])?'matchEnd':this.introRemaining?'roundIntro':'playing';if(this.phase==='matchEnd')this.metrics.winner=this.score.findIndex((n,i)=>n>=this.rules.winningScore&&n>this.score[1-i]);};

const DECOR={bell:{name:'Sino',w:62,h:78},lantern:{name:'Lanterna',w:24,h:38},bamboo:{name:'Bambu',w:15,h:135},flag:{name:'Bandeira',w:70,h:86},vase:{name:'Vaso',w:32,h:42}};
function cleanDecor(list=[],width=1280,height=720){if(!Array.isArray(list)||list.length>40)throw Error('Use até 40 objetos decorativos.');return list.map((p,i)=>{if(!DECOR[p?.type]||!Number.isFinite(p.x)||!Number.isFinite(p.y)||p.x<0||p.x>width||p.y<0||p.y>height)throw Error('Objeto decorativo inválido.');return{type:p.type,x:p.x,y:p.y,id:'prop'+i};});}
const WEATHER=['none','leaves','petals','rain','snow','embers'];
MAPS.bells={name:'Pátio dos Sinos',description:'Um sino ancestral entre passarelas e pilares. Cada golpe ecoa.',theme:'tower',weather:'petals',platforms:[{x:40,y:615,w:1200,solid:true},{x:160,y:400,w:270},{x:850,y:400,w:270},{x:540,y:295,w:200}],walls:[{x:70,y:250,w:28,h:365},{x:1182,y:250,w:28,h:365}],spawns:[{x:340,y:615},{x:940,y:615}],decor:[{type:'bell',x:640,y:467},{type:'lantern',x:270,y:335},{type:'lantern',x:1010,y:335},{type:'vase',x:1150,y:573}]};
MAPS.rooftops={name:'Telhados da Chuva',description:'Telhas molhadas, lanternas e bandeiras sobre um vão fatal.',theme:'bamboo',weather:'rain',platforms:[{x:35,y:595,w:410,solid:true},{x:835,y:595,w:410,solid:true},{x:470,y:460,w:340},{x:130,y:360,w:210},{x:940,y:360,w:210}],walls:[{x:65,y:425,w:22,h:170},{x:1193,y:425,w:22,h:170}],spawns:[{x:280,y:595},{x:1000,y:595}],decor:[{type:'lantern',x:400,y:535},{type:'lantern',x:870,y:535},{type:'flag',x:510,y:365},{type:'flag',x:1060,y:270},{type:'bamboo',x:165,y:460}]};
MAPS.tower.decor=[{type:'bell',x:640,y:480}];MAPS.bamboo.decor=[{type:'bamboo',x:600,y:480},{type:'lantern',x:1090,y:548}];
const v6original={};for(const k of['resetFighters','step','emit','finish','snapshot','loadSnapshot','adminApply','resolveCombat'])v6original[k]=Game.prototype[k];
Game.prototype.resetFighters=function(...args){v6original.resetFighters.apply(this,args);this.propStates=(this.map.decor||[]).map(()=>({hitAt:-100,side:1,broken:false,attacks:[-1,-1]}));};
Game.prototype.touchProps=function(){const props=this.map.decor||[];for(let i=0;i<props.length;i++){const p=props[i],state=this.propStates[i],d=DECOR[p.type],scale=this.map.scale||1;if(!state||state.broken)continue;const x=p.x*scale,y=p.y*scale;for(const f of this.fighters){if(f.dead||state.attacks[f.id]===f.attackId)continue;const poly=slash(f,this.map.walls).points;if(!poly.length||!polygonSegment(poly,{x,y:y+6},{x,y:y+d.h-6},d.w/2))continue;state.attacks[f.id]=f.attackId;state.hitAt=this.time;state.side=f.x<x?1:-1;state.broken=['lantern','bamboo','vase'].includes(p.type);this.emit('propHit',{index:i,prop:p.type,x,y:y+d.h/2,side:state.side});}}};
Game.prototype.resolveCombat=function(){this.touchProps();return v6original.resolveCombat.call(this);};
Game.prototype.finish=function(winner,reason,data={}){if(this.phase!=='playing')return;const finisher=this.mode!=='training'&&winner>=0&&this.score[winner]+1>=this.rules.winningScore;v6original.finish.call(this,winner,reason,{...data,finisher});if(finisher&&this.phase==='roundEnd')this.roundTimer+=.65;};
Game.prototype.snapshot=function(){return{...v6original.snapshot.call(this),propStates:JSON.parse(JSON.stringify(this.propStates||[]))};};
Game.prototype.loadSnapshot=function(s){if(!v6original.loadSnapshot.call(this,s))return false;this.propStates=JSON.parse(JSON.stringify(s.propStates||[]));return true;};
Game.prototype.adminApply=function(change){if(change.action==='preview'){if(['idle','tense','guard','perfect','finisher','entry','victory','stop'].includes(change.animation)&&[0,1].includes(change.id))this.emit('preview',{animation:change.animation,id:change.id});return;}const out=v6original.adminApply.call(this,change);if(change.action!=='refill')this.propStates=(this.map.decor||[]).map(()=>({hitAt:-100,side:1,broken:false,attacks:[-1,-1]}));return out;};
function cleanPreset(data){if(data?.format!=='um-corte-preset'||data.version!==1||typeof data.name!=='string'||!data.name.trim()||data.name.length>40||!data.rules||typeof data.rules!=='object')throw Error('Preset inválido.');for(const k of Object.keys(DEFAULT_RULES)){const v=data.rules[k];if(k==='chaos'){if(!Object.hasOwn(MODES,v))throw Error('Modo Caos inválido.');}else if(typeof DEFAULT_RULES[k]==='boolean'){if(typeof v!=='boolean')throw Error('Regra inválida: '+k);}else if(!Number.isFinite(v)||v<RULES[k].min||!RULES[k].unbounded&&v>RULES[k].max||(RULES[k].integer||k==='dashCount')&&!Number.isSafeInteger(v))throw Error('Valor inválido: '+RULES[k].name);}return{format:'um-corte-preset',version:1,name:data.name.trim(),rules:cleanRules(data.rules)};}


function cleanAdminOptions(list){return[0,1].map(i=>{const v=list?.[i]||{},scale=k=>Number.isFinite(v[k])&&v[k]>0?v[k]:1;return{bodyScale:scale('bodyScale'),attackScale:scale('attackScale'),invincible:v.invincible===true,fly:v.fly===true};});}
const v63original={};for(const k of['resetFighters','step','snapshot','loadSnapshot','adminApply','updateAI'])v63original[k]=Game.prototype[k];
Game.prototype.resetFighters=function(preserve=false){v63original.resetFighters.call(this,preserve);this.adminOptions=cleanAdminOptions(this.adminOptions);this.fighters.forEach((f,i)=>f.admin={...this.adminOptions[i]});this.entryRemaining=this.roundEntries&&this.v5Started&&!this.loadingV5&&(this.mode!=='training'||!preserve)?.65:0;if(this.entryRemaining){this.introRemaining=Math.max(this.introRemaining||0,this.mode==='training'?0:3);this.phase='roundEntry';}};
Game.prototype.step=function(dt,inputs=[]){if(this.phase==='roundEntry'){if(!(dt>0))return;this.entryRemaining=Math.max(0,this.entryRemaining-dt);if(!this.entryRemaining){this.phase=this.introRemaining?'roundIntro':'playing';if(this.phase==='playing')this.emit('roundGo');}return;}return v63original.step.call(this,dt,inputs);};
Game.prototype.setAdminActors=function(change){this.experimental=true;if(change.options)this.adminOptions=cleanAdminOptions(change.options);this.adminOptions=cleanAdminOptions(this.adminOptions);for(let i=0;i<2;i++){const f=this.fighters[i],kind=CLASSES[change.characters?.[i]]?change.characters[i]:f.kind,skin=cleanSkin(kind,change.skins?.[i]??f.skin),color=COLORS[change.colors?.[i]]?change.colors[i]:f.color;if(f.kind!==kind){const charge=f.specialCharge;this.resetSpecial(f);f.kind=kind;f.specialCharge=Math.min(charge,this.rules.specialCooldown);f.queued=null;f.attackHit=true;f.dashRemaining=f.slideRemaining=0;if(!f.dead)this.setState(f,'idle');f.anim=0;}f.skin=skin;f.color=color;this.characters[i]=kind;this.skins[i]=skin;this.colors[i]=color;f.admin={...this.adminOptions[i]};if(f.admin.fly){f.jumping=false;f.grounded=false;f.platform=-1;}}this.emit('actorsChanged');};
Game.prototype.adminApply=function(change){if(['day','night'].includes(change.timeOfDay))this.timeOfDay=change.timeOfDay;if(change.action==='actors'){this.setAdminActors(change);return;}if(change.action==='tempo'){this.adminSpeed=change.speed;return;}const saved={options:cleanAdminOptions(this.adminOptions),speed:this.adminSpeed||1},result=v63original.adminApply.call(this,change);this.adminOptions=saved.options;this.adminSpeed=saved.speed;this.fighters.forEach((f,i)=>f.admin={...this.adminOptions[i]});if(change.action==='apply'&&this.phase==='roundEntry'){this.entryRemaining=0;this.introRemaining=0;this.phase='playing';}return result;};
Game.prototype.snapshot=function(){return{...v63original.snapshot.call(this),roundEntries:!!this.roundEntries,entryRemaining:this.entryRemaining||0,adminOptions:cleanAdminOptions(this.adminOptions),adminSpeed:this.adminSpeed||1};};
Game.prototype.loadSnapshot=function(s){if(!v63original.loadSnapshot.call(this,s))return false;this.roundEntries=!!s.roundEntries;this.entryRemaining=s.entryRemaining||0;this.adminOptions=cleanAdminOptions(s.adminOptions);this.adminSpeed=s.adminSpeed||1;this.fighters.forEach((f,i)=>f.admin={...this.adminOptions[i]});return true;};
Game.prototype.updateAI=function(dt){
 if(this.difficulty!=='master')return v63original.updateAI.call(this,dt);
 const ai=this.ai,e=this.fighters[1],live=this.fighters[0],s=stats(e),inp=neutral();ai.observations??=[];if(!ai.observations.length||this.time-ai.observations.at(-1).at>=.012)ai.observations.push({at:this.time,f:{...live,admin:{...live.admin},dagger:live.dagger?{...live.dagger}:null}});while(ai.observations.length>32)ai.observations.shift();const seen=ai.observations.filter(o=>o.at<=this.time-.085).at(-1);if(!seen){ai.decision='observar';return inp;}const p=seen.f,lag=this.time-seen.at,predicted={...p,x:p.x+p.vx*lag*.7,y:p.y+p.vy*lag*.7},dx=predicted.x-e.x,dy=predicted.y-e.y,dist=Math.hypot(dx,dy),side=Math.sign(dx)||1,aim=Math.atan2(dy,dx),reach=s.reach;inp.aim=aim;inp.jumpHeld=e.vy<0;ai.attackDelay-=dt;ai.jumpDelay-=dt;ai.timer-=dt;ai.decision='medir distância';if(e.dead||p.dead)return inp;
 const attacking=['startup','active','ultWindup','ultCharge','throwWindup'].includes(p.state),open=['recovery','parryRecovery','stunned','feintRecovery','ultRecovery'].includes(p.state),range=dist>Math.max(20,s.minRange-12)&&dist<reach-8,ownFree=this.canAct(e);
 if(p.state==='parry'&&(e.state==='startup'||e.state==='active'&&e.stateTime<=.06&&!e.attackHit)&&dist<reach+40&&!['fenceStrike','sweepStrike'].includes(e.ultMode)&&e.feintCooldown<=0){inp.parry=true;ai.attackDelay=.17;ai.decision='fintar guarda';return inp;}
 inp.move=dist>reach*.86?side:dist<s.minRange+28?-side:0;
 if(attacking&&dist<stats(p).reach+100){
  const probe={...predicted,state:'active',stateTime:stats(p).active*.5,duration:stats(p).active},threat=this.bodyContact(probe,e)||p.state==='ultCharge'||p.state==='throwWindup';
  if(p.ultMode==='sweepStrike'||p.state==='ultCharge'){if(e.grounded&&ai.jumpDelay<=0){inp.jump=true;inp.jumpHeld=true;ai.jumpDelay=.32;ai.decision='saltar especial';}else inp.move=-side;}
  else if(ownFree&&threat&&e.parryCooldown<=0&&e.parryLock<=0){const incoming=this.incomingSector(probe,e);inp.aim=incoming.sector==='high'?-Math.PI/2:incoming.sector==='low'?Math.PI/2:incoming.side>0?0:Math.PI;inp.parry=true;ai.decision='interceptar';}
  else if(ownFree&&e.dashCharges>0&&dist<stats(p).reach+30){inp.move=-side;inp.aim=-Math.PI/5*side+(side<0?Math.PI:0);inp.dash=true;ai.decision='sair da linha';}
  else if(!threat)inp.move=-side;
 }
 if(ownFree&&!inp.parry&&!inp.dash&&ai.attackDelay<=0&&(open||!attacking&&p.state!=='parry')){
  if(range){inp.aim=aim;inp.attack=true;ai.attackDelay=this.between(.12,.23);ai.decision=open?'punir abertura':'estocar';}
  else if(open&&dist<reach+115&&e.dashCharges>0){inp.aim=aim;inp.move=side;inp.dash=true;inp.attack=dist<reach+65;ai.attackDelay=.14;ai.decision='avanço de punição';}
 }
 if(ownFree&&p.state==='parry'&&dist<reach+25)inp.move=dist>53?side:0;
 if(ownFree&&p.state==='parry'&&dist<66){inp.kick=true;ai.decision='romper espaço';}
 if(!inp.attack&&!inp.parry&&!attacking&&range&&ai.timer<=0){ai.timer=this.between(.20,.37);ai.intent=this.random()<.4?-side:side;}
 if(!open&&!attacking&&dist>=reach*.78&&dist<reach+45)inp.move=ai.intent||0;
 if(this.rules.specials&&ownFree&&e.specialCharge>=this.rules.specialCooldown&&!inp.parry&&dist<reach+180){inp.special=e.kind==='staff'?e.grounded&&Math.abs(dy)<35&&dist<reach*1.2:e.kind==='lancer'?Math.abs(dy)<30&&p.grounded&&open:true;}
 if(e.ultMode==='sweepReady'&&range){inp.attack=e.grounded&&p.grounded&&Math.abs(dy)<30;inp.move=side;}
 if(e.ultMode==='fenceReady'&&!attacking&&p.state!=='parry'&&dist<reach+100){inp.attack=true;inp.aim=aim;}
 if(e.ultMode==='boxerRush'&&range)inp.attackHeld=true;
 const navigating=(dist>reach+25||Math.abs(dy)>85)&&this.navigateAI(e,p,inp);
 if(e.wallSide&&inp.move*e.wallSide>0&&ai.jumpDelay<=0){inp.jump=inp.jumpHeld=true;ai.jumpDelay=.27;}
 if(!navigating&&e.grounded&&Math.abs(inp.move)>.1){const ahead=e.x+inp.move*(inp.dash?150:65),supported=this.map.platforms.some(q=>q.stage!=='gone'&&ahead>=q.x+8&&ahead<=q.x+q.w-8&&Math.abs(q.y-e.y)<35);if(!supported){inp.dash=false;if(ai.jumpDelay<=0&&this.map.platforms.some(q=>q.stage!=='gone'&&Math.abs(q.x+q.w/2-e.x)<420&&q.y>e.y-230)){inp.jump=inp.jumpHeld=true;ai.jumpDelay=.45;}else inp.move=0;}}
 if(!e.grounded&&e.vy>0&&!navigating){const below=this.map.platforms.filter(q=>q.stage!=='gone'&&q.y>=e.y-10);if(below.length&&!below.some(q=>e.x>q.x+12&&e.x<q.x+q.w-12)){const nearest=below.sort((a,b)=>Math.abs(clamp(e.x,a.x+24,a.x+a.w-24)-e.x)-Math.abs(clamp(e.x,b.x+24,b.x+b.w-24)-e.x))[0];inp.move=Math.sign(clamp(e.x,nearest.x+24,nearest.x+nearest.w-24)-e.x);if(e.dashCharges&&e.y>nearest.y-110){inp.aim=Math.atan2(-80,inp.move*140);inp.dash=true;}}}
 if(e.ultMode==='unarmed'&&e.dagger){inp.attack=false;inp.move=Math.sign(e.dagger.safe.x-e.x);if(e.grounded&&e.dagger.y<e.y-100)inp.jump=inp.jumpHeld=true;}
 if(inp.dash&&!e.grounded){inp.up=Math.sin(inp.aim)<-.4;inp.down=Math.sin(inp.aim)>.4;}return inp;
};

const api={sealPathMap,wallFraction,wallContour,RUNNER,cleanRaceMap,aimSide,makeFighter,cleanAdminOptions,DECOR,WEATHER,cleanDecor,cleanPreset,CHAOS,MODES,metricPlayer,PRESETS,COMBAT_KEYS,applyPreset,detectPreset,SKINS,cleanSkin,cleanMap,registerMap,mapWarnings,body,SCALE,slash,makeMap,pointInPolygon,polygonSegment,polygonsIntersect,C,CLASSES,COLORS,RULES,DEFAULT_RULES,MAPS,DIFFICULTIES,Game,stats,blade,guardSector,cleanRules,neutral,clamp,lerp,segmentDistance};if(typeof module!=='undefined')module.exports=api;root.DuelCore=api;
})(typeof globalThis!=='undefined'?globalThis:this);
