(function(root){
'use strict';
const D=typeof module!=='undefined'?require('./engine.js'):DuelCore,copy=o=>JSON.parse(JSON.stringify(o)),{Game,neutral,clamp,body,stats}=D;
class DuelLab{
 constructor(){this.config={move:'still',action:'idle',aim:'follow',attackInterval:.7,parryInterval:.7,variation:0};this.speed=1;this.collisions=false;this.note='Escolha um padrão para o boneco.';this.history=[];this.clip=null;this.viewGame=null;this.checkpoint=null;this.seat=0;this.accumulator=0;this.due={attack:0,parry:0};this.patrol=1;this.control=neutral();this.trainingPaused=false;}
 patchAdmin(g){if(!this.checkpoint)return;const s=this.checkpoint;s.characters=[...g.characters];s.skins=[...g.skins];s.colors=[...g.colors];s.adminOptions=D.cleanAdminOptions(g.adminOptions);s.adminSpeed=g.adminSpeed||1;for(let i=0;i<2;i++){const f=s.fighters[i],live=g.fighters[i];if(f.kind!==live.kind){g.resetSpecial(f);f.state='idle';f.duration=f.stateTime=0;f.queued=null;f.dashRemaining=f.slideRemaining=0;}f.kind=live.kind;f.skin=live.skin;f.color=live.color;f.admin={...s.adminOptions[i]};}}
 startTraining(g){this.checkpoint=g.snapshot();this.due={attack:0,parry:0};this.note='Um corte mata. O boneco reaparece; o treino não termina.';}
 patchLegacy(g){if(!this.checkpoint||g.mode!=='training')return;const L=root.DuelLegacy;if(!L)return;const safe=new Game();safe.loadSnapshot(this.checkpoint);safe.legacyEnabled=g.legacyEnabled;for(let i=0;i<safe.fighters.length;i++){L.reset(safe.fighters[i],g.fighters[i].legacy,'duel');safe.fighters[i].legacy.cd={};}safe.legacyWorld={entities:[],effects:[],serial:0,time:0};for(const f of safe.fighters)L.spawnCompanions(safe,f);L.captureRound(safe);this.checkpoint=safe.snapshot();}
 savePosition(g){if(g.phase!=='playing'||g.fighters.some(f=>f.dead))return false;this.checkpoint=g.snapshot();for(const f of this.checkpoint.fighters){f.vx=f.vy=f.dashRemaining=f.slideRemaining=f.dashCooldown=f.parryCooldown=f.feintCooldown=f.kickCooldown=0;f.state='idle';f.duration=f.stateTime=0;f.queued=null;f.dashCharges=g.rules.dashCount;f.airDashes=0;g.resetSpecial(f);}this.note='Posição salva. R reinicia aqui com os cooldowns prontos.';return true;}
 resetTraining(g,preserve=false){const charges=preserve&&g.rules.persistSpecial?g.fighters.map(f=>f.specialCharge):null;if(!this.checkpoint)return;const metrics=g.metrics;g.loadSnapshot(this.checkpoint);g.metrics=metrics;if(charges)g.fighters.forEach((f,i)=>f.specialCharge=Math.min(g.rules.specialCooldown,charges[i]));g.mode='training';g.aiEnabled=false;g.score=[0,0];g.phase='playing';g.hitstop=0;g.events=[];this.due={attack:0,parry:0};this.history=[];this.note='Posição e cooldowns restaurados.';}
 dummy(g){const [p,e]=g.fighters,c=this.config,inp=neutral(),dx=p.x-e.x;inp.aim=c.aim==='follow'?Math.atan2(p.y-body(p).center-e.y+body(e).center,dx):({right:0,left:Math.PI,up:-Math.PI/2,down:Math.PI/2}[c.aim]||0);
  if(c.move==='left')inp.move=-1;else if(c.move==='right')inp.move=1;else if(c.move==='approach')inp.move=Math.abs(dx)>40?Math.sign(dx):0;else if(c.move==='retreat')inp.move=-Math.sign(dx);else if(c.move==='patrol'){const center=this.checkpoint?.fighters[1].x||g.map.width*.7;if(e.x>center+150)this.patrol=-1;if(e.x<center-150)this.patrol=1;inp.move=this.patrol;}
  if(c.action==='constant'&&!e.dead&&!['stunned','pushed','clash'].includes(e.state)){g.setState(e,'idle');e.parryCooldown=0;inp.parry=true;}
  const next=(key,interval)=>{if(g.time<(this.due[key]||0))return false;this.due[key]=g.time+interval+(Math.random()*2-1)*c.variation;return true;};
  if(['attack','feint','alternate'].includes(c.action)&&g.canAct(e)&&next('attack',c.attackInterval)){inp.attack=true;if(c.action==='alternate'&&Math.floor(g.time/c.attackInterval)%2)inp.attack=false,inp.parry=true;}
  if(c.action==='feint'&&e.state==='startup'&&e.stateTime>e.duration*.45)inp.parry=true;
  if(c.action==='parry'&&g.canAct(e)&&e.parryCooldown<=0&&next('parry',c.parryInterval))inp.parry=true;
  if(c.action==='kick'&&g.canAct(e)&&next('attack',c.attackInterval))inp.kick=true;
  return inp;
 }
 record(g,before,commands,seat=0){if(before.phase==='roundEnd'){if(this.clip?.round===before.round&&g.round===before.round&&this.clip.frames.length<240)this.clip.frames.push({before,commands:copy(commands),after:g.snapshot()});return;}if(before.phase!=='playing')return;if(this.recordRound!==before.round||this.recordTime>before.time){this.history=[];this.recordRound=before.round;}this.recordTime=before.time;this.history.push({before,commands:copy(commands),after:g.snapshot(),constantGuard:g.mode==='training'&&this.config.action==='constant'});if(this.history.length>150)this.history.shift();if(g.phase==='roundEnd'){this.clip={round:before.round,frames:this.history.slice(),seat,reason:g.lastReason,characters:[...g.characters],mapId:g.mapId,highlight:g.lastHighlight};if(g.lastHighlight&&(!this.bestReplay||g.lastHighlight.weight>=this.bestReplay.highlight.weight))this.bestReplay=this.clip;}}
 observe(ev,g){if(g.mode!=='training')return;if(ev.type==='parry')this.note=ev.id===0?'Parry correto. A abertura é sua.':'O boneco leu o corte. Experimente finta, chute ou outro ângulo.';else if(ev.type==='whiff'&&ev.id===0){const[a,d]=g.fighters,dist=Math.hypot(d.x-a.x,d.y-a.y);this.note=dist>stats(a).reach+body(d).radius?'Fora do alcance: aproxime-se antes do corte.':'O corte passou fora do corpo: observe o ângulo e a altura.';}else if(ev.type==='parryMiss'&&ev.id===0)this.note='Parry sem contato. Confira o momento e a direção protegida.';else if(ev.type==='kill')this.note=ev.reason;else if(ev.type==='feint'&&ev.id===0)this.note='Finta: o golpe foi cancelado, mas você não está defendendo.';else if(ev.type==='kick')this.note='Chute: espaço aberto. O impacto não causa dano.';}
 open(){if(!this.clip)return false;this.viewGame=new Game();this.viewMode='watch';this.index=0;this.playing=true;this.speed=.5;this.loadFrame(0);this.note=this.clip.reason;return true;}
 loadFrame(index){if(!this.clip)return;this.index=clamp(index,0,this.clip.frames.length-1);const i=Math.floor(this.index),frame=this.clip.frames[i];this.viewGame.loadSnapshot(i===this.clip.frames.length-1?frame.after:frame.before);this.viewGame.aiEnabled=false;}
 seek(index){if(!this.viewGame)return;this.viewMode='watch';this.playing=false;this.loadFrame(index);}
 tryAgain(retry=false){if(!this.clip)return false;if(!retry)this.startFrame=this.index>=this.clip.frames.length-2?0:Math.floor(this.index);this.startFrame=this.startFrame||0;this.viewGame=new Game();this.viewGame.loadSnapshot(this.clip.frames[this.startFrame].before);this.viewGame.mode='training';this.viewGame.aiEnabled=false;this.viewGame.score=[0,0];this.viewMode='play';this.playing=true;this.index=this.startFrame;this.accumulator=0;this.control=neutral();this.note='Você controla seu personagem. O rival repete os comandos gravados.';return true;}
 close(){this.viewGame=null;this.control=neutral();this.playing=false;}
 tick(dt,input){if(!this.viewGame)return;const events=[];if(this.viewMode==='watch'){if(this.playing){this.loadFrame(this.index+dt*60*this.speed);if(this.index>=this.clip.frames.length-1)this.playing=false;}return events;}
  if(input){for(const k of['move','aim','jumpHeld','down','up','attackHeld','kickHeld'])this.control[k]=input[k];this.control.legado=[...new Set([...(this.control.legado||[]),...(input.legado||[])])];this.control.legadoHeld=[...(input.legadoHeld||[])];for(const k of['attack','parry','dash','jump','kick','special','taunt'])this.control[k]||=input[k];if(input.reset)this.tryAgain(true);}
  if(!this.playing)return events;this.accumulator=Math.min(this.accumulator+dt*this.speed,.15);while(this.accumulator>=1/60){const frame=this.clip.frames[Math.floor(this.index)],g=this.viewGame;const dummy=g.fighters[1],constant=frame?.constantGuard&&this.clip.seat===0&&!dummy.dead&&!['stunned','pushed','clash'].includes(dummy.state);if(constant){g.setState(dummy,'idle');dummy.parryCooldown=0;}for(let sub=0;sub<10;sub++){const commands=copy(frame?.commands[sub]||g.fighters.map(()=>neutral()));commands[this.clip.seat]={...this.control};if(constant&&sub===0)commands[1].parry=true;const frozen=g.hitstop>0;g.step(1/600,commands);if(!frozen){for(const k of['attack','parry','dash','jump','kick','special','taunt'])this.control[k]=false;this.control.legado=[];}}events.push(...g.events.splice(0));this.index++;this.accumulator-=1/60;if(g.phase==='roundEnd'){this.playing=false;this.note=g.fighters[this.clip.seat].dead?'Essa resposta ainda foi atingida. R tenta novamente.':'Outra resposta, outro resultado. R repete o desafio.';break;}}
  return events;
 }
}
if(typeof module!=='undefined')module.exports=DuelLab;root.DuelLab=DuelLab;
})(typeof globalThis!=='undefined'?globalThis:this);
