(function(root){
'use strict';
const D=root.DuelCore||(typeof require==='function'?require('./engine.js'):null),catalog=root.DuelLegacyCatalog||(typeof require==='function'?require('./legacy-catalog.js'):null);
const clone=x=>JSON.parse(JSON.stringify(x)),clamp=D.clamp,rarities=['common','rare','legendary'];
const WEAPONS={
 broom:{kind:'staff',reach:148,minRange:25,startup:.26,active:.14,recovery:.36},
 sword:{kind:'knight'},bow:{kind:'lancer',reach:0,length:65,startup:.25,active:.02,recovery:.38,shot:'arrow',cooldown:3},
 knuckles:{kind:'boxer',reach:55,startup:.09,active:.075,recovery:.15},axe:{kind:'swordsman',reach:139,minRange:25,startup:.28,active:.14,recovery:.41},
 kunai:{kind:'assassin',reach:0,length:50,startup:.09,active:.02,recovery:.19,shot:'kunai',cooldown:1.3},
 leviathan:{kind:'swordsman',reach:145,minRange:30,startup:.22,active:.13,recovery:.32},needle:{kind:'duelist',reach:141,minRange:20,startup:.13,active:.11,recovery:.23},
 gunblade:{kind:'knight',reach:132},blunderbuss:{kind:'lancer',reach:0,length:62,startup:.08,active:.035,recovery:.45,shot:'pellet',cooldown:2.4},
 yoyo:{kind:'assassin',reach:0,length:25,startup:.08,active:.02,recovery:.18,shot:'yoyo',cooldown:1},
 yamato:{kind:'knight',reach:152,startup:.12,active:.105,recovery:.23},ruyi:{kind:'staff',reach:160,startup:.14,active:.12,recovery:.23},
 zenith:{kind:'knight',reach:139,startup:.16,active:.12,recovery:.29},echo:{kind:'knight',reach:144,startup:.17,active:.12,recovery:.29}
};
const cooldown={glider:.2,rockets:.2,icarus:.2,gravitycloak:1,weaponmaster:1,falcon:5,dragon:16,kraken:13,fireball:2.7,pulse:4,impulse:3,barrier:7,telekinesis:2,gust:5,swap:5,web:2,blink:3.5,well:8,mist:7,lightning:5,ice:6,shadowbomb:6,repulsor:4,room:9,portals:1,amaterasu:12,kamehameha:12,thehand:8,domain:18};
const useText={weapon:'M1 · atacar; consulte a descrição para o gesto específico.',clothing:'Passivo · efeitos de voo podem receber tecla ou gesto no TAB.',relic:'Passivo · usos e escolhas especiais aparecem no TAB.',technique:'Combinação de movimento e combate indicada na descrição.',summon:'Companheiro automático; invocações ativas recebem tecla.',power:'Ative pela tecla atribuída. Mira pelo cursor ou controle.'};
function inventory(){return{items:[],weapon:null,bindings:{},gesture:null,cd:{},used:{duel:{},match:{},run:{}},effects:{},transforms:[],consumed:[],marked:null,draftBoost:0,fuel:1,charge:0};}
function ensure(f){return f.legacy??=inventory();}
function has(f,id){const l=f?.legacy;return!!l&&!l.consumed.includes(id)&&(l.items.includes(id)&&!l.transforms.some(t=>t.from===id)||l.transforms.some(t=>t.to===id));}
function items(f){const l=f?.legacy;if(!l)return[];return l.items.map(id=>l.transforms.find(t=>t.from===id)?.to||id).filter(id=>!l.consumed.includes(id));}
function add(f,id,{equip=true,admin=false}={}){if(!catalog[id])return false;const l=ensure(f);if(l.items.includes(id)||has(f,id))return false;l.items.push(id);if(l.marked===id)l.marked=null;if(catalog[id].category==='weapon'&&equip)l.weapon=id;if(catalog[id].active){const free=Array.from({length:9},(_,i)=>i+1).find(n=>!Object.values(l.bindings).includes('Digit'+n));if(free)l.bindings[id]='Digit'+free;}if(['glider','rockets','icarus'].includes(id)&&!l.gesture)l.gesture=id;return true;}
function remove(f,id){const l=ensure(f),t=l.transforms.find(t=>t.from===id||t.to===id),origin=t?.from||id,removed=new Set([origin,id,...(t?[t.to]:[])]);if(origin==='necromancer')delete l.servantKind;if(l.summonMemory)delete l.summonMemory[origin];l.items=l.items.filter(x=>x!==origin);for(const key of removed){delete l.bindings[key];delete l.effects[key];delete l.cd[key];for(const u of Object.values(l.used))delete u[key];}l.consumed=l.consumed.filter(k=>!removed.has(k));l.transforms=l.transforms.filter(t=>t.from!==origin);if(removed.has(l.weapon))l.weapon=l.items.find(x=>catalog[x].category==='weapon')||null;if(removed.has(l.gesture))l.gesture=null;return true;}
function equip(f,id,phase){const l=ensure(f);if(!['draft','roundEnd','matchEnd','title','between'].includes(phase)||!has(f,id)||catalog[id].category!=='weapon')return false;l.weapon=id;return true;}
function bind(f,id,code,base=[],replace=false){const l=ensure(f);if(!has(f,id)||!catalog[id]?.active)return{ok:false,error:'Legado não possui ação ativa.'};if(code!==null&&!/^(Key[A-Z]|Digit[0-9]|Numpad[0-9]|F[1-9]|Arrow(Up|Down|Left|Right)|Space|Shift(Left|Right)|Control(Left|Right)|Mouse[0-4]|Pad[0-9]{1,2})$/.test(code))return{ok:false,error:'Tecla inválida.'};const other=Object.keys(l.bindings).find(k=>k!==id&&l.bindings[k]===code);if(code&&base.includes(code))return{ok:false,error:'Já usado pelo movimento/combate. Remapeie esse controle primeiro.'};if(other&&!replace)return{ok:false,conflict:other,error:'Tecla já usada por '+catalog[other].name};if(other)delete l.bindings[other];if(code)l.bindings[id]=code;else delete l.bindings[id];return{ok:true};}
function scopeReady(f,id){const c=catalog[id],l=f?.legacy;return!!c&&!!l&&has(f,id)&&!(l.cd[id]>0)&&(c.scope==='cooldown'||!l.used[c.scope][id]);}
function spend(f,id){const l=ensure(f),c=catalog[id];if(c.scope!=='cooldown')l.used[c.scope][id]=true;else l.cd[id]=cooldown[id]??5;}
function reset(f,old,scope='duel'){const l=inventory();if(old)for(const key of ['items','weapon','bindings','gesture','used','transforms','consumed','marked','draftBoost','matchEffects','target','diceTarget','forcedDie','copied','summonMemory','servantKind','krakenForm'])if(old[key]!==undefined)l[key]=clone(old[key]);l.effects={};l.cd={};l.fuel=1;l.charge=0;l.used.duel={};if(scope==='match'){l.krakenForm=0;l.copied=null;l.summonMemory={};delete l.servantKind;l.used.match={};for(const t of l.transforms){const binding=l.bindings[t.to]||t.binding;delete l.bindings[t.to];if(catalog[t.from].active&&binding)l.bindings[t.from]=binding;if(l.weapon===t.to)l.weapon=t.from;if(l.gesture===t.to)l.gesture=t.from;}l.transforms=[];l.matchEffects={};}else if(l.matchEffects)Object.assign(l.effects,l.matchEffects);f.legacy=l;f.airJumps=1+(has(f,'wingboot')?1:0);return l;}
function status(f,id){
 const l=f?.legacy||inventory(),c=catalog[id],consumed=l.consumed.includes(id),used=c.scope!=='cooldown'&&!!l.used[c.scope]?.[id],weapon=(l.transforms.find(t=>t.from===l.weapon)?.to||l.weapon)===id,remaining=Math.max(0,l.cd[id]||0,weapon&&WEAPONS[id]?.shot?l.cd.weapon||0:0),total=weapon&&WEAPONS[id]?.shot?WEAPONS[id].cooldown:cooldown[id]||remaining||1;
 const away=weapon&&!!l.effects.weaponAway,ready=!consumed&&!used&&!away&&remaining<=0&&(id!=='brokenmirror'||!!l.copied),label=consumed?'CONSUMIDO':used?'USADO NESTA '+({duel:'RODADA',match:'PARTIDA',run:'RUN'})[c.scope]:away?'ARMA FORA':remaining>0?'RECARGA '+remaining.toFixed(1)+' s':id==='brokenmirror'&&!l.copied?'AGUARDANDO MEMÓRIA':c.active?'PRONTO':'PASSIVO';
 return{id,consumed,used,away,remaining,energy:['icarus','rockets'].includes(id)?clamp(l.fuel,0,1):null,progress:remaining>0?clamp(1-remaining/total,0,1):1,ready,label:id==='kraken'?label+' · '+['ESMAGAR','AGARRAR','BLOQUEAR ROTA'][l.krakenForm||0]:id==='brokenmirror'&&l.mirrorSpecial?(f.ultMode?'CÓPIA EM USO':'RECUPERANDO')+' · '+(L.mirrorName?.('class:'+l.mirrorSpecial.kind)||l.mirrorSpecial.kind):id==='brokenmirror'&&l.copied&&!used?label+' · '+(L.mirrorName?.(l.copied)||l.copied):label,binding:l.bindings[id]||null};
}
function weights(level){return level<5?[86,13,1]:level<10?[78,20,2]:level<15?[68,28,4]:[58,35,7];}
function randomRarity(rng,w){const v=rng()*w.reduce((a,b)=>a+b,0);return v<w[0]?'common':v<w[0]+w[1]?'rare':'legendary';}
function draftPattern(rng=Math.random,level=1){return Array.from({length:3},()=>randomRarity(rng,weights(level)));}
function eligible(id,ctx={}){if(['crown','contract'].includes(id)&&(ctx.mode!=='path'||ctx.futureDraft===false||ctx.level>=45))return false;if(['markedcard','destinyorb','coin','clover','magnet'].includes(id)&&ctx.futureDraft===false)return false;if(id==='necromancer'&&ctx.mode!=='path')return false;return true;}
function draft(f,ctx={},rng=Math.random,pattern){const l=ensure(f),n=has(f,'clover')?4:3,used=new Set([...l.items,...items(f)]),pool=Object.keys(catalog).filter(id=>!used.has(id)&&eligible(id,ctx)),w=weights(ctx.level||1),guarantee=['boss','last'].includes(ctx.reward)?2:ctx.reward==='mini'?1:-1;
 let ranks=pattern?[...pattern.slice(0,n)]:Array.from({length:n},()=>randomRarity(rng,w));while(ranks.length<n)ranks.push(randomRarity(rng,w));if(l.draftBoost){ranks=ranks.map(r=>rarities[clamp(rarities.indexOf(r)+(l.draftBoost>=15?1:l.draftBoost<=5?-1:0),0,2)]);if(l.draftBoost===1)ranks=ranks.map(()=>'common');if(l.draftBoost===20){ranks=ranks.map(r=>r==='common'?'rare':r);ranks[0]='legendary';}}
 if(guarantee>=0&&!ranks.some(r=>rarities.indexOf(r)>=guarantee))ranks[0]=rarities[guarantee];if(has(f,'magnet')&&ranks.includes('legendary')&&ranks.filter(r=>r!=='common').length<2)ranks[ranks[0]==='legendary'?1:0]='rare';
 const chosen=[];for(let i=0;i<n&&pool.length;i++){let candidates=pool.filter(id=>catalog[id].rarity===ranks[i]);if(!candidates.length)candidates=pool.filter(id=>rarities.indexOf(catalog[id].rarity)>=Math.max(0,i===0?guarantee:0));if(!candidates.length)candidates=pool;const id=candidates[Math.floor(rng()*candidates.length)];chosen.push(id);pool.splice(pool.indexOf(id),1);}
 // A marked card must not replace the only boss guarantee or Magnet partner.
 const quality=cards=>cards.map(id=>rarities.indexOf(catalog[id].rarity)),valid=cards=>{const q=quality(cards);return(guarantee<0||q.some(r=>r>=guarantee))&&(!has(f,'magnet')||!q.includes(2)||q.filter(r=>r>=1).length>=2)&&(l.draftBoost!==20||q.includes(2)&&q.every(r=>r>=1));};
 if(l.marked){if(chosen.includes(l.marked))l.marked=null;else if(pool.includes(l.marked)){const idx=chosen.findIndex((id,i)=>valid(chosen.map((k,j)=>j===i?l.marked:k)));if(idx>=0){chosen[idx]=l.marked;l.marked=null;}}else l.marked=null;}
 l.draftBoost=0;return{cards:chosen,selected:0,rerolled:false,choices:has(f,'contract')&&ctx.reward==='mini'?2:1,ctx:clone(ctx),pattern:pattern?[...pattern]:null};
}
function reroll(f,d,rng){if(!has(f,'coin')||d.rerolled||d.picked?.length)return null;return{...draft(f,d.ctx,rng,d.pattern),rerolled:true};}
// Preview advances randomness, but draft-only resources commit only on acceptance.
function peekDraft(f,d,rng,pattern=d.pattern){const l=ensure(f);if(!has(f,'destinyorb')||l.used.run.destinyorb||d.picked?.length)return null;const proxy={legacy:clone(l)},next=draft(proxy,d.ctx,rng,pattern);l.used.run.destinyorb=true;next.resourceCommit={before:{marked:l.marked,draftBoost:l.draftBoost},after:{marked:proxy.legacy.marked,draftBoost:proxy.legacy.draftBoost}};return next;}
function acceptDraft(f,next){const l=ensure(f),c=next.resourceCommit;if(c)for(const key of ['marked','draftBoost'])if(l[key]===c.before[key])l[key]=c.after[key];delete next.resourceCommit;return next;}
function rng(seed){let state=seed===undefined?1:seed>>>0;const fn=()=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state/4294967296;};Object.defineProperty(fn,'state',{get:()=>state,set:v=>state=v>>>0});return fn;}
// All combat state is plain data, shared by saves, replay and network snapshots.
const L={catalog,WEAPONS,status,cooldown,useText,inventory,ensure,has,items,add,remove,equip,bind,scopeReady,spend,reset,weights,draftPattern,draft,reroll,peekDraft,acceptDraft,eligible,rng,clone};root.DuelLegacy=L;
if(typeof module!=='undefined')module.exports=L;
})(globalThis);
