const A=require('node:assert/strict'),D=require('./engine'),L=require('./legacies');require('./legacy-combat');const P=require('./path');let total=0;
function test(name,fn){try{fn();total++;console.log('PASS',name);}catch(e){console.error('FAIL',name,e.stack);process.exitCode=1;}}
const game=(items=[],enemy=[])=>{const g=new D.Game({mode:'local',ai:false});g.start({mode:'local',ai:false,legacies:[items,enemy]});return g;};
test('catalogue has all six exact counts and 115 unique stable identities',()=>{A.equal(Object.keys(L.catalog).length,115);for(const [cat,n]of Object.entries({weapon:15,clothing:17,relic:21,technique:18,summon:22,power:22}))A.equal(Object.values(L.catalog).filter(c=>c.category===cat).length,n);for(const c of Object.values(L.catalog))A(c.description.length>20,c.id);});
test('inventory does not duplicate; first nine actives assigned, remap conflicts explicit',()=>{const f={};for(const id of Object.keys(L.catalog))L.add(f,id);A.equal(f.legacy.items.length,115);A(!L.add(f,'sword'));A.equal(Object.keys(f.legacy.bindings).length,9);const ids=Object.keys(f.legacy.bindings);A.equal(L.bind(f,ids[1],f.legacy.bindings[ids[0]]).conflict,ids[0]);A(!L.bind(f,ids[1],'Space',['Space']).ok);A(L.bind(f,ids[1],'KeyZ').ok);});
test('seeded draft excludes owned items, guarantees tiers and preserves clover reroll',()=>{for(let n=0;n<200;n++){const f={};L.add(f,'clover');L.add(f,'coin');L.add(f,'sword');for(const reward of['normal','mini','boss','last']){const d=L.draft(f,{mode:'path',level:15,reward},L.rng(n+1));A.equal(d.cards.length,4);A.equal(new Set(d.cards).size,4);A(!d.cards.includes('sword'));if(reward==='mini')A(d.cards.some(id=>L.catalog[id].rarity!=='common'));if(['boss','last'].includes(reward))A(d.cards.some(id=>L.catalog[id].rarity==='legendary'));const rerolled=L.reroll(f,d,L.rng(n+2));A.equal(rerolled.cards.length,4);A.equal(L.reroll(f,rerolled,L.rng(5)),null);}}});
test('PvP rarity template respected for eligible equal inventories',()=>{const pattern=['common','rare','legendary'];for(let i=1;i<20;i++){const a=L.draft({}, {mode:'online'},L.rng(i),pattern),b=L.draft({}, {mode:'online'},L.rng(i+99),pattern);A.deepEqual(a.cards.map(id=>L.catalog[id].rarity),b.cards.map(id=>L.catalog[id].rarity));A(!a.cards.some(id=>['crown','contract','necromancer'].includes(id)));}});
test('weapons retain class mobility and original class special',()=>{const g=game(['axe']),f=g.fighters[0];A.equal(D.stats(f).speed,D.CLASSES.knight.speed);A.equal(D.stats(f).reach,139);f.specialCharge=g.rules.specialCooldown;A(g.special(0));A.equal(f.ultMode,'shield');});
test('extra aerial jump, dash 320ms and W/Space input semantics preserved',()=>{const g=game(['wingboot']),f=g.fighters[0];g.moveFighter(f,D.neutral(),1/600);A.equal(f.airJumps,2);g.moveFighter(f,{...D.neutral(),jump:true,jumpHeld:true},1/60);for(let i=0;i<2;i++){g.moveFighter(f,{...D.neutral(),jump:true,jumpHeld:true},1/60);}A.equal(f.airJumps,0);A.equal(g.rules.dashCooldown,320);});
test('crystal prevents one fatal blow per match and does not recharge between duels',()=>{const g=game(['crystal']),[f,a]=g.fighters;A(!g.lethal(a,f,'hit'));A(!f.dead);A(f.legacy.used.match.crystal);g.resetFighters(true);A(g.fighters[0].legacy.used.match.crystal);A(g.lethal(g.fighters[1],g.fighters[0],'hit'));});
test('fireball can be reflected and kills with one clean hit',()=>{const g=game(['fireball']),[f,t]=g.fighters;f.x=400;t.x=590;f.aim=0;t.aim=Math.PI;g.parry(1);A(L.activate(g,f,'fireball'));for(let i=0;i<180;i++)L.worldStep(g,1/600);A(L.world(g).entities.some(e=>e.owner===1));g.setState(f,'idle');for(let i=0;i<200;i++)L.worldStep(g,1/600);A(f.dead);});
test('time stop is telegraphed, under 1s active, once per duel, serializable',()=>{const g=game(['star']);A(L.activate(g,g.fighters[0],'star'));A.equal(L.timeScale(g,g.fighters[1]),1);L.worldStep(g,.36);A.equal(L.timeScale(g,g.fighters[1]),0);A.equal(L.timeScale(g,g.fighters[0]),1);A(!L.activate(g,g.fighters[0],'star'));L.worldStep(g,1);A.equal(L.timeScale(g,g.fighters[1]),1);const copy=new D.Game();A(copy.loadSnapshot(g.snapshot()));A(copy.fighters[0].legacy.used.duel.star);});
test('all level boundaries have exact group counts, bosses do not repeat, final fixed',()=>{const r=new P.Run({seed:112});A.equal(new Set(Object.values(r.bosses)).size,5);for(const [level,n]of [[1,1],[5,1],[11,2],[15,1],[21,2],[25,1],[31,2],[35,1],[36,3],[41,3],[45,1],[49,3],[50,1]]){r.level=level;r.encounter=null;A.equal(r.makeEncounter().fighters.length,n,level);}A.equal(r.makeEncounter().boss,'first');A.equal(r.points,3);});
test('path multi-enemy core uses shared physics and only scores after every enemy dies',()=>{const run=new P.Run({seed:22});run.level=31;const g=run.game();g.aiEnabled=false;g.phase='playing';A.equal(g.fighters.length,3);A(g.fighters[1].legacy.items.length>=2);g.fighters.forEach(f=>{f.legacy.items=[];});g.lethal(g.fighters[0],g.fighters[1],'hit');A.equal(g.score[0],0);A.equal(g.phase,'playing');g.lethal(g.fighters[0],g.fighters[2],'hit');A.equal(g.score[0],1);const c=new D.Game();A(c.loadSnapshot(g.snapshot()));A.equal(c.fighters.length,3);});
test('save restores RNG, encounter, build, draft and rejects duplicate items',()=>{const run=new P.Run({seed:123,points:7});run.level=25;run.makeEncounter();L.add({legacy:run.inventory},'echo');const save=run.serialize(),restored=P.Run.restore(save);A.deepEqual(restored.serialize(),save);A.equal(restored.random(),run.random());const memory=new Map(),store=new P.Saves({getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)});A(store.write(run));A.deepEqual(store.read().inventory.items,['echo']);run.phase='lost';store.write(run);A.equal(store.read(),null);save.inventory.items.push('echo');A.throws(()=>P.Run.restore(save));});
test('all 115 items can coexist in snapshots without unserializable state',()=>{const g=game(Object.keys(L.catalog));for(let i=0;i<20;i++)g.step(1/600,[D.neutral(),D.neutral()]);const s=g.snapshot();A.equal(s.fighters[0].legacy.items.length,115);A(!JSON.stringify(s).includes('null,null,null'));const copy=new D.Game();A(copy.loadSnapshot(s));A.deepEqual(copy.snapshot().legacyWorld,s.legacyWorld);});
console.log(total+' V8 foundation groups passed');
