// Build-time extraction only. The shipped HTML embeds the resulting registry.
const fs=require('fs'),path=require('path'),p=f=>path.join(__dirname,f);
const spec=fs.readFileSync(p('SPEC-V8.txt'),'utf8').replace(/\r/g,'');
const groups=[['weapon',10,15,['broom','sword','bow','knuckles','axe','kunai','leviathan','needle','gunblade','blunderbuss','yoyo','yamato','ruyi','zenith','echo'],[6,11]],['clothing',11,17,['wingboot','sandals','kneepads','climbing','lightcape','duelistband','shadowcloak','glider','crystal','magnetic','mirrorcloak','rockets','berserker','icarus','ghostsuit','stonemask','gravitycloak'],[6,12]],['relic',12,21,['warbell','crackedglass','glasseye','coin','wolftooth','irontalisman','incense','clover','d6','stoppedclock','brokenmirror','markedcard','survivorglass','magnet','philosopher','crown','contract','destinyorb','secondchance','d20','destinyeye'],[7,14]],['technique',13,18,['downstrike','upstrike','flyingkick','roundhouse','stomp','wallstrike','counter','dashcancel','projectilecut','throw','backstep','lunge','iaijutsu','mikiri','disarm','perfectstep','nodraw','weaponmaster'],[6,13]],['summon',14,22,['raven','slime','beetle','fairy','hound','lantern','monkey','falcon','spectral','toad','skeleton','mimic','medusa','doppel','necromancer','dragon','mahoraga','star','kraken','slimeking','legion','hunter'],[7,15]],['power',15,22,['fireball','pulse','impulse','barrier','telekinesis','gust','swap','web','blink','well','mist','lightning','ice','shadowbomb','repulsor','sandevistan','room','portals','amaterasu','kamehameha','thehand','domain'],[7,15]]];
const active=new Set('glider rockets icarus gravitycloak d6 brokenmirror philosopher destinyorb d20 weaponmaster falcon dragon star kraken fireball pulse impulse barrier telekinesis gust swap web blink well mist lightning ice shadowbomb repulsor sandevistan room portals amaterasu kamehameha thehand domain'.split(' '));
const catalog=[];
for(const [category,section,count,ids,bounds] of groups){const start=spec.indexOf(section+'. CATÁLOGO COMPLETO'),end=spec.indexOf('\n'+(section+1)+'. '+(section<15?'CATÁLOGO COMPLETO':'EVITAR REPETIÇÃO'),start),chunk=spec.slice(start,end<0?undefined:end),matches=[...chunk.matchAll(/^([0-9]+)\. ([A-ZÁÀÂÃÉÊÍÓÔÕÚÇ][^\n]*)$/gm)].filter(m=>Number(m[1])<=count&&!m[2].startsWith('CATÁLOGO'));
 if(matches.length!==count)throw Error(category+' count '+matches.length);
 matches.forEach((m,i)=>{const next=matches[i+1]?.index??chunk.length;let description=chunk.slice(m.index+m[0].length,next).split(/\n-{5,}|\n={5,}/)[0].trim();const id=ids[i],rarity=i<bounds[0]?'common':i<bounds[1]?'rare':'legendary';catalog.push({id,name:m[2].replace(/ — VERSÃO V8 REFORMULADA/,''),category,rarity,description,active:active.has(id),icon:i+1,scope:['philosopher','destinyorb'].includes(id)?'run':['crystal','berserker','d6','brokenmirror','survivorglass','secondchance','d20','destinyeye'].includes(id)?'match':['star','sandevistan'].includes(id)?'duel':'cooldown'});});
}
if(catalog.length!==115)throw Error('Expected 115');
fs.writeFileSync(p('legacy-catalog.js'),`(function(root){'use strict';\nconst list=${JSON.stringify(catalog,null,1)};\nconst catalog=Object.freeze(Object.fromEntries(list.map(x=>[x.id,Object.freeze(x)])));\nroot.DuelLegacyCatalog=catalog;if(typeof module!=='undefined')module.exports=catalog;\n})(globalThis);\n`);
console.log('115 Legados extraídos: '+groups.map(g=>g[0]+': '+g[2]).join(', '));
