const A=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),D=require('./engine.js'),Old=require('../v7/engine.js'),P=require('./parkour.js'),OldP=require('../v7/parkour.js');
let count=0;const test=(name,fn)=>{fn();console.log('PASS '+name);count++;},n=o=>({...D.neutral(),...o});
function game(){const g=new D.Game({mode:'local',ai:false,rules:{specials:false}});g.start();g.entryRemaining=0;g.map.walls=[];g.map.platforms=[{x:0,y:900,baseX:0,baseY:900,w:4000,solid:true,stage:'solid'}];g.map.deathY=5000;g.fighters.forEach((f,i)=>Object.assign(f,{x:600+i*1000,y:900,grounded:true,platform:0}));return g;}
function tick(g,t,input=n()){for(let i=0;i<Math.ceil(t*600);i++)g.step(1/600,[input,n()]);}
const edge=(g,o)=>g.step(1/600,[n(o),n()]);
function controls(saved){const handlers={},values=new Map(Object.entries(saved||{})),ctx={DuelCore:D,navigator:{},window:{addEventListener:(k,f)=>handlers[k]=f},localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/controls.js','utf8'),ctx);const c=new ctx.window.DuelControls({addEventListener(){}});c.enabled=true;return{c,key:(code,down=true)=>handlers[down?'keydown':'keyup']({code,repeat:false,target:{tagName:'CANVAS'},preventDefault(){}}),read:()=>c.read('keyboard',{aim:0},{}),values};}
test('W and Space use the same jump edge, hold, release and no auto-repeat',()=>{for(const code of ['KeyW','Space']){const h=controls();h.key(code);let c=h.read();A(c.jump&&c.jumpHeld);A.equal(c.up,code==='KeyW');A(!h.read().jump);h.key(code,false);A(!h.read().jumpHeld);const g=game();edge(g,c);A(g.fighters[0].vy<-900);A.equal(g.fighters[0].airJumps,1);}});
test('simultaneous W + Shift suppresses jump, preserves extra jump and leaves no buffer',()=>{const h=controls(),g=game(),f=g.fighters[0];Object.assign(f,{grounded:false,y:500,coyote:0});h.key('KeyW');h.key('ShiftLeft');const c=h.read();A(c.up&&c.dash&&!c.jump);edge(g,c);A.equal(f.dashX,0);A.equal(f.dashY,-1);A.equal(f.airJumps,1);A.equal(f.jumpBuffer,0);h.key('ShiftLeft',false);tick(g,.2,h.read());A.equal(f.airJumps,1);A(!g.events.some(e=>e.type==='doubleJump'));});
test('holding W then dash retains its earlier jump but never spends the extra jump',()=>{const h=controls(),g=game();h.key('KeyW');edge(g,h.read());tick(g,.12,h.read());h.key('ShiftLeft');edge(g,h.read());A.equal(g.fighters[0].dashY,-1);A.equal(g.fighters[0].airJumps,1);});
test('single extra jump is immediate, third input is rejected, landing restores',()=>{for(const kind of ['runner',...Object.keys(D.CLASSES)]){const g=game(),f=g.fighters[0];f.kind=kind;edge(g,{jump:true,jumpHeld:true});tick(g,.15,n({jumpHeld:true}));edge(g,{jump:true,jumpHeld:true});A.equal(f.airJumps,0);A(f.vy<-860);A(f.doubleJumpTime>0);tick(g,.11,n({jumpHeld:true}));const vy=f.vy;edge(g,{jump:true,jumpHeld:true});A(f.vy>vy);A.equal(g.events.filter(e=>e.type==='doubleJump').length,1);tick(g,1.5);A(f.grounded);A.equal(f.airJumps,1);}});
test('W variable jump, coyote time and landing buffer remain responsive',()=>{const high=game(),low=game();for(const g of[high,low])edge(g,{jump:true,jumpHeld:true});tick(high,.2,n({jumpHeld:true}));tick(low,.2);A(high.fighters[0].y<low.fighters[0].y-45);const c=game(),f=c.fighters[0];f.grounded=false;f.y=890;f.coyote=.07;edge(c,{jump:true,jumpHeld:true});A.equal(f.airJumps,1);A(f.vy<-900);const b=game(),p=b.fighters[0];Object.assign(p,{grounded:false,y:890,vy:450,coyote:0,airJumps:0});edge(b,{jump:true,jumpHeld:true});tick(b,.06,n({jumpHeld:true}));A(p.vy<-800);A.equal(p.airJumps,1);});
test('falling from a ledge has one air jump; stun/dash do not consume it',()=>{const g=game(),f=g.fighters[0];Object.assign(f,{grounded:false,y:500,coyote:0,vy:500});edge(g,{jump:true,jumpHeld:true,down:true});A.equal(f.airJumps,0);A(f.vy<0);for(const state of ['stunned','dash']){const h=game(),p=h.fighters[0];Object.assign(p,{grounded:false,y:500,coyote:0});h.setState(p,state,.3);if(state==='dash')p.dashRemaining=.13;edge(h,{jump:true,jumpHeld:true});A.equal(p.airJumps,1);}});
test('wall jump neither consumes nor restores the aerial jump',()=>{for(const airJumps of[0,1]){const g=game(),f=g.fighters[0];g.map.walls=[{x:800,y:0,w:30,h:900}];Object.assign(f,{x:800-D.body(f).radius,y:500,grounded:false,wallSide:1,wallId:0,lastWall:-1,wallReleased:true,airJumps,coyote:0});edge(g,{jump:true,jumpHeld:true,up:true,move:1});A(g.events.some(e=>e.type==='wallJump'));A.equal(f.airJumps,airJumps);}});
test('default cooldown 320ms, Turbo 240ms, charge refill and reset are coherent',()=>{A.equal(D.cleanRules().dashCooldown,320);A.equal(D.applyPreset({},'classic').dashCooldown,320);A.equal(D.applyPreset({},'turbo').dashCooldown,240);const g=game(),f=g.fighters[0];g.dash(0,1);A.equal(f.dashCooldown,.32);tick(g,.31);A.equal(f.dashCharges,0);tick(g,.011);A.equal(f.dashCharges,1);A.equal(f.dashCooldown,0);for(const k of['dashTime','dashDistance','dashRecovery'])if(D.RULES[k])A.equal(D.RULES[k].default,Old.RULES[k].default);});
test('new normal arena is exactly old 1.5 geometry; physical character size stays fixed',()=>{for(const [id,m]of Object.entries(D.MAPS).filter(([,m])=>!m.custom&&!m.path)){const a=D.makeMap(id,1),b=Old.makeMap(id,1.5);A.deepEqual(a,b,id);A.equal(a.width,(m.width||1280)*1.5);}A.deepEqual(D.body(D.makeFighter(0,'knight','jade',{x:0,y:0})),Old.body(Old.makeFighter(0,'knight','jade',{x:0,y:0})));const g=game();A.equal(g.rules.mapSize,1);A.equal(D.detectPreset(D.cleanRules()),'classic');});
test('custom geometry, moving platform motion and props share the same 1.5 scale',()=>{const m=D.cleanMap({format:'um-corte-map',version:1,id:'custom_v72',name:'Fixture',width:1280,height:720,platforms:[{x:0,y:610,w:1280},{x:400,y:400,w:160,motion:{x:220,y:-100,period:4}}],walls:[],spawns:[{x:200,y:610},{x:1000,y:610}],decor:[{type:'bell',x:650,y:300,scale:1}]});A.deepEqual(D.makeMap(m.id,1,m),Old.makeMap(m.id,1.5,m));});
test('Reaper commitment grows, lance grows only at tip, Monge is identical',()=>{A(D.CLASSES.reaper.startup>Old.CLASSES.reaper.startup*1.10);A(D.CLASSES.reaper.recovery>Old.CLASSES.reaper.recovery*1.07);A.deepEqual(D.CLASSES.staff,{...Old.CLASSES.staff,dashCooldown:.32});const f=D.makeFighter(0,'lancer','jade',{x:500,y:500});Object.assign(f,{state:'active',duration:.1,stateTime:.05,attackAim:0});const a=D.slash(f),b=Old.slash(f);A(a.points.some((p,i)=>Math.abs(p.y-a.origin.y)>Math.abs(b.points[i].y-b.origin.y)));A.equal(D.stats(f).reach,Old.stats(f).reach);});
test('new race routes are 2–3 times the useful length, with more real platforms/checkpoints',()=>{const length=m=>m.race.routes.flatMap(r=>r.slice(1).map((p,i)=>Math.hypot(p.x-r[i].x,p.y-r[i].y))).reduce((a,b)=>a+b,0);for(const [id,m]of Object.entries(P.TRACKS)){const o=OldP.TRACKS[id],ratio=length(m)/length(o);A(ratio>=2&&ratio<=3.1,id+' ratio '+ratio);A(m.platforms.length>o.platforms.length*1.6);A(m.race.checkpoints.length>o.race.checkpoints.length);A.equal(D.makeMap(id,1,m).width,m.width);for(const cp of m.race.checkpoints)A(m.platforms.some(p=>cp.x>p.x&&cp.x<p.x+p.w&&cp.y===p.y));}});
test('duel replay snapshots include extra jump and dash charge timing deterministically',()=>{const a=game();edge(a,{jump:true,jumpHeld:true});tick(a,.16,n({jumpHeld:true}));edge(a,{jump:true,jumpHeld:true});const b=game();A(b.loadSnapshot(a.snapshot()));b.map=a.map;tick(a,.3,n({move:1}));tick(b,.3,n({move:1}));A.deepEqual(a.snapshot(),b.snapshot());});
test('eight race runners reproduce airborne inputs after snapshot; respawn knows its floor',()=>{const a=new P.Race({members:Array.from({length:8},()=>({}))});a.phase='playing';for(let frame=0;frame<110;frame++){const ins=a.fighters.map((f,i)=>n({move:.5,jump:frame===0||frame===70,jumpHeld:true}));a.step(1/600,ins);}A(a.fighters.every(f=>f.airJumps===0));const b=new P.Race();A(b.loadSnapshot(a.snapshot()));for(let i=0;i<150;i++)for(const g of[a,b])g.step(1/600,g.fighters.map(()=>n({up:true,dash:i===0,jumpHeld:true})));A.deepEqual(a.snapshot(),b.snapshot());const f=a.fighters[0];f.checkpoint=1;a.respawnRunner(f);A(f.platform>=0);A.equal(f.airJumps,1);A.equal(f.doubleJumpTime,0);});
test('race bots use real double jumps on every expanded course',()=>{for(const mapId of Object.keys(P.TRACKS)){const g=new P.Race({mapId,difficulty:'normal',members:[{bot:true}]});let extra=0;for(let i=0;i<240*600&&g.phase!=='raceEnd';i++){g.step(1/600);extra+=g.events.filter(e=>e.type==='doubleJump').length;g.events=[];}A(g.fighters[0].finished,mapId);A(extra>3,mapId+' double jumps '+extra);}});
test('landing on moving and fragile platforms restores exactly one extra jump',()=>{for(const fragile of [false,true]){const g=game(),f=g.fighters[0],p=g.map.platforms[0];if(fragile)p.fragile={delay:.3,respawn:2};else p.motion={x:100,y:0,period:2,route:true,pause:0};Object.assign(f,{grounded:false,y:892,vy:400,airJumps:0});tick(g,.04);A(f.grounded);A.equal(f.airJumps,1);if(fragile){tick(g,.32);A(!f.grounded);A.equal(f.airJumps,1);edge(g,{jump:true,jumpHeld:true});A.equal(f.airJumps,0);}}});
test('all nine runner classes can finish all three tracks with real physics',()=>{for(const kind of ['runner',...Object.keys(D.CLASSES)])for(const mapId of Object.keys(P.TRACKS)){const g=new P.Race({mapId,difficulty:'normal',members:[{bot:true,kind}],options:{allClasses:true}});for(let i=0;i<150*600&&g.phase!=='raceEnd';i++){g.step(1/600);g.events=[];}A(g.fighters[0].finished,kind+' '+mapId);}});
test('duel AI uses a double jump to reach a higher opponent',()=>{const g=game();g.aiEnabled=true;g.difficulty='normal';g.map.platforms.push({x:480,y:570,baseX:480,baseY:570,w:550,solid:false,stage:'solid'});Object.assign(g.fighters[0],{x:900,y:570,platform:1,grounded:true});Object.assign(g.fighters[1],{x:650,y:900,platform:0,grounded:true});g.routeCache.clear();for(let i=0;i<600*4&&!g.events.some(e=>e.type==='doubleJump'&&e.id===1);i++)g.step(1/600,[n(),n()]);A(g.events.some(e=>e.type==='doubleJump'&&e.id===1));});
test('control migration keeps custom combat keys and modern W binding after reload',()=>{const h=controls({'um-corte-v7-controls':JSON.stringify({keyboard:{jump:['Space'],attack:['KeyW'],up:['ArrowUp']}})});h.key('KeyW');A(h.read().attack);A(!h.c.settings.keyboard.jump.includes('KeyW'));const fresh=controls();fresh.c.save();const restored=controls(Object.fromEntries(fresh.values));restored.key('KeyW');A(restored.read().jump);});
test('actual replay frames record the second jump and seeking restores its charge',()=>{const Lab=require('./lab.js'),g=game(),lab=new Lab();for(let i=0;i<30;i++){const commands=[n({jump:i===0||i===18,jumpHeld:true}),n()],before=g.snapshot();for(let j=0;j<10;j++){g.step(1/600,commands);commands[0].jump=false;}lab.record(g,before,[n({jump:i===0||i===18,jumpHeld:true}),n()]);}A(lab.history.some(f=>f.before.fighters[0].airJumps===1&&f.after.fighters[0].airJumps===0));lab.clip={frames:lab.history,seat:0,reason:'test'};A(lab.open());lab.seek(5);A.equal(lab.viewGame.fighters[0].airJumps,1);lab.seek(25);A.equal(lab.viewGame.fighters[0].airJumps,0);});
console.log(count+' V7.2 groups passed');

