function makeV8(){
 const L=DuelLegacy,P=DuelPath,state={run:null,watch:null,watching:false,clock:0,inventorySide:0,hash:'',pending:new Set(),held:new Set(),offlineDraft:null,intro:null};
 const currentGame=()=>lab.viewGame||game,currentSeat=()=>lab.viewGame?(lab.clip?.seat||0):Math.max(0,seat);
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const block=el('section',undefined,'path-launch');block.innerHTML='<div><span class="eyebrow">V8 · UMA VIDA, MUITOS CAMINHOS</span><h2>Caminho do Guerreiro</h2><p>Comece sem nada. Construa sua própria lenda em 50 confrontos.</p></div><label>Pontos por partida <input id="path-points" type="number" min="1" max="25" value="3"></label><div class="path-buttons"><button id="path-new" class="primary">NOVA RUN ↗</button><button id="path-continue" class="secondary">CONTINUAR RUN</button><button id="path-watch" class="text-button">ASSISTIR UM AMIGO</button></div><p id="path-save-note" class="fine-print"></p>';
 $('menu').append(block);
 const settings=el('section',undefined,'legacy-settings');settings.innerHTML='<label>LEGADOS <select id="legacy-mode"><option value="off">DESATIVADOS · combate clássico</option><option value="match">1 POR PARTIDA</option><option value="round">1 POR DUELO · cumulativo</option></select></label><p class="fine-print">Escolha entre cartas para construir uma combinação. Sua classe mantém o especial.</p>';$('rules-details').append(settings);
 const hud=el('div',undefined,'legacy-hud');hud.id='legacy-hud';hud.hidden=true;$('arena').append(hud);
 const pathHud=el('div',undefined,'path-hud');pathHud.hidden=true;pathHud.innerHTML='<span id="path-level"></span><button id="path-invite" class="text-button">CONVIDAR ESPECTADORES</button><button id="path-build" class="text-button">TAB · BUILD</button><span id="path-room"></span>';$('arena').append(pathHud);
 const modal=el('dialog',undefined,'legacy-panel');modal.id='legacy-panel';modal.innerHTML='<header><div><span class="eyebrow">O QUE VOCÊ SE TORNOU</span><h2>Seus Legados.</h2></div><button id="legacy-close" class="secondary">VOLTAR · TAB</button></header><div class="legacy-toolbar"><label>Combatente <select id="legacy-side"></select></label><label>Buscar <input id="legacy-search" placeholder="Nome ou efeito"></label><label>Categoria <select id="legacy-category"><option value="">Todas</option></select></label><label>Raridade <select id="legacy-rarity"><option value="">Todas</option></select></label><button id="legacy-lab" class="secondary">LABORATÓRIO</button></div><div id="legacy-inventory" class="legacy-inventory"></div><p id="legacy-message" role="status"></p><section id="legacy-library" hidden><h3>Laboratório de Legados</h3><p>Adicione à build selecionada. Só treino e ADMIN.</p><button id="legacy-refill" class="secondary">RECARREGAR / RESETAR USOS</button><button id="legacy-clear" class="secondary">REMOVER TODOS</button><div class="legacy-lab-tools"><label>Quantidade de Legados distintos <input id="legacy-random-count" type="number" min="1" max="115" value="1"></label><button id="legacy-randomize" class="secondary">SORTEAR COM OS FILTROS</button></div><div id="legacy-debug-tools"></div><div id="legacy-catalogue" class="legacy-inventory"></div></section>';document.body.append(modal);
 const draft=el('dialog',undefined,'legacy-draft');draft.id='legacy-draft';draft.innerHTML='<span id="draft-caption" class="eyebrow">UM NOVO LEGADO</span><h2 id="draft-title">Escolha seu próximo passo.</h2><p id="draft-note"></p><div id="draft-cards" class="draft-cards"></div><div class="draft-actions"><button id="draft-confirm" class="primary">ESCOLHER ↗</button><button id="draft-reroll" class="secondary">MOEDA · SORTEAR NOVAMENTE</button><button id="draft-orb" class="secondary">ORBE · OLHAR O DESTINO</button><button id="draft-mark" class="text-button">MARCAR ESTA CARTA PARA DEPOIS</button></div><p id="draft-error" role="status"></p>';document.body.append(draft);draft.addEventListener('cancel',e=>e.preventDefault());
 const result=el('dialog',undefined,'path-result');result.innerHTML='<span class="eyebrow">CAMINHO DO GUERREIRO</span><h2 id="path-result-title"></h2><p id="path-result-stats"></p><div id="path-result-build" class="legacy-hud-static"></div><button id="path-retry" class="secondary">ADMIN · TENTAR NOVAMENTE</button><button id="path-result-menu" class="primary">VOLTAR AO MENU</button>';document.body.append(result);
 const intro=el('div',undefined,'path-intro');intro.hidden=true;intro.innerHTML='<canvas id="path-intro-art" width="900" height="240" aria-hidden="true"></canvas><small id="path-boss-sub"></small><h2 id="path-boss-name"></h2><button id="path-skip" class="text-button">PULAR INTRO</button>';$('arena').append(intro);
 const arenaNotice=el('div',undefined,'path-arena-notice');arenaNotice.hidden=true;arenaNotice.setAttribute('role','status');$('arena').append(arenaNotice);
 function showArenaNotice(mapId,duration=1800){const map=DuelCore.MAPS[mapId];if(!map)return;arenaNotice.replaceChildren(el('small','UM NOVO CÍRCULO'),el('strong',map.name));arenaNotice.hidden=false;state.arenaNotice={mapId,until:performance.now()+duration};}
 let saves;try{saves=new P.Saves(localStorage);}catch{}state.saves=saves;
 const categories={weapon:'Armas',clothing:'Vestimentas',relic:'Relíquias',technique:'Técnicas',summon:'Invocações',power:'Poderes'},rarities={common:'COMUM',rare:'RARO',legendary:'LENDÁRIO'};
 for(const [id,name]of Object.entries(categories)){const o=el('option',name);o.value=id;$('legacy-category').append(o);}
 for(const [id,name]of Object.entries(rarities)){const o=el('option',name);o.value=id;$('legacy-rarity').append(o);}
 function editBuild(op,value){if(state.watching||lab.viewGame&&lab.viewMode!=='play')return false;const c={side:state.inventorySide,op,value},active=currentGame();if(v7?.room&&!lab.viewGame){if(v7.watching&&!admin)return false;v7.room.send({t:'legacyEdit',sid:v7.room.s.id,change:c});notice('Alteração enviada à partida.');return true;}const changed=L.applyEdit(active,{...c,administrator:!!admin||active.mode==='training'});if(changed&&!lab.viewGame&&active.mode==='training')lab.patchLegacy(active);if(changed&&state.run&&!lab.viewGame){if(op==='seed'){state.run.seed=value;state.run.random=L.rng(value);}state.run.checkpoint(game);save();state.watch?.publish();}if(!changed)notice('Não foi possível aplicar: confira a build e os valores.');state.hash='';return changed;}
 function notice(t){$('legacy-message').textContent=t;}
 function save(){if(!state.run||state.watching)return;if(saves&&!saves.write(state.run)){$('path-save-note').textContent=saves.lastError;notice(saves.lastError);}updateContinue();}
 function readSavedRun(){try{return saves?.read()||null;}catch(e){$('path-save-note').textContent=e.message;return null;}} function updateContinue(){try{const r=saves?.read();$('path-continue').disabled=!r;$('path-continue').textContent=r?'CONTINUAR · NÍVEL '+r.level:'CONTINUAR RUN';}catch(e){$('path-save-note').textContent=e.message;$('path-continue').disabled=true;}}
 function cardIcon(id){const c=el('canvas');c.width=c.height=96;c.className='legacy-icon';c.setAttribute('aria-hidden','true');DuelV8Visuals.icon(c.getContext('2d'),id,96);return c;}
 function card(id,{draftMode=false,library=false}={}){const c=L.catalog[id],f=currentGame().fighters[state.inventorySide]||currentGame().fighters[0],l=f.legacy||L.inventory(),article=el(draftMode?'button':'article',undefined,'legacy-card '+c.rarity);article.dataset.legacy=id;article.append(cardIcon(id));const content=el('div'),name=el('h3',c.name),label=el('small',categories[c.category]+' · '+rarities[c.rarity]),description=el('p',L.describe(id));content.append(label,name,description);if(L.usageText(id))content.append(el('small',L.usageText(id),'legacy-usage'));article.append(content);if(!draftMode){const footer=el('div',undefined,'legacy-card-actions');if(l.items.includes(id)||L.has(f,id)){const status=L.status(f,id);if(status.consumed||status.used)article.classList.add('consumed');const label=el('small',status.label);label.dataset.legacyStatus=id;footer.append(label);
 if(c.active){const bind=el('button',l.bindings[id]?.replace('Digit','')||'SEM TECLA · MAPEAR','secondary');bind.disabled=state.watching||!!v7?.room&&state.inventorySide!==seat;bind.dataset.legacyBind=id;bind.onclick=()=>{state.capture={id,side:state.inventorySide,padOld:input.pad?.buttons.map(b=>b.pressed)||[]};notice('Pressione uma tecla, botão do mouse ou controle. Escape cancela.');};footer.append(bind);}
 if(c.category==='weapon'){const b=el('button',L.weaponId(f)===id?'EQUIPADA':'EQUIPAR','secondary');b.disabled=state.watching;b.onclick=()=>{if(editBuild('equip',id)){state.hash='';inventory();}else notice('Troque de arma entre duelos.');};footer.append(b);}
 if(['glider','rockets','icarus'].includes(id)){const b=el('button',l.gesture===id?'SEGURAR PULO ✓':'USAR COM PULO','secondary');b.onclick=()=>{if(!state.watching){editBuild('gesture',id);inventory();}};footer.append(b);}
 if(id==='d6'){const select=el('select');for(const k of l.items.filter(k=>k!==id&&!l.transforms.some(t=>t.from===k)&&!l.consumed.includes(k))){const o=el('option',L.catalog[k].name);o.value=k;select.append(o);}select.value=l.target||select.options[0]?.value;select.onchange=()=>editBuild('target',select.value);footer.append(select);}
 if(id==='d20'){const select=el('select');for(const [v,t]of[['character','AFETAR PERSONAGEM'],['draft','AFETAR PRÓXIMO DRAFT']]){const o=el('option',t);o.value=v;select.append(o);}select.value=l.diceTarget||'character';select.onchange=()=>editBuild('diceTarget',select.value);footer.append(select);}
 if(selected.mode==='training'||admin){const action=el('select');action.dataset.legacyAction=id;for(const [value,title]of [['ready','Recarga pronta'],['restore','Restaurar uso'],['consume','Consumir / desativar'],...(c.category==='summon'?[['spawn','Recriar invocação'],['despawn','Remover invocação da arena']]:[])]){const o=el('option',title);o.value=value;action.append(o);}action.disabled=state.watching;const apply=el('button','APLICAR','secondary');apply.disabled=state.watching;apply.onclick=()=>{if(editBuild(action.value,id)){notice('Comando aplicado: '+c.name);inventory();}};footer.append(action,apply);const b=el('button','REMOVER','text-button');b.disabled=state.watching;b.onclick=()=>{editBuild('remove',id);inventory();};footer.append(b);}}
 else if(library){const b=el('button','ADICIONAR','secondary');b.onclick=()=>{if(state.watching)return;editBuild('add',id);state.hash='';inventory();};footer.append(b);}article.append(footer);}article.onmouseenter=()=>renderer.legacyHighlight=id;article.onmouseleave=()=>renderer.legacyHighlight=null;return article;}
 function inventory(){const f=currentGame().fighters[state.inventorySide]||currentGame().fighters[0],l=f.legacy||L.inventory(),search=$('legacy-search').value.toLowerCase(),cat=$('legacy-category').value,rarity=$('legacy-rarity').value,filter=id=>(!rarity||L.catalog[id].rarity===rarity)&&(!cat||L.catalog[id].category===cat)&&(!search||(L.catalog[id].name+' '+L.describe(id)).toLowerCase().includes(search));$('legacy-inventory').replaceChildren();for(const [category,label]of Object.entries(categories)){const list=l.items.map(id=>l.transforms.find(t=>t.from===id)?.to||id).filter(id=>L.catalog[id].category===category&&filter(id));if(!list.length)continue;const group=el('section');group.append(el('h3',label));for(const id of list)group.append(card(id));$('legacy-inventory').append(group);}if(!l.items.length)$('legacy-inventory').append(el('p','Sua história ainda está começando. Nenhum Legado adquirido.'));if(!$('legacy-library').hidden){$('legacy-catalogue').replaceChildren();for(const id of Object.keys(L.catalog).filter(filter))$('legacy-catalogue').append(card(id,{library:true}));}state.watch?.publish();}
 function openInventory(){if(inMenu||draft.open)return;state.inventorySide=state.watching?0:currentSeat();$('legacy-side').replaceChildren();for(const f of currentGame().fighters){const o=el('option',f.wanderer?'ERRANTE':(f.id?'RIVAL '+f.id:'VOCÊ')+' · '+(CLASSES[f.kind]?.name||f.kind));o.value=f.id;$('legacy-side').append(o);}$('legacy-side').value=state.inventorySide;$('legacy-lab').hidden=!(selected.mode==='training'||admin)||state.watching;if(!(selected.mode==='training'||admin)||state.watching)$('legacy-library').hidden=true;state.beforePaused=paused;if(lab.viewGame){state.replayPlaying=lab.playing;lab.playing=false;}if(!v7?.room&&!state.watching)paused=true;clearInputs();inventory();state.pending.clear();state.held.clear();if(admin)refreshDebug();modal.showModal();}
 function closeInventory(){modal.close();state.capture=null;paused=state.watching?true:!!state.beforePaused;if(lab.viewGame)lab.playing=!!state.replayPlaying;clearInputs();state.pending.clear();state.held.clear();state.watch?.publish();}
 $('legacy-close').onclick=closeInventory;modal.addEventListener('cancel',e=>{e.preventDefault();closeInventory();});$('legacy-side').onchange=()=>{state.inventorySide=+$('legacy-side').value;if(admin)refreshDebug();inventory();};for(const id of['legacy-search','legacy-category','legacy-rarity'])$(id).oninput=inventory;$('legacy-lab').onclick=()=>{$('legacy-library').hidden=!$('legacy-library').hidden;inventory();};
 $('legacy-refill').onclick=()=>{if(state.watching)return;const f=currentGame().fighters[state.inventorySide],l=L.ensure(f);editBuild('refill');inventory();};$('legacy-clear').onclick=()=>{if(state.watching)return;editBuild('clear');inventory();};
 $('legacy-randomize').onclick=()=>{if(editBuild('randomize',{count:Number($('legacy-random-count').value),category:$('legacy-category').value,rarity:$('legacy-rarity').value})){notice('Legados sorteados entre os filtros selecionados.');inventory();}};
 function refreshDebug(){if(!admin)return;$('legacy-path-tools').hidden=!state.run||state.watching;$('legacy-debug-tools').hidden=state.watching;$('legacy-debug-seed').value=game.random.state??state.run?.random.state??1;$('legacy-debug-die').value=currentGame().fighters[state.inventorySide]?.legacy?.forcedDie||0;$('legacy-debug-difficulty').value=game.difficulty;if(state.run){$('legacy-path-level').value=state.run.level;$('legacy-path-arena').value=game.mapId;$('legacy-path-boss').value=state.run.encounter?.boss||'';$('legacy-path-mini').value=state.run.encounter?.mini?state.run.encounter.fighters[0].kind:'';}}
 if(admin){
  $('legacy-debug-tools').innerHTML='<h3>ADMIN · Controle da simulação</h3><div class="legacy-lab-tools"><label>D20 · 0 = aleatório<input id="legacy-debug-die" type="number" min="0" max="20" value="0"></label><button id="legacy-force-die" class="secondary">FIXAR D20</button><label>Seed · 0–4294967295<input id="legacy-debug-seed" type="number" min="0" max="4294967295" value="1"></label><button id="legacy-force-seed" class="secondary">APLICAR SEED</button><button id="legacy-force-philosopher" class="secondary">FORÇAR PEDRA FILOSOFAL</button><label>IA<select id="legacy-debug-difficulty"></select></label><button id="legacy-force-difficulty" class="secondary">ALTERAR IA</button></div><details><summary>SIMULAR DRAFT / RECOMPENSA</summary><p>A prévia não consome recursos nem avança o Caminho. Clique numa carta para adicioná-la ao combatente selecionado. Raridade usa o filtro acima; miniboss garante Raro e boss garante Lendário.</p><div class="legacy-lab-tools"><select id="legacy-preview-reward"><option value="normal">Draft comum</option><option value="mini">Recompensa de miniboss</option><option value="boss">Recompensa de boss</option></select><button id="legacy-preview-draft" class="secondary">GERAR PRÉVIA</button></div><div id="legacy-debug-draft" class="legacy-inventory"></div></details><section id="legacy-path-tools"><h3>ADMIN · Caminho do Guerreiro</h3><p>Reconstrói o encontro escolhido com sua build atual. O save passa para esse encontro.</p><div class="legacy-lab-tools"><label>Nível<input id="legacy-path-level" type="number" min="1" max="50"></label><label>Arena<select id="legacy-path-arena"></select></label><label>Boss<select id="legacy-path-boss"><option value="">Padrão do nível</option></select></label><label>Miniboss<select id="legacy-path-mini"><option value="">Padrão do nível</option></select></label><button id="legacy-path-apply" class="secondary">ABRIR ENCONTRO</button></div></section>';
  for(const [id,c]of Object.entries(DuelCore.DIFFICULTIES)){const o=el('option',c.name);o.value=id;$('legacy-debug-difficulty').append(o);}
  for(const id of P.ARENA_IDS){const o=el('option',MAPS[id].name);o.value=id;$('legacy-path-arena').append(o);}for(const b of P.BOSSES){const o=el('option',b.name);o.value=b.id;$('legacy-path-boss').append(o);}for(const [id,c]of Object.entries(CLASSES)){const o=el('option',c.name);o.value=id;$('legacy-path-mini').append(o);}
  $('legacy-path-boss').onchange=()=>{$('legacy-path-mini').value='';};$('legacy-path-mini').onchange=()=>{$('legacy-path-boss').value='';};
  for(const [button,op,inputId]of [['legacy-force-die','die','legacy-debug-die'],['legacy-force-seed','seed','legacy-debug-seed'],['legacy-force-difficulty','difficulty','legacy-debug-difficulty']])$(button).onclick=()=>{if(editBuild(op,op==='difficulty'?$(inputId).value:Number($(inputId).value))){notice('Configuração enviada à simulação.');inventory();}};
  $('legacy-force-philosopher').onclick=()=>{if(editBuild('philosopher')){notice('Transmutação aplicada.');inventory();}};
  $('legacy-preview-draft').onclick=()=>{const seed=Number($('legacy-debug-seed').value);if(!L.validEdit({op:'seed',value:seed},true)){notice('Use uma seed inteira entre 0 e 4294967295.');return;}const preview=L.previewDraft(currentGame().fighters[state.inventorySide],{seed,rarity:$('legacy-rarity').value,reward:$('legacy-preview-reward').value,level:state.run?.level||1,mode:state.run?'path':selected.mode});$('legacy-debug-draft').replaceChildren();for(const id of preview.cards){const c=card(id,{draftMode:true});c.onclick=()=>{if(editBuild('add',id)){c.disabled=true;notice('Legado da prévia enviado à build.');inventory();}};$('legacy-debug-draft').append(c);}if(!preview.cards.length)notice('Nenhum Legado elegível restante para esta build.');};
  $('legacy-path-apply').onclick=()=>{if(!state.run||state.watching||v7?.room)return;const r=state.run;r.inventory=L.clone(game.fighters[0].legacy);if(!r.debugEncounter({level:Number($('legacy-path-level').value),boss:$('legacy-path-boss').value,mini:$('legacy-path-mini').value,arena:$('legacy-path-arena').value,difficulty:$('legacy-debug-difficulty').value,seed:Number($('legacy-debug-seed').value)})){notice('Confira nível, arena e seed.');return;}closeInventory();state.intro=null;intro.hidden=true;nextLevel();};
  const shortcut=el('button','LEGADOS / CAMINHO','secondary');shortcut.id='admin-legacies';shortcut.onclick=()=>{if(state.watching||game.mode==='parkour')return;admin.close();openInventory();$('legacy-library').hidden=false;inventory();};$('admin-console').querySelector('.lab-buttons').append(shortcut);
  const get=admin.hooks.get;admin.hooks.get=()=>({...get(),allowed:!state.watching&&get().allowed});const apply=admin.hooks.apply;admin.hooks.apply=c=>state.watching?false:apply(c);
 }
 function currentDraft(){return state.onlineDraft?.draft||(state.run?.phase==='draft'?state.run.draft:state.offlineDraft?.draft);}
 function draftFighter(){return state.onlineDraft?{legacy:state.onlineDraft.inventory}:state.run?{legacy:state.run.inventory}:game.fighters[state.offlineDraft?.side||0];}
 function drawDraft(){const d=currentDraft();if(!d)return;const f=draftFighter();$('draft-cards').replaceChildren();$('draft-caption').textContent=state.run?'NÍVEL '+state.run.level+' · '+({mini:'VITÓRIA SOBRE MINIBOSS',boss:'BOSS DERROTADO',last:'ÚLTIMO LEGADO',normal:'UM NOVO LEGADO'})[d.ctx.reward]:'JOGADOR '+((state.onlineDraft?.side??state.offlineDraft?.side??0)+1)+' · SEU LEGADO';$('draft-note').textContent=(d.choices>1?'Escolha dois Legados. ':'')+'Sua escolha permanece nesta '+(state.run?'run.':'partida.');for(const [i,id]of d.cards.entries()){const c=card(id,{draftMode:true});c.classList.toggle('selected',i===d.selected);c.disabled=!!d.picked?.includes(id)||state.watching;c.onclick=()=>{d.selected=i;if(state.onlineDraft)v7.room.legacyAction('highlight',{index:i});drawDraft();};$('draft-cards').append(c);}$('draft-reroll').hidden=!L.has(f,'coin');$('draft-reroll').disabled=d.rerolled||!!d.picked?.length||state.watching;$('draft-orb').hidden=!L.has(f,'destinyorb')||!!f.legacy.used.run.destinyorb;$('draft-orb').disabled=!!d.picked?.length||state.watching;$('draft-mark').hidden=!L.has(f,'markedcard');$('draft-confirm').disabled=state.watching||!!state.onlineDraft?.waiting;if(!draft.open)draft.showModal();paused=true;clearInputs();state.watch?.publish();}
 function confirmDraft(){if(state.watching)return;const d=currentDraft();if(!d)return;const id=d.cards[d.selected];if(state.onlineDraft){if(!state.onlineDraft.waiting){state.onlineDraft.waiting=true;v7.room.legacyChoose(id);if(state.onlineDraft)drawDraft();}return;}if(state.run){if(state.run.draft.stealing)state.run.stealPick(id);else state.run.pick(id);save();if(state.run.phase==='between'){draft.close();nextLevel();}else if(state.run.steal?.length&&d.picked?.length>=d.choices){state.run.draft={...d,cards:[...state.run.steal],selected:0,picked:[],choices:1,stealing:true};save();drawDraft();}else drawDraft();}else{const od=state.offlineDraft,f=game.fighters[od.side];L.add(f,id);od.side++;if(od.side<2){od.draft=L.draft(game.fighters[od.side],{mode:selected.mode,futureDraft:$('legacy-mode').value==='round'},Math.random,od.pattern);if(['pve','training','tournament'].includes(selected.mode)){L.add(game.fighters[1],od.draft.cards[Math.floor(Math.random()*od.draft.cards.length)]);finishOfflineDraft();}else drawDraft();}else finishOfflineDraft();}}
 function finishOfflineDraft(){state.offlineDraft=null;draft.close();game.legacyWorld={entities:[],effects:[],serial:0,time:0};game.fighters.forEach(f=>L.spawnCompanions(game,f));L.captureRound(game);paused=false;clearInputs();presentSpecials(()=>{});}
 $('draft-confirm').onclick=confirmDraft;$('draft-reroll').onclick=()=>{if(state.onlineDraft){v7.room.legacyAction('reroll');return;}if(state.run){state.run.reroll();save();}else{const d=L.reroll(draftFighter(),currentDraft(),Math.random);if(d)state.offlineDraft.draft=d;}drawDraft();};$('draft-mark').onclick=()=>{const d=currentDraft(),f=draftFighter();if(state.onlineDraft){v7.room.legacyAction('mark',{legacy:d.cards[d.selected]});return;}f.legacy.marked=d.cards[d.selected];$('draft-error').textContent='Carta marcada para um draft futuro.';save();};
 $('draft-orb').onclick=()=>{const d=currentDraft(),f=draftFighter();if(state.onlineDraft){v7.room.legacyAction('peek');return;}const next=L.peekDraft(f,d,state.run?.random||Math.random);if(!next)return;const names=next.cards.map(id=>L.catalog[id].name).join(' · ');if(confirm('Destino possível: '+names+'\nSubstituir as cartas atuais?')){L.acceptDraft(f,next);if(state.run)state.run.draft=next;else state.offlineDraft.draft=next;}save();drawDraft();};
 function introSound(v,progress){const key=state.run?.level+':'+v.id;if(state.introSoundKey!==key){state.introSoundKey=key;state.introSounds=new Set();}for(const [stage,at]of[.02,.32,.72].entries()){if(progress>=at&&!state.introSounds.has(stage)){state.introSounds.add(stage);if(progress<at+.09)sfx.pathIntro(v.id,stage);}}}
 function beginBossIntro(){const e=state.run.encounter,b=P.BOSSES.find(b=>b.id===e.boss);if(!b||state.run.introCompleted===e.level+':'+b.id){state.intro=null;intro.hidden=true;paused=false;return;}const seen=state.run.seen.includes(b.id)||saves?.history().seen.includes(b.id);$('path-boss-name').textContent=b.name;$('path-boss-sub').textContent=b.subtitle;$('path-skip').hidden=!seen;intro.hidden=false;paused=true;state.intro={id:b.id,duration:b.id==='first'?7000:3200,until:performance.now()+(b.id==='first'?7000:3200)};state.watch?.publish();}
 function endIntro(){if(!state.intro)return;if(!state.run.seen.includes(state.intro.id))state.run.seen.push(state.intro.id);state.run.introCompleted=state.run.level+':'+state.intro.id;state.intro=null;intro.hidden=true;if(modal.open){state.beforePaused=false;paused=true;}else if(admin?.opened){admin.resumeOnClose=true;paused=true;}else paused=!$('pause').hidden;save();state.watch?.publish();}
 $('path-skip').onclick=endIntro;
 function nextLevel(){const r=state.run,enteringArena=!r.gameSave&&[11,21,31,41].includes(r.level);game=r.game();selected.mode='pve';selected.difficulty=game.difficulty;showGame();game.events=[];countdown=0;seat=0;renderer.followId=null;$('left-class').textContent='ERRANTE';pathHud.hidden=false;hud.hidden=false;r.checkpoint(game);save();beginBossIntro();if(enteringArena)showArenaNotice(game.mapId);}
 function beginRun(run){v7?.cleanup();disconnect();state.run=run;state.watching=false;$('path-invite').hidden=false;state.hash='';result.close();if(run.phase==='draft'){game=run.resumeDraftGame();selected.mode='pve';selected.difficulty=game.difficulty;seat=0;renderer.followId=null;showGame();game.events=[];countdown=0;pathHud.hidden=false;hud.hidden=false;drawDraft();}else nextLevel();}
 $('path-new').onclick=()=>{if(readSavedRun()&&!confirm('Já existe uma run salva. Começar outra substitui essa tentativa.'))return;unlockAudio();beginRun(new P.Run({...saves?.history(),points:+$('path-points').value,rules:selected.rules,color:selected.colors[0]}));};$('path-continue').onclick=()=>{const run=readSavedRun();if(run){unlockAudio();beginRun(run);}};
 const outcome=el('section',undefined,'path-outcome');$('path-result-build').before(outcome);
 const formatTime=seconds=>{const s=Math.max(0,Math.floor(seconds||0));return Math.floor(s/60)+':'+String(s%60).padStart(2,'0');};
 function showResult(){
  paused=true;draft.close();$('match').hidden=true;const run=state.run,stats=run.stats,records=state.watching?state.remoteRecords:saves?.history().records;
  $('path-result-title').textContent=run.result;$('path-result-stats').textContent='NÍVEL '+run.level+' / 50 · '+formatTime(stats.time)+' DE COMBATE';
  const numbers=el('dl',undefined,'path-outcome-numbers');for(const [label,value]of [['Duelos',stats.duels],['Inimigos derrotados',stats.kills],['Mortes',stats.deaths],['Legados na build',run.inventory.items.length]]){const cell=el('div');cell.append(el('dt',label),el('dd',String(value||0)));numbers.append(cell);}
  const bossList=el('ul',undefined,'path-outcome-bosses'),encountered=run.encountered||[...new Set([...run.defeated,...(run.encounter?.boss?[run.encounter.boss]:[])])];
  for(const id of encountered){const boss=P.BOSSES.find(b=>b.id===id);if(boss)bossList.append(el('li',boss.name+' · '+(run.defeated.includes(id)?'DERROTADO':'ENFRENTADO')));}
  if(!bossList.children.length)bossList.append(el('li','Nenhum boss enfrentado nesta tentativa.'));
  outcome.replaceChildren(numbers,el('h3','Bosses desta run'),bossList);
  if(records){outcome.append(el('h3',state.watching?'Recordes do anfitrião':'Recordes neste navegador'),el('p',records.wins+' vitórias · maior nível '+records.bestLevel+(records.bestTime!==null?' · melhor conclusão '+formatTime(records.bestTime):' · nenhuma conclusão registrada')));}
  outcome.append(el('h3','Sua build'));const f={legacy:run.inventory};$('path-result-build').replaceChildren(...run.inventory.items.map(id=>{const effective=run.inventory.transforms.find(t=>t.from===id)?.to||id,item=el('div',undefined,'path-result-item'),status=L.status(f,effective);item.append(cardIcon(effective),el('span',L.catalog[effective].name));if(status.consumed||status.used)item.append(el('small',status.label));item.title=L.describe(effective);return item;}));if(!run.inventory.items.length)$('path-result-build').append(el('p','Nenhum Legado adquirido nesta tentativa.'));
  $('path-retry').hidden=!admin||run.phase!=='lost';if(!result.open)result.showModal();state.watch?.publish();
 }
 $('path-retry').onclick=()=>{if(admin&&state.run.retry()){result.close();nextLevel();}};$('path-result-menu').onclick=()=>{result.close();returnMenu();};
 state.events=ev=>{if(state.watching)return false;if(ev.type==='round'&&v7?.room?.host&&v7.room.config?.legacyMode==='round')v7.room.startLegacyDraft(game);if(state.run){if(ev.type==='round'||ev.type==='roundGo'){state.run.checkpoint(game);save();}if(ev.type==='matchEnd'){state.run.reward(game);save();if(['won','lost'].includes(state.run.phase))showResult();else if(state.run.phase==='draft')drawDraft();else nextLevel();return true;}}else if(ev.type==='round'&&game.legacyEnabled&&$('legacy-mode').value==='round'&&!v7?.room){const pattern=L.draftPattern();state.offlineDraft={side:0,pattern,draft:L.draft(game.fighters[0],{mode:selected.mode,futureDraft:true},Math.random,pattern)};drawDraft();}return false;};
 state.afterStart=()=>{if($('legacy-mode').value==='off'||selected.mode==='parkour')return false;game.legacyEnabled=true;game.fighters.forEach(f=>L.ensure(f));const pattern=L.draftPattern();state.offlineDraft={side:0,pattern,draft:L.draft(game.fighters[0],{mode:selected.mode,futureDraft:$('legacy-mode').value==='round'},Math.random,pattern)};drawDraft();return true;};
 state.cleanup=()=>{state.arenaNotice=null;arenaNotice.hidden=true;if(state.run&&!state.watching)save();state.watch?.close();state.watch=null;state.run=null;state.watching=false;state.remoteRecords=null;state.offlineDraft=null;state.onlineDraft=null;state.intro=null;modal.close();draft.close();result.close();intro.hidden=true;hud.hidden=true;pathHud.hidden=true;state.pending.clear();state.held.clear();updateContinue();};
 state.frame=dt=>{state.clock+=dt;if(intro.hidden)state.introSoundKey=null;if(state.arenaNotice&&performance.now()>=state.arenaNotice.until){state.arenaNotice=null;arenaNotice.hidden=true;}if(!intro.hidden){const v=state.watching?state.remoteIntro:state.intro;if(v){const progress=state.watching?(v.progress||0)+(performance.now()-v.receivedAt)/(v.duration||3200):1-(v.until-performance.now())/(v.duration||3200);introSound(v,progress);DuelV8Visuals.bossIntro($('path-intro-art'),game,v.id,progress,state.clock);}}if(modal.open){const inventoryKey=JSON.stringify([state.inventorySide,currentGame().fighters[state.inventorySide]?.legacy?.items,currentGame().fighters[state.inventorySide]?.legacy?.transforms,currentGame().fighters[state.inventorySide]?.legacy?.consumed,currentGame().fighters[state.inventorySide]?.legacy?.used]);if(inventoryKey!==state.inventoryHash){state.inventoryHash=inventoryKey;inventory();}} if(state.capture&&input.pad){const down=input.pad.buttons.map(b=>b.pressed),i=down.findIndex((on,i)=>on&&!state.capture.padOld[i]);state.capture.padOld=down;if(i>=0)captureBinding('Pad'+i);}if(state.onlineDraft){$('draft-note').textContent=(state.onlineDraft.waiting?'ESCOLHA CONFIRMADA · aguardando o rival. ':'ESCOLHA SECRETA · ')+Math.max(0,Math.ceil((state.onlineDraft.deadline-Date.now())/1000))+' s';}if(state.intro&&performance.now()>=state.intro.until)endIntro();if(modal.open||draft.open||state.intro||state.watching)input.enabled=false;hud.hidden=inMenu||!currentGame().legacyEnabled;pathHud.hidden=inMenu||!state.run;const f=currentGame().fighters[state.watching?0:currentSeat()],l=f?.legacy,ids=l?l.items.map(id=>l.transforms.find(t=>t.from===id)?.to||id):[],key=ids.join(',');
 if(key!==state.hash){state.hash=key;hud.replaceChildren();hud.classList.toggle('crowded',ids.length>24);for(const id of ids){const button=el('button',undefined,'legacy-chip');button.dataset.legacyHud=id;button.append(cardIcon(id));if(['icarus','rockets'].includes(id)){const meter=el('span',undefined,'legacy-energy');meter.setAttribute('role','meter');meter.setAttribute('aria-label','Energia de voo');meter.setAttribute('aria-valuemin','0');meter.setAttribute('aria-valuemax','100');button.append(meter);}button.onclick=openInventory;hud.append(button);}const b=el('button','TAB','legacy-tab');b.onclick=openInventory;hud.append(b);}
 if(l)for(const b of hud.querySelectorAll('[data-legacy-hud]')){const id=b.dataset.legacyHud,status=L.status(f,id);b.classList.toggle('consumed',status.consumed||status.used);b.classList.toggle('cooling',status.remaining>0);b.classList.toggle('weapon-away',status.away);b.style.setProperty('--ready',Math.round(status.progress*100)+'%');const energy=b.querySelector('.legacy-energy');if(energy){const value=Math.round(status.energy*100);energy.style.setProperty('--energy',value+'%');energy.setAttribute('aria-valuenow',value);}b.title=L.catalog[id].name+' · '+status.label+(status.energy!==null?' · ENERGIA '+Math.round(status.energy*100)+'%':'')+(status.binding?' · '+status.binding.replace('Digit',''):'');b.setAttribute('aria-label',b.title);}
 if(modal.open){const actor=currentGame().fighters[state.inventorySide];if(actor)for(const e of modal.querySelectorAll('[data-legacy-status]'))e.textContent=L.status(actor,e.dataset.legacyStatus).label;}
 if(state.run){$('path-level').textContent='CAMINHO · '+state.run.level+' / 50 · PRIMEIRO A '+state.run.points;$('left-class').textContent='ERRANTE';$('right-class').textContent=state.run.encounter?.boss?P.BOSSES.find(b=>b.id===state.run.encounter.boss)?.name:game.fighters.length-1+' ADVERSÁRIO'+(game.fighters.length>2?'S':'');}$('path-build').disabled=inMenu;state.watch?.tick(dt);};
 $('path-build').onclick=openInventory;
 function captureBinding(code){const c=state.capture;if(!c||state.watching)return;const f=currentGame().fighters[c.side],base=code.startsWith('Pad')?Object.values(input.settings.pad).flat().map(n=>'Pad'+n):Object.values(input.settings.keyboard).flat();let r=L.bind(f,c.id,code,base);if(r.conflict&&confirm('Substituir o atalho de '+L.catalog[r.conflict].name+'?'))r=L.bind(f,c.id,code,base,true);notice(r.ok?'Atalho atribuído.':r.error);if(r.ok){state.capture=null;if(!lab.viewGame&&game.mode==='training')lab.patchLegacy(game);if(state.run&&!lab.viewGame){state.run.checkpoint(game);save();}}inventory();}
 window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(state.capture){e.preventDefault();if(e.code==='Escape'){state.capture=null;return;}captureBinding(e.code);return;}if(e.code==='Tab'&&!inMenu){e.preventDefault();if(modal.open)closeInventory();else openInventory();return;}if(draft.open&&!state.watching){const d=currentDraft();if(!d)return;if(['ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();d.selected=(d.selected+(e.code==='ArrowRight'?1:d.cards.length-1))%d.cards.length;if(state.onlineDraft)v7.room.legacyAction('highlight',{index:d.selected});drawDraft();}if(e.code==='Enter'){e.preventDefault();confirmDraft();}return;}if(!input.enabled||state.watching||inMenu)return;const id=Object.keys(currentGame().fighters[currentSeat()]?.legacy?.bindings||{}).find(id=>currentGame().fighters[currentSeat()].legacy.bindings[id]===e.code);if(id){e.preventDefault();if(!e.repeat)state.pending.add(id);state.held.add(id);}});
 window.addEventListener('pointerdown',e=>{if(state.capture){e.preventDefault();captureBinding('Mouse'+e.button);return;}if(e.target!==canvas||!input.enabled||state.watching||inMenu)return;const code='Mouse'+e.button,id=Object.keys(currentGame().fighters[currentSeat()]?.legacy?.bindings||{}).find(id=>currentGame().fighters[currentSeat()].legacy.bindings[id]===code);if(id){e.preventDefault();state.pending.add(id);state.held.add(id);}});window.addEventListener('pointerup',e=>{for(const f of currentGame().fighters)for(const [id,key]of Object.entries(f.legacy?.bindings||{}))if(key==='Mouse'+e.button)state.held.delete(id);});modal.addEventListener('contextmenu',e=>{if(state.capture)e.preventDefault();});
 window.addEventListener('keyup',e=>{for(const f of currentGame().fighters)for(const [id,key]of Object.entries(f.legacy?.bindings||{}))if(key===e.code)state.held.delete(id);});window.addEventListener('blur',()=>{state.pending.clear();state.held.clear();});
 window.DuelLegacyInput={read:(source,f,consume)=>{const active=source==='keyboard'?[...state.pending]:[],held=source==='keyboard'?[...state.held]:[];if(source==='pad'&&input.pad){for(const [id,key]of Object.entries(f.legacy?.bindings||{})){if(!key.startsWith('Pad'))continue;const n=+key.slice(3),down=input.pad.buttons[n]?.pressed;state.padOld??={};if(down){held.push(id);if(!state.padOld[id])active.push(id);}if(consume)state.padOld[id]=down;}}if(consume&&source==='keyboard')state.pending.clear();return{legado:active,legadoHeld:held};}};
 state.serializeWatch=()=>DuelPathWatch.frame(game,state.run,{records:state.run&&['won','lost'].includes(state.run.phase)?saves?.history().records:null,paused:paused||modal.open||draft.open,inventorySide:state.inventorySide,arenaNotice:state.arenaNotice?{mapId:state.arenaNotice.mapId,remaining:Math.max(0,state.arenaNotice.until-performance.now())}:null,view:draft.open?'draft':result.open?'result':modal.open?'inventory':intro.hidden?'fight':'intro',intro:state.intro?{...state.intro,progress:Math.max(0,1-(state.intro.until-performance.now())/state.intro.duration),name:$('path-boss-name').textContent,subtitle:$('path-boss-sub').textContent}:null});
 $('path-invite').onclick=async()=>{if(state.watching||!state.run)return;try{state.watch?.close();state.watch=new DuelPathWatch({status:t=>$('path-room').textContent=t,get:state.serializeWatch});await state.watch.open(true);$('path-room').textContent='ESPECTADORES · '+state.watch.code;try{await navigator.clipboard.writeText(state.watch.code);}catch{}}catch(e){$('path-room').textContent=e.message;}};
 $('path-watch').onclick=async()=>{const code=prompt('Código da run do seu amigo:');if(!code)return;try{state.watch?.close();const watch=new DuelPathWatch({status:t=>$('path-save-note').textContent=t,closed:reason=>returnMenu(reason),receive:s=>{if(!s?.game||!s.run)return;if(s.arenaNotice?.remaining>0)showArenaNotice(s.arenaNotice.mapId,s.arenaNotice.remaining);else{state.arenaNotice=null;arenaNotice.hidden=true;}const first=!state.watching;state.watching=true;state.run=P.Run.restore(s.run);state.remoteRecords=s.records||null;game.loadSnapshot(s.game);if(first){selected.mode='pve';showGame();}paused=true;pathHud.hidden=false;$('path-invite').hidden=true;$('path-room').textContent='ASSISTINDO · '+code.toUpperCase();if(s.view==='draft')drawDraft();else draft.close();if(s.view==='inventory'){if(!modal.open)openInventory();state.inventorySide=s.inventorySide||0;$('legacy-side').value=state.inventorySide;$('legacy-library').hidden=true;inventory();}else if(modal.open)modal.close();if(s.view==='result')showResult();else result.close();if(s.view==='intro'&&s.intro){state.remoteIntro={...s.intro,receivedAt:performance.now()};intro.hidden=false;$('path-boss-name').textContent=s.intro.name;$('path-boss-sub').textContent=s.intro.subtitle;$('path-skip').hidden=true;}else intro.hidden=true;}});state.watch=watch;await watch.open(false,code);}catch(e){$('path-save-note').textContent=e.message;}};
 const previousSnapshot=window.duelSnapshot;window.duelSnapshot=()=>({...previousSnapshot(),version:8,release:'8',pathEncounter:game.pathEncounter||null,legacyWorld:game.legacyWorld||null,path:state.run?.serialize()||null,legacyPanel:modal.open,legacyDraft:currentDraft()});
 const previousSync=session.sync.bind(session);session.sync=g=>{if(!(g||session.match)?.pathEncounter)previousSync(g);};
 state.onlineOffer=packet=>{state.onlineDraft=packet;state.inventorySide=packet.side;$('room-intro').close();drawDraft();if(packet.draft.preview){const text=packet.draft.preview.map(id=>L.catalog[id].name).join(' · ');if(confirm('Destino possível: '+text+'\nSubstituir as cartas atuais?'))v7.room.legacyAction('replace');}};
 state.onlineDone=packet=>{state.onlineDraft=null;draft.close();game.loadSnapshot(L.restoreLocalBindings(game,packet.snapshot));L.captureRound(game);paused=false;state.hash='';clearInputs();};
 $('legacy-mode').onchange=()=>v7?.configChanged();
 updateContinue();return state;
}



