(function(){
class DuelAudio{
 constructor(){this.muted=false;this.duckUntil=0;}
 unlock(){try{if(!this.ctx){const c=this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.master=c.createGain();const compressor=c.createDynamicsCompressor();compressor.threshold.value=-15;compressor.ratio.value=5;this.master.connect(compressor);compressor.connect(c.destination);this.ambience=c.createGain();this.ambience.gain.value=0;this.ambience.connect(this.master);for(const hz of[55,82.41]){const o=c.createOscillator();o.type='sine';o.frequency.value=hz;o.connect(this.ambience);o.start();}}if(this.ctx.state==='suspended')this.ctx.resume().catch(()=>{});}catch{}}
 setMuted(value){this.muted=value;if(this.master)this.master.gain.setTargetAtTime(value?0:.75,this.ctx.currentTime,.02);}
 ambient(active){if(!this.ctx)return;this.ambience.gain.setTargetAtTime(active&&this.ctx.currentTime>this.duckUntil?.008:0,this.ctx.currentTime,.06);}
 tone(hz,duration,volume,type='sine',end){if(!this.ctx||this.muted)return;const c=this.ctx,t=c.currentTime,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(hz,t);if(end)o.frequency.exponentialRampToValueAtTime(end,t+duration);g.gain.setValueAtTime(Math.max(.0001,volume),t);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(this.master);o.start();o.stop(t+duration);o.onended=()=>{o.disconnect();g.disconnect();};}
 noise(duration,volume,hz){if(!this.ctx||this.muted)return;const c=this.ctx,n=Math.ceil(c.sampleRate*duration),b=c.createBuffer(1,n,c.sampleRate),d=b.getChannelData(0);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n)**2;const s=c.createBufferSource(),g=c.createGain(),f=c.createBiquadFilter();s.buffer=b;f.type='bandpass';f.frequency.value=hz;f.Q.value=.8;g.gain.value=volume;s.connect(f);f.connect(g);g.connect(this.master);s.start();s.onended=()=>{s.disconnect();g.disconnect();f.disconnect();};}
 play(type,ev={}){if(!this.ctx||this.muted)return;const tone=(...a)=>this.tone(...a),noise=(...a)=>this.noise(...a),profiles={duelist:{pitch:3400,ring:2450,swing:.063,weight:.75},staff:{pitch:580,ring:185,swing:.17,weight:1.2,wood:true},knight:{pitch:1450,ring:840,swing:.12,weight:1},lancer:{pitch:1950,ring:1190,swing:.16,weight:.95},assassin:{pitch:3100,ring:1760,swing:.07,weight:.68},swordsman:{pitch:740,ring:470,swing:.18,weight:1.3},reaper:{pitch:1250,ring:610,swing:.21,weight:1.15},boxer:{pitch:330,ring:95,swing:.06,weight:1,body:true}},voice=profiles[ev.kind]||profiles.knight,pitch=voice.pitch;
 if(type==='propHit'){if(ev.prop==='bell'){tone(131,.9,.13);tone(196,1.2,.07);tone(370,.7,.04);}else noise(.09,.11,ev.prop==='bamboo'?900:2200);return;}if(type==='kill'){if(ev.finisher){tone(52,.3,.2,'sine',24);tone(pitch*.7,.24,.035,'triangle',pitch*.2);}this.duckUntil=this.ctx.currentTime+.48;this.ambience.gain.cancelScheduledValues(this.ctx.currentTime);this.ambience.gain.setValueAtTime(0,this.ctx.currentTime);tone(voice.body?65:voice.wood?98:82,.19,.34,'sine',29);noise(voice.body?.075:voice.wood?.095:.11,.53,pitch);tone(voice.ring,voice.wood?.085:.16,voice.body?.045:.06,'triangle',voice.ring*.42);}
 else if(type==='parry'||type==='clash'){if(ev.perfect){tone(220,.18,.18,'triangle',70);tone(3520,.38,.055);noise(.035,.3,5300);}if(voice.wood||voice.body){tone(voice.ring,.065,.19,'triangle',voice.ring*.65);noise(.045,.26,voice.wood?950:420);if(ev.attackerKind&&!['staff','boxer'].includes(ev.attackerKind))tone(profiles[ev.attackerKind]?.ring||1100,.15,.055);}else{for(const[h,v]of[[voice.ring,ev.perfect?.21:.14],[voice.ring*1.51,.085],[voice.ring*2.13,.04]])tone(h,type==='parry'?.24:.15,v);noise(.038,.19,pitch*1.6);}if(type==='clash'&&ev.kinds?.[1]&&ev.kinds[1]!==ev.kind){const other=profiles[ev.kinds[1]]||profiles.knight;tone(other.ring,.11,.06,'triangle');}}
 else if(type==='nearMiss'){noise(voice.swing*.55,.15,pitch*1.25);tone(voice.ring*.7,.055,.018,'sine',voice.ring*.25);}
 else if(type==='special'){const h={duelist:880,staff:165,knight:196,lancer:147,assassin:740,swordsman:294,reaper:110,boxer:370}[ev.kind]||220;tone(h,.3,.11,'triangle',h*1.5);tone(h*2,.2,.06);noise(.09,.08,pitch);}
 else if(type==='matchPoint'){tone(392,.35,.07);tone(587,.45,.035);}
 else if(type==='swing'){noise(voice.swing,.11*voice.weight,pitch);if(voice.wood)noise(.075,.04,240);else if(voice.body)tone(140,.04,.025,'sine',65);else if(ev.kind==='duelist')tone(4200,.045,.014,'sine',1900);}
 else if(['dash','slide','wallJump','daggerThrow','chargeStart'].includes(type))noise(type==='chargeStart'?.2:.10,.09,type==='daggerThrow'?2700:650);
 else if(['kick','shieldBreak','chargeStop'].includes(type)){tone(125,.13,.14,'triangle',45);noise(.08,.15,800);}
 else if(type==='feint')noise(.04,.05,900);
 else if(type==='roundGo'||type==='round'){tone(480,.1,.035);tone(720,.15,.02);}
 }
}
window.DuelAudio=DuelAudio;
})();
