(function(root){
'use strict';
const D=typeof module!=='undefined'?require('./engine.js'):root.DuelCore,{clamp,neutral,body,stats}=D,copy=o=>JSON.parse(JSON.stringify(o));
const TRACKS={};
function track(id,name,theme,width,height,platforms,walls,start,checkpoints,finish,routes){const m=D.cleanMap({format:'um-corte-map',version:1,id:'custom_race_'+id,type:'parkour',name,description:{wind:'Ventos da costa. Passagens baixas, saltos e atalhos sobre os portais.',spire:'Suba o pagode. Paredes, patamares e quedas com retorno rápido.',foundry:'Uma travessia sobre brasas. Elevadores e caminhos de risco.'}[id],width,height,theme,platforms,walls,spawns:[start,{x:start.x+40,y:start.y}],race:{start,checkpoints:checkpoints.map((p,i)=>({...p,order:i+1})),finish,routes},ground:theme==='forge'?'#716068':'#6e907c',weather:theme==='forge'?'embers':'leaves',decor:[],background:{layers:[],tint:'#17323b',shade:.12}});m.builtinRace=true;TRACKS[m.id]=m;D.MAPS[m.id]=m;return m;}
const ground=(x,y,w)=>({x,y,w,solid:true});
// Distinct courses, authored checkpoint-to-checkpoint lines define race progress.
track('wind','Caminho dos Ventos','sanctuary',6900,1000,
 [ground(30,770,750),ground(925,710,570),ground(1675,770,650),ground(2490,670,600),ground(3240,770,720),ground(4150,710,580),ground(4900,770,650),ground(5720,680,1100),{x:1250,y:530,w:240},{x:2110,y:555,w:240},{x:3500,y:560,w:230},{x:5190,y:560,w:230}],
 [{x:550,y:500,w:180,h:204},{x:3600,y:485,w:190,h:219},{x:6090,y:410,w:190,h:204}],{x:160,y:770},[{x:1870,y:770},{x:3440,y:770},{x:5110,y:770}],{x:6630,y:680},
 [[{x:160,y:770},{x:1100,y:710},{x:1870,y:770}],[{x:1870,y:770},{x:2770,y:670},{x:3440,y:770}],[{x:3440,y:770},{x:4440,y:710},{x:5110,y:770}],[{x:5110,y:770},{x:6000,y:680},{x:6630,y:680}]]);
const spirePlatforms=[ground(80,3550,1120)];for(let i=1;i<=19;i++)spirePlatforms.push({x:i%2?340:690,y:3550-i*160,w:290,solid:false});
track('spire','Escadaria do Céu','tower',1450,3900,spirePlatforms,[{x:250,y:420,w:35,h:3130},{x:1080,y:420,w:35,h:3130}],{x:460,y:3550},[{x:470,y:2750},{x:820,y:1950},{x:470,y:1150}],{x:470,y:510},
 [[{x:460,y:3550},{x:470,y:3390},{x:820,y:3230},{x:470,y:3070},{x:820,y:2910},{x:470,y:2750}],[{x:470,y:2750},{x:820,y:2590},{x:470,y:2430},{x:820,y:2270},{x:470,y:2110},{x:820,y:1950}],[{x:820,y:1950},{x:470,y:1790},{x:820,y:1630},{x:470,y:1470},{x:820,y:1310},{x:470,y:1150}],[{x:470,y:1150},{x:820,y:990},{x:470,y:830},{x:820,y:670},{x:470,y:510}]]);
const mixed=[ground(30,1640,650),{x:800,y:1480,w:260},{x:1220,y:1320,w:260},ground(1610,1160,510),{x:2260,y:1000,w:240},{x:2650,y:840,w:240},ground(3050,680,600),{x:3810,y:840,w:220},ground(4200,1000,400),{x:4740,y:1160,w:240},ground(5140,1320,430),{x:5720,y:1160,w:250},ground(6110,1000,510),{x:6760,y:840,w:260},ground(7180,680,590),
 {x:2220,y:1180,w:220,motion:{x:530,y:-340,period:3.5,pause:.6,route:true}},{x:3590,y:680,w:170,fragile:{delay:.6,respawn:3}},{x:3870,y:620,w:180,fragile:{delay:.6,respawn:3}},{x:4170,y:720,w:210},{x:5580,y:1330,w:170,motion:{x:410,y:-220,period:3,pause:.5,route:true}}];
track('foundry','Rota das Brasas','forge',7900,1920,mixed,[{x:3060,y:410,w:30,h:270},{x:7600,y:310,w:30,h:370}],{x:180,y:1640},[{x:1830,y:1160},{x:3380,y:680},{x:5310,y:1320},{x:6380,y:1000}],{x:7480,y:680},
 [[{x:180,y:1640},{x:930,y:1480},{x:1350,y:1320},{x:1830,y:1160}],[{x:1830,y:1160},{x:2380,y:1000},{x:2770,y:840},{x:3380,y:680}],[{x:3380,y:680},{x:3920,y:840},{x:4400,y:1000},{x:4860,y:1160},{x:5310,y:1320}],[{x:5310,y:1320},{x:5840,y:1160},{x:6380,y:1000}],[{x:6380,y:1000},{x:6890,y:840},{x:7480,y:680}]]);
function cleanOptions(o={}){return{contact:!!o.contact,allClasses:!!o.allClasses,afterFirst:clamp(Number.isFinite(+o.afterFirst)?+o.afterFirst:30,5,180)};}
function crossed(a,b,g){const left=g.x-g.w/2,right=g.x+g.w/2,top=g.y-g.h,bottom=g.y+10;let lo=0,hi=1;for(const [p,d,min,max]of[[a.x,b.x-a.x,left,right],[a.y-40,b.y-a.y,top,bottom]]){if(Math.abs(d)<1e-9){if(p<min||p>max)return false;}else{const t1=(min-p)/d,t2=(max-p)/d;lo=Math.max(lo,Math.min(t1,t2));hi=Math.min(hi,Math.max(t1,t2));}}return lo<=hi;}
function segmentProgress(p,points){let best=Infinity,progress=0,total=0,walk=0;for(let i=1;i<points.length;i++)total+=Math.hypot(points[i].x-points[i-1].x,points[i].y-points[i-1].y);for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy),u=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/(len*len||1),0,1),dist=Math.hypot(p.x-a.x-dx*u,p.y-a.y-dy*u);if(dist<best){best=dist;progress=walk+len*u;}walk+=len;}return clamp(progress/(total||1),0,.99999);}
class Race extends D.Game{
 constructor(o={}){super({mode:'local',ai:false,mapId:'dojo'});this.setup(o);}
 setup(o){this.mode='parkour';this.mapSource=D.cleanMap(o.mapData||D.MAPS[o.mapId]||Object.values(TRACKS)[0]);if(this.mapSource.type!=='parkour')throw Error('Escolha uma pista de Parkour.');this.mapId=this.mapSource.id;this.map=D.makeMap(this.mapId,1,this.mapSource);this.rules=D.cleanRules({...o.rules,specials:false,chaos:'off',mapSize:1});this.baseRules={...this.rules};this.options=cleanOptions(o.options);this.timeOfDay=o.timeOfDay||'day';this.difficulty=D.DIFFICULTIES[o.difficulty]?o.difficulty:'normal';this.members=(o.members?.length?o.members:[{name:'Você',kind:'runner',color:'jade'}]).slice(0,8).map((p,i)=>({name:String(p.name||'Corredor '+(i+1)).slice(0,24),kind:this.options.allClasses&&D.CLASSES[p.kind]?p.kind:'runner',color:D.COLORS[p.color]?p.color:Object.keys(D.COLORS)[i],skin:D.cleanSkin(p.kind,p.skin),bot:!!p.bot}));this.characters=this.members.map(p=>p.kind);this.colors=this.members.map(p=>p.color);this.skins=this.members.map(p=>p.skin);this.start();}
 emit(type,data={}){this.events??=[];this.events.push({type,...data});}
 start(){if(!this.members)return;this.phase='countdown';this.countTicks=1800;this.ticks=0;this.time=0;this.round=1;this.score=this.members.map(()=>0);this.hitstop=0;this.events=[];this.deadline=null;this.results=[];this.routeCache=new Map();this.propStates=[];this.fighters=this.members.map((p,id)=>{const f=D.makeFighter(id,p.kind,p.color,this.mapSource.race.start);this.resetSpecial(f);Object.assign(f,{parkour:true,skin:p.skin,name:p.name,bot:p.bot,admin:{},dashCharges:this.rules.dashCount,airDashes:0,checkpoint:0,progress:0,respawn:0,protection:1,finished:false,dnf:false,falls:0,aiRace:{}});return f;});this.map=D.makeMap(this.mapId,1,this.mapSource);this.updatePlatforms(0,false);this.emit('raceStart');}
 attack(){return false;}parry(){return false;}special(){return false;}tickSpecial(){}resolveCombat(){}separateBodies(){}
 kick(id){const f=this.fighters[id];if(!this.options.contact||!this.canAct(f)||f.kickCooldown>0)return false;f.protection=0;return super.kick(id);}
 respawnRunner(f){const cp=f.checkpoint?this.mapSource.race.checkpoints[f.checkpoint-1]:this.mapSource.race.start;Object.assign(f,{x:cp.x,y:cp.y,vx:0,vy:0,grounded:true,platform:-1,dead:false,state:'idle',stateTime:0,duration:0,dashRemaining:0,slideRemaining:0,wallSide:0,lastWall:-1,wallReleased:true,wallLock:0,dashCharges:this.rules.dashCount,dashCooldown:0,airDashes:0,airUsed:false,jumping:false,protection:1,aiRace:{},tauntTime:0});this.emit('respawn',{id:f.id,x:f.x,y:f.y});}
 fall(f){if(f.respawn||f.finished||f.dnf)return;f.falls++;f.respawn=.5;f.dead=true;f.deathTime=0;f.vx=f.vy=0;this.emit('raceFall',{id:f.id,x:f.x,y:f.y});}
 finishRunner(f){if(f.finished||f.dnf)return;f.finished=true;f.finishMs=Math.round(this.ticks*1000/600);f.place=this.results.length+1;this.results.push(f.id);f.state='idle';f.vx=f.vy=0;if(this.deadline===null)this.deadline=this.ticks+Math.round(this.options.afterFirst*600);this.emit('raceFinish',{id:f.id,place:f.place,time:f.finishMs});}
 drop(id){const f=this.fighters[id];if(f&&!f.finished){f.dnf=true;f.dead=true;}this.checkEnd();}
 checkEnd(){if(this.deadline!==null&&this.ticks>=this.deadline)for(const f of this.fighters)if(!f.finished)f.dnf=true;if(this.fighters.every(f=>f.finished||f.dnf)){this.phase='raceEnd';this.emit('raceEnd');}}
 step(dt,inputs=[]){if(!(dt>0)||this.phase==='raceEnd')return;if(this.phase==='countdown'){this.countTicks--;if(this.countTicks<=0){this.phase='playing';this.emit('raceGo');}return;}if(this.phase!=='playing')return;this.ticks++;this.time=this.ticks/600;this.updatePlatforms(this.time);const before=this.fighters.map(f=>({x:f.x,y:f.y}));
  for(const f of this.fighters){if(f.finished||f.dnf)continue;if(f.respawn>0){f.respawn=Math.max(0,f.respawn-dt);if(!f.respawn)this.respawnRunner(f);continue;}let c=f.bot?this.botInput(f,dt):{...neutral(),...inputs[f.id]};c.attack=c.parry=c.special=c.attackHeld=false;f.protection=Math.max(0,f.protection-dt);this.tickState(f,dt);f.aim=Number.isFinite(c.aim)?c.aim:f.aim;f.facing=D.aimSide(f.aim,f.facing);if(c.dash)this.command(f.id,'dash',c);if(c.kick)this.kick(f.id);if(f.queued&&this.canAct(f)){const q=f.queued;this.command(f.id,q.action,q);}if(c.move||c.jump||c.dash||c.kick||f.state!=='idle'||!f.grounded)f.tauntTime=0;else if(c.taunt)f.tauntTime=.9;else f.tauntTime=Math.max(0,(f.tauntTime||0)-dt);this.moveFighter(f,c,dt);if(f.y>this.map.deathY){this.fall(f);continue;}const cp=this.mapSource.race.checkpoints[f.checkpoint];if(cp&&crossed(before[f.id],f,cp)){f.checkpoint++;this.emit('checkpoint',{id:f.id,index:f.checkpoint,x:f.x,y:f.y});f.aiRace={};}else if(!cp&&crossed(before[f.id],f,this.mapSource.race.finish))this.finishRunner(f);f.progress=segmentProgress(f,this.mapSource.race.routes[Math.min(f.checkpoint,this.mapSource.race.routes.length-1)]);}
  if(this.options.contact)for(const a of this.fighters){if(a.state!=='kickActive'||a.kickHit||a.finished||a.dnf)continue;for(const b of this.fighters){if(a===b||b.dead||b.finished||b.dnf||b.protection>0)continue;if((b.x-a.x)*a.kickSide<0||Math.abs(b.x-a.x)>72||Math.abs(b.y-a.y)>65)continue;if(this.map.walls.some(w=>a.y-50>w.y&&a.y-50<w.y+w.h&&Math.min(a.x,b.x)<w.x+w.w&&Math.max(a.x,b.x)>w.x))continue;a.kickHit=true;this.setState(b,'pushed',.10);b.vx=a.kickSide*330;b.vy=Math.min(b.vy,-70);b.grounded=false;this.emit('kick',{id:a.id,x:b.x,y:b.y-50});}}
  this.checkEnd();
 }
 ranking(){return[...this.fighters].sort((a,b)=>a.finished&&b.finished?a.place-b.place:a.finished?-1:b.finished?1:a.dnf!==b.dnf?(a.dnf?1:-1):b.checkpoint-a.checkpoint||b.progress-a.progress||a.id-b.id).map((f,i)=>({id:f.id,name:f.name,place:f.place||i+1,checkpoint:f.checkpoint,progress:f.progress,finished:f.finished,dnf:f.dnf,time:f.finishMs??Math.round(this.ticks*1000/600),falls:f.falls}));}
 botInput(f,dt){const c=neutral(),a=f.aiRace||(f.aiRace={}),difficulty=this.difficulty,skill=Math.min(1,({easy:.74,normal:.82,adaptive:.87,impossible:.97,master:1}[difficulty]||.82)+(f.falls>0?.12:0)-(f.id%3)*.007);c.jumpHeld=true;const gate=this.mapSource.race.checkpoints[f.checkpoint]||this.mapSource.race.finish;
  // Plan only at a landing. Every edge describes a physical jump, never a teleport.
  if(f.grounded&&(!a.path||a.platform!==f.platform||a.age>.6)){a.path=this.path(f,gate,skill);a.platform=f.platform;a.age=0;}a.age=(a.age||0)+dt;
  let target=a.path?.[0];if(target&&f.grounded&&f.platform===target.id){a.path.shift();target=a.path[0];}const p=target?this.map.platforms[target.id]:null,tx=p?clamp(f.x,p.x+35,p.x+p.w-35):gate.x,ty=p?p.y:gate.y,dx=tx-f.x,dy=ty-f.y,dir=Math.sign(dx)||Math.sign(gate.x-f.x)||1;c.move=Math.abs(dx)>12?dir*skill:0;c.aim=dir<0?Math.PI:0;
  const floor=this.map.platforms[f.platform],edge=floor?(dir>0?floor.x+floor.w-f.x:f.x-floor.x):999;
  if(f.grounded){const gap=p&&floor&&(p.x>floor.x+floor.w||p.x+p.w<floor.x),rising=dy<-35;if(rising&&Math.abs(dx)<300||gap&&edge<75||!floor||edge<35)c.jump=true;if(!rising&&!gap&&Math.abs(dx)>230&&edge>230&&skill>.8)c.dash=true;const overhead=this.map.walls.find(w=>w.x<f.x+dir*140+40&&w.x+w.w>f.x+dir*140-40&&w.y+w.h>f.y-115&&w.y+w.h<f.y-40);if(overhead&&Math.abs(dx)>80){c.down=true;c.dash=true;c.jump=false;}}
  else{if(p){const near=f.x>p.x+20&&f.x<p.x+p.w-20;if(near){c.move=clamp((p.x+p.w/2-f.x)/65,-1,1)*skill;if(f.y<=p.y&&f.vy>0)c.down=skill>.8;}if(f.vy>-80&&f.vy<300&&!near&&Math.abs(dx)>85&&skill>.75){c.dash=true;c.up=dy<-100;}}if(f.wallSide){c.move=f.wallSide;c.up=true;if(f.wallLock<=0&&(f.wallId!==f.lastWall||f.wallReleased)){c.jump=true;a.wallAt=this.time;}}}
  if(a.launch&&this.time-a.launch<.12)c.jump=false; // one edge per landing; held jump controls height
  if(c.jump)a.launch=this.time;
  return c;
 }
 path(f,gate,skill){const ps=this.map.platforms,n=ps.length,start=f.platform,target=ps.findIndex(p=>gate.x>=p.x&&gate.x<=p.x+p.w&&Math.abs(gate.y-p.y)<4);if(start<0||target<0||start===target)return[];const cost=Array(n).fill(Infinity),prev=Array(n).fill(-1),open=new Set([start]);cost[start]=0;while(open.size){let u=-1;for(const v of open)if(u<0||cost[v]<cost[u])u=v;open.delete(u);if(u===target)break;const p=ps[u];for(let v=0;v<n;v++){const q=ps[v];if(v===u||q.stage==='gone')continue;const gap=Math.max(0,q.x-(p.x+p.w),p.x-(q.x+q.w)),dy=q.y-p.y,maxGap=dy<-80?170:dy>50?390:320;if(dy<-210||dy>760||gap>maxGap)continue;if(this.map.walls.some(w=>w.y<Math.min(p.y,q.y)-55&&w.y+w.h>Math.max(p.y,q.y)-55&&w.x>p.x+p.w-12&&w.x+w.w<q.x+12))continue;const c=cost[u]+Math.abs(q.x+q.w/2-p.x-p.w/2)*.002+Math.abs(dy)*.003+1+(q.fragile?(1-skill)*8:.0)+(q.motion?2:0);if(c<cost[v]){cost[v]=c;prev[v]=u;open.add(v);}}}if(prev[target]<0)return[];const result=[];for(let v=target;v!==start&&v>=0;v=prev[v]){result.unshift({id:v});if(result.length>n)return[];}return result;}
 snapshot(){return copy({version:70,type:'parkour',mapId:this.mapId,mapData:this.mapSource,options:this.options,rules:this.rules,members:this.members,difficulty:this.difficulty,timeOfDay:this.timeOfDay,ticks:this.ticks,time:this.time,countTicks:this.countTicks,phase:this.phase,deadline:this.deadline,results:this.results,fighters:this.fighters,adminSpeed:this.adminSpeed||1,platformStates:this.map.platforms.map(p=>({stage:p.stage,crumbleAt:p.crumbleAt,goneAt:p.goneAt}))});}
 loadSnapshot(s){if(s?.version!==70||s.type!=='parkour'||!Array.isArray(s.fighters)||s.fighters.length<1||s.fighters.length>8)return false;this.setup(s);for(const k of['ticks','time','countTicks','phase','deadline','results','fighters','adminSpeed'])this[k]=copy(s[k]);s.platformStates?.forEach((p,i)=>Object.assign(this.map.platforms[i]||{},p));this.rules=D.cleanRules(s.rules,true);this.baseRules={...this.rules};this.characters=this.fighters.map(f=>f.kind);this.colors=this.fighters.map(f=>f.color);this.skins=this.fighters.map(f=>f.skin);this.updatePlatforms(this.time,false);this.events=[];return true;}
}
const api={Race,TRACKS,cleanOptions,crossed,segmentProgress,formatTime:ms=>{const n=Math.max(0,Math.floor(ms));return String(Math.floor(n/60000)).padStart(2,'0')+':'+String(Math.floor(n/1000)%60).padStart(2,'0')+'.'+String(n%1000).padStart(3,'0');}};if(typeof module!=='undefined')module.exports=api;root.DuelParkour=api;
})(typeof globalThis!=='undefined'?globalThis:this);
