(function(){
'use strict';
const {clamp,lerp,COLORS,blade,stats}=DuelCore,TAU=Math.PI*2;
class DuelRenderer{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.camera={x:640,y:360,zoom:1};this.previousBlades=[[],[]];this.lastRound=0;this.lastTime=0;this.lighting=new DuelLighting();this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;}
 resize(){const b=this.canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.round(b.width*d),h=Math.round(b.height*d);if(w!==this.canvas.width||h!==this.canvas.height){this.canvas.width=w;this.canvas.height=h;}this.scale=this.raceSplit?h/720:document.documentElement.classList.contains('immersive')?Math.max(w/1280,h/720):Math.min(w/1280,h/720);this.viewWidth=w/this.scale;this.viewHeight=h/this.scale;this.ox=(w-1280*this.scale)/2;this.oy=(h-720*this.scale)/2;this.dpr=d;}
 screenToWorld(x,y){const r=this.canvas.getBoundingClientRect();return{x:((x-r.left)*this.dpr-this.ox)/this.scale/this.camera.zoom+this.camera.x-640/this.camera.zoom,y:((y-r.top)*this.dpr-this.oy)/this.scale/this.camera.zoom+this.camera.y-360/this.camera.zoom};}
 line(a,b,color,width=1){const c=this.ctx;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.strokeStyle=color;c.lineWidth=width;c.stroke();}
 path(pts,fill,stroke,width=1){const c=this.ctx;c.beginPath();pts.forEach((p,i)=>i?c.lineTo(p[0],p[1]):c.moveTo(p[0],p[1]));if(fill){c.closePath();c.fillStyle=fill;c.fill();}if(stroke){c.strokeStyle=stroke;c.lineWidth=width;c.stroke();}}
 ellipse(x,y,rx,ry,color){const c=this.ctx;c.beginPath();c.ellipse(x,y,Math.max(.1,rx),Math.max(.1,ry),0,0,TAU);c.fillStyle=color;c.fill();}
 background(game,t){DuelScenery.draw(this,game,t);}
 platforms(game,t){DuelScenery.platforms(this,game,t);}
 fighter(f,time,w,portrait=false){DuelActors.draw(this,f,time,w,portrait);}
 sword(f,w,t,portrait=false){if(portrait||f.dead)return;const c=this.ctx,shape=DuelCore.slash(f,this.walls||[]),color=f.skin==='yuji'?'#49cbe2':f.ultMode==='edgeStrike'?'#dfb34b':f.state==='ultCharge'?'#e5b870':COLORS[f.color]?.hex||'#80b6ae';
  this.slashTrails??=[[],[]];const trail=this.slashTrails[f.id];while(trail.length&&t-trail[0].time>.10)trail.shift();if(!this.reduced){for(const item of trail){c.globalAlpha=Math.max(0,1-(t-item.time)/.10)*.12;this.path(item.points.map(p=>[p.x,p.y]),null,color,1);}c.globalAlpha=1;}if(shape.points.length&&(!trail.length||t>trail[trail.length-1].time+.014))trail.push({points:shape.points.map(p=>({...p})),time:t});
  if(shape.points.length){const pts=shape.points.map(p=>[p.x,p.y]),s=stats(f),p=shape.progress||0,origin=shape.origin,lowSweep=f.kind==='staff'&&f.ultMode==='sweepStrike',visualReach=s.reach*(lowSweep?1.4:1);
   // The entire solid contour is the damaging polygon; animation lives inside it.
   this.path(pts,color+'85');c.save();c.beginPath();pts.forEach((q,i)=>i?c.lineTo(...q):c.moveTo(...q));c.closePath();c.clip();const g=c.createRadialGradient(origin.x,origin.y,0,origin.x,origin.y,visualReach);g.addColorStop(0,color+'45');g.addColorStop(.48,color+'66');g.addColorStop(.76,'#ffe7b0ad');g.addColorStop(.92,'#fff4d4eb');g.addColorStop(1,'#ffffff');c.fillStyle=g;c.fillRect(origin.x-visualReach-5,origin.y-visualReach-5,visualReach*2+10,visualReach*2+10);
   c.translate(origin.x,origin.y);c.rotate(lowSweep?0:f.attackAim);if(lowSweep){for(let i=0;i<3;i++){const phase=p*TAU+i*TAU/3;c.beginPath();c.ellipse(0,0,visualReach*(.7+i*.1),9,0,phase-1.5,phase);c.strokeStyle=i===2?'#fffbea':'#ffdda3aa';c.lineWidth=i===2?3:1.5;c.stroke();}}else if(['lancer','boxer','duelist'].includes(f.kind)){for(let i=0;i<5;i++){const x=s.minRange+((p*1.7+i*.22)%1)*(s.reach-s.minRange);this.line({x:x-38,y:(i-2)*4},{x:x+25,y:(i-2)*4},i===2?'#ffffff':'#fff4c999',i===2?4:1);}}else{for(let i=0;i<5;i++){c.beginPath();c.arc(0,0,s.minRange+(s.reach-s.minRange)*(i+1)/5,-s.sweep*.6+p*.3,s.sweep*.6+p*.3);c.strokeStyle=i===4?'#ffffff':i%2?'#fff5d4bb':'#f3dfab77';c.lineWidth=i===4?3:1.5;c.stroke();}const angle=-s.sweep*.55+p*s.sweep;c.rotate(angle);this.line({x:s.minRange,y:0},{x:s.reach,y:0},'#ffffff',2);}
   c.restore();this.path(pts,null,'#fff6d6',.8);
  }
  if(f.state==='startup'){const aim=f.attackAim,rad=stats(f).reach,p=clamp(f.stateTime/f.duration,0,1);c.globalAlpha=.25+p*.5;this.line({x:f.x+Math.cos(aim)*30,y:f.y-DuelCore.body(f).center+Math.sin(aim)*30},{x:f.x+Math.cos(aim)*Math.min(rad,53),y:f.y-DuelCore.body(f).center+Math.sin(aim)*Math.min(rad,53)},'#fff2c4',2);c.globalAlpha=1;}
  if(f.state==='parry'){const a=f.guardFacing>0?0:Math.PI,remaining=clamp(1-f.stateTime/f.duration,0,1);c.beginPath();c.arc(f.x,f.y-DuelCore.body(f).center,47,a-Math.PI/2,a+Math.PI/2);c.strokeStyle='#9e895c88';c.lineWidth=3;c.stroke();c.beginPath();c.arc(f.x,f.y-DuelCore.body(f).center,47,a-Math.PI/2,a-Math.PI/2+Math.PI*remaining);c.strokeStyle='#fff0af';c.lineWidth=3;c.stroke();c.font='9px monospace';c.textAlign='center';c.fillStyle=DuelScenery.THEMES[this.lastTheme]?.dark?'#f4e6bc':'#6e5733';const label=f.guardFacing>0?'DIREITA':'ESQUERDA';c.fillText(label+(f.duration>.3?' · '+Math.max(0,f.duration-f.stateTime).toFixed(1).replace('.',',')+' s':''),f.x,f.y-144);}
  if(!f.dead){c.globalAlpha=.65;this.ellipse(f.x+Math.cos(f.aim)*47,f.y-DuelCore.body(f).center+Math.sin(f.aim)*47,1.8,1.8,color);c.globalAlpha=1;}
 }
 render(game,effects,t){this.walls=game.map.walls||[];if(this.lastTheme!==game.mapId){this.lastTheme=game.mapId;if(this.canvas.parentElement){this.canvas.parentElement.dataset.theme=game.mapId;this.canvas.parentElement.classList.toggle('dark-arena',!!DuelScenery.THEMES[game.mapId]?.dark);}}this.resize();const c=this.ctx,dt=clamp(t-this.lastTime,0,.05);this.lastTime=t;if(this.lastRound!==game.round){this.previousBlades=[[],[]];this.actorHistory=[];this.slashTrails=[[],[]];this.lastRound=game.round;}this.effects=effects;const alive=effects.fatal?game.fighters:game.fighters.filter(f=>!f.dead),fs=this.followId!=null?[game.fighters[this.followId]||game.fighters[0]]:(alive.length?alive:game.fighters),minX=Math.min(...fs.map(f=>f.x))-210,maxX=Math.max(...fs.map(f=>f.x))+210,minY=Math.min(...fs.map(f=>f.y))-235,maxY=Math.max(...fs.map(f=>f.y))+95,z=this.followId!=null?.82:clamp(Math.min(this.viewWidth/(maxX-minX),this.viewHeight/(maxY-minY)),.00001,1.12),half=this.viewWidth/2/z,tx=game.map.width<half*2?game.map.width/2:clamp((minX+maxX)/2,half,game.map.width-half),ty=Math.min(game.map.height-(this.viewHeight/2-150)/z,(minY+maxY)/2),smooth=this.snapCamera?1:1-Math.exp(-dt*7);this.camera.zoom=lerp(this.camera.zoom,z,smooth);this.camera.x=lerp(this.camera.x,tx,smooth);this.camera.y=lerp(this.camera.y,ty,smooth);this.snapCamera=false;
  c.setTransform(1,0,0,1,0,0);c.fillStyle=DuelScenery.THEMES[game.mapId]?.dark?'#202d3c':'#d7ceba';c.fillRect(0,0,this.canvas.width,this.canvas.height);c.setTransform(this.scale,0,0,this.scale,this.ox,this.oy);this.background(game,t);this.lighting.backdrop(this,game,t);c.save();c.beginPath();c.rect(0,0,1280,720);c.clip();const shake=this.reduced?0:effects.shake||0;c.translate(640+(Math.random()-.5)*shake,360+(Math.random()-.5)*shake);const kick=effects.fatal&&!this.reduced?1+(effects.fatal.finisher?.075:.045)*Math.sin(Math.min(1,effects.fatal.age/(effects.fatal.finisher?.65:.48))*Math.PI):effects.perfect&&!this.reduced?1+.025*Math.sin(Math.min(1,effects.perfect/.42)*Math.PI):1;c.scale(this.camera.zoom*kick,this.camera.zoom*kick);c.translate(-this.camera.x,-this.camera.y);this.platforms(game,t);this.drawWalls(game);this.lighting.environment(this,game,t);for(const fighter of game.fighters){this.lighting.shadow(this,game,fighter);const age=effects.fatal?.age||0,f=effects.fatal&&fighter.dead?{...fighter,deathTime:age<.085?0:age<.305?(age-.085)*.2:.044+age-.305}:fighter;this.fighter(f,t,blade(f));}if(game.mode!=='parkour'){for(const f of game.fighters)this.sword(f,blade(f),t);this.specials(game,t);}this.lighting.combat(this,game,effects,t);this.fatalFrame(game,effects);if(this.debug)this.hitboxes(game);if(this.adminOverlays)this.inspectAdmin(game);this.wallJumpEffects(effects);for(const p of effects.particles||[]){c.globalAlpha=p.life/p.maxLife;this.line({x:p.x-p.vx*.015,y:p.y-p.vy*.015},p,p.color,p.size);}c.globalAlpha=1;for(const cut of effects.cuts||[]){c.globalAlpha=cut.life/cut.maxLife;this.line({x:cut.x-90,y:cut.y+60},{x:cut.x+90,y:cut.y-60},'#fff5d6',3);}c.globalAlpha=1;c.restore();if(effects.flash){c.fillStyle='#fff2d6';c.globalAlpha=Math.min(.4,effects.flash*2.5);c.fillRect(0,0,1280,720);c.globalAlpha=1;}this.impact(game,effects);}
 fatalFrame(game,effects){const f=effects.fatal;if(!f||f.age>.66)return;const c=this.ctx;c.save();const alpha=Math.max(0,1-f.age/.38);if(f.contours?.length){c.globalAlpha=alpha*.45;this.path(f.contours.map(p=>[p.x,p.y]),'#ffefd0');c.globalAlpha=alpha;this.path(f.contours.map(p=>[p.x,p.y]),null,'#fff7dd',1.4);}const radius=45+Math.min(1,f.age/.15)*55;if(f.age<.22&&f.cause!=='QUEDA'){c.globalAlpha=Math.max(0,1-f.age/.22);const a=(f.angle||0)-.7;this.line({x:f.x-Math.cos(a)*radius,y:f.y-Math.sin(a)*radius},{x:f.x+Math.cos(a)*radius,y:f.y+Math.sin(a)*radius},'#fff9e6',2);this.line({x:f.x-8,y:f.y+12},{x:f.x+8,y:f.y-12},'#fff9e6',1);}
  c.globalAlpha=Math.min(1,(.66-f.age)*5);const x=DuelCore.clamp(f.x,65,game.map.width-65),y=Math.max(50,Math.min(game.map.height-30,f.y-105));c.font='bold 12px monospace';c.textAlign='center';const width=c.measureText(f.cause).width+22;c.fillStyle='#101624d9';c.fillRect(x-width/2,y-13,width,23);c.fillStyle='#f1e4c6';c.fillText(f.cause,x,y+2);c.restore();
 }

 specials(game,t){const c=this.ctx;for(const f of game.fighters){if(f.dead)continue;const b=DuelCore.body(f),x=f.x,y=f.y-b.center,w=blade(f);c.save();
  if(['fenceReady','fenceStrike','sweepReady','sweepStrike'].includes(f.ultMode)){const fencing=f.kind==='duelist',color=fencing?'#d7eeff':'#ffd696';c.globalAlpha=.75;for(const seg of w.segments)this.line(seg.a,seg.b,color,fencing?2:4);if(fencing){const a=f.attackAim||f.aim;for(let i=0;i<3;i++)this.line({x:x-Math.cos(a)*(16+i*12),y:y-Math.sin(a)*(16+i*12)+i*3},{x:x-Math.cos(a)*(35+i*20),y:y-Math.sin(a)*(35+i*20)+i*3},color,1);}else{c.setLineDash([5,7]);c.beginPath();c.ellipse(x,f.y-9,DuelCore.stats(f).reach*1.4,12,0,0,TAU);c.strokeStyle=color;c.lineWidth=1;c.stroke();c.setLineDash([]);}c.globalAlpha=1;}
  if(f.admin?.invincible||f.admin?.fly||f.admin?.bodyScale!==undefined&&f.admin.bodyScale!==1||f.admin?.attackScale!==undefined&&f.admin.attackScale!==1){c.font='8px monospace';c.textAlign='center';c.fillStyle='#ffecb5';c.fillText([f.admin.invincible?'INVENCÍVEL':'',f.admin.fly?'VOO':'',f.admin.bodyScale!==1?'CORPO '+f.admin.bodyScale+'×':'',f.admin.attackScale!==1?'CORTE '+f.admin.attackScale+'×':''].filter(Boolean).join(' · '),x,f.y-b.top-38);if(f.admin.bodyScale!==1){c.globalAlpha=.15;c.lineCap='round';this.line({x,y:f.y-b.top},{x,y:f.y-b.bottom},'#ffdc91',b.radius*2);c.globalAlpha=1;}}
  if(['boxerGuard','boxerRush'].includes(f.ultMode)){const rush=f.ultMode==='boxerRush';c.globalAlpha=.75;this.ellipse(x,f.y-b.top-20,rush?6:4,rush?6:4,rush?'#6cddea':'#ead18b');if(rush){for(let i=0;i<4;i++)this.line({x:x-f.facing*(14+i*5),y:y+i*7-12},{x:x-f.facing*(31+i*8),y:y+i*7-12},f.skin==='yuji'?'#60d9ef':'#eed49b',2);}}
  if(f.ultMode==='shield'){const pulse=.18+Math.sin(t*7)*.035;c.globalAlpha=pulse;c.fillStyle='#f4d884';c.beginPath();c.ellipse(x,y,41,77,0,0,TAU);c.fill();c.globalAlpha=.8;c.strokeStyle='#ffe7a6';c.lineWidth=2;c.stroke();for(let i=0;i<4;i++){const a=t*.7+i*TAU/4;this.ellipse(x+Math.cos(a)*42,y+Math.sin(a)*76,2.3,2.3,'#fff4cd');}}
  if(['edge','edgeStrike','reaperBoost','reaperWeak'].includes(f.ultMode)){const weak=f.ultMode==='reaperWeak',color=weak?'#81909d':'#ffe0a2';c.globalAlpha=weak?.6:.25+Math.sin(t*10)*.06;for(const s of w.segments)this.line(s.a,s.b,color,weak?3:10);c.globalAlpha=1;for(const s of w.segments)this.line(s.a,s.b,color,1.2);}
  if(f.parryLock>0){c.strokeStyle='#ffb2a0';c.lineWidth=1.5;c.beginPath();c.arc(x,f.y-b.top-23,7,0,TAU);c.stroke();this.line({x:x-5,y:f.y-b.top-28},{x:x+5,y:f.y-b.top-18},'#ffb2a0',1.5);}
  if(f.state==='ultWindup'){c.setLineDash([9,7]);c.globalAlpha=.65;this.line({x,y},{x:x+f.ultSide*270,y},'#ffcc79',2);c.setLineDash([]);this.ellipse(x,y,5+f.stateTime*12,5+f.stateTime*12,'#ffe0a2');}
  if(f.state==='ultCharge'){c.globalAlpha=.4;for(let i=0;i<4;i++)this.line({x:x-f.ultSide*(30+i*15),y:y-14+i*9},{x:x-f.ultSide*(155+i*13),y:y-14+i*9},'#fff0bc',2);}
  const p=f.dagger;if(p){if(p.mode!=='lost'){const a=p.mode==='flying'?Math.atan2(p.vy,p.vx):-.6,dx=Math.cos(a),dy=Math.sin(a);this.line({x:p.x-dx*12,y:p.y-dy*12},{x:p.x+dx*17,y:p.y+dy*17},'#fff1c0',4);this.line({x:p.x-dx*19,y:p.y-dy*19},{x:p.x-dx*10,y:p.y-dy*10},COLORS[f.color].hex,5);if(p.mode==='flying'){c.globalAlpha=.5;this.line({x:p.x-dx*28,y:p.y-dy*28},{x:p.x-dx*75,y:p.y-dy*75},'#f6d991',2);}else{c.globalAlpha=.8;this.path([[p.x-5,p.y-22],[p.x,p.y-17],[p.x+5,p.y-22]],null,'#fff0bd',2);}}else{c.globalAlpha=.45;this.ellipse(p.safe.x,p.safe.y,9,3,'#ffe6a0');}}
  c.restore();}}
 impact(game,effects){if(!effects.impact)return;const c=this.ctx,p=effects.impactPoint||{x:640,y:360};c.save();const perfect=effects.perfect>0;c.globalAlpha=this.reduced?.08:perfect?.98:.62;c.fillStyle=perfect?'#081b30':'#f4efd9';c.fillRect(0,0,1280,720);c.globalAlpha=1;c.translate(640,360);c.scale(this.camera.zoom,this.camera.zoom);c.translate(-this.camera.x,-this.camera.y);for(const f of game.fighters){c.save();c.filter=perfect?'brightness(0) invert(1)':'brightness(0)';this.fighter(f,this.lastTime,blade(f));c.restore();}const rays=this.reduced?3:perfect?16:8;for(let i=0;i<rays;i++){const a=i*TAU/rays+.15,length=i%3===0?105:60;this.line({x:p.x+Math.cos(a)*12,y:p.y+Math.sin(a)*12},{x:p.x+Math.cos(a)*length,y:p.y+Math.sin(a)*length},perfect?(i%2?'#efffff':'#72d7ff'):(i%2?'#263640':'#b99249'),i%3===0?3:1.5);}this.ellipse(p.x,p.y,6,6,'#ffffff');c.restore();}

 drawWalls(game){const c=this.ctx,theme=DuelScenery.THEMES[game.mapId]||DuelScenery.THEMES.dojo;for(const w of game.map.walls||[]){c.fillStyle=theme.edge;c.fillRect(w.x,w.y,w.w,w.h);c.fillStyle=theme.surface;c.fillRect(w.x+4,w.y+4,w.w-8,w.h-4);this.line({x:w.x+3,y:w.y},{x:w.x+3,y:w.y+w.h},theme.top,3);for(let y=w.y+22;y<w.y+w.h;y+=Math.max(30,w.h/160)){this.line({x:w.x+5,y},{x:w.x+w.w-5,y},theme.detail,2);}c.fillStyle=theme.top;c.fillRect(w.x-3,w.y-3,w.w+6,5);}}

 inspectAdmin(g){const c=this.ctx,o=this.adminOverlays;if(!o)return;c.save();c.lineCap='round';
 if(o.geometry){for(const w of g.map.walls){c.strokeStyle='#f8b47c';c.lineWidth=1;c.strokeRect(w.x,w.y,w.w,w.h);}for(const p of g.map.platforms){c.setLineDash(p.stage==='gone'?[3,4]:[]);this.line({x:p.x,y:p.y},{x:p.x+p.w,y:p.y},'#5ce8ac',2);}c.setLineDash([]);}
 if(o.spawns)g.map.spawns.forEach((p,i)=>{this.line({x:p.x-10,y:p.y-8},{x:p.x+10,y:p.y-8},'#ffe984',2);this.line({x:p.x,y:p.y-18},{x:p.x,y:p.y+2},'#ffe984',2);c.fillStyle='#ffe984';c.font='10px monospace';c.fillText('INÍCIO J'+(i+1),p.x+13,p.y-10);});
 for(const f of g.fighters){const b=DuelCore.body(f),y=f.y-b.center;if(o.body){c.globalAlpha=.17;this.line({x:f.x,y:f.y-b.top},{x:f.x,y:f.y-b.bottom},'#52eeff',b.radius*2);c.globalAlpha=1;for(const yy of[f.y-b.top,f.y-b.bottom]){c.beginPath();c.arc(f.x,yy,b.radius,0,TAU);c.strokeStyle='#52eeff';c.lineWidth=1;c.stroke();}}
 if(o.slash){const poly=DuelCore.slash(f,g.map.walls).points;if(poly.length)this.path(poly.map(p=>[p.x,p.y]),'#ff72662a','#ff8266',1.5);}
 if(o.parry){const side=f.state==='parry'?f.guardFacing:DuelCore.aimSide(f.aim,f.facing),angle=side>0?0:Math.PI;c.beginPath();c.moveTo(f.x,y);c.arc(f.x,y,70,angle-Math.PI/2,angle+Math.PI/2);c.closePath();c.fillStyle='#a1f78c22';c.fill();c.strokeStyle='#a1f78c';c.lineWidth=1;c.stroke();if(f.state==='parry')this.line(blade(f).guard.a,blade(f).guard.b,'#daffc7',3);}
 if(o.vectors){this.line({x:f.x,y},{x:f.x+Math.cos(f.aim)*100,y:y+Math.sin(f.aim)*100},'#fff2b5',1);this.line({x:f.x,y},{x:f.x+f.vx*.15,y:y+f.vy*.15},'#67cef8',2);if(f.dashRemaining>0)this.line({x:f.x,y},{x:f.x+f.dashX*130,y:y+f.dashY*130},'#ff9bed',2);}
 if(o.projectiles&&f.dagger&&f.dagger.mode!=='lost'){const p=f.dagger;this.ellipse(p.x,p.y,5,5,'#ffdb89');this.line(p,{x:p.x+p.vx*.15,y:p.y+p.vy*.15},'#ffdb89',1);}
 if(o.timers){c.font='10px monospace';c.textAlign='center';const label=f.state+' · '+Math.max(0,(f.duration-f.stateTime)*1000).toFixed(0)+' ms',width=c.measureText(label).width+8;c.fillStyle='#0c1a2be8';c.fillRect(f.x-width/2,f.y-b.top-30,width,17);c.fillStyle='#edf6ee';c.fillText(label,f.x,f.y-b.top-18);}
 }if(o.ai&&g.aiEnabled){c.font='11px monospace';c.textAlign='left';c.fillStyle='#ffe6af';const f=g.fighters[1];c.fillText('IA · '+(g.ai.decision||(g.ai.intent?'posicionar':'observar')),f.x-80,f.y-DuelCore.body(f).top-52);}c.restore();}
 wallJumpEffects(e){const c=this.ctx;for(const hit of e.wallJumps||[]){const u=hit.age/.36;if(u>=1)continue;c.save();c.translate(hit.x,hit.y);c.scale(-(hit.side||1),1);c.globalAlpha=(1-u)*.75;if(!this.reduced){c.strokeStyle='#e9e2c2';c.lineWidth=1.5;c.beginPath();c.ellipse(0,0,4+u*32,9+u*26,0,-Math.PI/2,Math.PI/2);c.stroke();for(let i=0;i<5;i++){const angle=-1+i*.5,x=Math.cos(angle)*(9+u*42),y=Math.sin(angle)*(9+u*37);this.line({x,y},{x:x+6*(1-u),y:y+Math.sin(angle)*4},'#ffe9c3',1.5);}}this.line({x:0,y:-13*(1-u)},{x:0,y:13*(1-u)},'#fff0cc',3*(1-u));c.restore();}}

 hitboxes(game){const c=this.ctx;c.save();for(const f of game.fighters){if(f.dead)continue;const b=DuelCore.body(f);c.globalAlpha=.19;this.line({x:f.x,y:f.y-b.top},{x:f.x,y:f.y-b.bottom},'#55ddff',b.radius*2);c.globalAlpha=1;c.setLineDash([3,3]);this.line({x:f.x,y:f.y-b.top},{x:f.x,y:f.y-b.bottom},'#7af4ff',1);c.setLineDash([]);const shape=DuelCore.slash(f,game.map.walls);if(shape.points.length)this.path(shape.points.map(p=>[p.x,p.y]),null,'#ff654c',2);if(f.state==='parry'){const g=blade(f).guard;this.line(g.a,g.b,'#a6ff7b',4);}if(f.state==='kickActive')this.line({x:f.x+f.kickSide*18,y:f.y-b.center+12},{x:f.x+f.kickSide*56,y:f.y-b.center+12},'#ffaa55',18);c.font='10px monospace';c.fillStyle=DuelScenery.THEMES[game.mapId]?.dark?'#ecf4df':'#183e49';c.textAlign='center';c.fillText(f.state+' · '+Math.max(0,(f.duration-f.stateTime)*1000).toFixed(0)+' ms',f.x,f.y-b.top-27);}c.restore();}
 drawPortrait(canvas,kind,side=0,color,time=0,skin='default',pose='idle'){if(kind==='random'){const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);c.fillStyle=COLORS[color]?.hex||'#426b64';c.textAlign='center';c.font='70px Georgia';c.fillText('?',canvas.width/2,canvas.height*.66);return;}const old=this.ctx;this.ctx=canvas.getContext('2d');const c=this.ctx;c.clearRect(0,0,canvas.width,canvas.height);c.save();c.imageSmoothingEnabled=false;const f={id:side,kind,skin,color:color||'jade',x:0,y:0,vx:pose==='run'?250:0,vy:0,aim:-.15,facing:1,attackAim:0,state:pose==='attack'?'active':pose==='parry'?'parry':'idle',guard:'normal',guardFacing:1,stateTime:pose==='attack'?.04:0,duration:pose==='attack'?.08:.4,grounded:true,anim:pose==='run'?time*8:0,landing:0,dead:false,dashX:0,dashY:0,move:0};if(pose==='attack'){const cycle=time%.65;f.state=cycle<.15?'startup':cycle<.28?'active':'recovery';f.duration=f.state==='startup'?.15:f.state==='active'?.13:.37;f.stateTime=cycle-(f.state==='startup'?0:f.state==='active'?.15:.28);f.punch=Math.floor(time/.65)%2;}if(pose==='special'){f.ultMode={knight:'shield',lancer:'charge',assassin:'unarmed',swordsman:'edge',reaper:'reaperBoost',boxer:'boxerRush',duelist:'fenceReady',staff:'sweepReady'}[kind];f.ultTime=7;}if(pose==='victory'){const gesture=Math.sin(time*2.1)*.08;f.aim={knight:-1.1,lancer:-1.15,assassin:-.4,swordsman:-1.25,reaper:-.8,boxer:-1.15,duelist:-1.3,staff:-.5}[kind]+gesture;f.visualLean=Math.sin(time*2)*2;f.visualCrouch=2+Math.sin(time*3);f.state='idle';}const w=blade(f),pts=[{x:-65,y:-152},{x:35,y:7},...w.segments.flatMap(s=>[s.a,s.b]),...(w.shaft?[w.shaft.a,w.shaft.b]:[])],minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxY=Math.max(...pts.map(p=>p.y)),scale=Math.min((canvas.width-34)/(maxX-minX),(canvas.height-34)/(maxY-minY));c.translate(canvas.width/2-(minX+maxX)/2*scale,canvas.height-17-maxY*scale);c.scale(scale,scale);this.fighter(f,time,w,true);if(pose==='special')this.specials({fighters:[f]},time);c.restore();this.ctx=old;}
}
window.DuelRenderer=DuelRenderer;
})();
