(function(root){
'use strict';
const D=root.DuelCore,VERSION=70,PREFIX='umcorte-v7-',ALPHABET='23456789ABCDEFGHJKLMNPQRSTUVWXYZ',DELAY=8,clone=o=>JSON.parse(JSON.stringify(o)),clock=()=>performance.now();
function cleanInput(c){if(!c||typeof c!=='object'||!Number.isFinite(c.move)||!Number.isFinite(c.aim))return null;const o={...D.neutral(),move:D.clamp(c.move,-1,1),aim:Math.atan2(Math.sin(c.aim),Math.cos(c.aim))};for(const k of Object.keys(o))if(typeof o[k]==='boolean')o[k]=c[k]===true;return o;}
function validData(v){let n=0;function scan(x,d){if(++n>40000||d>16)return false;if(x===null||typeof x==='boolean')return true;if(typeof x==='number')return Number.isFinite(x);if(typeof x==='string')return x.length<1900000;if(Array.isArray(x))return x.length<=800&&x.every(v=>scan(v,d+1));if(typeof x!=='object')return false;return Object.entries(x).every(([k,v])=>!['__proto__','constructor','prototype'].includes(k)&&scan(v,d+1));}try{return scan(v,0)&&JSON.stringify(v).length<2300000;}catch{return false;}}
class DuelRoom{
 constructor(hooks){this.h=hooks;this.links=new Map();this.members=[];this.id='';this.code='';this.host=false;this.closed=false;this.playing=false;this.config=null;this.s=null;this.lastSnapshot=null;this.readyFor=new Set();this.ops=[];this.paused=false;}
 status(text){this.h.status?.(text);}
 async open(create,code,profile){this.host=create;this.profile=this.cleanProfile(profile);this.code=create?Array.from(crypto.getRandomValues(new Uint8Array(6)),b=>ALPHABET[b%ALPHABET.length]).join(''):String(code).trim().toUpperCase();if(!/^[23456789ABCDEFGHJKLMNPQRSTUVWXYZ]{6}$/.test(this.code))throw Error('Digite os 6 caracteres da sala V7.');this.status(create?'Criando sala…':'Entrando na sala V7…');
  await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('A conexão demorou demais. Confira a rede e tente novamente.')),15000);this.peer=new Peer(create?PREFIX+this.code:undefined,{debug:0});this.peer.on('open',id=>{clearTimeout(timeout);this.id=id;if(create){this.members=[{id,...this.profile,seat:0,ready:false}];this.publish();resolve();}else{const c=this.peer.connect(PREFIX+this.code,{reliable:true,serialization:'json',metadata:{version:VERSION}});this.attach(c,false);this.joinResolve=resolve;this.joinReject=reject;this.joinTimer=setTimeout(()=>reject(Error('Sala V7 não encontrada ou conexão bloqueada.')),15000);}});this.peer.on('connection',c=>{if(!this.host){c.close();return;}this.attach(c,true);});this.peer.on('error',e=>{clearTimeout(timeout);const msg=e.type==='peer-unavailable'?'Sala V7 não encontrada. Confira o código e a versão.':'Falha na conexão: '+(e.type||'rede');if(!this.id||!create&&!this.members.length)reject(Error(msg));else this.status(msg);});this.peer.on('disconnected',()=>{if(!this.closed)this.status('Sinalização desconectada; a conexão direta continua ativa.');});});
  this.pulse=setInterval(()=>{if(this.closed)return;for(const [id,c]of this.links){if(c.open)this.sendTo(id,{t:'ping',stamp:clock()});}if(this.host&&this.introDeadline&&clock()>=this.introDeadline)this.go();},300);this.status('Sala '+this.code+' · até 8 pessoas.');
 }
 cleanProfile(p={}){return{name:String(p.name||'Jogador').slice(0,24),kind:D.CLASSES[p.kind]||p.kind==='runner'||p.kind==='random'?p.kind:'knight',skin:D.cleanSkin(p.kind,p.skin),color:D.COLORS[p.color]?p.color:'jade',admin:!!p.admin};}
 attach(c,incoming){const id=c.peer;if(this.links.has(id)){c.close();return;}this.links.set(id,c);const timeout=setTimeout(()=>{if(!this.members.some(p=>p.id===id)&&incoming)c.close();},12000);c.on('open',()=>{if(!incoming)this.sendTo(id,{t:'join',v:VERSION,profile:this.profile});});c.on('data',data=>{if(!validData(data))return;try{this.receive(id,data);}catch(e){this.status('Mensagem recusada: '+e.message);}});c.on('close',()=>{clearTimeout(timeout);this.links.delete(id);if(this.closed)return;if(this.host)this.leaveMember(id);else this.close('O anfitrião saiu. A sala foi encerrada.');});c.on('error',()=>{if(!this.closed)this.status('Conexão instável com um participante.');});}
 sendTo(id,m){const c=this.links.get(id);if(c?.open){try{c.send(m);return true;}catch{}}return false;}
 broadcast(m){for(const id of this.links.keys())this.sendTo(id,m);}
 send(m){if(this.host)this.receive(this.id,m);else this.sendTo(PREFIX+this.code,m);}
 canManage(id=this.id){return id===PREFIX+this.code||!!this.members.find(p=>p.id===id)?.admin;}
 publish(){const state={t:'state',v:VERSION,members:this.members,config:this.config,playing:this.playing};this.broadcast(state);this.h.state?.(clone(state));}
 receive(id,m){if(m.t==='ping'){this.sendTo(id,{t:'pong',stamp:m.stamp});return;}if(m.t==='pong'){this.latency=Math.round(clock()-m.stamp);return;}
  if(this.host){const actor=this.members.find(p=>p.id===id);if(m.t==='join'){if(m.v!==VERSION||this.members.length>=8||actor){this.sendTo(id,{t:'reject',reason:m.v!==VERSION?'Versões incompatíveis. Todos precisam usar V7.':'A sala está cheia (8/8).'});setTimeout(()=>this.links.get(id)?.close(),250);return;}const p=this.cleanProfile(m.profile),seat=!this.playing?[0,1].find(n=>!this.members.some(p=>p.seat===n)):-1;this.members.push({id,...p,seat:seat??-1,ready:false});this.publish();if(this.s&&this.playing){this.sendTo(id,{t:'watch',session:this.s.init,snapshot:this.lastSnapshot,frame:this.s.frame,paused:this.paused});}return;}if(!actor)return;
   if(m.t==='profile'&&!this.playing){Object.assign(actor,this.cleanProfile({...m.profile,admin:actor.admin}));actor.ready=false;this.publish();}
   else if(m.t==='configure'&&this.canManage(id)&&!this.playing){const next=this.h.validateConfig(m.config);if(!next)return;this.config=next;for(const p of this.members)p.ready=false;this.publish();}
   else if(m.t==='seat'&&this.canManage(id)&&!this.playing&&[-1,0,1].includes(m.seat)){const p=this.members.find(p=>p.id===m.id);if(!p)return;for(const q of this.members)if(q.seat===m.seat&&m.seat>=0)q.seat=-1;p.seat=m.seat;for(const p of this.members)p.ready=false;this.publish();}
   else if(m.t==='ready'&&!this.playing){actor.ready=!!m.value;this.publish();}
   else if(m.t==='launch'&&this.canManage(id)&&!this.playing)this.launch();
   else if(m.t==='confirmed'&&this.s&&m.sid===this.s.id){this.readyFor.add(id);if(this.s.ids.every(id=>this.readyFor.has(id)))this.go();}
   else if(m.t==='input'&&this.s&&m.sid===this.s.id&&this.s.ids.includes(id)&&Number.isSafeInteger(m.frame)&&m.frame>=this.s.frame&&m.frame<this.s.frame+120){const c=cleanInput(m.input);if(c){const buf=this.s.inputs.get(id);if(!buf.has(m.frame))buf.set(m.frame,c);}}
   else if(m.t==='admin'&&actor.admin&&this.s&&m.sid===this.s.id){if(this.h.validateAdmin(m.change))this.ops.push(clone(m.change));}
   else if(m.t==='lobby'&&!this.playing){this.sendTo(id,{t:'lobby'});if(id===this.id)this.h.lobby?.();}
   return;
  }
  if(id!==PREFIX+this.code)return;
  if(m.t==='reject'){this.joinReject?.(Error(m.reason));this.close(m.reason);}
  else if(m.t==='state'&&m.v===VERSION){this.members=m.members;this.config=m.config;this.playing=m.playing;clearTimeout(this.joinTimer);this.joinResolve?.();this.joinResolve=null;this.h.state?.(clone(m));}
  else if(m.t==='begin'){this.acceptSession(m.session);}
  else if(m.t==='watch'){this.acceptSession(m.session,true,m.snapshot);this.s.frame=m.frame;this.paused=m.paused;this.s.running=true;}
  else if(m.t==='go'&&this.s?.id===m.sid){this.s.running=true;this.h.go?.();}
  else if(m.t==='tick'&&this.s?.id===m.sid&&this.s.ids.includes(this.id)){if(m.frame!==this.s.frame){this.status('Sincronizando sequência da partida…');return;}this.applyTick(m);this.queueLocal(m.frame+DELAY);}
  else if(m.t==='snapshot'&&this.s?.id===m.sid){if(!this.s.ids.includes(this.id)){this.h.snapshot?.(m.snapshot,m.events);this.s.frame=m.frame;this.paused=m.paused;}else if(m.frame===this.s.frame&&m.check&&this.h.digest?.()!==m.check){this.h.snapshot?.(m.snapshot,[]);this.status('Estado da partida ressincronizado.');}}
  else if(m.t==='abort'){this.s=null;this.playing=false;this.h.abort?.(m.reason);}
  else if(m.t==='lobby')this.h.lobby?.();
 }
 launch(){if(!this.config)return;const race=this.config.mode==='parkour',players=race?this.members:[0,1].map(n=>this.members.find(p=>p.seat===n));if(players.some(p=>!p)||!race&&players.length!==2){this.status('Escolha os dois lutadores antes de começar.');return;}if(players.some(p=>!p.ready)){this.status('Os participantes precisam confirmar antes de começar.');return;}if(new Set(players.map(p=>p.color)).size!==players.length){this.status('Escolham cores diferentes antes de começar.');return;}
  const session={id:crypto.randomUUID(),seed:crypto.getRandomValues(new Uint32Array(1))[0],players:clone(players),config:clone(this.config)};this.playing=true;this.readyFor.clear();this.acceptSession(session);this.broadcast({t:'begin',session});this.introDeadline=clock()+(race||!this.config.rules.specials?700:10000);this.publish();}
 acceptSession(init,watch=false,snapshot=null){this.paused=false;this.s={id:init.id,init,ids:init.players.map(p=>p.id),frame:0,running:false,accum:0,inputs:new Map(init.players.map(p=>[p.id,new Map()])),stall:0};for(const buf of this.s.inputs.values())for(let i=0;i<DELAY;i++)buf.set(i,D.neutral());this.h.begin?.(init,watch,snapshot);}
 confirm(){if(this.s)this.send({t:'confirmed',sid:this.s.id});}
 go(){if(!this.s||this.s.running)return;this.introDeadline=0;this.s.running=true;this.broadcast({t:'go',sid:this.s.id});this.h.go?.();}
 queueLocal(frame){if(!this.s?.ids.includes(this.id))return;this.send({t:'input',sid:this.s.id,frame,input:this.h.input(this.s.ids.indexOf(this.id))});}
 applyTick(m){for(const op of m.ops||[]){if(op.action==='pause')this.paused=!!op.paused;this.h.admin?.(op);}if(!this.paused)this.h.step(m.inputs);this.s.frame++;}
 tick(dt){const s=this.s;if(!this.host||!s?.running||!this.playing)return;s.accum=Math.min(.15,s.accum+dt);let n=0;while(s.accum>=1/60&&n++<6){const inputs=s.ids.map(id=>s.inputs.get(id)?.get(s.frame));if(inputs.some(c=>!c)){s.stall||=clock();if(clock()-s.stall>8000){this.abort('Um lutador parou de responder. A sala permanece aberta.');}else if(clock()-s.stall>250)this.status('Aguardando conexão de um participante…');return;}s.stall=0;const packet={t:'tick',sid:s.id,frame:s.frame,inputs,ops:this.ops.splice(0)};this.applyTick(packet);this.broadcast(packet);for(const id of s.ids)s.inputs.get(id).delete(packet.frame);this.queueLocal(packet.frame+DELAY);s.accum-=1/60;if(s.frame%3===0||this.h.ended()){this.lastSnapshot=this.h.snapshotGet();this.broadcast({t:'snapshot',sid:s.id,frame:s.frame,snapshot:this.lastSnapshot,events:this.h.drainEvents?.()||[],paused:this.paused,check:this.h.digest?.()});}if(this.h.ended()){this.playing=false;s.running=false;for(const p of this.members)p.ready=false;this.publish();break;}}}
 leaveMember(id){const active=this.playing&&this.s?.ids.includes(id);this.members=this.members.filter(p=>p.id!==id);if(active){if(this.config?.mode==='parkour'){this.ops.push({action:'raceDisconnect',id:this.s.ids.indexOf(id)});this.s.inputs.set(id,new Map());for(let f=this.s.frame;f<this.s.frame+120;f++)this.s.inputs.get(id).set(f,D.neutral());this.s.disconnected??=new Set();this.s.disconnected.add(id);}else this.abort('Um lutador saiu. Escolha um substituto para continuar.');}this.publish();}
 abort(reason){this.playing=false;this.s=null;this.introDeadline=0;this.broadcast({t:'abort',reason});this.h.abort?.(reason);for(const p of this.members)p.ready=false;this.publish();}
 updateProfile(profile){this.send({t:'profile',profile});}configure(config){this.send({t:'configure',config});}assign(id,seat){this.send({t:'seat',id,seat});}ready(value){this.send({t:'ready',value});}start(){this.send({t:'launch'});}admin(change){if(!this.s)return false;this.send({t:'admin',sid:this.s.id,change});return true;}
 close(reason){if(this.closed)return;this.closed=true;clearInterval(this.pulse);clearTimeout(this.joinTimer);for(const c of this.links.values())c.close();this.links.clear();this.peer?.destroy();if(reason)this.h.closed?.(reason);}
}
const originalTick=DuelRoom.prototype.tick;DuelRoom.prototype.tick=function(dt){if(this.host&&this.s?.disconnected)for(const id of this.s.disconnected){const buf=this.s.inputs.get(id);for(let f=this.s.frame;f<this.s.frame+DELAY+2;f++)buf.set(f,D.neutral());}return originalTick.call(this,dt);};
DuelRoom.VERSION=VERSION;DuelRoom.cleanInput=cleanInput;root.DuelRoom=DuelRoom;
})(typeof globalThis!=='undefined'?globalThis:this);
