const A=require('node:assert/strict'),D=require('./engine.js');let count=0;
function test(n,fn){try{fn();count++;console.log('PASS',n)}catch(e){console.error('FAIL',n,e.stack);process.exitCode=1}}
const make=o=>{const g=new D.Game({mode:'local',ai:false,...o});g.start();return g};
function parryCase(time,ground=true,dir=0,window=400){const g=make({rules:{parryWindow:window}}),[a,b]=g.fighters;a.x=600;a.y=450;b.x=600+Math.cos(dir)*110;b.y=450+Math.sin(dir)*110;b.grounded=ground;b.aim=dir+Math.PI;b.facing=Math.cos(b.aim)>0?1:-1;g.parry(1);b.stateTime=time;a.attackId=++g.attackCounter;a.attackAim=dir;g.setState(a,'active',D.stats(a).active);a.stateTime=a.duration/2;g.resolveCombat();return g;}
test('Perfect uses the first 80 ms and preserves regular stun, cooldown and hitstop',()=>{for(const time of[0,.04,.08,.081,.2,.399]){const g=parryCase(time),e=g.events.find(e=>e.type==='parry');A(e);A.equal(e.perfect,time<=.08);A.equal(g.fighters[0].state,'stunned');A.equal(g.fighters[0].duration,g.rules.stun/1000);A.equal(g.hitstop,.07);A.equal(g.fighters[1].parryCooldown,.22);A.deepEqual(g.score,[0,0]);}});
test('Perfect works in high, low airborne and normal guard, including a shorter custom window',()=>{for(const dir of[0,Math.PI,Math.PI/2,-Math.PI/2]){const g=parryCase(.025,false,dir);A(g.events.find(e=>e.type==='parry')?.perfect);}const g=parryCase(.02,true,0,40);A(g.events.find(e=>e.type==='parry')?.perfect);});
test('Decoration reacts once per attack and never consumes the lethal slash',()=>{for(const type of Object.keys(D.DECOR)){const g=make(),[a,b]=g.fighters;a.x=500;b.x=610;g.map.decor=[{type,x:565,y:500}];g.propStates=[{hitAt:-100,broken:false,side:1,attacks:[-1,-1]}];a.attackId=++g.attackCounter;a.attackAim=0;g.setState(a,'active',D.stats(a).active);a.stateTime=a.duration/2;g.resolveCombat();A.equal(g.events.filter(e=>e.type==='propHit').length,1);A(b.dead);A.equal(g.score[0],1);g.touchProps();A.equal(g.events.filter(e=>e.type==='propHit').length,1);}});
test('New arenas and prop state replay identically, reset each round and after ADMIN map edits',()=>{for(const mapId of['bells','rooftops']){const a=make({mapId}),b=make();a.propStates[0].hitAt=.5;a.propStates[0].broken=true;A(b.loadSnapshot(a.snapshot()));for(let n=0;n<300;n++){const input=[D.neutral(),D.neutral()];a.step(1/600,input);b.step(1/600,input);}A.deepEqual(a.snapshot(),b.snapshot());a.resetFighters();A(a.propStates.every(p=>!p.broken&&p.hitAt===-100));a.adminApply({action:'apply',mapId:'tower'});A.equal(a.propStates.length,1);}});
test('Only the winning point adds the 650 ms signature; no bonus in training or ties',()=>{for(const [mode,score,winner,expected]of[['local',0,0,false],['local',4,0,true],['local',4,-1,false],['training',4,0,false]]){const g=make({mode});g.score[0]=score;g.finish(winner,'test');A.equal(g.events.find(e=>e.type==='kill').finisher,expected);A.equal(g.roundTimer,(mode==='training'?.6:D.C.roundPause)+(expected?.65:0));const timer=g.roundTimer;g.finish(winner,'again');A.equal(g.roundTimer,timer);}});
test('ADMIN presentation requests do not alter physics, stats, score or clocks',()=>{const g=make({mapId:'bells'});for(const animation of['idle','tense','guard','perfect','finisher','stop']){const before=g.snapshot();g.adminApply({action:'preview',animation,id:1});A.deepEqual(g.snapshot(),before);A.equal(g.events.at(-1).type,'preview');}});
const old={format:'um-corte-map',version:1,id:'custom_v6',name:'Meu mapa',width:1280,height:720,theme:'bamboo',platforms:[{x:40,y:610,w:1200,solid:true}],walls:[],spawns:[{x:350,y:610},{x:920,y:610}]};
test('Editor format keeps old maps and roundtrips new props/weather without executable content',()=>{const basic=D.cleanMap(old);A.deepEqual(basic.decor,[]);A.equal(basic.weather,'none');for(const weather of D.WEATHER){const raw={...old,weather,decor:[{type:'bell',x:600,y:400}]},m=D.cleanMap(raw);A.equal(m.weather,weather);A.deepEqual(D.cleanMap(JSON.parse(JSON.stringify(m))),m);}for(const decor of[[{type:'script',x:20,y:20}],[{type:'bell',x:NaN,y:20}],Array(41).fill({type:'bell',x:20,y:20})])A.throws(()=>D.cleanMap({...old,decor}));});
test('Named presets preserve every rule and reject unsupported values on import',()=>{const rules=D.cleanRules({speed:1.6,chaos:'ultra',winningScore:7,specialCooldown:9,persistSpecial:true}),p={format:'um-corte-preset',version:1,name:'TURBO DO LUIZ',rules};A.deepEqual(D.cleanPreset(JSON.parse(JSON.stringify(p))),p);for(const overrides of[{speed:100},{dashCount:1.3},{chaos:'bad'},{gravity:null},{specials:'yes'}])A.throws(()=>D.cleanPreset({...p,rules:{...rules,...overrides}}));A.throws(()=>D.cleanPreset({...p,name:' '}));});
console.log(count+' V6 groups passed');
