const A=require('node:assert/strict'),D=require('./engine.js'),P=require('./parkour.js');let count=0;const test=(s,f)=>{f();console.log('PASS '+s);count++;};
const game=()=>{const g=new D.Game({mode:'local',ai:false});g.start();g.fighters[1].x=1150;return g;},advance=(g,t,inputs=[])=>{for(let i=0;i<Math.round(t*600);i++)g.step(1/600,inputs);};
test('eight airborne directions ignore aim, diagonals have equal length',()=>{for(const x of[-1,0,1])for(const y of[-1,0,1]){if(!x&&!y)continue;for(const aim of[-2.2,.4,1.57]){const g=game(),f=g.fighters[0];f.grounded=false;f.y=250;f.aim=aim;A(g.dash(0,x,y>0,y<0));A(Math.abs(f.dashX-x/Math.hypot(x,y))<1e-8);A(Math.abs(f.dashY-y/Math.hypot(x,y))<1e-8);}}for(const facing of[-1,1]){const g=game(),f=g.fighters[0];f.grounded=false;f.facing=facing;f.aim=1.1;g.dash(0);A.equal(f.dashX,facing);A.equal(f.dashY,0);}});
test('ground dash trajectory and distance equal V6.3',()=>{const O=require('../v63/engine.js');for(const aim of[-.4,0,.5,Math.PI]){const a=game(),b=new O.Game({mode:'local',ai:false});b.start();b.fighters[1].x=1150;for(const g of[a,b]){g.fighters[0].aim=aim;g.dash(0,1);}for(let i=0;i<90;i++)for(const g of[a,b])g.step(1/600,[{...D.neutral(),aim},D.neutral()]);A(Math.abs(a.fighters[0].x-b.fighters[0].x)<.01);A(Math.abs(a.fighters[0].y-b.fighters[0].y)<.01);}});
test('wall slide releases and wall jump does not recharge air dash',()=>{const g=game(),f=g.fighters[0];g.map.walls=[{x:600,y:0,w:30,h:600}];f.x=600-D.body(f).radius;f.y=350;f.grounded=false;f.vy=600;f.wallSide=1;f.wallId=0;f.airDashes=1;f.dashCharges=0;f.dashCooldown=2;advance(g,.05,[{...D.neutral(),move:1},D.neutral()]);A(f.wallSliding);A(f.vy<160);g.step(1/600,[D.neutral(),D.neutral()]);A(!f.wallSliding);A(f.vy>155);g.step(1/600,[{...D.neutral(),move:1,up:true,jump:true,jumpHeld:true},D.neutral()]);A(f.vy<-900);A(f.vx<0);A.equal(f.dashCharges,0);A.equal(f.airDashes,1);});
test('lateral guard blocks high, middle, low and loses a cross-up',()=>{for(const side of[-1,1])for(const dy of[-70,0,70]){const g=game(),[a,d]=g.fighters;a.x=600+side*70;a.y=500+dy;d.x=600;d.y=500;d.grounded=false;d.aim=side<0?Math.PI:0;d.facing=side;g.parry(1);a.attackAim=Math.atan2(-dy,-side*70);a.state='active';a.duration=.1;a.stateTime=.05;g.resolveCombat();A.equal(a.state,'stunned');A(!d.dead);A.equal(d.guardFacing,side);}const g=game(),[a,d]=g.fighters;d.x=600;d.y=500;d.aim=0;g.parry(1);a.x=540;a.y=500;a.attackAim=0;a.state='active';a.duration=.1;a.stateTime=.05;g.resolveCombat();A(d.dead);A.equal(g.score[0],1);A.equal(D.aimSide(Math.PI/2,-1),-1);});
test('taunt is cosmetic and immediate movement cancels it',()=>{const g=game(),f=g.fighters[0],shape=D.body(f);g.step(1/600,[{...D.neutral(),taunt:true},D.neutral()]);A(f.tauntTime>0);A.deepEqual(D.body(f),shape);g.step(1/600,[{...D.neutral(),move:1},D.neutral()]);A.equal(f.tauntTime,0);A(f.vx>0);});
test('race clocks/countdown, no combat, checkpoint order, respawn and protection',()=>{const g=new P.Race({members:[{name:'A'},{name:'B'}]}),f=g.fighters[0],x=f.x;advance(g,2,[{...D.neutral(),move:1,attack:true}]);A.equal(f.x,x);A.equal(g.ticks,0);advance(g,1);A.equal(g.phase,'playing');A(!g.attack(0));A(!g.parry(0));A(!g.special(0));A(!g.kick(0));const second=g.mapSource.race.checkpoints[1];f.x=second.x;f.y=second.y;g.step(1/600);A.equal(f.checkpoint,0);f.y=g.map.deathY+10;g.step(1/600);A(f.dead);advance(g,.51);A(!f.dead);A(f.protection>.95);A.equal(f.x,g.mapSource.race.start.x);});
test('ordered checkpoints, DNF, individual finish and stable results',()=>{const g=new P.Race({members:[{},{}],options:{afterFirst:5}});advance(g,3);const f=g.fighters[0];for(const cp of [...g.mapSource.race.checkpoints,g.mapSource.race.finish]){f.x=cp.x;f.y=cp.y;g.step(1/600);}A(f.finished);const ms=f.finishMs;advance(g,5.1);A.equal(g.phase,'raceEnd');A.equal(f.finishMs,ms);A(g.fighters[1].dnf);A.equal(g.ranking()[0].id,0);A.equal(P.formatTime(84583),'01:24.583');});
test('race snapshot replays deterministically with eight participants',()=>{const a=new P.Race({members:Array.from({length:8},(_,i)=>({bot:i>0,name:'R'+i})),options:{contact:true}});advance(a,5);const b=new P.Race();A(b.loadSnapshot(a.snapshot()));advance(a,2);advance(b,2);A.deepEqual(a.snapshot(),b.snapshot());});
test('all three routes can be completed by genuine physics-driven bots',()=>{for(const difficulty of['easy','normal','master'])for(const mapId of Object.keys(P.TRACKS)){const g=new P.Race({mapId,difficulty,members:[{bot:true}]});for(let i=0;i<600*120&&g.phase!=='raceEnd';i++)g.step(1/600);A.equal(g.phase,'raceEnd',difficulty+' '+mapId+' '+JSON.stringify(g.ranking()));A(g.fighters[0].finished);}});
test('course export validation preserves type and rejects missing/broken checkpoints',()=>{for(const m of Object.values(P.TRACKS)){const clean=D.cleanMap(JSON.parse(JSON.stringify(m)));A.equal(clean.type,'parkour');A.deepEqual(clean.race,m.race);const bad=JSON.parse(JSON.stringify(m));delete bad.race.finish;A.throws(()=>D.cleanMap(bad));bad.race=m.race;bad.race=JSON.parse(JSON.stringify(m.race));bad.race.checkpoints[0].order=3;A.throws(()=>D.cleanMap(bad));}A(!D.CLASSES.runner);A.equal(D.cleanSkin('runner'), 'default');A.equal(D.cleanSkin('staff'), 'default');A.equal(D.CLASSES.staff.name,'Monge');A(P.segmentProgress({x:100,y:500},[{x:100,y:1000},{x:100,y:0}])>.49);});

test('same wall can be used again only after separation; high/outward jumps are distinct',()=>{
 const make=()=>{const g=game(),f=g.fighters[0];g.map.platforms=[];g.map.walls=[{x:600,y:-1800,w:30,h:2600}];g.map.deathY=1800;Object.assign(f,{x:600-D.body(f).radius,y:400,grounded:false,wallSide:1,wallId:0,vy:100,lastWall:-1});return g;};
 const high=make(),away=make();high.step(1/600,[{...D.neutral(),move:1,jump:true,jumpHeld:true}]);away.step(1/600,[{...D.neutral(),move:-1,jump:true,jumpHeld:true}]);A(high.fighters[0].vy<away.fighters[0].vy);A(Math.abs(high.fighters[0].vx)<Math.abs(away.fighters[0].vx));
 const f=high.fighters[0];advance(high,.13,[{...D.neutral(),move:-1,jumpHeld:true}]);A(f.wallReleased);for(let i=0;i<600&&!f.wallSide;i++)high.step(1/600,[{...D.neutral(),move:1,jumpHeld:true}]);A.equal(f.wallSide,1);high.events=[];high.step(1/600,[{...D.neutral(),move:1,jump:true,jumpHeld:true}]);A(high.events.some(e=>e.type==='wallJump'));
});
test('contact is opt-in; protection blocks kicks and ends on own kick',()=>{
 for(const contact of[false,true]){const g=new P.Race({members:[{},{}],options:{contact}});advance(g,3);const[a,b]=g.fighters;Object.assign(a,{x:220,y:770,aim:0});Object.assign(b,{x:265,y:770,protection:0});A.equal(g.kick(0),contact);advance(g,.22);A.equal(g.events.some(e=>e.type==='kick'),contact);A(!a.dead&&!b.dead);}
 const g=new P.Race({members:[{},{}],options:{contact:true}});advance(g,3);const[a,b]=g.fighters;Object.assign(a,{x:220,y:770,aim:0});Object.assign(b,{x:265,y:770,protection:1});A(g.kick(0));A.equal(a.protection,0);advance(g,.22);A(!g.events.some(e=>e.type==='kick'));A.equal(b.x,265);
});
test('all duel classes are optional race runners with their own stats and no combat',()=>{
 for(const kind of Object.keys(D.CLASSES)){const blocked=new P.Race({members:[{kind}]});A.equal(blocked.fighters[0].kind,'runner');const g=new P.Race({members:[{kind}],options:{allClasses:true}});A.equal(g.fighters[0].kind,kind);A.equal(D.stats(g.fighters[0]).speed,D.CLASSES[kind].speed);advance(g,3.2,[{...D.neutral(),attack:true,parry:true,special:true,move:1}]);A(!['startup','parry','active','ultCharge'].includes(g.fighters[0].state));}
});
test('day/night never changes geometry or physics',()=>{
 for(const mapId of Object.keys(D.MAPS).filter(id=>!D.MAPS[id].custom)){const a=new D.Game({mapId,mode:'local',timeOfDay:'day',ai:false}),b=new D.Game({mapId,mode:'local',timeOfDay:'night',ai:false});a.start();b.start();A.deepEqual(a.map,b.map);const commands=[{...D.neutral(),move:1,jumpHeld:true},D.neutral()];advance(a,.5,commands);advance(b,.5,commands);A.deepEqual(a.fighters,b.fighters);}
});
test('race snapshots preserve unbounded ADMIN rules and live class',()=>{const a=new P.Race({members:[{}]});a.rules.speed=12;a.rules.dashCount=30;a.fighters[0].kind='staff';const b=new P.Race();A(b.loadSnapshot(a.snapshot()));A.equal(b.rules.speed,12);A.equal(b.rules.dashCount,30);A.equal(b.characters[0],'staff');A.deepEqual(a.snapshot(),b.snapshot());});
console.log(count+' V7 groups passed');
