const assert=require('node:assert/strict'),{chromium}=require('C:/Users/Luiz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),path=require('node:path'),{pathToFileURL}=require('node:url'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--allow-file-access-from-files']}),page=await browser.newPage({viewport:{width:1440,height:1040}});try{await page.goto(pathToFileURL(path.resolve(__dirname,'../../outputs/um-corte-v3.html')).href);await page.waitForFunction(()=>window.duelSnapshot);await page.screenshot({path:path.join(__dirname,'v33-final-menu.png'),fullPage:true});
 const result=await page.evaluate(async()=>{const {Game,CLASSES,blade}=DuelCore,canvas=document.createElement('canvas');canvas.width=1800;canvas.height=600;const c=canvas.getContext('2d'),colors=['jade','gold','coral','indigo','plum'],kinds=Object.keys(CLASSES),actors=kinds.map((kind,i)=>({r:new DuelRenderer(canvas),f:new Game({characters:[kind,'knight'],colors:[colors[i],'ice']}).fighters[0]}));let operations=0;
  for(const {r}of actors)for(const method of['line','path','ellipse']){const original=r[method].bind(r);r[method]=(...args)=>{const numbers=method==='line'?[args[0].x,args[0].y,args[1].x,args[1].y]:method==='path'?args[0].flat():args.slice(0,4);if(numbers.some(n=>!Number.isFinite(n)))throw Error('Non-finite '+method);operations++;return original(...args);};}
  const states=['idle','run','backstep','jump','dash','startup','active','recovery','parry','high','low','clash','stunned','dead','slide','kickStartup','kickActive','kickRecovery','feintRecovery','wallJump'];
  for(let frame=0;frame<states.length*30;frame++){const state=states[Math.floor(frame/30)],time=frame/60;for(const {r,f}of actors){Object.assign(f,{x:0,y:0,move:state==='backstep'?-1:1,vx:state==='run'?310:state==='backstep'?-210:state==='dash'?990:0,vy:state==='jump'?-400+(frame%30)*30:0,grounded:!['jump','low'].includes(state),aim:(frame%30)/30*Math.PI*2,attackAim:(frame%30)/30*Math.PI*2,state:['run','backstep','jump'].includes(state)?'idle':['high','low'].includes(state)?'parry':state,stateTime:frame%30/30*.12,duration:.12,anim:frame*.13,dashRemaining:state==='dash'?.1:0,dashX:1,dashY:0,slideRemaining:state==='slide'?.4:0,kickSide:1,wallJumpTime:state==='wallJump'?.2:0,guard:state==='high'?'high':state==='low'?'low':'normal',dead:state==='dead',deathTime:state==='dead'?(frame%30)/30*.6:0});f.facing=Math.cos(f.aim)>=0?1:-1;r.fighter(f,time,blade(f));r.sword(f,blade(f),time);}}
  const chunks=[],recorder=new MediaRecorder(canvas.captureStream(60),{mimeType:'video/webm;codecs=vp9',videoBitsPerSecond:3600000});recorder.ondataavailable=e=>chunks.push(e.data);const done=new Promise(resolve=>recorder.onstop=resolve);recorder.start();actors.forEach(a=>a.r.actorHistory=[]);const duration=14000,started=performance.now();
  await new Promise(resolve=>{const frame=()=>{const elapsed=performance.now()-started,t=elapsed/1000,stage=Math.min(6,Math.floor(t/2)),p=t%2;const titles=['EM GUARDA · RESPIRAÇÃO E ROUPAS','CORRIDA, RECUO E DESLIZE','SALTO E IMPULSO NA PAREDE','DASH + ATAQUE','CORTES EM TODAS AS DIREÇÕES','PARRY NORMAL, ALTO E BAIXO','CHUTE, FINTA E QUEDA'];c.fillStyle='#141a24';c.fillRect(0,0,1800,600);c.fillStyle='#b9c7c3';c.textAlign='center';c.font='18px monospace';c.fillText('UM CORTE III / V3.3',900,40);c.font='13px monospace';c.fillText(titles[stage],900,72);
   actors.forEach(({r,f},i)=>{const speed=stage===1?(p<1?310:-200):stage===3?900:0,angle=stage===4?-Math.PI+t*2:stage===5?p<.7?0:p<1.4?-Math.PI/2:Math.PI/2:0,air=stage===2||stage===5&&p>=1.4,attackStage=stage===3||stage===4,beat=p% .65;
    Object.assign(f,{x:0,y:stage===2?-Math.sin(p/2*Math.PI)*35:0,vx:speed,vy:stage===2?(p-1)*700:0,move:Math.sign(speed),grounded:!air,aim:angle,attackAim:angle,anim:f.anim+Math.abs(speed)/60*.026,state:attackStage?(beat<.16?'startup':beat<.28?'active':beat<.56?'recovery':'idle'):stage===5?'parry':stage===6?(p<.8?'clash':'dead'):'idle',stateTime:beat<.16?beat:beat<.28?beat-.16:beat-.28,duration:beat<.16?.16:beat<.28?.12:.28,dashRemaining:stage===3&&p% .65<.2?.1:0,dashX:speed<0?-1:1,dashY:0,guard:stage===5?p<.7?'normal':p<1.4?'high':'low':'normal',facing:Math.cos(angle)>=0?1:-1,dead:stage===6&&p>=.8,deathTime:stage===6?Math.max(0,p-.8):0,landing:stage===2&&p>1.85?2-p:0});f.slideRemaining=stage===1&&p>1?.35:0;f.wallJumpTime=stage===2&&p<.4?.2:0;f.kickSide=1;if(stage===6){f.dead=p>1.3;f.state=p<.16?'kickStartup':p<.36?'kickActive':p<.7?'kickRecovery':p<1.3?'feintRecovery':'dead';f.stateTime=p<.16?p:p<.36?p-.16:p<.7?p-.36:p<1.3?p-.7:p-1.3;f.duration=p<.16?.16:p<.36?.2:p<.7?.34:.6;f.deathTime=Math.max(0,p-1.3);}if(stage===5){f.duration=2;f.stateTime=p;}
    c.save();c.beginPath();c.rect(i*360,95,360,440);c.clip();c.translate(i*360+123,455);c.scale(1.65,1.65);r.fighter(f,t,blade(f));r.sword(f,blade(f),t);c.restore();c.fillStyle='#d5ded9';c.font='16px monospace';c.fillText(CLASSES[f.kind].name.toUpperCase(),i*360+180,555);});
   if(elapsed>=duration){recorder.stop();resolve();}else requestAnimationFrame(frame);};frame();});await done;const bytes=new Uint8Array(await new Blob(chunks,{type:'video/webm'}).arrayBuffer());let str='';for(let i=0;i<bytes.length;i+=32768)str+=String.fromCharCode(...bytes.subarray(i,i+32768));return{operations,video:btoa(str)};
 });assert(result.operations>10000);fs.writeFileSync(path.resolve(__dirname,'../../outputs/um-corte-v33-animacoes.webm'),Buffer.from(result.video,'base64'));console.log('All five rigs × 20 motions × 30 aim/phase samples: finite geometry.',result.operations,'draw operations. Animation preview recorded.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
