const fs=require('node:fs'),path=require('node:path'),p=path.join(__dirname,'app.js');let s=fs.readFileSync(p,'utf8');
const sub=(a,b)=>{if(!s.includes(a))throw Error('Missing '+a.slice(0,100));s=s.replace(a,b);};
const fn=(name,next,body)=>{const a=s.indexOf('function '+name+'('),b=s.indexOf('function '+next+'(',a);if(a<0||b<0)throw Error(name);s=s.slice(0,a)+body+'\n'+s.slice(b);};
sub("const canvas=$('game')", "const CHAR_CHOICES={...CLASSES,random:{name:'Aleatório',weapon:'Sorteio por partida',description:'Uma classe é sorteada antes de cada partida.'}},MAP_CHOICES={...MAPS,random:{name:'Mapa aleatório',description:'Uma nova arena a cada partida e revanche.',platforms:[]}};\nconst canvas=$('game')");
sub('const input=new DuelControls',"const lab=new DuelLab();let replayUI=null;\nconst input=new DuelControls");
sub('function unlockAudio()',`function resolveSelection(o,random=Math.random){const choose=keys=>keys[Math.floor(random()*keys.length)],characters=o.characters.map(k=>k==='random'?choose(Object.keys(CLASSES)):k),mapId=o.mapId==='random'?choose(Object.keys(MAPS)):o.mapId;return{...o,characters,mapId};}
function unlockAudio()`);
sub("if(type==='swing')noise", "if(type==='feint')noise(.055,.08,900);else if(type==='kick'){tone(130,.1,.12,'triangle',55);noise(.08,.1,450);}else if(type==='slide')noise(.2,.09,370);else if(type==='wallJump')noise(.12,.1,700);else if(type==='swing')noise");
sub("!!CLASSES[p.kind]","!!CHAR_CHOICES[p.kind]");
fn('ruleValue','config',"function ruleValue(key,value){return key==='parryWindow'?Math.round(value*150)+' ms':Number(value.toFixed(3)).toLocaleString('pt-BR')+'×';}");
s=s.replaceAll('Object.entries(CLASSES)','Object.entries(CHAR_CHOICES)').replaceAll('CLASSES[selected.characters[0]].description','CHAR_CHOICES[selected.characters[0]].description').replaceAll('CLASSES[selected.characters[1]].description','CHAR_CHOICES[selected.characters[1]].description').replaceAll('CLASSES[p.kind].name','CHAR_CHOICES[p.kind].name');
sub("b.className='character'+","b.className='character'+(k==='random'?' random-character':'')+");
sub('Object.entries(MAPS)','Object.entries(MAP_CHOICES)');sub('const theme=DuelScenery.THEMES[k];','const theme=DuelScenery.THEMES[k]||DuelScenery.THEMES.dojo;');
sub('preview.append(orb);','preview.append(orb);if(k===\'random\')preview.textContent=\'↻\';');
sub("label.append(out,el);parent.append(label);",`label.append(out,el);if(r.numeric){const number=document.createElement('input');number.type='number';number.step='any';number.min=r.min;number.max=r.max;number.value=selected.rules[k];number.className='rule-number';number.id='number-'+k;number.setAttribute('aria-label',r.name+' em multiplicador');number.disabled=configLocked();number.onchange=()=>{const value=Number(number.value);selected.rules[k]=number.value!==''&&Number.isFinite(value)?Math.max(r.min,Math.min(r.max,value)):selected.rules[k];rulesChanged();};const previous=el.oninput;el.oninput=()=>{previous();number.value=el.value;};label.append(number);}parent.append(label);`);
s=s.replaceAll("'SEIS ARENAS · SEIS ATMOSFERAS'","'SETE ARENAS · PAREDES E MOVIMENTO'");
sub('game=new Game({...selected,colors});renderer.previousBlades=',"game=new Game({...selected,characters:selected.characters.map(k=>k==='random'?'knight':k),mapId:selected.mapId==='random'?'dojo':selected.mapId,colors});renderer.previousBlades=");
sub("$('opponent-select-label').textContent=selected.mode==='local'?'JOGADOR 2 · CONTROLE':'ADVERSÁRIO';","$('opponent-select-label').textContent=selected.mode==='local'?'JOGADOR 2 · CONTROLE':selected.mode==='training'?'BONECO DE TREINO':'ADVERSÁRIO';");
sub("MAPS[l.config.mapId].name","MAP_CHOICES[l.config.mapId].name");
sub("function returnMenu(message=''){disconnect();","function returnMenu(message=''){lab.close();replayUI=null;disconnect();$('training-panel').hidden=$('replay-panel').hidden=true;");
sub("function showGame(){renderer.snapCamera=true;", "function showGame(){lab.close();replayUI=null;$('replay-panel').hidden=true;$('training-panel').hidden=selected.mode!=='training';renderer.snapCamera=true;");
sub("selected.mode==='pve'?'RIVAL':seat===1", "selected.mode==='pve'?'RIVAL':selected.mode==='training'?'BONECO':seat===1");
sub("selected.mode==='local'?'LOCAL':'SALA '+net.roomCode", "selected.mode==='local'?'LOCAL':selected.mode==='training'?'TREINO':'SALA '+net.roomCode");
sub('game=new Game({...selected,colors});game.start();countdown=1;',"game=new Game(resolveSelection({...selected,colors}));game.start();if(selected.mode==='training')lab.startTraining(game);countdown=1;");
sub("for(const ev of game.events.splice(0)){sound(ev.type);","for(const ev of game.events.splice(0)){lab.observe(ev,game);sound(ev.type);");
sub("['dash','land','jump'].includes(ev.type)","['dash','slide','wallJump','land','jump'].includes(ev.type)");
sub("else if(ev.type==='round'){clearInputs();","else if(ev.type==='round'){if(game.mode==='training'){lab.resetTraining(game);renderer.actorHistory=[];}clearInputs();");
sub("function readInput(id,consume=true){if(countdown", "function readInput(id,consume=true){if(lab.viewGame)return neutral();if(countdown");
sub('return input.read(sourceFor(id),game.fighters[id],renderer,consume);',"const command=input.read(sourceFor(id),game.fighters[id],renderer,consume);if(command.reset&&selected.mode==='training'){resetTraining();return neutral();}return command;");
fn('simulate','seeded',`function simulate(inputs){const before=game.phase==='playing'?game.snapshot():null,recorded=[];for(let id=0;id<2;id++){for(const k of['move','aim','jumpHeld','down'])buffers[id][k]=inputs[id][k];for(const k of['attack','parry','dash','jump','kick'])buffers[id][k]||=inputs[id][k];}for(let sub=0;sub<10;sub++){const frozen=game.hitstop>0;game.step(1/600,buffers);recorded.push(frozen?[neutral(),neutral()]:(game.lastCommands||[neutral(),neutral()]).map(c=>({...c})));if(!frozen)for(const b of buffers)b.attack=b.parry=b.dash=b.jump=b.kick=false;}if(before)lab.record(game,before,recorded,selected.mode==='online'?seat:0);consumeEvents();}
`);
sub("['attack','parry','dash','jump','jumpHeld','down'].every","['attack','parry','dash','jump','jumpHeld','down','kick'].every");
sub("!!MAPS[c.mapId]","!!MAP_CHOICES[c.mapId]");
sub("if(!net?.connected||!packet||", "if(!net?.connected||!packet||!MAPS[packet.mapId]||");
fn('hostNewMatch','stateHash',`function hostNewMatch(){if(!net?.connected||net.role!=='host'||!lobby)return;const seed=new Uint32Array(1);crypto.getRandomValues(seed);const selection={characters:lobby.players.map(p=>p.kind),mapId:lobby.config.mapId},resolved=resolveSelection(selection,seeded(seed[0])),p={type:'start',id:net.roomCode+'-'+(++sessionCounter)+'-'+seed[0],seed:seed[0],...lobby.config,...resolved,selection,colors:lobby.players.map(p=>p.color),delay:6};lobby.rematch=false;if(initSession(p))sendRequired(p);}
`);
fn('stateHash','checkHash',`function stateHash(){const snapshot=game.snapshot(),q=JSON.stringify(snapshot,(_,v)=>typeof v==='number'?Math.round(v*1e5)/1e5:v);let hash=2166136261;for(let i=0;i<q.length;i++)hash=Math.imul(hash^q.charCodeAt(i),16777619);return(hash>>>0).toString(16);}
`);
sub("if(msg.type==='lobby'&&seat===1&&inMenu)","if(msg.type==='lobby'&&seat===1&&(inMenu||game.phase==='matchEnd'))");
sub("CLASSES[msg.kind]&&COLORS[msg.color]","CHAR_CHOICES[msg.kind]&&COLORS[msg.color]");
sub("const configMatches=lobby&&JSON.stringify(msg.characters)===JSON.stringify(lobby.players.map(p=>p.kind))&&JSON.stringify(msg.colors)===JSON.stringify(lobby.players.map(p=>p.color))&&msg.mapId===lobby.config.mapId&&JSON.stringify(msg.rules)===JSON.stringify(lobby.config.rules);", "const expected=msg.selection&&resolveSelection(msg.selection,seeded(msg.seed)),configMatches=lobby&&expected&&JSON.stringify(msg.selection.characters)===JSON.stringify(lobby.players.map(p=>p.kind))&&msg.selection.mapId===lobby.config.mapId&&JSON.stringify(msg.characters)===JSON.stringify(expected.characters)&&msg.mapId===expected.mapId&&JSON.stringify(msg.colors)===JSON.stringify(lobby.players.map(p=>p.color))&&JSON.stringify(msg.rules)===JSON.stringify(lobby.config.rules);");
sub("if(msg.type==='rematch'&&game.phase==='matchEnd'){s.votes[1-seat]=true;$('rematch-status').textContent='O oponente pediu revanche. Confirme para jogar novamente.';if(seat===0&&s.votes.every(Boolean))hostNewMatch();}","if(msg.type==='rematch'&&game.phase==='matchEnd'){s.votes[1-seat]=true;if(seat===0)prepareRematch();$('rematch-status').textContent='O oponente pediu revanche. Escolha seu personagem para o próximo duelo.';}");
fn('requestRematch','renderBindings',`function prepareRematch(){if(seat!==0||!lobby||lobby.rematch)return;lobby.rematch=true;lobby.revision++;lobby.players.forEach(p=>p.ready=false);broadcastLobby();}
function requestRematch(){if(selected.mode!=='online'){startOffline();return;}if(!onlineSession||!net?.connected)return;lab.close();$('replay-panel').hidden=true;replayUI=null;if(seat===0)prepareRematch();if(!sendRequired({type:'rematch',id:onlineSession.id}))return;onlineSession.votes[seat]=true;inMenu=true;paused=false;clearInputs();resetEffects();$('match').hidden=true;$('menu').hidden=false;$('arena').classList.add('menu-open');for(const id of['hud','match-meta','cooldowns','cooldowns-two','menu-button','countdown'])$(id).hidden=true;selected.characters[0]=lobby.players[seat].kind;selected.colors[0]=lobby.players[seat].color;refreshMenu();$('menu').querySelector('h1').textContent='Escolha seu próximo corte.';networkStatus('Sala mantida. Escolham os personagens e confirmem novamente.','connected');}
function resetTraining(){if(lab.viewGame){lab.tryAgain(true);renderer.actorHistory=[];return;}if(selected.mode!=='training')return;lab.resetTraining(game);clearInputs();resetEffects();renderer.actorHistory=[];accumulator=0;}
function openReplay(){if(!lab.clip||selected.mode==='online'&&game.phase!=='matchEnd')return;replayUI={inMenu,paused,pauseVisible:!$('pause').hidden,matchVisible:!$('match').hidden};lab.open();inMenu=false;$('menu').hidden=$('match').hidden=$('pause').hidden=$('training-panel').hidden=true;$('arena').classList.remove('menu-open');$('replay-panel').hidden=false;$('replay-seek').max=lab.clip.frames.length-1;$('replay-speed').value='.5';renderer.actorHistory=[];renderer.snapCamera=true;clearInputs();}
function closeReplay(){lab.close();$('replay-panel').hidden=true;if(replayUI){inMenu=replayUI.inMenu;paused=replayUI.paused;$('menu').hidden=!inMenu;$('arena').classList.toggle('menu-open',inMenu);$('pause').hidden=!replayUI.pauseVisible;$('match').hidden=!replayUI.matchVisible;}replayUI=null;renderer.actorHistory=[];renderer.snapCamera=true;clearInputs();}
`);
sub("if(!paused&&game.hitstop<=0)clock+=dt;","if(!paused&&game.hitstop<=0)clock+=dt*(selected.mode==='training'?lab.speed:1);");
sub("input.enabled=!inMenu&&!$('settings').open;", "input.enabled=(!inMenu||!!lab.viewGame)&&!$('settings').open;");
sub("if(selected.mode==='online')onlineTick(dt);else if(countdown>0)","if(selected.mode==='online')onlineTick(dt);else if(lab.viewGame||selected.mode==='training'&&lab.trainingPaused){}else if(countdown>0)");
sub("accumulator=Math.min(accumulator+dt,.08)","accumulator=Math.min(accumulator+dt*(selected.mode==='training'?lab.speed:1),.08)");
sub("selected.mode==='local'?readInput(1):neutral()","selected.mode==='local'?readInput(1):selected.mode==='training'?lab.dummy(game):neutral()");
sub('renderer.render(game,effects,clock);',`if(lab.viewGame){const command=lab.viewMode==='play'&&!$('settings').open?input.read(selected.source,lab.viewGame.fighters[lab.clip.seat],renderer):null;for(const ev of lab.tick(dt,command)||[]){sound(ev.type);if(['parry','clash','kick'].includes(ev.type))burst(ev.x,ev.y,18,'#fff2b6');}if(lab.viewMode==='watch')$('replay-seek').value=Math.floor(lab.index);$('replay-title').textContent=lab.viewMode==='play'?'OUTRA RESPOSTA · TREINO':'REPLAY DO ÚLTIMO PONTO';$('replay-note').textContent=lab.note;$('replay-play').textContent=lab.playing?'PAUSAR':'REPRODUZIR';$('replay-seek').disabled=lab.viewMode==='play';}const drawn=lab.viewGame||game;renderer.debug=(!!lab.viewGame||selected.mode==='training')&&lab.collisions;renderer.render(drawn,effects,lab.viewGame?drawn.time:clock);`);
const aa=s.indexOf(" $('player-score').textContent=game.score"),bb=s.indexOf('\n}',aa);let hud=s.slice(aa,bb).replaceAll('game.','drawn.');hud+=`\n $('open-replay').disabled=!lab.clip||(selected.mode==='online'&&game.phase!=='matchEnd');$('training-toggle').hidden=inMenu||selected.mode!=='training'||!!lab.viewGame;$('training-note').hidden=inMenu||selected.mode!=='training'||!!lab.viewGame;$('training-note').textContent=lab.note;document.querySelector('.first-to').textContent=drawn.mode==='training'?'TREINO · UM CORTE CONTINUA FATAL':'PRIMEIRO A 5 · UM GOLPE DECIDE';if(lab.viewGame){$('countdown').hidden=$('round-feedback').hidden=true;}else $('round-feedback').hidden=false;`;
s=s.slice(0,aa)+hud+s.slice(bb);
sub("release:'3.2'","release:'3.3'");sub("controller:!!input.pad,online:","training:{config:{...lab.config},speed:lab.speed,note:lab.note,checkpoint:!!lab.checkpoint},replay:{available:!!lab.clip,open:!!lab.viewGame,mode:lab.viewMode,index:lab.index||0,length:lab.clip?.frames.length||0,fighters:lab.viewGame?.fighters.map(f=>({...f}))||[]},controller:!!input.pad,online:");
sub("window.duelSnapshot=",`$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.classList.contains('theater'))document.documentElement.classList.remove('theater');else await document.documentElement.requestFullscreen();}catch{document.documentElement.classList.toggle('theater');}$('fullscreen').textContent=document.fullscreenElement||document.documentElement.classList.contains('theater')?'SAIR DA TELA CHEIA':'TELA CHEIA';};document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'SAIR DA TELA CHEIA':'TELA CHEIA';renderer.snapCamera=true;});
$('open-replay').onclick=openReplay;$('replay-close').onclick=closeReplay;$('replay-play').onclick=()=>lab.playing=!lab.playing;$('replay-step').onclick=()=>{if(lab.viewMode==='watch')lab.seek(Math.floor(lab.index)+1);else{lab.playing=true;lab.tick(1/60/lab.speed,neutral());lab.playing=false;}};$('replay-seek').oninput=()=>{lab.seek(+$('replay-seek').value);renderer.actorHistory=[];};$('replay-speed').onchange=()=>lab.speed=+$('replay-speed').value;$('replay-try').onclick=()=>{lab.tryAgain();renderer.actorHistory=[];clearInputs();canvas.focus({preventScroll:true});};$('replay-retry').onclick=()=>resetTraining();
for(const id of['training-hitboxes','replay-hitboxes'])$(id).onchange=()=>{lab.collisions=$(id).checked;$('training-hitboxes').checked=$('replay-hitboxes').checked=lab.collisions;};$('training-toggle').onclick=()=>$('training-panel').hidden=!$('training-panel').hidden;$('training-close').onclick=()=>$('training-panel').hidden=true;$('training-reset').onclick=resetTraining;$('training-save').onclick=()=>lab.savePosition(game);$('training-speed').onchange=()=>lab.speed=+$('training-speed').value;$('training-pause').onclick=()=>{lab.trainingPaused=!lab.trainingPaused;$('training-pause').textContent=lab.trainingPaused?'RETOMAR TEMPO':'PAUSAR TEMPO';};$('training-step').onclick=()=>{if(selected.mode==='training'&&!inMenu){lab.trainingPaused=true;simulate([neutral(),lab.dummy(game)]);$('training-pause').textContent='RETOMAR TEMPO';}};for(const k of['move','action','aim','attackInterval','parryInterval','variation'])$('dummy-'+k).onchange=()=>{const el=$('dummy-'+k);lab.config[k]=el.type==='number'?Math.max(+el.min,Math.min(+el.max,Number(el.value)||0)):el.value;el.value=lab.config[k];lab.due={attack:0,parry:0};};
window.duelSnapshot=`);
// A lobby refresh must never replace the finished official game while players choose a rematch.
sub("function preview(){if(!inMenu)return;","function preview(){if(!inMenu||selected.mode==='online'&&onlineSession)return;");
fs.writeFileSync(p,s);
