const fs=require('fs'),path=require('path');
function edit(name,fn){const p=path.join(__dirname,name);fs.writeFileSync(p,fn(fs.readFileSync(p,'utf8')));}
edit('engine.js',s=>s.replace('function slash(f,walls=[]){',`// Clip rays at physical walls; both rendering and collisions use this contour.
function wallFraction(a,b,w){let lo=0,hi=1;for(const [key,min,max]of[['x',w.x,w.x+w.w],['y',w.y,w.y+w.h]]){const d=b[key]-a[key];if(Math.abs(d)<1e-9){if(a[key]<min||a[key]>max)return 1;continue;}let t=(min-a[key])/d,u=(max-a[key])/d;if(t>u)[t,u]=[u,t];lo=Math.max(lo,t);hi=Math.min(hi,u);if(lo>hi)return 1;}return lo;}
function wallContour(poly,origin,walls,reach){const nearby=walls.filter(w=>Math.hypot(origin.x-clamp(origin.x,w.x,w.x+w.w),origin.y-clamp(origin.y,w.y,w.y+w.h))<=reach);if(!nearby.length)return poly;const rays=nearby.flatMap(w=>[[w.x,w.y],[w.x+w.w,w.y],[w.x,w.y+w.h],[w.x+w.w,w.y+w.h]]).map(([x,y])=>Math.atan2(y-origin.y,x-origin.x));const out=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],dx=b.x-a.x,dy=b.y-a.y,ts=[0];for(const angle of rays)for(const offset of[-1e-6,0,1e-6]){const rx=Math.cos(angle+offset),ry=Math.sin(angle+offset),cross=dx*ry-dy*rx;if(Math.abs(cross)<1e-8)continue;const t=((origin.x-a.x)*ry-(origin.y-a.y)*rx)/cross;if(t>0&&t<1&&(a.x+t*dx-origin.x)*rx+(a.y+t*dy-origin.y)*ry>0)ts.push(t);}ts.sort((x,y)=>x-y);for(const t of ts){const p={x:a.x+dx*t,y:a.y+dy*t},hit=Math.min(1,...nearby.map(w=>wallFraction(origin,p,w)));out.push({x:lerp(origin.x,p.x,hit),y:lerp(origin.y,p.y,hit)});}}return out;}
function slash(f,walls=[]){`).replace("for(const w of walls){if(origin.y>w.y&&origin.y<w.y+w.h){if(f.x<w.x)points=clipPlane(points,'x',w.x,-1);else if(f.x>w.x+w.w)points=clipPlane(points,'x',w.x+w.w,1);}}return{points,origin,aim,progress};","points=wallContour(points,origin,walls,s.reach);return{points,origin,aim,progress};").replace("if(segmentDistance(from,to,{x:d.x,y:d.y-db.top}","if(!this.map.walls.some(w=>wallFraction({x:a.x,y},{x:d.x,y},w)<1)&&segmentDistance(from,to,{x:d.x,y:d.y-db.top}"));
edit('app.js',s=>s.replace("if(!$('settings').open)togglePause();","if(!$('settings').open){if(lab.viewGame)closeReplay();else togglePause();}")
 .replace("replayUI={inMenu,paused,pauseVisible:","replayUI={inMenu,paused,speed:lab.speed,collisions:lab.collisions,pauseVisible:")
 .replace("inMenu=replayUI.inMenu;paused=replayUI.paused;","inMenu=replayUI.inMenu;paused=replayUI.paused;lab.speed=replayUI.speed;lab.collisions=replayUI.collisions;")
 .replace("function returnMenu(message=''){lab.close();","function returnMenu(message=''){$('menu').querySelector('h1').textContent='O próximo corte é seu.';lab.close();")
 .replace("height:game.map.height,platforms:","height:game.map.height,walls:game.map.walls,platforms:"));
edit('test-engine.cjs',s=>s.replace("startup is harmless; no attack cancel, parry or dash cancel","startup is harmless and cannot cancel into another attack or dash").replace("assert.equal(g.parry(0),false);","").replace("assert(!g.dash(0)&&!g.parry(0));","assert(!g.dash(0));").replace("assert.equal(r.speed,1.4)","assert.equal(r.speed,3)"));
edit('test-pixels.cjs',s=>s.replace("attackSpeed,2)","attackSpeed,3)").replace("attackSpeed,1)","attackSpeed,1.2)").replace("g.setState(a,'active',.12);d.x=", "g.setState(a,'active',.12);a.stateTime=.06;d.x="));
