const fs=require('node:fs'),path=require('node:path');
function edit(file,old,next){const p=path.join(__dirname,file),s=fs.readFileSync(p,'utf8');if(!s.includes(old))throw new Error('Not found: '+file+' '+old.slice(0,55));fs.writeFileSync(p,s.replace(old,next));}
edit('renderer.js',"lean=clamp(f.vx/80,-5,5),squat=f.landing>0?Math.sin(f.landing/.15*Math.PI)*7:0", "lean=clamp(f.vx/47,-12,12)+(f.state==='active'?Math.sin(f.stateTime/f.duration*Math.PI)*f.facing*6:0),squat=(f.landing>0?Math.sin(f.landing/.15*Math.PI)*7:0)+(f.state==='dash'?10:0)");
edit('renderer.js',"this.ellipse(head.x,head.y,12,14,ink);if(f.kind", "this.line({x:shoulder.x,y:shoulder.y+3},{x:head.x,y:head.y+9},ink,10);this.ellipse(head.x,head.y,12,14,ink);if(f.kind");
edit('renderer.js',"const scale=Math.min(canvas.width/160,canvas.height/180);c.translate(canvas.width/2,canvas.height-9);c.scale(scale,scale);const f=", "const f=");
edit('renderer.js',"const w=blade(f);this.fighter(f,0,w,true);", "const w=blade(f),pts=[{x:-65,y:-152},{x:35,y:7},...w.segments.flatMap(s=>[s.a,s.b]),...(w.shaft?[w.shaft.a,w.shaft.b]:[])],minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxY=Math.max(...pts.map(p=>p.y)),scale=Math.min((canvas.width-10)/(maxX-minX),(canvas.height-10)/(maxY-minY));c.translate(canvas.width/2-(minX+maxX)/2*scale,canvas.height-5-maxY*scale);c.scale(scale,scale);this.fighter(f,0,w,true);");
edit('renderer.js',"for(const f of game.fighters){const w=blade(f);this.fighter(f,t,w);", "for(const f of game.fighters){if(!f.grounded&&!f.dead){const surfaces=game.map.platforms.filter(p=>p.y>=f.y&&f.x>=p.x&&f.x<=p.x+p.w).sort((a,b)=>a.y-b.y);if(surfaces.length){const ground=surfaces[0],height=ground.y-f.y;this.ellipse(f.x,ground.y+3,Math.max(9,27-height*.035),3,'#213f331d');}}const w=blade(f);this.fighter(f,t,w);");
edit('engine.js',"d.stateBefore==='recovery'?'O golpe errado abriu sua recuperação.':'A lâmina encontrou uma abertura.'", "d.stateBefore==='recovery'?'O golpe errado abriu sua recuperação.':d.stateBefore==='parryRecovery'?'O parry terminou antes de o golpe chegar.':d.stateBefore==='parry'?'O golpe veio por fora da direção protegida.':d.stateBefore==='dash'?'O dash entrou no alcance da lâmina.':d.stateBefore==='stunned'?'O parry deixou uma abertura para o contra-ataque.':'A lâmina encontrou uma abertura.'");
edit('engine.js',"const commands=[inputs[0]||neutral(),this.aiEnabled?this.updateAI(dt):inputs[1]||neutral()];", "const commands=[inputs[0]||neutral(),this.aiEnabled?this.updateAI(dt):inputs[1]||neutral()];if(commands[0].move*(this.fighters[1].x-this.fighters[0].x)<0)this.habits.retreat+=dt;");
edit('engine.js',"return{...base,parry:clamp", "return{...base,attack:clamp(base.attack+(this.difficulty==='adaptive'?Math.min(.12,h.retreat/100):0),0,1),parry:clamp");
edit('controls.js',"if(this.capture?.device==='keyboard'){e.preventDefault();this.bind('Mouse'+e.button);return;}", "if(this.capture?.device==='keyboard'){if(e.target.closest('button,input,select'))return;e.preventDefault();this.bind('Mouse'+e.button);return;}");
edit('app.js',"$('opponent-side').hidden=selected.mode==='online';", "$('input-source').value=selected.source;$('opponent-side').hidden=selected.mode==='online';");
edit('app.js',"selected.mode=b.dataset.mode;if(selected.mode==='local')", "selected.mode=b.dataset.mode;if(selected.mode!=='pve'&&selected.colors[1]==='random')selected.colors[1]=Object.keys(COLORS).find(k=>k!==selected.colors[0]);if(selected.mode==='local')");
edit('app.js',"mapId:game.mapId,rules:{...game.rules},fighters:", "mapId:game.mapId,rules:{...game.rules},camera:{...renderer.camera},fighters:");
edit('v3.css',".guard-hint{align-self", ".ability kbd{white-space:nowrap}.ability{width:101px}.guard-hint{align-self");
console.log('Applied animation, readability and input polish.');
