const fs=require('fs'),path=require('path');function edit(n,f){const p=path.join(__dirname,n);fs.writeFileSync(p,f(fs.readFileSync(p,'utf8')));}
edit('engine.js',s=>s.replace("a=lerp(-arc,arc,t)+sweep,r=s.reach", "a=lerp(-arc,arc,t)*(.35+.65*Math.sin(progress*Math.PI))+lerp(-arc*.6,arc*.6,progress)*(Math.cos(aim)>=0?1:-1),r=s.reach").replace("thickness=(s.reach-s.minRange)*Math.pow(Math.sin(t*Math.PI),.8)","thickness=(s.reach-s.minRange)*Math.pow(Math.sin(t*Math.PI),.8)*(.55+.45*Math.sin(progress*Math.PI))").replace("Chão seguro. Duas plataformas para ataques por cima.","Chão seguro, plataformas e pilares para saltar pelas paredes.").replace("Três alturas, rotas aéreas e uma abertura no centro.","Rotas aéreas, paredes e um vão no centro. Cuidado ao recuar."));
edit('scenery.js',s=>s.replace("mist:'#ac8d91',dark:false","mist:'#ac8d91',dark:true"));
edit('renderer.js',s=>s.replace("c.fillStyle='#d7ceba';c.fillRect", "c.fillStyle=DuelScenery.THEMES[game.mapId]?.dark?'#202d3c':'#d7ceba';c.fillRect").replace("c.fillStyle='#183e49';c.textAlign='center';c.fillText(f.state+", "c.fillStyle=DuelScenery.THEMES[game.mapId]?.dark?'#ecf4df':'#183e49';c.textAlign='center';c.fillText(f.state+"));
edit('app.js',s=>s.replace("function openSettings(){if(!inMenu", "function openSettings(){if(lab.viewGame){lab.resumeAfterSettings=lab.playing;lab.playing=false;}if(!lab.viewGame&&!inMenu")
 .replace("function lostFocus(){clearInputs();if(!inMenu", "function lostFocus(){clearInputs();if(lab.viewGame){lab.playing=false;return;}if(!inMenu")
 .replace("$('settings').addEventListener('cancel',", "$('settings').addEventListener('close',()=>{if(lab.viewGame&&lab.resumeAfterSettings){lab.playing=true;lab.resumeAfterSettings=false;}});$('settings').addEventListener('cancel',")
 .replace("$('menu-button').onclick=togglePause;", "$('menu-button').onclick=()=>lab.viewGame?closeReplay():togglePause();")
 .replace("lab.collisions=replayUI.collisions;", "lab.collisions=replayUI.collisions;$('training-hitboxes').checked=$('replay-hitboxes').checked=lab.collisions;")
 .replace("if(ev.type==='parry'||ev.type==='clash'){effects.shake", "if(ev.type==='kick'){effects.shake=reduced?0:2;burst(ev.x,ev.y,10,'#d6c79f',.5);effects.eventText='CHUTE · ESPAÇO ABERTO';effects.eventLife=.35;}else if(ev.type==='feint'){effects.eventText='FINTA';effects.eventLife=.2;}else if(ev.type==='parry'||ev.type==='clash'){effects.shake")
 .replace("const yours=ev.winner===seat;$('round-eyebrow').textContent=ev.trade?", "const yours=ev.winner===seat;$('round-eyebrow').textContent=selected.mode==='training'?'TREINO · REINÍCIO RÁPIDO':ev.trade?")
 .replace("$('player-score').textContent=drawn.score[0];", "for(let i=0;i<2;i++)$(i?'right-class':'left-class').textContent=CLASSES[drawn.fighters[i].kind].name;$('player-score').textContent=drawn.score[0];")
 .replace("function showGame(){lab.close();", "function showGame(){lab.trainingPaused=false;$('training-pause').textContent='PAUSAR TEMPO';lab.close();")
 .replace("click E", "clique esquerdo"));
edit('test-pixels.cjs',s=>s.replace("g.setState(a,'active',.12);d.aim=", "g.setState(a,'active',.12);a.stateTime=.06;d.aim=").replace("for(const f of[x,y])h.setState(f,'active',.12);", "for(const f of[x,y]){h.setState(f,'active',.12);f.stateTime=.06;}"));
