const assert=require('node:assert/strict'),D=require('./engine.js'),Lab=require('./lab.js');
const {Game,neutral,stats,body,slash}=D,cmd=o=>({...neutral(),...o}),make=o=>{const g=new Game({mode:'local',ai:false,...o});g.start();return g;};
let passed=0;function test(n,f){try{f();passed++;console.log('PASS',n);}catch(e){console.error('FAIL',n,e.stack);process.exitCode=1;}}
function tick(g,n,inputs){for(let i=0;i<n;i++)g.step(1/600,inputs||[cmd(),cmd({aim:Math.PI})]);}
function pair(g,d=100){g.fighters[0].x=570;g.fighters[1].x=570+d;}
function active(g,id,aim=0){const f=g.fighters[id];g.setState(f,'active',stats(f).active);f.stateTime=f.duration/2;f.attackAim=aim;}
test('feint uses startup only, cannot guard, and imposes recovery/cooldown',()=>{const g=make();g.attack(0);assert(g.parry(0));const f=g.fighters[0];assert.equal(f.state,'feintRecovery');assert.equal(f.duration,.15);assert.equal(f.feintCooldown,.45);assert(!g.parry(0)&&!g.attack(0)&&!g.dash(0));tick(g,92);assert(g.attack(0));assert(!g.parry(0));assert.equal(f.state,'startup');tick(g,120);assert.equal(f.state,'active');assert(!g.parry(0));});
test('feint remains vulnerable to a clean slash',()=>{const g=make();pair(g);g.attack(1);g.parry(1);active(g,0);g.resolveCombat();assert(g.fighters[1].dead);});
test('kick breaks guard, pushes, but neither kills nor awards a point',()=>{const g=make();pair(g,52);g.parry(1);g.kick(0);tick(g,100);assert(g.events.some(e=>e.type==='kick'));assert.equal(g.fighters[1].state,'pushed');assert(!g.fighters[1].dead);assert.deepEqual(g.score,[0,0]);assert(g.fighters[1].vx>400);assert.equal(g.fighters[0].state,'kickActive');});
test('kick has limited reach and loses to an active blade',()=>{const g=make();pair(g,90);g.kick(0);tick(g,170);assert(!g.events.some(e=>e.type==='kick'));const h=make();pair(h,60);h.kick(0);active(h,1,Math.PI);h.resolveCombat();assert(h.fighters[0].dead);assert.deepEqual(h.score,[0,1]);});
test('kick cannot pass through a wall',()=>{const g=make();pair(g,65);g.map.walls=[{x:600,y:400,w:20,h:250}];g.kick(0);g.setState(g.fighters[0],'kickActive',.1);g.resolveCombat();assert(!g.events.some(e=>e.type==='kick'));});
test('slide lowers real body and permits attacks, using the dash cooldown',()=>{const g=make(),f=g.fighters[0],top=body(f).top;assert(g.dash(0,1,true));assert.equal(f.state,'slide');assert(body(f).top<top/2);assert(g.attack(0));assert(f.dashRemaining>0);tick(g,350);assert.equal(f.slideRemaining,0);assert.equal(body(f).top,top);assert(f.dashCooldown>0);});
test('sliding avoids a level lance but not a downward cut',()=>{const g=make({characters:['lancer','knight']}),[a,d]=g.fighters;pair(g,180);active(g,0);assert(g.bodyContact(a,d));d.slideRemaining=.4;assert(!g.bodyContact(a,d));a.kind='knight';a.x=d.x;a.y=d.y-85;active(g,0,Math.PI/2);g.resolveCombat();assert(d.dead);});
test('down plus air dash does not start a ground slide',()=>{const g=make({rules:{airDash:true}}),f=g.fighters[0];f.grounded=false;f.y=200;f.aim=.5;g.dash(0,1,true);assert.equal(f.state,'dash');assert.equal(f.slideRemaining,0);assert(f.dashY>0);});
test('wall collision stops walking and dash; wall jump launches away',()=>{const g=make(),f=g.fighters[0];f.x=237;f.y=520;f.grounded=false;f.coyote=0;f.airUsed=true;g.collideWalls(f);tick(g,100,[cmd({move:-1}),cmd()]);assert.equal(f.wallSide,-1);const cooldown=f.dashCooldown;g.step(1/600,[cmd({jump:true,jumpHeld:true,move:-1}),cmd()]);assert(f.vx>400&&f.vy<-800);assert(f.airUsed);assert.equal(f.dashCooldown,cooldown);assert(g.events.some(e=>e.type==='wallJump'));const h=make(),a=h.fighters[0];a.x=260;a.aim=Math.PI;h.dash(0,-1);tick(h,90,[cmd({aim:Math.PI}),cmd()]);assert(a.x>=216+body(a).radius-.001);assert.equal(a.dashRemaining,0);});
test('same wall cannot supply infinite jumps without landing',()=>{const g=make(),f=g.fighters[0];f.grounded=false;f.y=500;f.x=231.3;f.wallSide=-1;f.wallId=2;f.lastWall=2;f.coyote=0;g.step(1/600,[cmd({jump:true,jumpHeld:true}),cmd()]);assert(f.vy>=0);});
test('solid wall clips the actual slash, including diagonal corner attacks',()=>{for(const [x,y,dx,dy]of[[590,610,65,0],[580,490,85,105],[680,490,-110,105]]){const g=make(),[a,d]=g.fighters;a.x=x;a.y=y;d.x=x+dx;d.y=y+dy;g.map.walls=[{x:600,y:450,w:35,h:230}];active(g,0,Math.atan2(dy,dx));assert(!g.bodyContact(a,d));const points=slash(a,g.map.walls).points;for(const p of points)assert(!(p.x>600.01&&p.x<634.99&&p.y>450.01&&p.y<679.99));}});
test('moving platform carries the fighter and restores deterministically',()=>{const g=make({mapId:'tower'}),f=g.fighters[0],i=g.map.platforms.findIndex(p=>p.motion),p=g.map.platforms[i];f.x=640;f.y=p.y;f.platform=i;f.grounded=true;tick(g,100);assert(f.grounded);assert.equal(f.platform,i);assert(Math.abs(f.y-p.y)<.001);const h=make();h.loadSnapshot(g.snapshot());tick(g,350);tick(h,350);assert.deepEqual(g.snapshot(),h.snapshot());g.step(1/600,[cmd({jump:true,jumpHeld:true}),cmd()]);assert(!f.grounded&&f.vy<0);});
test('input buffer accepts last 80ms without canceling recovery',()=>{const g=make(),f=g.fighters[0];g.setState(f,'recovery',.32);f.stateTime=.26;g.step(1/600,[cmd({attack:true,aim:.7}),cmd()]);assert.equal(f.state,'recovery');assert(f.queued);tick(g,38);assert.equal(f.state,'startup');assert.equal(f.attackAim,.7);assert.equal(g.attackCounter,1);assert.equal(f.queued,null);});
test('early buffered input is discarded rather than stored through entire recovery',()=>{const g=make(),f=g.fighters[0];g.setState(f,'recovery',.32);g.step(1/600,[cmd({attack:true}),cmd()]);assert.equal(f.queued,null);tick(g,200);assert.equal(f.state,'idle');});
test('continuous rules preserve exact factors and class timing differences',()=>{for(const speed of[.1,.73,1.4,2.35,3])for(const kind of Object.keys(D.CLASSES)){const g=make({characters:[kind,'knight'],rules:{speed,attackSpeed:speed,mapSize:2.3}});g.attack(0);assert.equal(g.fighters[0].duration,stats(kind).startup/speed);assert.equal(g.rules.speed,speed);assert.equal(g.map.width,1280*2.3);}assert.equal(D.cleanRules({speed:0,attackSpeed:90,mapSize:4}).speed,.1);assert.equal(D.cleanRules({attackSpeed:90}).attackSpeed,3);});
test('training never ends at five and reset restores saved position/cooldowns',()=>{const g=make({mode:'training'}),l=new Lab();l.startTraining(g);g.fighters[0].x=530;l.savePosition(g);for(let i=0;i<7;i++){g.finish(0,'test');tick(g,500);}assert.deepEqual(g.score,[0,0]);assert.equal(g.phase,'playing');g.fighters[0].x=600;g.fighters[0].dashCooldown=.7;l.resetTraining(g);assert.equal(g.fighters[0].x,530);assert.equal(g.fighters[0].dashCooldown,0);assert.equal(g.mode,'training');});
test('dummy movement/action/aim can be configured independently',()=>{const g=make({mode:'training'}),l=new Lab();l.startTraining(g);l.config={...l.config,move:'left',action:'attack',aim:'up'};let i=l.dummy(g);assert.equal(i.move,-1);assert.equal(i.aim,-Math.PI/2);assert(i.attack);assert(!l.dummy(g).attack);l.config.action='constant';g.setState(g.fighters[1],'parryRecovery',.4);i=l.dummy(g);assert(i.parry);assert.equal(g.fighters[1].parryCooldown,0);});
test('slash sweeps during active time; no damage shape remains in recovery',()=>{for(const kind of Object.keys(D.CLASSES)){const g=make({characters:[kind,'knight']}),f=g.fighters[0];active(g,0);f.stateTime=.002;const start=slash(f).points;f.stateTime=f.duration*.55;assert.notDeepEqual(slash(f).points,start);g.setState(f,'recovery',.4);assert.equal(slash(f).points.length,0);}});
function recordedDefeat(){const g=make(),l=new Lab();pair(g,115);g.fighters[1].aim=Math.PI;for(let frame=0;frame<40;frame++){const before=g.snapshot(),commands=[];for(let sub=0;sub<10;sub++){const ins=[cmd(),cmd({aim:Math.PI,attack:frame===6&&sub===0})];commands.push(ins);g.step(1/600,ins);}l.record(g,before,commands);if(g.phase==='roundEnd')break;}return{g,l};}
test('recorder restores original positions, phase timers and opponent inputs',()=>{const {g,l}=recordedDefeat();assert(g.fighters[0].dead);assert(l.clip.frames.length>10);l.open();l.seek(4);const before=l.clip.frames[4].before;l.tryAgain();assert.deepEqual(l.viewGame.fighters,before.fighters);l.speed=1;for(let i=0;i<50&&l.playing;i++)l.tick(1/60,cmd());assert(l.viewGame.fighters[0].dead);});
test('playable replay permits a different outcome and preserves the official match',()=>{const {g,l}=recordedDefeat(),official=g.snapshot();l.open();l.seek(0);l.tryAgain();l.speed=1;for(let i=0;i<90;i++)l.tick(1/60,cmd({move:-1}));assert(!l.viewGame.fighters[0].dead);assert.deepEqual(g.snapshot(),official);l.tryAgain(true);assert.deepEqual(l.viewGame.fighters,l.clip.frames[0].before.fighters);l.close();assert.equal(l.viewGame,null);});
test('recording is bounded at 2.5 seconds and retains a completed clip',()=>{const g=make(),l=new Lab();for(let i=0;i<200;i++){const b=g.snapshot();tick(g,10);l.record(g,b,Array.from({length:10},()=>[cmd(),cmd()]));}assert.equal(l.history.length,150);const b=g.snapshot();g.finish(1,'test');l.record(g,b,[]);const clip=l.clip;tick(g,800);assert.equal(l.clip,clip);});
console.log(passed+' V3.3 tests passed');
