const fs=require('node:fs'),path=require('node:path'),rd=f=>fs.readFileSync(path.join(__dirname,f),'utf8'),wr=(f,s)=>fs.writeFileSync(path.join(__dirname,f),s);
let s=rd('renderer.js').replace('shape=DuelCore.slash(f)','shape=DuelCore.slash(f,this.walls||[])');
s=s.replace("  if(shape.points.length){",`  this.slashTrails??=[[],[]];const trail=this.slashTrails[f.id];while(trail.length&&t-trail[0].time>.085)trail.shift();if(!this.reduced){for(const item of trail){c.globalAlpha=Math.max(0,1-(t-item.time)/.085)*.16;this.path(item.points.map(p=>[p.x,p.y]),null,color,1.4);}c.globalAlpha=1;}if(shape.points.length&&(!trail.length||t>trail[trail.length-1].time+.012))trail.push({points:shape.points.map(p=>({...p})),time:t});
  if(shape.points.length){`);
s=s.replace("gradient.addColorStop(.58,color)","gradient.addColorStop(.38,color)");
s=s.replace("c.fillRect(f.x-250,f.y-DuelCore.C.bodyCenter-250,500,500);c.restore();",`c.fillRect(f.x-250,f.y-DuelCore.body(f).center-250,500,500);c.globalAlpha=.9;const count=shape.points.length;for(let i=0;i<3;i++){const j=Math.floor((shape.progress*.65+i*.12+.12)*(count/2-1));if(shape.points[j]&&shape.points[j+1])this.line(shape.points[j],shape.points[j+1],'#ffffff',2.8-i*.6);}c.restore();`);
s=s.replaceAll('f.y-DuelCore.C.bodyCenter','f.y-DuelCore.body(f).center');
s=s.replace('render(game,effects,t){','render(game,effects,t){this.walls=game.map.walls||[];');
s=s.replace('this.previousBlades=[[],[]];this.actorHistory=[];','this.previousBlades=[[],[]];this.actorHistory=[];this.slashTrails=[[],[]];');
s=s.replace('this.platforms(game,t);for(const f', 'this.platforms(game,t);this.drawWalls(game);for(const f');
s=s.replace('for(const p of effects.particles||[])','if(this.debug)this.hitboxes(game);for(const p of effects.particles||[])');
s=s.replace(' drawPortrait(canvas,kind,side=0,color,time=0){',` drawWalls(game){const c=this.ctx,theme=DuelScenery.THEMES[game.mapId]||DuelScenery.THEMES.dojo;for(const w of game.map.walls||[]){c.fillStyle=theme.edge;c.fillRect(w.x,w.y,w.w,w.h);c.fillStyle=theme.surface;c.fillRect(w.x+4,w.y+4,w.w-8,w.h-4);this.line({x:w.x+3,y:w.y},{x:w.x+3,y:w.y+w.h},theme.top,3);for(let y=w.y+22;y<w.y+w.h;y+=30){this.line({x:w.x+5,y},{x:w.x+w.w-5,y},theme.detail,2);}c.fillStyle=theme.top;c.fillRect(w.x-3,w.y-3,w.w+6,5);}}
 hitboxes(game){const c=this.ctx;c.save();for(const f of game.fighters){if(f.dead)continue;const b=DuelCore.body(f);c.globalAlpha=.19;this.line({x:f.x,y:f.y-b.top},{x:f.x,y:f.y-b.bottom},'#55ddff',b.radius*2);c.globalAlpha=1;c.setLineDash([3,3]);this.line({x:f.x,y:f.y-b.top},{x:f.x,y:f.y-b.bottom},'#7af4ff',1);c.setLineDash([]);const shape=DuelCore.slash(f,game.map.walls);if(shape.points.length)this.path(shape.points.map(p=>[p.x,p.y]),null,'#ff654c',2);if(f.state==='parry'){const g=blade(f).guard;this.line(g.a,g.b,'#a6ff7b',4);}if(f.state==='kickActive')this.line({x:f.x+f.kickSide*18,y:f.y-b.center+12},{x:f.x+f.kickSide*56,y:f.y-b.center+12},'#ffaa55',18);c.font='10px monospace';c.fillStyle='#183e49';c.textAlign='center';c.fillText(f.state+' · '+Math.max(0,(f.duration-f.stateTime)*1000).toFixed(0)+' ms',f.x,f.y-b.top-27);}c.restore();}
 drawPortrait(canvas,kind,side=0,color,time=0){if(kind==='random'){const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);c.fillStyle=COLORS[color]?.hex||'#426b64';c.textAlign='center';c.font='70px Georgia';c.fillText('?',canvas.width/2,canvas.height*.66);return;}`);
wr('renderer.js',s);
s=rd('actors.js');
s=s.replace("  const death=",`  const low=clamp((f.slideRemaining||0)/.12,0,1);if(low){hip.x=lerp(hip.x,-side*3,low);hip.y=lerp(hip.y,-14,low);shoulder.x=lerp(shoulder.x,-side*15,low);shoulder.y=lerp(shoulder.y,-31,low);head.x=shoulder.x+side*3;head.y=lerp(head.y,-43,low);}if(f.state==='feintRecovery'){shoulder.x-=Math.cos(f.attackAim)*Math.sin(phase*Math.PI)*10;head.x=shoulder.x+side*2;}if(f.state==='kickActive'){hip.x+=f.kickSide*10;shoulder.x-=f.kickSide*5;}
  const death=`);
s=s.replace("  if(f.kind==='assassin'){this.ribbon",`  if(low){feet[0]={x:-side*24,y:-3};feet[1]={x:side*43,y:0};}if(f.wallJumpTime>0){feet[0]={x:-Math.sign(f.vx)*21,y:-23};feet[1]={x:Math.sign(f.vx)*25,y:-6};}if(['kickStartup','kickActive','kickRecovery'].includes(f.state)){const k=f.state==='kickStartup'?phase*.3:f.state==='kickActive'?1:Math.pow(1-phase,2);feet[1]={x:lerp(side*20,f.kickSide*62,k),y:lerp(-4,-65,k)};}
  if(f.kind==='assassin'){this.ribbon`);
wr('actors.js',s);
s=rd('scenery.js');const marker=' static sky(';s=s.replace(marker,` static tower(r,s,t,off){const c=r.ctx;this.sky(r,s);r.ellipse(990+off,180,80,80,'#eac895');this.hills(r,s,t,off);for(const x of[120,280,1000,1160]){r.path([[x+off,600],[x+off,170],[x+60+off,120],[x+110+off,170],[x+110+off,600]],'#46405766');for(let y=220;y<550;y+=80)r.path([[x+35+off,y+30],[x+35+off,y],[x+55+off,y-18],[x+75+off,y],[x+75+off,y+30]],'#262c4444');}for(const x of[574,706])r.line({x,y:0},{x,y:620},'#63584f55',2);r.path([[599,90],[606,52],[623,32],[657,32],[674,52],[681,90],[690,102],[590,102]],'#a78964');r.line({x:640,y:0},{x:640,y:32},'#47434e',4);r.ellipse(640,109,8,8,'#534957');this.mist(r,s.mist,.3);}
`+marker);
s=s.replace("if(game.mapId==='bamboo')", "if(game.mapId==='tower')this.tower(r,theme,time,offset);\n  else if(game.mapId==='bamboo')");
s=s.replace('const h=p.solid?130:20;',"const h=p.solid?130:20;if(p.wallTop)continue;if(p.motion){for(const x of[p.x+12,p.x+p.w-12])r.line({x,y:50},{x,y:p.y},'#4c485e88',2);r.line({x:p.x,y:p.y+12},{x:p.x+p.w,y:p.y+12},'#e2bc71',4);}");
s=s.replace('DuelScenery.THEMES=THEMES;',"THEMES.tower={tag:'O SINO E O VENTO',sky:['#34354f','#988095','#dfae88'],hills:['#8c7890','#736780','#5e5670'],surface:'#8e7770',side:'#625762',edge:'#353442',top:'#d9b689',detail:'#494151',mist:'#ac8d91',dark:false};\nDuelScenery.THEMES=THEMES;");wr('scenery.js',s);
s=rd('engine.js').replace('for(const w of walls)platforms.push({x:w.x,y:w.y,w:w.w,solid:true,wallTop:true});',"for(const w of walls){platforms.push({x:w.x,y:w.y,w:w.w,solid:true,wallTop:true});if(scale>1)for(let y=w.y+w.h-180;y>w.y+60;y-=180)platforms.push({x:Math.max(0,w.x-65),y,w:w.w+130,wallLedge:true});}");
s=s.replace("if(f.state==='stunned')angle=", "if(f.state==='feintRecovery')angle=f.attackAim-side*.9*(1-p);\n if(f.state==='stunned')angle=");wr('engine.js',s);
s=rd('app.js').replace("function onlineTick(dt){const s=onlineSession;","function onlineTick(dt){if(game.phase==='matchEnd')return;const s=onlineSession;").replace("&&lobby&&inMenu&&CHAR_CHOICES", "&&lobby&&(inMenu||game.phase==='matchEnd')&&CHAR_CHOICES").replace("&&seat===0&&inMenu&&lobby&&msg.revision", "&&seat===0&&(inMenu||game.phase==='matchEnd')&&lobby&&msg.revision");wr('app.js',s);
