(function(){
const $=id=>document.getElementById(id),{RULES,MAPS,CLASSES,COLORS,cleanRules}=DuelCore;
class DuelAdmin{
 constructor(hooks){this.hooks=hooks;this.testRoom=false;this.opened=false;const label=document.createElement('label');label.className='test-room-option';label.innerHTML='<input id="admin-test-room" type="checkbox"> Criar sala de testes com administração';$('online-actions').prepend(label);$('admin-test-room').onchange=e=>{this.testRoom=e.target.checked;hooks.changed();};const tag=document.createElement('span');tag.className='admin-banner';tag.textContent='EDIÇÃO ADMIN · CTRL + SHIFT + F10';document.querySelector('footer').prepend(tag);window.addEventListener('keydown',e=>{if(e.code==='F10'&&e.ctrlKey&&e.shiftKey){e.preventDefault();this.opened?this.close():this.open();}});$('admin-close').onclick=()=>this.close();$('admin-console').addEventListener('cancel',e=>{e.preventDefault();this.close();});$('admin-apply').onclick=()=>this.apply();$('admin-pause').onclick=()=>{this.resumeOnClose=false;this.send({action:'pause',paused:!hooks.get().paused});};$('admin-step').onclick=()=>{if(!hooks.get().paused){$('admin-status').textContent='Pause a simulação antes de avançar um quadro.';return;}this.send({action:'step'});};$('admin-refill').onclick=()=>this.send({action:'refill'});$('admin-reset').onclick=()=>this.send({action:'reset'});$('admin-defaults').onclick=()=>{this.draw(cleanRules());$('admin-status').textContent='Padrões carregados no formulário. Clique em Aplicar.';};}
 open(){const s=this.hooks.get();if(s.inMenu)return;if(!s.allowed){alert('O menu só controla partidas offline ou salas de teste que você criou e o oponente aceitou.');return;}this.resumeOnClose=!s.online&&!s.paused;if(this.resumeOnClose)this.hooks.apply({action:'pause',paused:true});this.opened=true;this.draw();this.hooks.clear();$('admin-status').textContent=s.online?'Sala de testes: comandos aplicados nos dois jogos no mesmo quadro.':'Laboratório local. A versão comum não inclui este menu.';$('admin-console').showModal();}
 close(){this.opened=false;$('admin-console').close();this.hooks.clear();if(this.resumeOnClose)this.hooks.apply({action:'pause',paused:false});this.resumeOnClose=false;}
 draw(rules){const g=this.hooks.get().game,parent=$('admin-fields');parent.replaceChildren();const grid=document.createElement('div');grid.className='admin-grid';parent.append(grid);const select=(id,name,choices,value)=>{const label=document.createElement('label');label.textContent=name;const el=document.createElement('select');el.id=id;for(const[k,v]of Object.entries(choices)){const op=document.createElement('option');op.value=k;op.textContent=v.name;el.append(op);}el.value=value;label.append(el);grid.append(label);};select('admin-map','Mapa',MAPS,g.mapId);for(let i=0;i<2;i++){select('admin-character-'+i,'Personagem '+(i+1),CLASSES,g.characters[i]);select('admin-color-'+i,'Cor '+(i+1),COLORS,g.colors[i]);}for(const[k,v]of Object.entries(RULES)){const label=document.createElement('label');label.textContent=v.name+(v.unit?' ('+v.unit+')':' (×)');const el=document.createElement('input');el.id='admin-rule-'+k;el.type='number';el.step='any';el.value=(rules||g.rules)[k];label.append(el);grid.append(label);}for(const[k,name]of[['airDash','Dash aéreo'],['specials','Especiais']]){const label=document.createElement('label');label.className='check';const el=document.createElement('input');el.type='checkbox';el.id='admin-rule-'+k;el.checked=(rules||g.rules)[k];label.append(el,document.createTextNode(' '+name));parent.append(label);}const text=document.createElement('p');text.textContent='Posições opcionais: deixe em branco para usar o início do mapa.';parent.append(text);const positions=document.createElement('div');positions.className='admin-grid';for(let i=0;i<2;i++)for(const axis of['x','y']){const l=document.createElement('label');l.textContent='Jogador '+(i+1)+' · '+axis.toUpperCase();const el=document.createElement('input');el.id='admin-pos-'+i+'-'+axis;el.type='number';el.step='any';el.placeholder=Math.round(g.fighters[i][axis]);l.append(el);positions.append(l);}parent.append(positions);}
 apply(){const rules={};for(const k of Object.keys(RULES)){const v=$('admin-rule-'+k).value,n=Number(v);if(v===''||!Number.isFinite(n)||n<0||['mapSize','attackSpeed'].includes(k)&&n<=0||k==='dashCount'&&(n<1||!Number.isInteger(n))){$('admin-status').textContent='Confira '+RULES[k].name+': use um número finito válido. Cargas precisam ser inteiras; mapa e ataque precisam ser maiores que zero.';return;}rules[k]=n;}for(const k of['airDash','specials'])rules[k]=$('admin-rule-'+k).checked;const colors=[0,1].map(i=>$('admin-color-'+i).value);if(colors[0]===colors[1]){$('admin-status').textContent='Os jogadores precisam ter cores diferentes.';return;}const positions=[0,1].map(i=>Object.fromEntries(['x','y'].filter(k=>$('admin-pos-'+i+'-'+k).value!=='').map(k=>[k,Number($('admin-pos-'+i+'-'+k).value)])));this.send({action:'apply',rules,mapId:$('admin-map').value,characters:[0,1].map(i=>$('admin-character-'+i).value),colors,positions});}
 send(change){const ok=this.hooks.apply(change);$('admin-status').textContent=ok?'Comando enviado. No online, aguarde a aplicação sincronizada.':'Há uma alteração pendente, ou a partida não permite esse comando.';return ok;}
}
window.DuelAdmin=DuelAdmin;
})();
