(function(root){
'use strict';
const SCALE=.9;
const C={scale:SCALE,bodyTop:121*SCALE,bodyBottom:25*SCALE,bodyCenter:79*SCALE,width:1280,height:720,ground:610,radius:17*SCALE,bladeWidth:3*SCALE,winningScore:5,deathY:890,roundPause:1.05};
const CLASSES={
 knight:{name:'Cavaleiro',weapon:'Espada',description:'Equilíbrio. Cortes precisos e recuperação confiável.',speed:310,startup:.19,active:.12,recovery:.32,reach:142,minRange:30,length:112,sweep:2.1,dashSpeed:990},
 lancer:{name:'Lanceiro',weapon:'Lança',description:'Controle de distância. Só a ponta fere; aproxime-se para vencê-lo.',speed:290,startup:.23,active:.12,recovery:.39,reach:222,minRange:157,length:194,sweep:0,dashSpeed:930},
 assassin:{name:'Assassino',weapon:'Adaga',description:'Mobilidade e velocidade. Precisa entrar muito perto.',speed:360,startup:.14,active:.105,recovery:.25,reach:92,minRange:28,length:62,sweep:2.2,dashSpeed:1080},
 swordsman:{name:'Espadachim',weapon:'Espada longa',description:'Duas mãos, arco amplo. O alcance cobra comprometimento.',speed:300,startup:.245,active:.14,recovery:.40,reach:187,minRange:34,length:153,sweep:2.55,dashSpeed:970},
 reaper:{name:'Ceifador',weapon:'Foice',description:'A lâmina curva envolve o rival. Dentro do arco há uma abertura.',speed:305,startup:.24,active:.14,recovery:.40,reach:208,minRange:116,length:156,sweep:2.55,dashSpeed:975}
};
for(const s of Object.values(CLASSES)){for(const k of ['reach','minRange','length'])s[k]*=SCALE;}
for(const s of Object.values(CLASSES))Object.assign(s,{parry:.15,parryRecovery:.4,parryCooldown:.55,dash:.14,dashRecovery:.075,dashCooldown:.80,stun:.49});
for(const st of Object.values(CLASSES))for(const key of['startup','active','recovery'])st[key]/=1.25;
const COLORS={jade:{name:'Jade',hex:'#367f75'},coral:{name:'Coral',hex:'#b75640'},indigo:{name:'Índigo',hex:'#5a64a7'},gold:{name:'Ouro',hex:'#af842e'},plum:{name:'Ameixa',hex:'#995879'},ice:{name:'Gelo',hex:'#5796b4'}};
Object.assign(COLORS,{ruby:{name:'Rubi',hex:'#b83f60'},teal:{name:'Turquesa',hex:'#168f99'},violet:{name:'Violeta',hex:'#8254ba'},orange:{name:'Âmbar',hex:'#c57528'},rose:{name:'Rosa',hex:'#bf7397'},olive:{name:'Oliva',hex:'#7b873d'},silver:{name:'Prata',hex:'#a4b1ba'},copper:{name:'Cobre',hex:'#996146'},navy:{name:'Safira',hex:'#315ead'},mint:{name:'Menta',hex:'#61ac86'}});
const RULES={attackSpeed:{name:'Velocidade de ataque',min:.1,max:3,step:.01},mapSize:{name:'Tamanho da arena',min:.5,max:3,step:.1},gravity:{name:'Gravidade',min:.1,max:5,step:.1},jump:{name:'Força do pulo',min:.1,max:5,step:.1},speed:{name:'Velocidade de movimento',min:.1,max:3,step:.01},dashDistance:{name:'Distância do dash',min:.1,max:5,step:.1},dashCount:{name:'Dashes consecutivos',min:1,max:5,step:1,unit:'cargas',default:1},dashRecovery:{name:'Recuperação do dash',min:0,max:2000,step:5,unit:'ms',default:75},dashCooldown:{name:'Recarga de cada dash',min:0,max:5000,step:10,unit:'ms',default:800},parryWindow:{name:'Duração do parry',min:50,max:2000,step:10,unit:'ms',default:400},parryRecovery:{name:'Recuperação do parry',min:0,max:3000,step:10,unit:'ms',default:400},stun:{name:'Atordoamento após parry',min:0,max:3000,step:10,unit:'ms',default:490},specialCooldown:{name:'Recarga do especial',min:.1,max:120,step:.1,unit:'s',default:15,unbounded:true}};for(const r of Object.values(RULES))r.numeric=true;
const DEFAULT_RULES=Object.fromEntries([...Object.entries(RULES).map(([k,v])=>[k,v.default??1]),['airDash',true],['specials',false]]);
const MAPS={
 dojo:{name:'Dojo elevado',description:'Chão seguro, plataformas e pilares para saltar pelas paredes.',platforms:[{x:40,y:610,w:1200,solid:true},{x:220,y:405,w:270},{x:790,y:405,w:270}],spawns:[{x:385,y:610},{x:895,y:610}]},
 bridge:{name:'Ponte quebrada',description:'Distância, saltos e vãos fatais. Não recue sem olhar.',platforms:[{x:55,y:590,w:360,solid:true},{x:490,y:525,w:300},{x:865,y:590,w:360,solid:true}],spawns:[{x:290,y:590},{x:990,y:590}]},
 ruins:{name:'Ruínas',description:'Rotas aéreas, paredes e um vão no centro. Cuidado ao recuar.',platforms:[{x:45,y:620,w:460,solid:true},{x:775,y:620,w:460,solid:true},{x:430,y:460,w:420},{x:90,y:400,w:200},{x:990,y:400,w:200},{x:510,y:265,w:260}],spawns:[{x:315,y:620},{x:965,y:620}]},
 bamboo:{name:'Bosque da Lua',description:'Bambu, lanternas e luar. Rotas laterais acima de um chão seguro.',platforms:[{x:40,y:615,w:1200,solid:true},{x:130,y:425,w:235},{x:915,y:425,w:235},{x:420,y:290,w:440}],spawns:[{x:385,y:615},{x:895,y:615}]},
 frost:{name:'Fortaleza Nevada',description:'Torres congeladas e um vão central. Avance pelos bastiões.',platforms:[{x:40,y:610,w:410,solid:true},{x:830,y:610,w:410,solid:true},{x:435,y:450,w:410},{x:110,y:405,w:220},{x:950,y:405,w:220}],spawns:[{x:300,y:610},{x:980,y:610}]},
 forge:{name:'Forja de Cinzas',description:'Correntes sobre lava. Dispute a ilha e as passarelas centrais.',platforms:[{x:45,y:590,w:290,solid:true},{x:945,y:590,w:290,solid:true},{x:485,y:605,w:310,solid:true},{x:305,y:420,w:245},{x:730,y:420,w:245}],spawns:[{x:235,y:590},{x:1045,y:590}]}
};
MAPS.dojo.walls=[{x:55,y:280,w:26,h:330},{x:1199,y:280,w:26,h:330},{x:190,y:390,w:26,h:220},{x:1064,y:390,w:26,h:220}];
MAPS.ruins.walls=[{x:65,y:315,w:28,h:305},{x:1187,y:315,w:28,h:305},{x:480,y:500,w:25,h:120},{x:775,y:500,w:25,h:120}];
MAPS.tower={name:'Torre do Sino',description:'Paredes, pilares e um elevador central. O terreno também se move.',platforms:[{x:50,y:630,w:1180,solid:true},{x:180,y:430,w:240},{x:860,y:430,w:240},{x:470,y:240,w:340},{x:540,y:450,w:200,motion:{y:115,period:5.6}}],walls:[{x:70,y:165,w:35,h:465},{x:1175,y:165,w:35,h:465},{x:340,y:450,w:30,h:180},{x:910,y:450,w:30,h:180}],spawns:[{x:470,y:630},{x:810,y:630}]};
const DIFFICULTIES={easy:{name:'Fácil',description:'Mais hesitação e erros. Reação de 260–400 ms.',reaction:[.26,.40],parry:.24,attack:.48},normal:{name:'Normal',description:'Lê distância e aberturas, mas pode ser enganada.',reaction:[.16,.26],parry:.57,attack:.72},adaptive:{name:'Adaptativo',description:'Ajusta defesa, pressão e fintas aos seus hábitos nesta partida.',reaction:[.15,.25],parry:.53,attack:.68},impossible:{name:'Impossível',description:'Prevê golpes e reage quase instantaneamente. Mesmas regras físicas.',reaction:[.005,.018],parry:1,attack:.96}};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,stats=f=>{const base=CLASSES[typeof f==='string'?f:f.kind]||CLASSES.knight,scale=typeof f==='object'&&f.kind==='reaper'?(f.ultMode==='reaperBoost'?1.4:f.ultMode==='reaperWeak'?.6:1):1;return scale===1?base:{...base,reach:base.reach*scale,minRange:base.minRange*scale,length:base.length*scale,weaponScale:scale};};
function cleanRules(r={},experimental=false){const o={};for(const[k,v]of Object.entries(RULES)){let n=Number.isFinite(r[k])?r[k]:DEFAULT_RULES[k];n=experimental?Math.max(k==='dashCount'?1:['attackSpeed','mapSize'].includes(k)?.001:0,n):Math.max(v.min,v.unbounded?n:Math.min(v.max,n));o[k]=k==='dashCount'?Math.floor(n):n;}o.airDash=r.airDash!==false;o.specials=r.specials===true;return o;}
const neutral=()=>({move:0,aim:0,jump:false,jumpHeld:false,down:false,attack:false,parry:false,dash:false,kick:false,special:false});
function nearest(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1),0,1);return{x:a.x+dx*t,y:a.y+dy*t};}
const pointSegment=(p,a,b)=>{const n=nearest(p,a,b);return Math.hypot(p.x-n.x,p.y-n.y);};
function segmentDistance(a,b,c,d){const cross=(p,q,r)=>(q.x-p.x)*(r.y-p.y)-(q.y-p.y)*(r.x-p.x),v1=cross(a,b,c),v2=cross(a,b,d),v3=cross(c,d,a),v4=cross(c,d,b);if(v1*v2<0&&v3*v4<0)return 0;return Math.min(pointSegment(a,c,d),pointSegment(b,c,d),pointSegment(c,a,b),pointSegment(d,a,b));}
function guardSector(angle,grounded){const s=Math.sin(angle);return s<-.7071?'high':s>.7071&&!grounded?'low':'normal';}
// Scale both axes of the arena. Large layouts receive intermediate stepping stones
// along existing routes so increasing space never removes the basic jump route.
function makeMap(id,scale=1){const base=MAPS[id]||MAPS.dojo,platforms=base.platforms.map(p=>({...p,x:p.x*scale,y:p.y*scale,w:p.w*scale}));
 if(scale>1){const original=[...platforms];for(let i=0;i<original.length;i++)for(let j=i+1;j<original.length;j++){const a=original[i],b=original[j],gap=Math.max(0,Math.max(a.x,b.x)-Math.min(a.x+a.w,b.x+b.w)),rise=Math.abs(a.y-b.y);if(rise<1||rise>240*scale||gap>150*scale||rise<=205&&gap<=180)continue;
  const left=Math.max(a.x,b.x),right=Math.min(a.x+a.w,b.x+b.w),x=right>=left?(left+right)/2:(a.x<b.x?(a.x+a.w+b.x)/2:(b.x+b.w+a.x)/2),steps=Math.min(64,Math.max(Math.ceil(rise/190),Math.ceil(gap/180)));
  for(let n=1;n<steps;n++){const y=lerp(a.y,b.y,n/steps),w=110;if(!platforms.some(p=>Math.abs(p.y-y)<55&&x>=p.x-25&&x<=p.x+p.w+25))platforms.push({x:x-w/2,y,w,step:true});}
 }}
 const walls=(base.walls||[]).map(w=>({x:w.x*scale,y:w.y*scale,w:w.w*scale,h:w.h*scale}));for(const w of walls){platforms.push({x:w.x,y:w.y,w:w.w,solid:true,wallTop:true});if(scale>1)for(let y=w.y+w.h-180;y>w.y+60;y-=Math.max(180,(w.h-240)/64))platforms.push({x:Math.max(0,w.x-65),y,w:w.w+130,wallLedge:true});}for(const p of platforms){p.baseX=p.x;p.baseY=p.y;if(p.motion)p.motion={...p.motion,y:p.motion.y*scale};}
 return{...base,walls,platforms,spawns:base.spawns.map(p=>({x:p.x*scale,y:p.y*scale})),width:C.width*scale,height:C.height*scale,deathY:C.deathY*scale,scale};
}
function pointInPolygon(p,poly){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a.y>p.y)!==(b.y>p.y)&&p.x<(b.x-a.x)*(p.y-a.y)/(b.y-a.y)+a.x)inside=!inside;}return inside;}
function polygonSegment(poly,a,b,r=0){if(!poly.length)return false;if(pointInPolygon(a,poly)||pointInPolygon(b,poly))return true;return poly.some((p,i)=>segmentDistance(p,poly[(i+1)%poly.length],a,b)<=r);}
function polygonsIntersect(a,b){return a.length&&b.length&&(pointInPolygon(a[0],b)||pointInPolygon(b[0],a)||a.some((p,i)=>polygonSegment(b,p,a[(i+1)%a.length])));}
// The same polygon is filled by the renderer and used by hit, guard and clash tests.
// No separate enlarged hitbox and no damage from the weapon model or its handle.
function body(f){const low=clamp((f.slideRemaining||0)/.12,0,1);return{top:lerp(C.bodyTop,44,low),bottom:lerp(C.bodyBottom,13,low),radius:lerp(C.radius,11,low),center:lerp(C.bodyCenter,27,low)};}
function clipPlane(poly,key,edge,sign){const out=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],da=(a[key]-edge)*sign,db=(b[key]-edge)*sign;if(da>=0)out.push(a);if((da>=0)!==(db>=0)){const t=da/(da-db);out.push({x:lerp(a.x,b.x,t),y:lerp(a.y,b.y,t)});}}return out;}
// Clip rays at physical walls; both rendering and collisions use this contour.
function wallFraction(a,b,w){let lo=0,hi=1;for(const [key,min,max]of[['x',w.x,w.x+w.w],['y',w.y,w.y+w.h]]){const d=b[key]-a[key];if(Math.abs(d)<1e-9){if(a[key]<min||a[key]>max)return 1;continue;}let t=(min-a[key])/d,u=(max-a[key])/d;if(t>u)[t,u]=[u,t];lo=Math.max(lo,t);hi=Math.min(hi,u);if(lo>hi)return 1;}return lo;}
function wallContour(poly,origin,walls,reach){const nearby=walls.filter(w=>Math.hypot(origin.x-clamp(origin.x,w.x,w.x+w.w),origin.y-clamp(origin.y,w.y,w.y+w.h))<=reach);if(!nearby.length)return poly;const rays=nearby.flatMap(w=>[[w.x,w.y],[w.x+w.w,w.y],[w.x,w.y+w.h],[w.x+w.w,w.y+w.h]]).map(([x,y])=>Math.atan2(y-origin.y,x-origin.x));const out=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],dx=b.x-a.x,dy=b.y-a.y,ts=[0];for(const angle of rays)for(const offset of[-1e-6,0,1e-6]){const rx=Math.cos(angle+offset),ry=Math.sin(angle+offset),cross=dx*ry-dy*rx;if(Math.abs(cross)<1e-8)continue;const t=((origin.x-a.x)*ry-(origin.y-a.y)*rx)/cross;if(t>0&&t<1&&(a.x+t*dx-origin.x)*rx+(a.y+t*dy-origin.y)*ry>0)ts.push(t);}ts.sort((x,y)=>x-y);for(const t of ts){const p={x:a.x+dx*t,y:a.y+dy*t},hit=Math.min(1,...nearby.map(w=>wallFraction(origin,p,w)));out.push({x:lerp(origin.x,p.x,hit),y:lerp(origin.y,p.y,hit)});}}return out;}
function slash(f,walls=[]){if(!['active','ultCharge'].includes(f.state)||f.dead)return{points:[]};const s=stats(f),aim=f.attackAim,origin={x:f.x,y:f.y-body(f).center},at=(x,y)=>({x:origin.x+Math.cos(aim)*x-Math.sin(aim)*y,y:origin.y+Math.sin(aim)*x+Math.cos(aim)*y});let points=[];
 const progress=clamp((f.state==='ultCharge'?.5:f.stateTime/Math.max(.001,f.duration)),0,1),sweep=lerp(-.28,.28,progress)*(Math.cos(aim)>=0?1:-1);
 if(f.kind==='lancer'){const lo=s.minRange,hi=lerp(s.reach*.82,s.reach,Math.sin(progress*Math.PI));points=[[lo,0],[lo+12,-5*SCALE],[hi-18,-10*SCALE],[hi,0],[hi-18,10*SCALE],[lo+12,5*SCALE]].map(p=>at(...p));}
 else{const steps=18,arc=f.kind==='reaper'?1.2:f.kind==='swordsman'?1.12:f.kind==='assassin'?.8:.95,outer=[],inner=[];for(let i=0;i<=steps;i++){const t=i/steps,a=lerp(-arc,arc,t)*(.35+.65*Math.sin(progress*Math.PI))+lerp(-arc*.6,arc*.6,progress)*(Math.cos(aim)>=0?1:-1),r=s.reach*(.83+.17*Math.sin(t*Math.PI)),thickness=(s.reach-s.minRange)*Math.pow(Math.sin(t*Math.PI),.8)*(.55+.45*Math.sin(progress*Math.PI));outer.push(at(Math.cos(a)*r,Math.sin(a)*r));inner.push(at(Math.cos(a)*(r-thickness),Math.sin(a)*(r-thickness)));}points=[...outer,...inner.reverse()];}
 points=wallContour(points,origin,walls,s.reach);return{points,origin,aim,progress};
}
function blade(f){
 const s=stats(f),p=clamp(f.stateTime/Math.max(.001,f.duration),0,1),attack=['startup','active','recovery','ultWindup','ultCharge','throwWindup'].includes(f.state),aim=attack?f.attackAim:f.aim,side=Math.cos(aim)>=0?1:-1;
 let angle=aim+(f.kind==='assassin'?.45:f.kind==='reaper'?-.85:f.kind==='swordsman'?-.7:-.45)*side,extend=0,offset=24*SCALE,start=12*SCALE,end=s.length;
 if(s.sweep){if(f.state==='startup')angle=aim-side*s.sweep*.48*Math.sin(p*Math.PI/2);else if(f.state==='active')angle=aim+side*s.sweep*.46;else if(f.state==='recovery')angle=aim+side*lerp(s.sweep*.46,-.18,1-Math.pow(1-p,3));}
 else{angle=['startup','active','recovery','ultWindup','ultCharge'].includes(f.state)?aim:aim-.35*side;if(f.state==='startup')extend=-20*SCALE*p;else if(f.state==='active')extend=18*SCALE;else if(f.state==='recovery')extend=-20*SCALE*(1-p);start=s.length-44*SCALE;}
 if(f.state==='parry'){const ga=f.guard==='high'?-Math.PI/2:f.guard==='low'?Math.PI/2:(f.guardFacing>0?0:Math.PI);angle=ga+Math.PI/2;offset=0;}
 if(f.state==='feintRecovery')angle=f.attackAim-side*.9*(1-p);
 if(f.state==='stunned')angle=aim+side*1.2;
 const hand={x:f.x+Math.cos(aim)*(offset+extend),y:f.y-body(f).center+Math.sin(aim)*(offset+extend)};
 if(f.state==='parry'){const ga=f.guard==='high'?-Math.PI/2:f.guard==='low'?Math.PI/2:(f.guardFacing>0?0:Math.PI);hand.x=f.x+Math.cos(ga)*37*SCALE-Math.cos(angle)*s.length*.33;hand.y=f.y-body(f).center+Math.sin(ga)*48*SCALE-Math.sin(angle)*s.length*.33;}
 const at=(n,l=0)=>({x:hand.x+Math.cos(angle)*n-Math.sin(angle)*l,y:hand.y+Math.sin(angle)*n+Math.cos(angle)*l});
 let segments=[{a:at(start),b:at(end)}],shaft=null;
 if(f.kind==='lancer')shaft={a:at(-45*SCALE),b:at(start)};
 if(f.kind==='reaper'){
  shaft={a:at(-34*SCALE),b:at(s.length)};const pts=[[139,-4],[167,7],[174,29],[166,53],[145,73],[119,84]].map(p=>at(p[0]*SCALE*(s.weaponScale||1),p[1]*SCALE*(s.weaponScale||1)));segments=pts.slice(1).map((p,i)=>({a:pts[i],b:p}));
 }
 return{hand,angle,a:segments[0].a,b:segments[segments.length-1].b,segments,shaft,guard:{a:at(-12*SCALE),b:at(Math.min(120*SCALE,s.length))}};
}
function makeFighter(id,kind,color,spawn){return{id,kind,color,...spawn,vx:0,vy:0,facing:id?-1:1,aim:id?Math.PI:0,attackAim:0,grounded:true,platform:-1,coyote:.085,jumpBuffer:0,jumping:false,airUsed:false,dropTimer:0,move:0,state:'idle',stateTime:0,duration:0,dead:false,deathTime:0,dashCooldown:0,parryCooldown:0,dashX:0,dashY:0,dashRemaining:0,slideRemaining:0,wallSide:0,wallId:-1,lastWall:-1,wallLock:0,wallJumpTime:0,feintCooldown:0,kickCooldown:0,kickHit:false,queued:null,attackId:0,attackHit:false,guard:'normal',guardFacing:id?-1:1,anim:0,landing:0};}
class Game{
 resetSpecial(f){f.specialCharge=0;f.ultMode='';f.ultTime=0;f.parryLock=0;f.breakAttackId=0;f.dagger=null;f.ultSide=f.facing;}
 special(id){const f=this.fighters[id];if(!this.rules.specials||!this.canAct(f)||f.specialCharge+1e-6<this.rules.specialCooldown||f.ultMode||f.parryLock>0)return false;f.specialCharge=0;f.ultSide=f.facing;f.attackAim=f.aim;f.attackHit=false;
  if(f.kind==='knight'){f.ultMode='shield';f.ultTime=10;}
  if(f.kind==='reaper'){f.ultMode='reaperBoost';f.ultTime=10;}
  if(f.kind==='swordsman')f.ultMode='edge';
  if(f.kind==='lancer'){f.ultMode='charge';f.attackAim=f.ultSide>0?0:Math.PI;this.setState(f,'ultWindup',.3);}
  if(f.kind==='assassin'){f.ultMode='throw';this.setState(f,'throwWindup',.18);}
  this.emit('special',{id,kind:f.kind,x:f.x,y:f.y-body(f).center});return true;
 }
 endEdge(f){if(f.ultMode==='edgeStrike'){f.ultMode='';f.parryLock=10;f.breakAttackId=0;this.emit('specialEnd',{id:f.id});}}
 stopCharge(f){if(f.state!=='ultCharge')return;f.ultMode='';f.vx=0;this.setState(f,'ultRecovery',.4);this.emit('chargeStop',{id:f.id,x:f.x,y:f.y-body(f).center});}
 absorb(f,a){if(f.ultMode!=='shield')return false;f.ultMode='';f.ultTime=0;f.parryLock=10;if(a)a.attackHit=true;this.hitstop=.07;this.emit('shieldBreak',{id:f.id,x:f.x,y:f.y-body(f).center});return true;}
 lethal(a,d,reason){if(d.dead||this.absorb(d,a))return false;d.dead=true;d.deathTime=0;this.setState(d,'dead');this.finish(a.id,reason,{x:d.x,y:d.y-body(d).center});return true;}
 tickSpecial(f,dt){if(f.dead)return;f.parryLock=Math.max(0,(f.parryLock||0)-dt);if(f.ultTime>0){f.ultTime=Math.max(0,f.ultTime-dt);if(!f.ultTime){if(f.ultMode==='shield'){f.ultMode='';f.parryLock=10;}else if(f.ultMode==='reaperBoost'){f.ultMode='reaperWeak';f.ultTime=10;}else if(f.ultMode==='reaperWeak')f.ultMode='';this.emit('specialEnd',{id:f.id});}}
  if(this.rules.specials&&!f.ultMode&&f.parryLock<=0)f.specialCharge=Math.min(this.rules.specialCooldown,(f.specialCharge||0)+dt);
 }
 daggerPoint(from,to){const fraction=Math.min(1,...this.map.walls.map(w=>wallFraction(from,to,w))),length=Math.hypot(to.x-from.x,to.y-from.y),t=fraction<1?Math.max(0,fraction-1.1/(length||1)):1;return{x:lerp(from.x,to.x,t),y:lerp(from.y,to.y,t),blocked:fraction<1};}
 daggerSafe(x,y){const points=this.map.platforms.map(p=>({x:clamp(x,p.x+Math.min(8,p.w/2),p.x+p.w-Math.min(8,p.w/2)),y:p.y-5})).filter(p=>!this.map.walls.some(w=>p.x>=w.x&&p.x<=w.x+w.w&&p.y>=w.y&&p.y<=w.y+w.h));points.sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y));return points[0]||{x:this.map.spawns[0].x,y:this.map.spawns[0].y-5};}
 throwDagger(f){const a=f.attackAim,from={x:f.x,y:f.y-body(f).center},p=this.daggerPoint(from,{x:from.x+Math.cos(a)*34,y:from.y+Math.sin(a)*34});f.ultMode='unarmed';f.dagger={x:p.x,y:p.y,vx:p.blocked?0:Math.cos(a)*1350,vy:p.blocked?40:Math.sin(a)*1350,mode:p.blocked?'dropped':'flying',time:0,safe:this.daggerSafe(f.x,f.y),pickup:.25};this.setState(f,'ultRecovery',.24);this.emit('daggerThrow',{id:f.id,x:f.dagger.x,y:f.dagger.y});}
 updateDaggers(dt){for(const owner of this.fighters){const p=owner.dagger;if(!p||owner.dead)continue;const d=this.fighters[1-owner.id];p.time+=dt;p.pickup=Math.max(0,p.pickup-dt);if(p.mode==='lost'){if(p.time>=2){Object.assign(p,{...p.safe,vx:0,vy:0,mode:'dropped',time:0,pickup:.2});}continue;}
   const from={x:p.x,y:p.y};if(p.mode==='dropped')p.vy+=1980*this.rules.gravity*dt;let to=this.daggerPoint(from,{x:p.x+p.vx*dt,y:p.y+p.vy*dt});if(to.blocked){p.vx=0;p.vy=40;p.mode='dropped';}
   if(p.mode==='flying'&&!d.dead){const db=body(d),guard=blade(d).guard,hit=segmentDistance(from,to,{x:d.x,y:d.y-db.top},{x:d.x,y:d.y-db.bottom})<=db.radius+5,guardTouch=d.state==='parry'&&segmentDistance(from,to,guard.a,guard.b)<=8,angle=Math.atan2(from.y-(d.y-db.center),from.x-d.x),valid=d.state==='parry'&&d.guard===guardSector(angle,false)&&(d.guard!=='normal'||Math.sign(from.x-d.x)===d.guardFacing);
    if((hit||guardTouch)&&valid){p.mode='dropped';to=this.daggerPoint({x:d.x,y:d.y-db.center},{x:d.x+d.guardFacing*22,y:d.y-db.center});p.vx=to.blocked?0:d.guardFacing*65;p.vy=-110;p.pickup=.2;this.setState(d,'idle');d.parryCooldown=Math.min(d.parryCooldown,.18);this.hitstop=.07;this.emit('parry',{id:d.id,x:to.x,y:to.y,projectile:true});}
    else if(hit){if(this.absorb(d)){p.mode='dropped';p.vx=0;p.vy=30;}else{this.lethal(owner,d,'A adaga encontrou uma abertura.');}}
   }
   p.x=to.x;p.y=to.y;const supports=this.map.platforms.filter(q=>p.x>=q.x&&p.x<=q.x+q.w&&q.y>=p.y-6).sort((a,b)=>a.y-b.y);if(supports.length)p.safe={x:p.x,y:supports[0].y-5};
   if(p.mode==='dropped'&&p.vy>=0){const q=this.map.platforms.find(q=>p.x>=q.x&&p.x<=q.x+q.w&&from.y<=q.y+5&&p.y>=q.y-5);if(q){p.y=q.y-5;p.vy=0;p.vx=0;p.safe={x:p.x,y:p.y};}}
   if(p.x<0||p.x>this.map.width||p.y>this.map.deathY||p.mode==='flying'&&p.time>3){p.mode='lost';p.time=0;}
   if(p.mode==='dropped'&&p.pickup<=0&&Math.abs(owner.x-p.x)<29&&p.y>=owner.y-body(owner).top-15&&p.y<=owner.y+12){owner.dagger=null;owner.ultMode='';this.emit('daggerPickup',{id:owner.id,x:owner.x,y:owner.y});}
  }}
 adminApply(change){const score=[...this.score],round=this.round;if(change.action==='refill'){for(const f of this.fighters){f.dashCharges=this.rules.dashCount;f.dashCooldown=0;f.parryCooldown=0;f.airDashes=0;this.resetSpecial(f);f.specialCharge=this.rules.specialCooldown;}return;}
  const options={mode:this.mode,ai:this.aiEnabled,difficulty:this.difficulty,characters:change.characters||this.characters,colors:change.colors||this.colors,mapId:change.mapId||this.mapId,rules:change.rules||this.rules,experimental:true};this.start(options);this.score=score;this.round=round;if(Array.isArray(change.positions))for(let i=0;i<2;i++)for(const k of['x','y'])if(Number.isFinite(change.positions[i]?.[k])){this.fighters[i][k]=change.positions[i][k];this.fighters[i].grounded=false;this.fighters[i].platform=-1;}this.emit('adminReset');
 }

 constructor(o={}){this.random=o.random||Math.random;this.mode='pve';this.difficulty='normal';this.characters=['knight','knight'];this.colors=['jade','coral'];this.mapId='dojo';this.rules=cleanRules();this.configure(o);this.events=[];this.time=0;this.round=1;this.score=[0,0];this.phase='title';this.hitstop=0;this.roundTimer=0;this.attackCounter=0;this.lastReason='';this.fallTimer=0;this.habits={attacks:0,parries:0,whiffs:0,jumps:0,retreat:0};this.resetFighters();}
 configure(o={}){if(['pve','local','online','training'].includes(o.mode))this.mode=o.mode;if(DIFFICULTIES[o.difficulty])this.difficulty=o.difficulty;if(o.characters)this.characters=[0,1].map(i=>CLASSES[o.characters[i]]?o.characters[i]:'knight');if(o.colors)this.colors=[0,1].map(i=>COLORS[o.colors[i]]?o.colors[i]:(i?'coral':'jade'));if(this.colors[0]===this.colors[1])this.colors[1]=Object.keys(COLORS).find(c=>c!==this.colors[0]);if(MAPS[o.mapId])this.mapId=o.mapId;if(typeof o.experimental==='boolean')this.experimental=o.experimental;if(o.rules)this.rules=cleanRules(o.rules,this.experimental);this.aiEnabled=typeof o.ai==='boolean'?o.ai:this.mode==='pve';this.map=makeMap(this.mapId,this.rules.mapSize);this.routeCache=new Map();}
 resetFighters(){this.fighters=[0,1].map(i=>makeFighter(i,this.characters[i],this.colors[i],this.map.spawns[i]));for(const f of this.fighters){this.resetSpecial(f);f.dashCharges=this.rules.dashCount;f.airDashes=0;}for(const f of this.fighters)f.platform=this.map.platforms.findIndex(p=>f.x>=p.x&&f.x<=p.x+p.w&&f.y===p.y);this.ai={timer:.3,intent:0,seen:0,reaction:-1,answer:0,attackDelay:.5,jumpDelay:.6,bait:false,navTarget:-1};this.fallTimer=0;}
 start(o){if(o)this.configure(o);this.time=0;this.round=1;this.score=[0,0];this.phase='playing';this.hitstop=0;this.roundTimer=0;this.attackCounter=0;this.lastReason='';this.habits={attacks:0,parries:0,whiffs:0,jumps:0,retreat:0};this.events=[];this.resetFighters();this.emit('start');}
 emit(type,data={}){this.events.push({type,...data});}
 between(a,b){return lerp(a,b,this.random());}
 setState(f,state,duration=0){if(f.state==='active'&&state!=='active')this.endEdge(f);if(['ultCharge','ultWindup','throwWindup'].includes(f.state)&&['stunned','clash','pushed','dead'].includes(state))f.ultMode='';f.state=state;f.stateTime=0;f.duration=duration;if(duration===0&&state==='parry'){f.state='parryRecovery';f.duration=this.rules.parryRecovery/1000;}if(f.duration===0&&['recovery','parryRecovery','dashRecovery','slideRecovery','stunned'].includes(f.state))f.state='idle';if(['stunned','clash','pushed','dead'].includes(state)){f.dashRemaining=0;f.slideRemaining=0;f.queued=null;}}
 canAct(f){return!f.dead&&f.state==='idle'&&this.phase==='playing';}
 attack(id){const f=this.fighters[id];if(f.ultMode==='unarmed')return false;if(!this.canAct(f)&&!(['dash','slide'].includes(f.state)&&!f.dead&&this.phase==='playing'))return false;f.attackAim=f.aim;f.attackId=++this.attackCounter;f.attackHit=false;this.setState(f,'startup',stats(f).startup/this.rules.attackSpeed);if(!id)this.habits.attacks++;this.emit('windup',{id});return true;}
 parry(id){const f=this.fighters[id],s=stats(f);if(f.state==='startup'||f.state==='active'&&f.stateTime<=.06&&!f.attackHit)return this.feint(id);if(!this.canAct(f)||f.parryCooldown>0||f.parryLock>0)return false;f.guard=guardSector(f.aim,f.grounded);f.guardFacing=f.facing;this.setState(f,'parry',this.rules.parryWindow/1000);f.parryCooldown=(this.rules.parryWindow+this.rules.parryRecovery)/1000;if(!id)this.habits.parries++;this.emit('guard',{id});return true;}
 feint(id){const f=this.fighters[id];if(f.dead||!(f.state==='startup'||f.state==='active'&&f.stateTime<=.06&&!f.attackHit)||f.feintCooldown>0)return false;this.setState(f,'feintRecovery',.15);f.feintCooldown=.45;f.queued=null;this.emit('feint',{id});return true;}
 kick(id){const f=this.fighters[id];if(!this.canAct(f)||f.kickCooldown>0)return false;f.kickHit=false;f.kickSide=f.facing;f.kickCooldown=.7;this.setState(f,'kickStartup',.16);this.emit('kickWindup',{id});return true;}
 command(id,action,inp){const f=this.fighters[id],ok=action==='dash'?this.dash(id,inp.move,inp.down):this[action](id);if(ok){f.queued=null;return true;}if(['recovery','parryRecovery','dashRecovery','slideRecovery','kickRecovery','feintRecovery','stunned','clash','pushed','dash','slide'].includes(f.state)&&f.duration-f.stateTime<=.08)f.queued={action,ttl:.085,move:inp.move,down:inp.down,aim:inp.aim};return false;}
 dash(id,move=0,down=false){const f=this.fighters[id],s=stats(f);if(!(this.canAct(f)||['dashRecovery','slideRecovery'].includes(f.state)&&f.dashCharges>0)||f.dashRemaining>0||f.dashCharges<1||(!f.grounded&&(!this.rules.airDash||f.airDashes>=this.rules.dashCount)))return false;
  let x=Math.cos(f.aim),y=Math.sin(f.aim);if(Math.abs(move)>.1){const slope=Math.min(Math.PI/3,Math.asin(Math.abs(y)));x=Math.sign(move)*Math.cos(slope);y=Math.sign(y)*Math.sin(slope);}if(f.grounded&&y>0){x=Math.sign(x)||f.facing;y=0;}
  const slide=down&&f.grounded;if(slide){x=Math.sign(move)||f.facing;y=0;}f.dashX=x;f.dashY=y;f.dashRemaining=slide?.28:s.dash;f.slideRemaining=slide?.42:0;f.airUsed=true;f.airDashes++;f.dashCharges--;if(f.dashCooldown<=0)f.dashCooldown=this.rules.dashCooldown/1000;this.setState(f,slide?'slide':'dash',f.dashRemaining);this.emit(slide?'slide':'dash',{id});return true;
 }
 tickState(f,dt){this.tickSpecial(f,dt);for(const k of['slideRemaining','wallLock','wallJumpTime','feintCooldown','kickCooldown'])f[k]=Math.max(0,(f[k]||0)-dt);if(f.queued){f.queued.ttl-=dt;if(f.queued.ttl<=0)f.queued=null;}if(f.dashCharges<this.rules.dashCount){f.dashCooldown=Math.max(0,f.dashCooldown-dt);if(f.dashCooldown<=0){f.dashCharges=this.rules.dashCooldown<=0?this.rules.dashCount:Math.min(this.rules.dashCount,f.dashCharges+1);f.dashCooldown=f.dashCharges<this.rules.dashCount?this.rules.dashCooldown/1000:0;}}else f.dashCooldown=0;f.parryCooldown=Math.max(0,f.parryCooldown-dt);f.dropTimer=Math.max(0,f.dropTimer-dt);f.landing=Math.max(0,f.landing-dt);f.stateTime+=dt;
  if(f.dead){f.deathTime+=dt;return;}
  if(f.dashRemaining>0){f.dashRemaining=Math.max(0,f.dashRemaining-dt);if(!f.dashRemaining){f.vx*=.45;f.vy*=.55;if(['dash','slide'].includes(f.state))this.setState(f,f.dashCharges>0?'idle':f.state==='slide'?'slideRecovery':'dashRecovery',f.dashCharges>0?0:this.rules.dashRecovery/1000);}}
  if(f.duration&&f.stateTime>=f.duration){const s=stats(f),old=f.state;if(old==='ultWindup'){this.setState(f,'ultCharge',1e6);f.attackId=++this.attackCounter;f.attackHit=false;this.emit('chargeStart',{id:f.id});}else if(old==='throwWindup'){this.throwDagger(f);}else if(old==='kickStartup'){this.setState(f,'kickActive',.10);}else if(old==='kickActive'){this.setState(f,'kickRecovery',.27);}else if(old==='startup'){this.setState(f,'active',s.active/this.rules.attackSpeed);if(f.ultMode==='edge'){f.ultMode='edgeStrike';f.breakAttackId=f.attackId;}this.emit('swing',{id:f.id});}else if(old==='active'){this.setState(f,'recovery',s.recovery/this.rules.attackSpeed);if(!f.attackHit){if(!f.id)this.habits.whiffs++;this.emit('whiff',{id:f.id});}}else if(old==='parry'){this.setState(f,'parryRecovery',this.rules.parryRecovery/1000);this.emit('parryMiss',{id:f.id});}else if(old==='dash'){this.setState(f,'dashRecovery',this.rules.dashRecovery/1000);}else this.setState(f,'idle');}
 }
 moveFighter(f,inp,dt){if(f.dead)return;const s=stats(f),r=this.rules,oldX=f.x,wasGrounded=f.grounded;if(f.grounded&&f.platform>=0){const platform=this.map.platforms[f.platform];if(platform?.motion){f.x+=platform.dx||0;f.y+=platform.dy||0;}}const oldY=f.y;
  f.aim=Number.isFinite(inp.aim)?inp.aim:f.aim;f.facing=Math.cos(f.aim)>=0?1:-1;f.move=clamp(inp.move||0,-1,1);f.coyote=f.grounded?.085:Math.max(0,f.coyote-dt);f.jumpBuffer=inp.jump?.09:Math.max(0,f.jumpBuffer-dt);
  if(f.jumpBuffer>0&&!f.grounded&&f.wallSide&&f.wallId!==f.lastWall&&!['stunned','clash','pushed','dead','ultCharge','ultWindup','throwWindup'].includes(f.state)&&f.dashRemaining<=0){f.vx=-f.wallSide*430;f.vy=-850*r.jump;f.wallLock=.15;f.wallJumpTime=.23;f.lastWall=f.wallId;f.jumpBuffer=0;f.jumping=true;f.coyote=0;this.emit('wallJump',{id:f.id});}
  if(f.jumpBuffer>0&&f.dashRemaining<=0&&!['dash','slide','stunned','clash','pushed','dead','ultCharge','ultWindup','throwWindup'].includes(f.state)&&this.phase==='playing'&&(f.grounded||f.coyote>0)){
   const platform=this.map.platforms[f.platform];if(inp.down&&platform&&!platform.solid){f.dropTimer=.22;f.y+=3;f.grounded=false;f.coyote=0;}else{f.vy=-940*r.jump;f.grounded=false;f.jumping=true;f.coyote=0;this.emit('jump',{id:f.id});if(!f.id)this.habits.jumps++;}f.jumpBuffer=0;
  }
  if(f.jumping&&!inp.jumpHeld&&f.vy<-250){f.vy*=.48;f.jumping=false;}
  if(f.state==='ultCharge'){f.vx=f.ultSide*2200;f.vy+=1980*r.gravity*dt;}else if(f.dashRemaining>0){f.vx=f.dashX*s.dashSpeed*r.dashDistance*(f.slideRemaining>0?.55:1);f.vy=f.dashY*s.dashSpeed*r.dashDistance;if(f.vy<0)f.grounded=false;}
  else{
   const attacking=['startup','active','recovery'].includes(f.state),locked=['stunned','clash','pushed'].includes(f.state),target=f.move*s.speed*r.speed*(attacking&&f.grounded?.7:1),accel=(f.grounded?3800:1100)*(locked?0:1);
   if(!locked&&f.wallLock<=0)f.vx+=clamp(target-f.vx,-accel*dt,accel*dt);else if(locked)f.vx*=Math.exp(-5*dt);
   f.vy+=1980*r.gravity*(inp.down&&f.vy>0?1.7:1)*dt;
  }
  f.x=f.state==='ultCharge'?f.x+f.vx*dt:clamp(f.x+f.vx*dt,24*SCALE,this.map.width-24*SCALE);f.y+=f.vy*dt;f.grounded=false;f.platform=-1;
  if(f.vy>=0){for(let i=0;i<this.map.platforms.length;i++){const p=this.map.platforms[i];if(f.dropTimer>0&&!p.solid)continue;if(f.x+C.radius*.7>p.x&&f.x-C.radius*.7<p.x+p.w&&oldY<=p.y+.5&&f.y>=p.y){f.y=p.y;f.vy=0;f.grounded=true;f.platform=i;f.jumping=false;if(!wasGrounded){f.landing=.15;if(f.dashRemaining<=0)f.airUsed=false;this.emit('land',{id:f.id});}break;}}}
  this.collideWalls(f,oldX,oldY);
  if(f.grounded){f.lastWall=-1;if(f.dashRemaining<=0){f.airUsed=false;f.airDashes=0;}}
  if(f.grounded&&f.state==='parry'&&f.guard==='low')this.setState(f,'parryRecovery',r.parryRecovery/1000);
  f.anim+=Math.abs(f.vx)*dt*.026;
 }
 updatePlatforms(time,carry=true){for(const p of this.map.platforms){const y=p.motion?p.baseY+Math.sin(time*Math.PI*2/p.motion.period)*p.motion.y:p.baseY;p.dy=carry?y-p.y:0;p.dx=0;p.y=y;}}
 collideWalls(f,oldX=f.x,oldY=f.y){f.wallSide=0;f.wallId=-1;const b=body(f);for(let i=0;i<this.map.walls.length;i++){const w=this.map.walls[i];const crosses=(oldX+b.radius<=w.x&&f.x+b.radius>=w.x)||(oldX-b.radius>=w.x+w.w&&f.x-b.radius<=w.x+w.w);if(!crosses&&(f.x+b.radius<w.x-.001||f.x-b.radius>w.x+w.w+.001)||f.y-b.bottom-b.radius<=w.y||f.y-b.top-b.radius>=w.y+w.h)continue;
   if(oldY-b.top-b.radius>=w.y+w.h&&f.vy<0){f.y=w.y+w.h+b.top+b.radius;f.vy=0;continue;}
   if(w.x+w.w+b.radius>this.map.width-24*SCALE||w.x-b.radius>=24*SCALE&&(oldX<=w.x||f.x<w.x+w.w/2)){f.x=w.x-b.radius;f.wallSide=1;if(f.vx>0)f.vx=0;}else{f.x=w.x+w.w+b.radius;f.wallSide=-1;if(f.vx<0)f.vx=0;}f.wallId=i;if(f.state==='ultCharge')this.stopCharge(f);if(f.dashRemaining>0){f.dashRemaining=0;if(['dash','slide'].includes(f.state))this.setState(f,'dashRecovery',.09);}
  }}
 bodyContact(a,d){return polygonSegment(slash(a,this.map.walls).points,{x:d.x,y:d.y-body(d).top},{x:d.x,y:d.y-body(d).bottom},body(d).radius);}
 incomingSector(a,d){const poly=slash(a,this.map.walls).points,center={x:d.x,y:d.y-C.bodyCenter};let best=center,dist=Infinity;for(let i=0;i<poly.length;i++){const p=nearest(center,poly[i],poly[(i+1)%poly.length]),n=Math.hypot(p.x-center.x,p.y-center.y);if(n<dist){best=p;dist=n;}}const dx=a.x-d.x,dy=a.y-d.y;return{sector:guardSector(Math.atan2(dy,dx),false),side:Math.sign(dx)||1,point:best};}
 resolveCombat(){const[p,e]=this.fighters;if(p.dead||e.dead)return;const ps=slash(p,this.map.walls),es=slash(e,this.map.walls);
  if(p.state!=='ultCharge'&&e.state!=='ultCharge'&&polygonsIntersect(ps.points,es.points)){for(const f of[p,e]){f.attackHit=true;this.setState(f,'clash',.16);f.vx=(f.x<(f===p?e:p).x?-1:1)*170;}this.hitstop=.055;this.emit('clash',{x:(p.x+e.x)/2,y:(p.y+e.y)/2-C.bodyCenter});return;}
  const hits=[];for(const[a,d]of[[p,e],[e,p]]){if(!['active','ultCharge'].includes(a.state)||a.attackHit)continue;const body=this.bodyContact(a,d),g=blade(d).guard,guardTouch=d.state==='parry'&&polygonSegment(slash(a,this.map.walls).points,g.a,g.b,C.bladeWidth);if(!body&&!guardTouch)continue;const incoming=this.incomingSector(a,d),valid=a.state!=='ultCharge'&&!(a.breakAttackId&&a.breakAttackId===a.attackId)&&d.state==='parry'&&incoming.sector===d.guard&&(d.guard!=='normal'||incoming.side===d.guardFacing);
   if(valid){a.attackHit=true;this.setState(a,'stunned',this.rules.stun/1000);a.vx=(a.x<d.x?-1:1)*120;this.setState(d,'idle');d.parryCooldown=Math.min(d.parryCooldown,.22);this.hitstop=.07;this.emit('parry',{id:d.id,...incoming.point});return;}if(body){a.attackHit=true;if(!this.absorb(d,a))hits.push([a,d]);}
  }
  if(!hits.length)for(const[a,d]of[[p,e],[e,p]]){if(a.state!=='kickActive'||a.kickHit)continue;const y=a.y-body(a).center+12,from={x:a.x+a.kickSide*18,y},to={x:a.x+a.kickSide*56,y},db=body(d);if(!this.map.walls.some(w=>wallFraction({x:a.x,y},{x:d.x,y},w)<1)&&segmentDistance(from,to,{x:d.x,y:d.y-db.top},{x:d.x,y:d.y-db.bottom})<=db.radius+9){a.kickHit=true;this.setState(d,'pushed',.12);d.vx=a.kickSide*570;d.vy=Math.min(d.vy,-85);d.grounded=false;this.hitstop=.035;this.emit('kick',{id:a.id,x:d.x,y:d.y-db.center});}}
  if(hits.length){const trade=hits.length===2,winner=trade?-1:hits[0][0].id;for(const[,d]of hits){d.dead=true;d.deathTime=0;this.setState(d,'dead');}const d=hits[0][1];const reason=trade?'Os dois cortes chegaram juntos.':d.stateBefore==='recovery'?'O golpe errado abriu sua recuperação.':d.stateBefore==='parryRecovery'?'O parry terminou antes de o corte chegar.':d.stateBefore==='parry'?'O corte veio por fora da direção protegida.':d.stateBefore==='dash'?'O dash entrou no alcance do corte.':d.stateBefore==='stunned'?'O parry abriu espaço para o contra-ataque.':'O corte encontrou uma abertura.';this.finish(winner,reason,{x:d.x,y:d.y-C.bodyCenter,trade});}
 }
 finish(winner,reason,data={}){if(this.phase!=='playing')return;if(winner>=0&&this.mode!=='training')this.score[winner]++;this.phase='roundEnd';this.roundTimer=this.mode==='training'?.6:C.roundPause;this.hitstop=.095;this.lastReason=reason;this.emit('kill',{winner,reason,trade:winner<0,...data});}
 separateBodies(){const[a,b]=this.fighters;if(a.state==='ultCharge'||b.state==='ultCharge'||a.dead||b.dead||a.y-body(a).bottom+body(a).radius<b.y-body(b).top-body(b).radius||b.y-body(b).bottom+body(b).radius<a.y-body(a).top-body(a).radius)return;const dx=b.x-a.x,overlap=35*SCALE-Math.abs(dx);if(overlap>0){const sign=dx>=0?1:-1;a.x=clamp(a.x-overlap*.5*sign,24*SCALE,this.map.width-24*SCALE);b.x=clamp(b.x+overlap*.5*sign,24*SCALE,this.map.width-24*SCALE);if(a.vx*sign>0)a.vx=0;if(b.vx*sign<0)b.vx=0;}}
 getAIPolicy(){const base=DIFFICULTIES[this.difficulty],h=this.habits,total=h.attacks+h.parries+1,confidence=clamp(total/14,0,1);return{...base,attack:clamp(base.attack+(this.difficulty==='adaptive'?Math.min(.12,h.retreat/100):0),0,1),parry:clamp(base.parry+(this.difficulty==='adaptive'?confidence*(h.attacks/total-.4)*.5:0),0,1),bait:this.difficulty==='adaptive'?.14+confidence*h.parries/total*.55:.15,punish:this.difficulty==='easy'?.4:this.difficulty==='adaptive'?.65+Math.min(.3,h.whiffs/total*.4):.85,learned:this.difficulty==='adaptive'&&total>6};}
 nextPlatform(f,goal){const key=f.kind+':'+f.platform+':'+goal;if(this.routeCache.has(key))return this.routeCache.get(key);const ps=this.map.platforms,start=f.platform,cost=ps.map(()=>Infinity),prev=ps.map(()=>-1),open=new Set(ps.map((_,i)=>i));cost[start]=0;const speed=stats(f).speed*this.rules.speed,jump=940*this.rules.jump,gravity=1980*this.rules.gravity;
  while(open.size){let i=-1;for(const j of open)if(i<0||cost[j]<cost[i])i=j;if(!Number.isFinite(cost[i])||i===goal)break;open.delete(i);const a=ps[i];for(const j of open){const b=ps[j],rise=a.y-b.y,disc=jump*jump-2*gravity*rise;if(disc<0)continue;const gap=Math.max(0,Math.max(a.x,b.x)-Math.min(a.x+a.w,b.x+b.w)),flight=(jump+Math.sqrt(disc))/gravity;if(gap+38>speed*flight*.88)continue;const candidate=cost[i]+gap+Math.abs(rise)*.3+65;if(candidate<cost[j]){cost[j]=candidate;prev[j]=i;}}}
  let next=goal;if(prev[next]<0)next=-1;else while(prev[next]!==start&&prev[next]>=0)next=prev[next];this.routeCache.set(key,next);return next;
 }
 navigateAI(e,p,inp){const ai=this.ai,ps=this.map.platforms,s=stats(e);if(e.grounded){ai.navTarget=-1;if(e.platform<0)return;const goal=p.grounded?p.platform:ps.findIndex(q=>p.y<=q.y+20&&p.x>=q.x&&p.x<=q.x+q.w);if(goal<0||goal===e.platform)return;const next=this.nextPlatform(e,goal);if(next<0)return;const q=ps[next],target=clamp(e.x,q.x+30,q.x+q.w-30),dx=target-e.x,rise=e.y-q.y,disc=(940*this.rules.jump)**2-2*1980*this.rules.gravity*rise;if(disc<0)return;const flight=(940*this.rules.jump+Math.sqrt(disc))/(1980*this.rules.gravity),launch=Math.min(190,s.speed*this.rules.speed*flight*.67);inp.jump=false;inp.down=false;inp.move=Math.abs(dx)>9?Math.sign(dx):0;
   if(rise<-15&&!ps[e.platform].solid&&e.x>q.x+10&&e.x<q.x+q.w-10){inp.down=true;inp.jump=true;inp.jumpHeld=false;ai.navTarget=next;ai.jumpDelay=.25;return true;}
   if(Math.abs(dx)<=launch&&ai.jumpDelay<=0&&!['stunned','clash'].includes(e.state)){inp.jump=true;inp.jumpHeld=true;inp.down=false;ai.navTarget=next;ai.jumpDelay=.25;}else if(Math.abs(dx)<=launch)inp.move=0;return true;
  }else if(ai.navTarget>=0){const q=ps[ai.navTarget];if(!q||e.y>q.y+30&&e.vy>0){ai.navTarget=-1;return;}const target=clamp(p.x,q.x+38,q.x+q.w-38),dx=target-e.x;inp.move=clamp(dx*.025-e.vx*.002,-1,1);inp.jumpHeld=e.vy<0;return true;}
 }
 updateAI(dt){const p=this.fighters[0],e=this.fighters[1],ai=this.ai,s=stats(e),policy=this.getAIPolicy(),dx=p.x-e.x,dy=p.y-e.y,dist=Math.hypot(dx,dy),toward=Math.sign(dx)||1,impossible=this.difficulty==='impossible';const inp=neutral();inp.aim=Math.atan2(dy,dx);inp.move=ai.intent;inp.jumpHeld=e.vy<0;ai.timer-=dt;ai.attackDelay-=dt;ai.jumpDelay-=dt;
  if(p.dead||e.dead)return inp;
  if(p.state==='startup'&&p.attackId!==ai.seen){ai.seen=p.attackId;ai.reaction=this.between(...policy.reaction);ai.answer=this.random();}
  if(ai.reaction>=0){ai.reaction-=dt;if(ai.reaction<=0&&['startup','active'].includes(p.state)&&dist<stats(p).reach+55&&this.canAct(e)){if(ai.answer<policy.parry){const from=Math.atan2(p.y-e.y,p.x-e.x);inp.aim=from;inp.parry=true;}else if(ai.answer<.92){ai.intent=-toward;inp.move=-toward;inp.dash=this.random()<.3;}ai.reaction=-1;}}
  if(impossible&&this.canAct(e)&&['startup','active'].includes(p.state)){const probe={...p,state:'active',duration:stats(p).active/this.rules.attackSpeed,stateTime:Math.max(0,p.state==='active'?p.stateTime:p.stateTime-p.duration)+.025};if(this.bodyContact(probe,e)){const incoming=this.incomingSector(probe,e);inp.aim=incoming.sector==='high'?-Math.PI/2:incoming.sector==='low'?Math.PI/2:incoming.side>0?0:Math.PI;inp.parry=true;}}
  if(ai.timer<=0){ai.timer=this.between(.09,.19);const roll=this.random(),inRange=dist<s.reach-9&&dist>s.minRange;
   if(inRange&&ai.attackDelay<=0&&p.state!=='parry'&&((['recovery','parryRecovery','stunned'].includes(p.state)&&p.stateTime>(impossible?0:.11)&&roll<policy.punish)||roll<policy.attack)){inp.attack=true;ai.attackDelay=this.between(.38,.85)*(this.difficulty==='easy'?1.4:1);ai.intent=0;}
   else if(dist<s.minRange+15)ai.intent=-toward;
   else if(dist>s.reach-28)ai.intent=toward;
   else if(roll<policy.bait){ai.intent=-toward;ai.bait=true;}
   else ai.intent=roll<.5?0:toward;
   if(ai.bait&&roll>.55){ai.bait=false;ai.intent=toward;}
   if(e.grounded&&ai.jumpDelay<=0&&(dy<-110||(dist<320&&roll<.16))){inp.jump=true;inp.jumpHeld=true;ai.jumpDelay=this.between(.6,1.3);}
   if(e.grounded&&dy>130&&!this.map.platforms[e.platform]?.solid&&Math.abs(dx)<170){inp.down=true;inp.jump=true;}
  }
  inp.move=ai.intent;
  const navigating=(dist>s.reach-15||Math.abs(dy)>85)&&this.navigateAI(e,p,inp);
  if(!navigating&&e.grounded&&Math.abs(inp.move)>.1){const edge=e.x+inp.move*65,support=this.map.platforms.some(q=>edge>=q.x&&edge<=q.x+q.w&&Math.abs(q.y-e.y)<35);if(!support){const landing=this.map.platforms.some(q=>(q.x+q.w-e.x)*inp.move>0&&Math.abs(q.x+q.w*.5-e.x)<430&&q.y>e.y-240);if(landing&&ai.jumpDelay<=0){inp.jump=true;inp.jumpHeld=true;ai.jumpDelay=.65;}else inp.move=0;}}
  if(!navigating&&!e.grounded&&e.vy>0){const below=this.map.platforms.filter(q=>q.y>=e.y-10);if(below.length&&!below.some(q=>e.x>q.x+12&&e.x<q.x+q.w-12)){const target=below.reduce((a,b)=>Math.abs(clamp(e.x,a.x+24,a.x+a.w-24)-e.x)<Math.abs(clamp(e.x,b.x+24,b.x+b.w-24)-e.x)?a:b);inp.move=Math.sign(clamp(e.x,target.x+24,target.x+target.w-24)-e.x);}}
  if(e.wallSide&&inp.move*e.wallSide>0&&ai.jumpDelay<=0){inp.jump=true;inp.jumpHeld=true;ai.jumpDelay=.3;}if(p.state==='parry'&&dist<62&&this.canAct(e))inp.kick=true;
  if(this.rules.specials&&this.canAct(e)&&e.specialCharge>=this.rules.specialCooldown&&dist<600&&ai.timer<.03)inp.special=true;if(e.ultMode==='unarmed'&&e.dagger){inp.attack=false;inp.move=Math.sign(e.dagger.safe.x-e.x);if(e.dagger.y<e.y-110&&e.grounded)inp.jump=true;}
  return inp;
 }
 step(dt,inputs=[]){if(!Number.isFinite(dt)||dt<=0)return;if(this.hitstop>0){this.hitstop=Math.max(0,this.hitstop-dt);return;}if(this.phase==='title'||this.phase==='matchEnd')return;this.time+=dt;this.updatePlatforms(this.time);
  if(this.phase==='roundEnd'){for(const f of this.fighters){if(f.dead)f.deathTime+=dt;else{this.tickState(f,dt);f.vx*=Math.exp(-12*dt);f.move=0;}}this.roundTimer-=dt;if(this.roundTimer<=0){const winner=this.score.findIndex(n=>n>=C.winningScore);if(winner>=0&&this.mode!=='training'){this.phase='matchEnd';this.emit('matchEnd',{winner});}else{this.round++;this.phase='playing';this.resetFighters();this.emit('round');}}return;}
  const commands=[inputs[0]||neutral(),this.aiEnabled?this.updateAI(dt):inputs[1]||neutral()];this.lastCommands=commands.map(c=>({...c}));if(commands[0].move*(this.fighters[1].x-this.fighters[0].x)<0)this.habits.retreat+=dt;
  for(let i=0;i<2;i++){const f=this.fighters[i],inp=commands[i];this.tickState(f,dt);if(f.dead)continue;f.aim=Number.isFinite(inp.aim)?inp.aim:f.aim;f.facing=Math.cos(f.aim)>=0?1:-1;f.stateBefore=f.state;if(f.queued&&this.canAct(f)){const q=f.queued;f.aim=q.aim;this.command(i,q.action,q);f.aim=inp.aim;}if(inp.dash)this.command(i,'dash',inp);if(inp.attack)this.command(i,'attack',inp);if(inp.parry)this.command(i,'parry',inp);if(inp.kick)this.command(i,'kick',inp);if(inp.special)this.command(i,'special',inp);this.moveFighter(f,inp,dt);}
  this.separateBodies();for(const f of this.fighters)if(!f.dead)this.collideWalls(f);this.resolveCombat();if(this.phase!=='playing')return;this.updateDaggers(dt);if(this.phase!=='playing')return;
  for(const f of this.fighters)if(!f.dead&&f.y>this.map.deathY){f.dead=true;f.deathTime=0;this.setState(f,'dead');if(!this.fallTimer)this.fallTimer=.15;}
  if(this.fallTimer){this.fallTimer-=dt;const dead=this.fighters.filter(f=>f.dead);if(dead.length===2||this.fallTimer<=0){const loser=dead[0],winner=dead.length===2?-1:1-loser.id;this.finish(winner,winner<0?'Os dois caíram na mesma janela.':'Queda fora da arena.',{x:loser.x,y:710});}}
 }
 snapshot(){return JSON.parse(JSON.stringify({version:4,experimental:!!this.experimental,aiEnabled:this.aiEnabled,mode:this.mode,difficulty:this.difficulty,characters:this.characters,colors:this.colors,mapId:this.mapId,rules:this.rules,phase:this.phase,time:this.time,score:this.score,round:this.round,hitstop:this.hitstop,roundTimer:this.roundTimer,attackCounter:this.attackCounter,fallTimer:this.fallTimer,lastReason:this.lastReason,fighters:this.fighters,habits:this.habits,ai:this.ai}));}
 loadSnapshot(s){if(!s||s.version!==4||!Array.isArray(s.fighters)||s.fighters.length!==2)return false;this.configure({...s,ai:s.aiEnabled});for(const key of['phase','time','score','round','hitstop','roundTimer','attackCounter','fallTimer','lastReason','fighters','habits','ai'])this[key]=JSON.parse(JSON.stringify(s[key]));this.updatePlatforms(this.time,false);this.events=[];return true;}
}
const api={body,SCALE,slash,makeMap,pointInPolygon,polygonSegment,polygonsIntersect,C,CLASSES,COLORS,RULES,DEFAULT_RULES,MAPS,DIFFICULTIES,Game,stats,blade,guardSector,cleanRules,neutral,clamp,lerp,segmentDistance};if(typeof module!=='undefined')module.exports=api;root.DuelCore=api;
})(typeof globalThis!=='undefined'?globalThis:this);
