(function(){
'use strict';
const {clamp,lerp,COLORS,blade,stats}=DuelCore,TAU=Math.PI*2;
class DuelRenderer{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.camera={x:640,y:360,zoom:1};this.previousBlades=[[],[]];this.lastRound=0;this.lastTime=0;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;}
 resize(){const b=this.canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.round(b.width*d),h=Math.round(b.height*d);if(w!==this.canvas.width||h!==this.canvas.height){this.canvas.width=w;this.canvas.height=h;}this.scale=document.documentElement.classList.contains('immersive')?Math.max(w/1280,h/720):Math.min(w/1280,h/720);this.viewWidth=w/this.scale;this.viewHeight=h/this.scale;this.ox=(w-1280*this.scale)/2;this.oy=(h-720*this.scale)/2;this.dpr=d;}
 screenToWorld(x,y){const r=this.canvas.getBoundingClientRect();return{x:((x-r.left)*this.dpr-this.ox)/this.scale/this.camera.zoom+this.camera.x-640/this.camera.zoom,y:((y-r.top)*this.dpr-this.oy)/this.scale/this.camera.zoom+this.camera.y-360/this.camera.zoom};}
 line(a,b,color,width=1){const c=this.ctx;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.strokeStyle=color;c.lineWidth=width;c.stroke();}
 path(pts,fill,stroke,width=1){const c=this.ctx;c.beginPath();pts.forEach((p,i)=>i?c.lineTo(p[0],p[1]):c.moveTo(p[0],p[1]));if(fill){c.closePath();c.fillStyle=fill;c.fill();}if(stroke){c.strokeStyle=stroke;c.lineWidth=width;c.stroke();}}
 ellipse(x,y,rx,ry,color){const c=this.ctx;c.beginPath();c.ellipse(x,y,Math.max(.1,rx),Math.max(.1,ry),0,0,TAU);c.fillStyle=color;c.fill();}
 background(game,t){DuelScenery.draw(this,game,t);}
 platforms(game,t){DuelScenery.platforms(this,game,t);}
 fighter(f,time,w,portrait=false){DuelActors.draw(this,f,time,w,portrait);}
 sword(f,w,t,portrait=false){if(portrait||f.dead)return;const c=this.ctx,shape=DuelCore.slash(f,this.walls||[]),color=f.ultMode==='edgeStrike'?'#dfb34b':f.state==='ultCharge'?'#e5b870':COLORS[f.color]?.hex||'#80b6ae';
  this.slashTrails??=[[],[]];const trail=this.slashTrails[f.id];while(trail.length&&t-trail[0].time>.085)trail.shift();if(!this.reduced){for(const item of trail){c.globalAlpha=Math.max(0,1-(t-item.time)/.085)*.16;this.path(item.points.map(p=>[p.x,p.y]),null,color,1.4);}c.globalAlpha=1;}if(shape.points.length&&(!trail.length||t>trail[trail.length-1].time+.012))trail.push({points:shape.points.map(p=>({...p})),time:t});
  if(shape.points.length){const pts=shape.points.map(p=>[p.x,p.y]);this.path(pts,'#fff8d9');c.save();c.beginPath();pts.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.closePath();c.clip();const gradient=c.createRadialGradient(shape.origin.x,shape.origin.y,stats(f).minRange,shape.origin.x,shape.origin.y,stats(f).reach);gradient.addColorStop(0,color);gradient.addColorStop(.38,color);gradient.addColorStop(.88,'#fff6bb');gradient.addColorStop(1,'#ffffff');c.globalAlpha=.78;c.fillStyle=gradient;c.fillRect(f.x-250,f.y-DuelCore.body(f).center-250,500,500);c.globalAlpha=.9;const count=shape.points.length;for(let i=0;i<3;i++){const j=Math.floor((shape.progress*.65+i*.12+.12)*(count/2-1));if(shape.points[j]&&shape.points[j+1])this.line(shape.points[j],shape.points[j+1],'#ffffff',2.8-i*.6);}c.restore();}
  if(f.state==='startup'){const aim=f.attackAim,rad=stats(f).reach,p=clamp(f.stateTime/f.duration,0,1);c.globalAlpha=.25+p*.5;this.line({x:f.x+Math.cos(aim)*30,y:f.y-DuelCore.body(f).center+Math.sin(aim)*30},{x:f.x+Math.cos(aim)*Math.min(rad,53),y:f.y-DuelCore.body(f).center+Math.sin(aim)*Math.min(rad,53)},'#fff2c4',2);c.globalAlpha=1;}
  if(f.state==='parry'){const a=f.guard==='high'?-Math.PI/2:f.guard==='low'?Math.PI/2:f.guardFacing>0?0:Math.PI,remaining=clamp(1-f.stateTime/f.duration,0,1);c.beginPath();c.arc(f.x,f.y-DuelCore.body(f).center,47,a-.66,a+.66);c.strokeStyle='#9e895c88';c.lineWidth=3;c.stroke();c.beginPath();c.arc(f.x,f.y-DuelCore.body(f).center,47,a-.66,a-.66+1.32*remaining);c.strokeStyle='#fff0af';c.lineWidth=3;c.stroke();c.font='9px monospace';c.textAlign='center';c.fillStyle=DuelScenery.THEMES[this.lastTheme]?.dark?'#f4e6bc':'#6e5733';const label=f.guard==='high'?'ALTO':f.guard==='low'?'BAIXO':'NORMAL';c.fillText(label+(f.duration>.3?' · '+Math.max(0,f.duration-f.stateTime).toFixed(1).replace('.',',')+' s':''),f.x,f.y-144);}
  if(!f.dead){c.globalAlpha=.65;this.ellipse(f.x+Math.cos(f.aim)*47,f.y-DuelCore.body(f).center+Math.sin(f.aim)*47,1.8,1.8,color);c.globalAlpha=1;}
 }
 render(game,effects,t){this.walls=game.map.walls||[];if(this.lastTheme!==game.mapId){this.lastTheme=game.mapId;if(this.canvas.parentElement){this.canvas.parentElement.dataset.theme=game.mapId;this.canvas.parentElement.classList.toggle('dark-arena',!!DuelScenery.THEMES[game.mapId]?.dark);}}this.resize();const c=this.ctx,dt=clamp(t-this.lastTime,0,.05);this.lastTime=t;if(this.lastRound!==game.round){this.previousBlades=[[],[]];this.actorHistory=[];this.slashTrails=[[],[]];this.lastRound=game.round;}const alive=game.fighters.filter(f=>!f.dead),fs=alive.length?alive:game.fighters,minX=Math.min(...fs.map(f=>f.x))-210,maxX=Math.max(...fs.map(f=>f.x))+210,minY=Math.min(...fs.map(f=>f.y))-235,maxY=Math.max(...fs.map(f=>f.y))+95,z=clamp(Math.min(this.viewWidth/(maxX-minX),this.viewHeight/(maxY-minY)),.00001,1.12),half=this.viewWidth/2/z,tx=game.map.width<half*2?game.map.width/2:clamp((minX+maxX)/2,half,game.map.width-half),ty=Math.min(game.map.height-(this.viewHeight/2-150)/z,(minY+maxY)/2),smooth=this.snapCamera?1:1-Math.exp(-dt*7);this.camera.zoom=lerp(this.camera.zoom,z,smooth);this.camera.x=lerp(this.camera.x,tx,smooth);this.camera.y=lerp(this.camera.y,ty,smooth);this.snapCamera=false;
  c.setTransform(1,0,0,1,0,0);c.fillStyle=DuelScenery.THEMES[game.mapId]?.dark?'#202d3c':'#d7ceba';c.fillRect(0,0,this.canvas.width,this.canvas.height);c.setTransform(this.scale,0,0,this.scale,this.ox,this.oy);this.background(game,t);c.save();c.beginPath();c.rect(0,0,1280,720);c.clip();const shake=this.reduced?0:effects.shake||0;c.translate(640+(Math.random()-.5)*shake,360+(Math.random()-.5)*shake);c.scale(this.camera.zoom,this.camera.zoom);c.translate(-this.camera.x,-this.camera.y);this.platforms(game,t);this.drawWalls(game);for(const f of game.fighters){if(!f.grounded&&!f.dead){const surfaces=game.map.platforms.filter(p=>p.y>=f.y&&f.x>=p.x&&f.x<=p.x+p.w).sort((a,b)=>a.y-b.y);if(surfaces.length){const ground=surfaces[0],height=ground.y-f.y;this.ellipse(f.x,ground.y+3,Math.max(9,27-height*.035),3,'#213f331d');}}const w=blade(f);this.fighter(f,t,w);}for(const f of game.fighters)this.sword(f,blade(f),t);this.specials(game,t);if(this.debug)this.hitboxes(game);for(const p of effects.particles||[]){c.globalAlpha=p.life/p.maxLife;this.line({x:p.x-p.vx*.015,y:p.y-p.vy*.015},p,p.color,p.size);}c.globalAlpha=1;for(const cut of effects.cuts||[]){c.globalAlpha=cut.life/cut.maxLife;this.line({x:cut.x-90,y:cut.y+60},{x:cut.x+90,y:cut.y-60},'#fff5d6',3);}c.globalAlpha=1;c.restore();if(effects.flash){c.fillStyle='#fff2d6';c.globalAlpha=Math.min(.4,effects.flash*2.5);c.fillRect(0,0,1280,720);c.globalAlpha=1;}this.impact(game,effects);}
 specials(game,t){const c=this.ctx;for(const f of game.fighters){if(f.dead)continue;const b=DuelCore.body(f),x=f.x,y=f.y-b.center,w=blade(f);c.save();
  if(f.ultMode==='shield'){const pulse=.18+Math.sin(t*7)*.035;c.globalAlpha=pulse;c.fillStyle='#f4d884';c.beginPath();c.ellipse(x,y,41,77,0,0,TAU);c.fill();c.globalAlpha=.8;c.strokeStyle='#ffe7a6';c.lineWidth=2;c.stroke();for(let i=0;i<4;i++){const a=t*.7+i*TAU/4;this.ellipse(x+Math.cos(a)*42,y+Math.sin(a)*76,2.3,2.3,'#fff4cd');}}
  if(['edge','edgeStrike','reaperBoost','reaperWeak'].includes(f.ultMode)){const weak=f.ultMode==='reaperWeak',color=weak?'#81909d':'#ffe0a2';c.globalAlpha=weak?.6:.25+Math.sin(t*10)*.06;for(const s of w.segments)this.line(s.a,s.b,color,weak?3:10);c.globalAlpha=1;for(const s of w.segments)this.line(s.a,s.b,color,1.2);}
  if(f.parryLock>0){c.strokeStyle='#ffb2a0';c.lineWidth=1.5;c.beginPath();c.arc(x,f.y-b.top-23,7,0,TAU);c.stroke();this.line({x:x-5,y:f.y-b.top-28},{x:x+5,y:f.y-b.top-18},'#ffb2a0',1.5);}
  if(f.state==='ultWindup'){c.setLineDash([9,7]);c.globalAlpha=.65;this.line({x,y},{x:x+f.ultSide*270,y},'#ffcc79',2);c.setLineDash([]);this.ellipse(x,y,5+f.stateTime*12,5+f.stateTime*12,'#ffe0a2');}
  if(f.state==='ultCharge'){c.globalAlpha=.4;for(let i=0;i<4;i++)this.line({x:x-f.ultSide*(30+i*15),y:y-14+i*9},{x:x-f.ultSide*(155+i*13),y:y-14+i*9},'#fff0bc',2);}
  const p=f.dagger;if(p){if(p.mode!=='lost'){const a=p.mode==='flying'?Math.atan2(p.vy,p.vx):-.6,dx=Math.cos(a),dy=Math.sin(a);this.line({x:p.x-dx*12,y:p.y-dy*12},{x:p.x+dx*17,y:p.y+dy*17},'#fff1c0',4);this.line({x:p.x-dx*19,y:p.y-dy*19},{x:p.x-dx*10,y:p.y-dy*10},COLORS[f.color].hex,5);if(p.mode==='flying'){c.globalAlpha=.5;this.line({x:p.x-dx*28,y:p.y-dy*28},{x:p.x-dx*75,y:p.y-dy*75},'#f6d991',2);}else{c.globalAlpha=.8;this.path([[p.x-5,p.y-22],[p.x,p.y-17],[p.x+5,p.y-22]],null,'#fff0bd',2);}}else{c.globalAlpha=.45;this.ellipse(p.safe.x,p.safe.y,9,3,'#ffe6a0');}}
  c.restore();}}
 impact(game,effects){if(!effects.impact)return;const c=this.ctx,p=effects.impactPoint||{x:640,y:360};c.save();c.globalAlpha=this.reduced?.1:.93;c.fillStyle='#f4efd9';c.fillRect(0,0,1280,720);c.globalAlpha=1;c.translate(640,360);c.scale(this.camera.zoom,this.camera.zoom);c.translate(-this.camera.x,-this.camera.y);for(const f of game.fighters){c.save();c.filter='brightness(0)';this.fighter(f,this.lastTime,blade(f));c.restore();}const rays=this.reduced?4:12;for(let i=0;i<rays;i++){const a=i*TAU/rays+.15,length=i%3===0?105:60;this.line({x:p.x+Math.cos(a)*12,y:p.y+Math.sin(a)*12},{x:p.x+Math.cos(a)*length,y:p.y+Math.sin(a)*length},i%2?'#263640':'#b99249',i%3===0?3:1.5);}this.ellipse(p.x,p.y,6,6,'#ffffff');c.restore();}

 drawWalls(game){const c=this.ctx,theme=DuelScenery.THEMES[game.mapId]||DuelScenery.THEMES.dojo;for(const w of game.map.walls||[]){c.fillStyle=theme.edge;c.fillRect(w.x,w.y,w.w,w.h);c.fillStyle=theme.surface;c.fillRect(w.x+4,w.y+4,w.w-8,w.h-4);this.line({x:w.x+3,y:w.y},{x:w.x+3,y:w.y+w.h},theme.top,3);for(let y=w.y+22;y<w.y+w.h;y+=Math.max(30,w.h/160)){this.line({x:w.x+5,y},{x:w.x+w.w-5,y},theme.detail,2);}c.fillStyle=theme.top;c.fillRect(w.x-3,w.y-3,w.w+6,5);}}
 hitboxes(game){const c=this.ctx;c.save();for(const f of game.fighters){if(f.dead)continue;const b=DuelCore.body(f);c.globalAlpha=.19;this.line({x:f.x,y:f.y-b.top},{x:f.x,y:f.y-b.bottom},'#55ddff',b.radius*2);c.globalAlpha=1;c.setLineDash([3,3]);this.line({x:f.x,y:f.y-b.top},{x:f.x,y:f.y-b.bottom},'#7af4ff',1);c.setLineDash([]);const shape=DuelCore.slash(f,game.map.walls);if(shape.points.length)this.path(shape.points.map(p=>[p.x,p.y]),null,'#ff654c',2);if(f.state==='parry'){const g=blade(f).guard;this.line(g.a,g.b,'#a6ff7b',4);}if(f.state==='kickActive')this.line({x:f.x+f.kickSide*18,y:f.y-b.center+12},{x:f.x+f.kickSide*56,y:f.y-b.center+12},'#ffaa55',18);c.font='10px monospace';c.fillStyle=DuelScenery.THEMES[game.mapId]?.dark?'#ecf4df':'#183e49';c.textAlign='center';c.fillText(f.state+' · '+Math.max(0,(f.duration-f.stateTime)*1000).toFixed(0)+' ms',f.x,f.y-b.top-27);}c.restore();}
 drawPortrait(canvas,kind,side=0,color,time=0){if(kind==='random'){const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);c.fillStyle=COLORS[color]?.hex||'#426b64';c.textAlign='center';c.font='70px Georgia';c.fillText('?',canvas.width/2,canvas.height*.66);return;}const old=this.ctx;this.ctx=canvas.getContext('2d');const c=this.ctx;c.clearRect(0,0,canvas.width,canvas.height);c.save();c.imageSmoothingEnabled=false;const f={id:side,kind,color:color||'jade',x:0,y:0,vx:0,vy:0,aim:-.15,facing:1,attackAim:0,state:'idle',stateTime:0,duration:0,grounded:true,anim:0,landing:0,dead:false,dashX:0,dashY:0,move:0};const w=blade(f),pts=[{x:-65,y:-152},{x:35,y:7},...w.segments.flatMap(s=>[s.a,s.b]),...(w.shaft?[w.shaft.a,w.shaft.b]:[])],minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxY=Math.max(...pts.map(p=>p.y)),scale=Math.min((canvas.width-10)/(maxX-minX),(canvas.height-10)/(maxY-minY));c.translate(canvas.width/2-(minX+maxX)/2*scale,canvas.height-5-maxY*scale);c.scale(scale,scale);this.fighter(f,time,w,true);c.restore();this.ctx=old;}
}
window.DuelRenderer=DuelRenderer;
})();
