(function(){
const D=DuelCore,TAU=Math.PI*2,clamp=D.clamp;
function moment(r,e){return e.preview?.animation==='finisher'?{...e.preview,winner:e.preview.id,age:(performance.now()-e.preview.start)/1000,finisher:true,angle:0}:e.fatal;}
const fighter=DuelRenderer.prototype.fighter;
DuelRenderer.prototype.fighter=function(f,t,w,portrait=false){const p=moment(this,this.effects||{});if(!portrait&&p?.finisher&&p.age<.95&&p.winner===f.id&&!f.dead&&p.cause!=='QUEDA'&&!this.reduced){const age=p.age,q={...f};q.attackAim=p.angle||0;q.state=age<.085?'startup':age<.27?'active':'recovery';q.stateTime=age<.085?age:age<.27?age-.085:age-.27;q.duration=age<.085?.085:age<.27?.185:.68;q.visualLean=f.facing*(age<.27?Math.sin(age/.27*Math.PI)*8:0);q.visualCrouch=age<.27?Math.sin(age/.27*Math.PI)*5:0;return fighter.call(this,q,t,D.blade(q),false);}return fighter.call(this,f,t,w,portrait);};
DuelPresentation.finale=function(r,e){const p=moment(r,e);if(!p?.finisher||p.age>1.1)return;const c=r.ctx,age=p.age,fade=clamp((1.1-age)/.4,0,1),u=clamp((age-.07)/.32,0,1),dissolve=clamp((age-.38)/.55,0,1),kind=p.kind||'knight',color={knight:'#ffe1ac',lancer:'#ffcc97',assassin:'#ffbfc2',swordsman:'#c4e5ff',reaper:'#dfbaff',boxer:'#b5fff0'}[kind];
 const x=clamp(((p.x??r.camera.x)-r.camera.x)*r.camera.zoom+640,200,1080),y=clamp(((p.y??r.camera.y)-r.camera.y)*r.camera.zoom+360,160,520);
 c.save();c.setTransform(r.scale,0,0,r.scale,r.ox,r.oy);const bars=r.reduced?7:18*Math.sin(clamp(age/.9,0,1)*Math.PI);c.globalAlpha=fade*.85;c.fillStyle='#080e1e';c.fillRect(0,0,1280,bars);c.fillRect(0,720-bars,1280,bars);c.globalAlpha=fade*(r.reduced?.07:.17);c.fillRect(0,0,1280,720);c.translate(x,y);
 if(r.reduced){c.globalAlpha=fade*.6;r.line({x:-60,y:15},{x:60,y:-15},color,2);}
 else if(p.cause==='QUEDA'){for(let i=0;i<7;i++){const yy=-160+age*(250+i*20);c.globalAlpha=fade*(1-i*.1);r.path([[-24+i*8,yy-80],[-22+i*8,yy],[-20+i*8,yy-80]],color);}}
 else if(kind==='reaper'){const angle=-2.8+u*5.8,rad=95+u*94+dissolve*70;for(let i=0;i<5;i++){c.globalAlpha=fade*(1-i*.18)*(1-dissolve*.65);c.strokeStyle=i===0?'#fff9ef':color;c.lineWidth=i===0?6*(1-dissolve)+1:2;c.beginPath();c.arc(0,0,rad+i*5,angle-(1.4+u*.8)*(1-dissolve*.7),angle);c.stroke();}const head={x:Math.cos(angle)*rad,y:Math.sin(angle)*rad};c.globalAlpha=fade*(1-dissolve);r.path([[head.x-15,head.y],[head.x,head.y-6],[head.x+16,head.y],[head.x,head.y+6]],'#fff6ed');}
 else if(kind==='boxer'){const power=1-Math.pow(1-u,3);for(let i=0;i<4;i++){const rad=12+power*(115+i*32)+dissolve*95;c.globalAlpha=fade*(1-i*.18)*(1-dissolve*.55);c.strokeStyle=i?'#88cbbd':'#f0ffdc';c.lineWidth=i?1:6*(1-power)+2;c.beginPath();c.ellipse(0,0,rad,rad*.52,0,0,TAU);c.stroke();}if(u<.7){c.globalAlpha=(1-u/.7)*.9;r.path([[0,-28],[8,-9],[45,-2],[9,9],[0,27],[-9,8],[-43,0],[-10,-9]],'#ffffe7');}}
 else{const baseAngle=kind==='lancer'?(p.angle||0):kind==='assassin'?-.2:kind==='swordsman'?-.42:-.7;c.rotate(baseAngle);const span=kind==='lancer'?800:kind==='assassin'?230:kind==='swordsman'?650:460,head=-span+2*span*(1-Math.pow(1-u,3)),tail=head-span*(.68-dissolve*.38),thick=(kind==='swordsman'?19:kind==='knight'?14:7)*(1-dissolve*.8);for(let i=3;i>=0;i--){c.globalAlpha=fade*(1-dissolve*.55)*(i?.12:1);const offset=i*5,yShift=i?Math.sin(i+age*9)*7:0;r.path([[tail-offset,yShift],[head-span*.14-offset,-thick/(i+1)+yShift],[head-offset,yShift],[head-span*.23-offset,thick*.45/(i+1)+yShift]],i?color:'#fff6dc');}c.globalAlpha=fade*(1-dissolve);r.line({x:tail,y:0},{x:head+12,y:0},color,1.2);if(kind==='assassin'&&age>.17&&age<.55){c.rotate(.5);const h=-170+clamp((age-.17)/.12,0,1)*400;c.globalAlpha=fade*(.55-age)/.38;r.path([[h-120,0],[h-25,-4],[h,0],[h-60,2]],'#ffdcd3');}c.rotate(-baseAngle);}
 if(!r.reduced&&p.cause!=='QUEDA'){for(let i=0;i<9;i++){const angle=(p.angle||0)-1.25+i*.31,travel=clamp((age-.14)/.65,0,1),dist=28+travel*(90+i%3*60);c.globalAlpha=fade*(1-travel)*.65;r.line({x:Math.cos(angle)*dist,y:Math.sin(angle)*dist},{x:Math.cos(angle)*(dist+12+i%3*8),y:Math.sin(angle)*(dist+12+i%3*8)},i%3?color:'#fffbe6',i%2?1:2);}}
 c.setTransform(r.scale,0,0,r.scale,r.ox,r.oy);c.globalAlpha=fade*clamp(age*6,0,1);c.fillStyle='#fff0cb';c.font='11px monospace';c.textAlign='center';c.fillText(p.cause==='QUEDA'?'A ÚLTIMA QUEDA':'O ÚLTIMO CORTE',640,605-(r.reduced?0:Math.exp(-age*7)*8));c.restore();
};
})();
