const A=require('node:assert/strict'),fs=require('fs'),path=require('path'),{pathToFileURL}=require('url'),{chromium}=require('C:/Users/Luiz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const snapshot=p=>p.evaluate(()=>duelSnapshot());
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--allow-file-access-from-files','--disable-background-timer-throttling','--disable-renderer-backgrounding']}),errors=[],results=[];let pages=[];
async function scenario(editions,confirmation){
 const contexts=await Promise.all(editions.map(()=>browser.newContext({viewport:{width:1440,height:1050}})));pages=await Promise.all(contexts.map(c=>c.newPage()));const[h,g]=pages;pages.forEach(p=>p.on('pageerror',e=>errors.push(e.message)));const both=async(fn,arg,timeout=15000)=>Promise.all(pages.map(p=>p.waitForFunction(fn,arg,{timeout}))),sync=async()=>{await both(()=>!duelSnapshot().adminPending);const states=await Promise.all(pages.map(snapshot));A.deepEqual(states[0].fighters,states[1].fighters);A.deepEqual(states[0].rules,states[1].rules);A.equal(states[0].online.frame,states[1].online.frame);return states;};
 await Promise.all(pages.map((p,i)=>p.goto(pathToFileURL(path.resolve(__dirname,'../../outputs/um-corte-v6.2'+(editions[i]?'-admin':'')+'.html')).href)));
 await Promise.all(pages.map(p=>p.click('#title-play')));await both(()=>!duelSnapshot().titleOpen);await h.click('#rules-details summary');await h.fill('#number-winningScore','3');await h.locator('#number-winningScore').press('Tab');await h.check('#persist-special');await h.click('[data-preset="turbo"]');
 await Promise.all(pages.map(p=>p.click('[data-mode="online"]')));await h.click('#create-room');await h.waitForFunction(()=>/^[23456789ABCDEFGHJKLMNPQRSTUVWXYZ]{6}$/.test(document.getElementById('room-display').textContent),null,{timeout:35000});const code=await h.locator('#room-display').textContent();await g.fill('#room-code',code);await g.click('#join-room');await g.waitForFunction(()=>duelSnapshot().lobby&&duelSnapshot().online.connected,null,{timeout:35000});await g.click('#player-colors [data-color="coral"]');await h.waitForFunction(()=>!document.getElementById('ready-button').disabled);A.deepEqual((await snapshot(g)).lobby.players.map(p=>p.admin),editions);await h.click('#ready-button');await g.click('#ready-button');await both(()=>duelSnapshot().intro.open);const began=Date.now();
 if(confirmation==='early'){await Promise.all(pages.map(p=>p.click('#special-understood')));}else if(confirmation==='one'){await g.click('#special-understood');await g.waitForTimeout(400);A.equal((await snapshot(h)).online.frame,0);A.equal((await snapshot(g)).intro.accepted,true);}
 await both(()=>!duelSnapshot().intro.open&&duelSnapshot().online.frame>10);const elapsed=Date.now()-began;if(confirmation==='early')A(elapsed<6000);else A(elapsed>=9000&&elapsed<13000);A.equal((await snapshot(g)).rules.speed,1.6);A.equal((await snapshot(g)).rules.winningScore,3);A.equal((await snapshot(g)).rules.persistSpecial,true);console.log('PASS online intro '+confirmation+' / editions '+editions.join(',')+' / '+elapsed+' ms');
 const owner=editions[1]?g:h,actor=editions[1]?1:0;await owner.keyboard.press('NumpadMultiply');await owner.click('#admin-pause');await both(()=>duelSnapshot().adminPaused);const frozen=await sync();await owner.click('[data-admin-preview="guard"]');await both(()=>duelSnapshot().preview?.animation==='guard');let visual=await sync();A.deepEqual(visual[0].fighters,frozen[0].fighters);A.deepEqual(visual[0].metrics,frozen[0].metrics);await owner.click('[data-admin-preview="perfect"]');await both(()=>duelSnapshot().preview?.animation==='perfect');await owner.click('[data-admin-preview="stop"]');await both(()=>!duelSnapshot().preview);await sync();console.log('PASS synchronized ADMIN visual previews, no score/physics/stats change');await owner.selectOption('#admin-map','bamboo');await owner.selectOption('#admin-character-0','knight');await owner.selectOption('#admin-skin-0','hollow');await owner.selectOption('#admin-character-1','assassin');await owner.selectOption('#admin-skin-1','thorfinn');await owner.fill('#admin-rule-speed','100');await owner.fill('#admin-rule-attackRecovery','10');await owner.fill('#admin-rule-winningScore','11');await owner.click('#admin-apply');await both(()=>duelSnapshot().rules.speed===100);let states=await sync();A.equal(states[0].lastAdmin.actor,actor);A.equal(states[1].fighters[0].skin,'hollow');A.equal(states[0].fighters[1].skin,'thorfinn');await owner.click('#admin-refill');await both(()=>duelSnapshot().fighters[0].specialCharge===7);await owner.click('#admin-step');await owner.waitForTimeout(150);await sync();console.log('PASS ADMIN seat '+actor+' / pause, extreme settings, map, skins, refill and frame-step');
 if(editions.every(Boolean)){
  await h.keyboard.press('NumpadMultiply');await h.fill('#admin-rule-speed','1.7');await g.fill('#admin-rule-speed','2.2');await h.click('#admin-apply');await g.click('#admin-apply');await both(()=>duelSnapshot().rules.speed===2.2&&!duelSnapshot().adminPending);states=await sync();A.equal(states[0].lastAdmin.actor,1);await h.click('#admin-close');console.log('PASS simultaneous ADMIN commands: final guest change wins and exact state agrees');
 }
 // Resume into a normal one-hit duel, preserve charge after the point, then lower target to end.
 await owner.click('#admin-defaults');await owner.selectOption('#admin-map','bamboo');await owner.selectOption('#admin-character-0','knight');await owner.selectOption('#admin-character-1','knight');await owner.fill('#admin-rule-winningScore','3');await owner.check('#admin-rule-persistSpecial');await owner.fill('#admin-pos-0-x','750');await owner.fill('#admin-pos-1-x','860');await owner.click('#admin-apply');await both(()=>duelSnapshot().rules.speed===1&&duelSnapshot().fighters[0].x===750);await sync();await owner.click('#admin-refill');await both(()=>duelSnapshot().fighters[0].specialCharge===7);await owner.click('#admin-pause');await both(()=>!duelSnapshot().adminPaused);await owner.click('#admin-close');
 let s=await snapshot(h),box=await h.locator('#game').boundingBox(),sc=Math.min(box.width/1280,box.height/720),enemy=s.fighters[1];await h.mouse.move(box.x+(box.width-1280*sc)/2+((enemy.x-s.camera.x)*s.camera.zoom+640)*sc,box.y+(box.height-720*sc)/2+((enemy.y-71.1-s.camera.y)*s.camera.zoom+360)*sc);await h.keyboard.press('KeyJ');await both(()=>duelSnapshot().score[0]===1&&duelSnapshot().round===2);A.equal((await snapshot(g)).fighters[0].specialCharge,7);A.equal((await snapshot(g)).fighters[1].specialCharge,7);
 await owner.keyboard.press('NumpadMultiply');await owner.fill('#admin-rule-winningScore','1');await owner.click('#admin-apply');await both(()=>duelSnapshot().phase==='matchEnd');await owner.click('#admin-close');await h.click('#restart');await g.click('#restart');await both(()=>duelSnapshot().inMenu);await h.click('#ready-button');await g.click('#ready-button');await both(()=>duelSnapshot().intro.open);A((await snapshot(h)).fighters.every(f=>f.specialCharge===0));await Promise.all(pages.map(p=>p.click('#special-understood')));await both(()=>duelSnapshot().online.frame>20&&!duelSnapshot().inMenu);console.log('PASS configurable match, charge across rounds, rematch empty and same admin privileges');
 // Disconnect during the next description must close the modal too.
 await owner.keyboard.press('NumpadMultiply');await owner.fill('#admin-rule-winningScore','1');await owner.fill('#admin-pos-0-x','750');await owner.fill('#admin-pos-1-x','860');await owner.click('#admin-apply');await both(()=>!duelSnapshot().adminPending);await owner.click('#admin-close');
 await g.close();await h.waitForFunction(()=>duelSnapshot().inMenu,null,{timeout:15000});results.push({editions,confirmation,elapsed,passed:true});await Promise.all(contexts.map(c=>c.close()));pages=[];
}
try{await scenario([true,false],'early');await scenario([false,true],'one');await scenario([true,true],'none');A.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'online-result.json'),JSON.stringify({passed:true,environment:'Real PeerJS/WebRTC between isolated Chrome contexts on one PC',results,errors},null,2));}catch(e){for(let i=0;i<pages.length;i++)if(!pages[i].isClosed()){const s=await snapshot(pages[i]);console.error('SIDE',i,JSON.stringify({inMenu:s.inMenu,phase:s.phase,intro:s.intro,online:s.online,adminPaused:s.adminPaused,adminPending:s.adminPending,lastAdmin:s.lastAdmin,score:s.score,ruleSpeed:s.rules.speed}));await pages[i].screenshot({path:path.join(__dirname,'online-failure-'+i+'.png'),fullPage:true});}console.error('errors',errors);throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
