(function(){
class DuelPostFX{
 constructor(){try{this.canvas=document.createElement('canvas');this.gl=this.canvas.getContext('webgl',{alpha:false,antialias:false,preserveDrawingBuffer:true,depth:false,stencil:false});const gl=this.gl;if(!gl)return;const shader=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;},program=this.program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec2 p;varying vec2 uv;void main(){uv=p*.5+.5;gl_Position=vec4(p,0.,1.);}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,`precision mediump float;varying vec2 uv;uniform sampler2D scene;uniform vec2 texel;
vec3 bright(vec2 p){vec3 c=texture2D(scene,p).rgb;float l=max(c.r,max(c.g,c.b));return c*smoothstep(.65,.96,l);}
void main(){vec3 bloom=bright(uv)*.13;for(int i=0;i<8;i++){float a=float(i)*.785398;vec2 d=vec2(cos(a),sin(a))*texel;bloom+=bright(uv+d*5.)*.058;bloom+=bright(uv+d*14.)*.027;}gl_FragColor=vec4(bloom*1.05,1.);}`));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('Bloom indisponível');gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const loc=gl.getAttribLocation(program,'p');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);this.tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,this.tex);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);this.down=document.createElement('canvas');this.downCtx=this.down.getContext('2d');this.available=true;}catch{this.available=false;}}
 draw(r){const out=r.ctx,w=r.canvas.width,h=r.canvas.height;out.save();out.setTransform(1,0,0,1,0,0);if(this.available){try{const gl=this.gl,scale=Math.min(.65,1024/w),tw=Math.max(1,Math.round(w*scale)),th=Math.max(1,Math.round(h*scale));if(this.canvas.width!==tw||this.canvas.height!==th){this.canvas.width=this.down.width=tw;this.canvas.height=this.down.height=th;}this.downCtx.drawImage(r.canvas,0,0,tw,th);gl.viewport(0,0,tw,th);gl.useProgram(this.program);gl.bindTexture(gl.TEXTURE_2D,this.tex);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,this.down);gl.uniform2f(gl.getUniformLocation(this.program,'texel'),1/tw,1/th);gl.drawArrays(gl.TRIANGLES,0,6);out.globalCompositeOperation='screen';out.globalAlpha=r.lighting.palette(r.gameView).daylight?.22:.75;out.drawImage(this.canvas,0,0,w,h);}catch{this.available=false;}}out.globalCompositeOperation='soft-light';out.globalAlpha=r.lighting.palette(r.gameView).daylight?.07:.18;const grade=out.createLinearGradient(0,0,w,h);grade.addColorStop(0,'#5786c8');grade.addColorStop(1,'#ec9b76');out.fillStyle=grade;out.fillRect(0,0,w,h);out.restore();}
}
window.DuelPostFX=DuelPostFX;
})();
