const fs=require('fs'),A=require('node:assert/strict'),{chromium}=require('C:/Users/Luiz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=__dirname;
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),p=await b.newPage({viewport:{width:1440,height:980}}),errs=[];p.on('pageerror',e=>errs.push(e.message));const snap=()=>p.evaluate(()=>duelSnapshot());try{
await p.goto('http://127.0.0.1:4182/um-corte-v6.2-admin.html');await p.waitForFunction(()=>window.duelSnapshot);A.equal((await snap()).version,62);
// Ordinary hover and click are separate from the held swipe.
const letter=p.locator('#title-logo [data-cut]').first(),box=await letter.boundingBox(),y=box.y+box.height*.5;await p.mouse.move(box.x-10,y);await p.mouse.move(box.x+box.width+10,y,{steps:8});A.equal(await letter.getAttribute('data-sliced'),null);await p.mouse.move(box.x-10,y);await p.mouse.down();await p.mouse.move(box.x+box.width+10,y,{steps:4});A.equal(await letter.getAttribute('data-sliced'),'1');await p.mouse.up();await p.screenshot({path:root+'/title-cut.png'});await p.waitForFunction(()=>!document.querySelector('#title-logo [data-cut]').dataset.sliced);
const play=await p.locator('#title-play').boundingBox();await p.mouse.move(play.x+20,play.y+play.height/2);await p.mouse.down();await p.mouse.move(play.x+play.width-10,play.y+play.height/2,{steps:5});await p.mouse.up();A.equal((await snap()).titleOpen,true);await p.click('#title-play');await p.waitForFunction(()=>!duelSnapshot().titleOpen);await p.waitForTimeout(300);console.log('PASS hover, held slash, letter reconstruction and cut-vs-click');
await p.click('#settings-button');await p.selectOption('#graphics-quality','ultra');await p.uncheck('#graphics-shadows');await p.check('#graphics-reduced');await p.click('#close-settings');await p.reload();await p.waitForFunction(()=>window.duelSnapshot);A.deepEqual((await snap()).graphics,{quality:'ultra',shadows:false,reduced:true});await p.click('#title-play');await p.waitForFunction(()=>!duelSnapshot().titleOpen);await p.click('#settings-button');await p.check('#graphics-shadows');await p.uncheck('#graphics-reduced');await p.click('#close-settings');console.log('PASS Ultra, independent shadows, reduced effects and persistence');
// Exact preset rules survive export/import and require an explicit apply.
await p.click('#rules-details summary');await p.fill('#preset-name','Meu torneio');await p.click('[data-preset="turbo"]');await p.fill('#number-winningScore','7');await p.locator('#number-winningScore').press('Tab');await p.selectOption('#chaos-mode','normal');await p.click('#preset-save');A.equal(await p.locator('#preset-library option').textContent(),'Meu torneio');const download=p.waitForEvent('download');await p.click('#preset-export');const d=await download;await d.saveAs(root+'/test-preset.json');const rules=JSON.parse(fs.readFileSync(root+'/test-preset.json')).rules;await p.click('#reset-rules');A.notDeepEqual((await snap()).rules,rules);await p.setInputFiles('#preset-file',root+'/test-preset.json');await p.locator('#preset-review').waitFor({state:'visible'});A.equal(await p.locator('#preset-review').isVisible(),true);A.notDeepEqual((await snap()).rules,rules);const beforeMap=(await snap()).mapId;await p.click('#preset-accept');await p.click('#preset-save');A.equal((await snap()).mapId,beforeMap);const exported=p.waitForEvent('download');await p.click('#preset-export');await(await exported).saveAs(root+'/test-preset-roundtrip.json');A.deepEqual(JSON.parse(fs.readFileSync(root+'/test-preset-roundtrip.json')).rules,rules);await p.click('#reset-rules');console.log('PASS named preset save, import review and exact export roundtrip');
// Map editor: actual visual props + weather, no regression of save/import/test.
await p.click('#editor-button');await p.selectOption('#editor-weather','petals');await p.click('[data-tool="bell"]');const eb=await p.locator('#editor-canvas').boundingBox();await p.mouse.click(eb.x+eb.width*.5,eb.y+eb.height*.5);await p.click('[data-tool="bamboo"]');await p.mouse.click(eb.x+eb.width*.7,eb.y+eb.height*.62);await p.screenshot({path:root+'/editor-v2.png'});const mapdl=p.waitForEvent('download');await p.click('#editor-export');await(await mapdl).saveAs(root+'/test-map.umcorte.json');const map=JSON.parse(fs.readFileSync(root+'/test-map.umcorte.json'));A.equal(map.decor.length,2);A.equal(map.weather,'petals');await p.click('#editor-new');await p.setInputFiles('#editor-file',root+'/test-map.umcorte.json');await p.waitForFunction(()=>document.querySelector('#editor-weather').value==='petals');await p.click('#editor-test');await p.waitForFunction(()=>!duelSnapshot().inMenu);if(await p.locator('#special-intro').isVisible())await p.click('#special-understood');A.equal((await snap()).propStates.length,2);await p.click('#editor-return');await p.click('#editor-close');A.equal(await p.locator('#map-choices button').last().getAttribute('data-map'),'random');console.log('PASS editor decoration placement, weather, export/import and test');
await p.click('[data-mode="training"]');await p.click('[data-map="bells"]');await p.click('#start');await p.click('#special-understood');await p.keyboard.press('NumpadMultiply');A((await snap()).paused);await p.locator('#admin-rule-speed').focus();await p.keyboard.press('NumpadMultiply');A(await p.locator('#admin-console').isVisible());await p.locator('#admin-close').focus();await p.keyboard.press('NumpadMultiply');A(!await p.locator('#admin-console').isVisible());await p.keyboard.press('*');A(await p.locator('#admin-console').isVisible());const original=await snap();await p.click('[data-admin-preview="finisher"]');await p.waitForFunction(()=>duelSnapshot().preview?.animation==='finisher');await p.screenshot({path:root+'/admin-preview.png'});await p.click('[data-admin-preview="perfect"]');await p.waitForFunction(()=>duelSnapshot().perfect>0);await p.click('[data-admin-preview="stop"]');const after=await snap();A.deepEqual(after.fighters,original.fighters);A.deepEqual(after.metrics,original.metrics);A.deepEqual(after.score,original.score);await p.click('#admin-close');console.log('PASS paused ADMIN visual previews preserve actors, score and stats');A.deepEqual(errs,[]);fs.writeFileSync(root+'/ui-result.json',JSON.stringify({passed:true,errors:errs,checks:['menu cut vs click','preferences persistence','preset export/import','editor roundtrip','random map last','asterisk shortcut and typing exclusion','ADMIN previews']},null,2));
}catch(e){console.error(errs);await p.screenshot({path:root+'/ui-failure.png',fullPage:true});throw e;}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
