const fs=require('fs'),r=__dirname;function edit(f,a,b){let s=fs.readFileSync(r+'/'+f,'utf8');if(!s.includes(a))throw Error(f+' missing '+a.slice(0,80));fs.writeFileSync(r+'/'+f,s.replace(a,b));}
for(const file of['build.cjs','serve.cjs']){let s=fs.readFileSync(r+'/'+file,'utf8').replaceAll('um-corte-v6','um-corte-v6.2').replaceAll('UM-CORTE-V6','UM-CORTE-V6.2').replaceAll('4180','4182');fs.writeFileSync(r+'/'+file,s);}
edit('build.cjs',"['APP','app.js']", "['TOURNAMENT','tournament.js'],['DAYLIGHT','daylight.js'],['APP','app.js']");edit('build.cjs',"'v6.css']", "'v6.css','v62.css']");
let shell=fs.readFileSync(r+'/shell.html','utf8').replaceAll('um-corte-v6.html','um-corte-v6.2.html').replaceAll('UM-CORTE-V6.html','UM-CORTE-V6.2.html').replace('V6 · CADA CORTE TEM UMA HISTÓRIA.','V6.2 · UM CAMINHO ATÉ O TÍTULO.').replace('versão V6.','versão V6.2.').replace('UM CORTE VI · O instante que decide','UM CORTE V6.2 · Um caminho até o título');
const start=shell.indexOf('<section class="custom-presets">'),end=shell.indexOf('</section>',start)+10;let block=shell.slice(start,end).replace('SUAS REGRAS, SEU NOME','SALVAR E COMPARTILHAR REGRAS').replace('placeholder="TURBO DO LUIZ"','placeholder="Nome do preset"');shell=shell.slice(0,start)+shell.slice(end);const rulesEnd=shell.indexOf('</details>',shell.indexOf('<details id="rules-details"'));shell=shell.slice(0,rulesEnd)+block+shell.slice(rulesEnd);
shell=shell.replace('<button data-mode="local"', '<button data-mode="tournament" class="mode" aria-pressed="false">Torneio <small>Eliminação · IA</small></button><button data-mode="local"');
shell=shell.replace('<div class="map-section">',`<section id="tournament-setup" class="tournament-setup" hidden><div><span class="eyebrow">UMA DERROTA ENCERRA SUA TENTATIVA</span><h2>Um personagem. Até o fim.</h2><p>Escolha sua classe e as regras antes de entrar na chave. Os adversários são sorteados.</p></div><div class="tournament-fields"><label for="tournament-stages">Duelos até conquistar o título<select id="tournament-stages"><option value="1">1 duelo · 2 participantes</option><option value="2">2 duelos · 4 participantes</option><option value="3" selected>3 duelos · 8 participantes</option><option value="4">4 duelos · 16 participantes</option><option value="5">5 duelos · 32 participantes</option></select></label><label for="tournament-map-mode">Arenas<select id="tournament-map-mode"><option value="choose">Escolher antes de cada duelo</option><option value="fixed">Manter a arena selecionada</option><option value="random">Aleatórias · sem repetição</option></select></label></div><small>Escolha a dificuldade abaixo. Partidas entre os outros bots são simuladas para completar a chave e a classificação.</small></section><div class="map-section">`);
shell=shell.replace('/* APP */','/* TOURNAMENT */</script><script>/* DAYLIGHT */</script><script>/* APP */');
shell=shell.replace('<details open><summary>V6 · Cada corte tem uma história — atual</summary>',`<details open><summary>V6.2 · Um caminho até o título — atual</summary><p>Torneio eliminatório contra IA: de 1 a 5 duelos até o título, classe fixa, dificuldade escolhida, arenas por duelo, fixa ou aleatórias sem repetição. Chave e classificação completa ao fim da tentativa.</p><p>Ponte quebrada reconstruída como cânion ensolarado, Ruínas de arenito no deserto e Santuário Suspenso diurno e vibrante. Novas finalizações com movimentos, cortes que atravessam a cena e dissipação.</p><p>Cursor invisível na tela inicial, rastro afiado, miniatura aleatória neutra, presets pessoais ao final da personalização. Carga especial mantida entre rounds por padrão, impact frame do Perfect Parry de 110 ms e atalho ADMIN na tecla asterisco (*).</p></details><details><summary>V6 · Cada corte tem uma história</summary>`);
shell=shell.replace('<!-- ADMIN_HTML -->',`<dialog id="tournament-screen" class="tournament-screen"><header><div><span id="tournament-eyebrow" class="eyebrow"></span><h2 id="tournament-title"></h2><p id="tournament-caption"></p></div><span class="tournament-mark" aria-hidden="true">一</span></header><div id="tournament-duel"><div id="tournament-fighters" class="tournament-fighters"></div><label id="tournament-arena-label">Arena do próximo duelo<select id="tournament-arena"></select></label><p id="tournament-arena-note"></p><div class="tournament-actions"><button id="tournament-fight" class="primary">EM GUARDA ↗</button><button id="tournament-quit" class="text-button">ABANDONAR TORNEIO</button></div><details><summary>CHAVE DO TORNEIO</summary><div id="tournament-bracket"></div></details></div><div id="tournament-results" hidden><div class="tournament-table-wrap"><table><thead><tr><th>POS.</th><th>PARTICIPANTE</th><th>FASE</th><th>VITÓRIAS</th><th>ROUNDS</th></tr></thead><tbody id="tournament-ranking"></tbody></table></div><p class="fine-print">Classificação por fase alcançada; na mesma fase: saldo de rounds, rounds vencidos e sorteio inicial. Os outros confrontos de bots são simulados.</p><div class="tournament-actions"><button id="tournament-new" class="primary">NOVO TORNEIO ↗</button><button id="tournament-menu" class="secondary">VOLTAR AO MENU</button></div></div></dialog><!-- ADMIN_HTML -->`);
fs.writeFileSync(r+'/shell.html',shell);
edit('engine.js',"['persistSpecial',false]", "['persistSpecial',true]");edit('engine.js','o.persistSpecial=r.persistSpecial===true','o.persistSpecial=r.persistSpecial!==false');
let engine=fs.readFileSync(r+'/engine.js','utf8').replaceAll('version:60','version:62').replaceAll('version!==60','version!==62');fs.writeFileSync(r+'/engine.js',engine);
let net=fs.readFileSync(r+'/network.js','utf8').replace('VERSION = 60','VERSION = 62').replace('umcorte-v6-','umcorte-v62-');fs.writeFileSync(r+'/network.js',net);
edit('admin.js',"CTRL + SHIFT + F10", "TECLA *");edit('admin.js',"if(e.code==='F10'&&e.ctrlKey&&e.shiftKey){", "if((e.key==='*'||e.code==='NumpadMultiply')&&!e.repeat&&!['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)&&!e.target.isContentEditable){");
edit('lighting.js','window.DuelLighting=DuelLighting;','DuelLighting.palettes=palettes;window.DuelLighting=DuelLighting;');
edit('app.js',"effects.impact=renderer.reduced?.015:.07", "effects.impact=renderer.reduced?.015:.11");edit('app.js',"ev.perfect?.075:.045", "ev.perfect?.11:.045");
edit('app.js',"sound(ev.type);if(ev.type==='parry'){effects.impact=renderer.reduced?.025:.06;", "sound(ev.type,ev);if(ev.type==='parry'){effects.perfect=ev.perfect?.42:0;effects.impact=renderer.reduced?.015:ev.perfect?.11:.045;");
edit('app.js',"preview.style.background='linear-gradient('+theme.sky[0]+','+theme.sky[1]+')';", "preview.style.background=k==='random'?'linear-gradient(#eee9db,#efddbf)':'linear-gradient('+theme.sky[0]+','+theme.sky[1]+')';");edit('app.js','tag.textContent=theme.tag;', "tag.textContent=k==='random'?'SURPRESA A CADA DUELO':theme.tag;");
edit('post-fx.js','out.globalAlpha=.75;', "out.globalAlpha=r.lighting.palette(r.gameView).daylight?.22:.75;");edit('post-fx.js','out.globalAlpha=.18;', "out.globalAlpha=r.lighting.palette(r.gameView).daylight?.07:.18;");
let menu=fs.readFileSync(r+'/menu-fx.js','utf8'),a=menu.indexOf('for(let i=1;i<this.trail.length;i++){'),b=menu.indexOf('c.globalAlpha=1;}else{this.trail=[]',a);if(a<0||b<0)throw Error('trail');menu=menu.slice(0,a)+'this.drawTrail(c,ms);'+menu.slice(b);menu=menu.replace(' frame(ms){',` drawTrail(c,ms){if(this.trail.length<2)return;const raw=this.trail,points=[];for(let i=0;i<raw.length-1;i++){points.push(raw[i]);points.push({x:(raw[i].x+raw[i+1].x)/2,y:(raw[i].y+raw[i+1].y)/2,cut:raw[i+1].cut,t:(raw[i].t+raw[i+1].t)/2});}points.push(raw.at(-1));const cut=points.some(p=>p.cut),sides=[[],[]];for(let i=0;i<points.length;i++){const p=points[i],a=points[Math.max(0,i-1)],b=points[Math.min(points.length-1,i+1)],dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1,u=i/(points.length-1),w=Math.pow(Math.sin(u*Math.PI),.85)*(cut?5.5:.65);sides[0].push({x:p.x-dy/len*w,y:p.y+dx/len*w});sides[1].push({x:p.x+dy/len*w,y:p.y-dx/len*w});}c.save();c.globalAlpha=cut?.9:.24;c.fillStyle=cut?'#fff3d1':'#bddae2';c.beginPath();const edge=sides[0].concat(sides[1].reverse());c.moveTo(edge[0].x,edge[0].y);for(let i=1;i<edge.length-1;i++)c.quadraticCurveTo(edge[i].x,edge[i].y,(edge[i].x+edge[i+1].x)/2,(edge[i].y+edge[i+1].y)/2);c.lineTo(edge.at(-1).x,edge.at(-1).y);c.closePath();c.fill();if(cut){c.lineCap='round';c.lineJoin='round';c.lineWidth=.7;c.strokeStyle='#ffffff';c.beginPath();c.moveTo(points[0].x,points[0].y);for(const p of points)c.lineTo(p.x,p.y);c.stroke();}c.restore();}
 frame(ms){`);fs.writeFileSync(r+'/menu-fx.js',menu);
