const {chromium}=require('C:/Users/Luiz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),A=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),errors=[];try{
 const p=await b.newPage({viewport:{width:1600,height:1000}});p.on('pageerror',e=>errors.push(e.stack));
 await p.addInitScript(()=>{let ctor;Object.defineProperty(window,'DuelMenuFX',{configurable:true,get:()=>ctor,set:v=>{ctor=v;const frame=v.prototype.frame;v.prototype.frame=function(ms){if(!window.qaRain){window.qaRain=this;this.scene={name:'CHUVA SOBRE OS TELHADOS',sky:['#10172e','#374761'],accent:'#9ac1e3',weather:'rain'};this.objects=[];this.title.classList.remove('light-menu');document.querySelector('#title-scene-name').textContent=this.scene.name;}return frame.call(this,ms);};}});});
 await p.goto('http://127.0.0.1:4188/um-corte-v7.2.html');await p.waitForTimeout(1100);
 for(const [w,h]of [[1600,1000],[1280,720],[390,844]]){await p.setViewportSize({width:w,height:h});await p.waitForTimeout(350);await p.screenshot({path:`outputs/v72-rain-${w}.png`});A(await p.locator('#title-play').isVisible());const rain=await p.evaluate(()=>({drops:qaRain.rainDrops.length,parts:qaRain.rainSplashes.length,finite:qaRain.rainDrops.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)),overflow:document.documentElement.scrollWidth>innerWidth}));A(rain.drops<=210&&rain.parts<=48&&rain.finite);A(!rain.overflow);}
 await p.setViewportSize({width:1600,height:1000});const logo=await p.locator('[data-cut]').first().boundingBox();await p.mouse.move(logo.x,logo.y+logo.height/2);await p.mouse.down();await p.mouse.move(logo.x+logo.width,logo.y+logo.height/2,{steps:8});await p.mouse.up();A(await p.locator('#title-screen').isVisible());await p.waitForTimeout(700);await p.locator('#title-play').click();await p.waitForTimeout(350);
 A.equal(await p.evaluate(()=>duelSnapshot().release),'7.2');await p.locator('[data-mode="parkour"]').click();A.equal(await p.locator('#player-characters .character').count(),1);A.equal(await p.locator('#player-characters .selected').getAttribute('data-kind'),'runner');await p.screenshot({path:'outputs/v72-runner-selection.png'});
 await p.locator('#race-classes').check();A.equal(await p.locator('#player-characters .character').count(),9);A.equal(await p.locator('#player-characters .selected').getAttribute('data-kind'),'runner');await p.locator('#player-characters [data-kind="reaper"]').click();await p.locator('#race-classes').uncheck();A.equal(await p.locator('#player-characters .selected').getAttribute('data-kind'),'runner');await p.locator('#race-count').fill('1');await p.locator('#start').click();await p.waitForFunction(()=>duelSnapshot().phase==='playing');
 await p.keyboard.down('KeyW');await p.waitForFunction(()=>duelSnapshot().fighters[0].vy<-200);await p.waitForTimeout(120);await p.keyboard.up('KeyW');await p.keyboard.down('Space');await p.waitForFunction(()=>duelSnapshot().fighters[0].airJumps===0);await p.keyboard.up('Space');await p.waitForTimeout(80);await p.keyboard.down('KeyW');await p.keyboard.down('ShiftLeft');await p.waitForTimeout(45);const f=await p.evaluate(()=>duelSnapshot().fighters[0]);A.equal(f.airJumps,0);A.equal(f.dashY,-1);await p.keyboard.up('ShiftLeft');await p.keyboard.up('KeyW');await p.waitForTimeout(140);A.equal((await p.evaluate(()=>duelSnapshot())).fighters[0].airJumps,0);await p.waitForTimeout(900);await p.locator('#race-pause').click();await p.locator('#pause-menu').click();await p.locator('[data-mode="training"]').click();A.equal(await p.locator('#player-characters [data-kind="runner"]').count(),0);A.equal(await p.locator('#player-characters .selected').getAttribute('data-kind'),'knight');
 await p.locator('#rules-details summary').click();A.equal(await p.locator('#rule-mapSize').inputValue(),'1');A.equal(await p.locator('#rule-dashCooldown').inputValue(),'320');await p.locator('#specials-enabled').uncheck();await p.locator('#start').click();await p.waitForFunction(()=>duelSnapshot().phase==='playing'&&duelSnapshot().countdown===0);await p.keyboard.down('Space');await p.waitForTimeout(150);await p.keyboard.up('Space');await p.keyboard.down('KeyW');await p.waitForFunction(()=>duelSnapshot().fighters[0].airJumps===0);await p.keyboard.up('KeyW');await p.waitForTimeout(1100);A.equal((await p.evaluate(()=>duelSnapshot())).fighters[0].airJumps,1);
 console.log('PASS V7.2 browser: rain 3 resolutions, cut/click, Runner 1/9 cards, W/Space, air dash priority, training, standard rules');A.equal(errors.length,0,errors.join('\n'));
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1);});
