const A=require('node:assert/strict'),D=require('./engine.js'),{Game,neutral}=D;let checks=0;const n=o=>({...neutral(),...o}),make=o=>{const g=new Game({mode:'local',...o,rules:{mapSize:2/3,...o?.rules}});g.start();return g;},tick=(g,t,inputs=[n(),n({aim:Math.PI})])=>{for(let i=0;i<Math.ceil(t*600);i++)g.step(1/600,inputs);};
function check(name,fn){fn();checks++;console.log('PASS',name);}
check('boxer has shortest reach and modest speed advantage',()=>{A(Math.abs(D.CLASSES.boxer.reach-D.CLASSES.assassin.reach*.75)<1e-8);A.equal(D.CLASSES.boxer.speed,D.CLASSES.assassin.speed*1.05);});
check('parry unlocks two seconds of held alternating punches with no recovery',()=>{const g=make({characters:['boxer','knight'],rules:{specials:true}}),f=g.fighters[0];f.specialCharge=15;A(g.special(0));A.equal(f.ultMode,'boxerGuard');f.x=570;const e=g.fighters[1];e.x=680;A(g.parry(0));e.attackAim=Math.PI;e.attackId=1;g.setState(e,'active',.15);e.stateTime=.07;g.resolveCombat();A.equal(f.ultMode,'boxerRush');A.equal(f.ultTime,2);e.x=1000;const hands=[],states=new Set();let count=0;for(let i=0;i<1300;i++){g.step(1/600,[n({attackHeld:true}),n({aim:Math.PI})]);if(f.ultMode==='boxerRush')states.add(f.state);for(const ev of g.events.splice(0))if(ev.type==='windup'&&ev.id===0){count++;hands.push(f.punch);}}A(count>20&&count<40,count);A(!states.has('recovery'));A(hands.every((v,i)=>i===0||v!==hands[i-1]));A.equal(f.ultMode,'');const attacks=g.attackCounter;tick(g,.6,[n({attackHeld:true}),n()]);A.equal(g.attackCounter,attacks);});
check('missed boxer parry locks dash and recharge waits',()=>{const g=make({characters:['boxer','knight'],rules:{specials:true,boxerWindow:100}}),f=g.fighters[0];f.specialCharge=15;g.special(0);tick(g,.12);A(f.dashLock>2.97);A(!g.dash(0));A.equal(f.specialCharge,0);tick(g,3.1);A(g.dash(0));});
check('every skin keeps identical attack and body geometry',()=>{for(const[k,v]of Object.entries(D.SKINS)){const g=make({characters:[k,k],skins:['default',v.id]});for(const f of g.fighters)Object.assign(f,{x:500,y:500,attackAim:.72,state:'active',stateTime:.035,duration:.1});A.deepEqual(D.slash(g.fighters[0]),D.slash(g.fighters[1]));A.deepEqual(D.body(g.fighters[0]),D.body(g.fighters[1]));}});
const map={format:'um-corte-map',version:1,id:'custom_test',name:'Teste',width:1280,height:720,theme:'bamboo',platforms:[{x:40,y:610,w:1200,solid:true},{x:300,y:420,w:170,motion:{x:250,y:-120,period:1,pause:.2},fragile:{delay:.3,respawn:.5}}],walls:[{x:100,y:420,w:30,h:190}],spawns:[{x:385,y:610},{x:895,y:610}],background:{layers:[],shade:.2,tint:'#172838'},ground:'#687767'};
check('custom maps validate and reject unsafe / malformed input',()=>{D.registerMap(map);A.throws(()=>D.cleanMap({...map,width:Infinity}));A.throws(()=>D.cleanMap({...map,background:{layers:[{image:'https://invalid/image.png'}]}}));A.throws(()=>D.cleanMap({...map,platforms:[{x:1270,y:400,w:80}]}));A.equal(D.mapWarnings(map).length,0);});
check('moving platforms travel A-B with pauses and carry standing players',()=>{const g=make({mapId:map.id}),p=g.map.platforms[1],f=g.fighters[0];Object.assign(f,{x:350,y:420,platform:1,grounded:true});p.fragile=null;tick(g,.1);A.equal(p.x,300);tick(g,.5);A(p.x>380);A(f.x>430);A.equal(f.y,p.y);tick(g,.6);A(Math.abs(p.x-550)<1);});
check('fragile platforms collapse, do not restore through a player, reset per round',()=>{const g=make({mapId:'sanctuary'}),p=g.map.platforms[2],f=g.fighters[0];Object.assign(f,{x:400,y:p.y,platform:2,grounded:true});tick(g,.81);A.equal(p.stage,'gone');A(!f.grounded);f.x=400;f.y=p.y;g.updatePlatforms(g.time+4.1);A.equal(p.stage,'gone');f.x=100;g.updatePlatforms(g.time+4.2);A.equal(p.stage,'solid');p.stage='gone';g.resetFighters();A.equal(p.stage,'solid');});
check('custom map moving / collapsing snapshots replay deterministically',()=>{const g=make({mapId:map.id,characters:['boxer','knight'],skins:['yuji','hollow']}),h=make();tick(g,.3);g.map.platforms[1].stage='cracking';g.map.platforms[1].crumbleAt=g.time;h.loadSnapshot(g.snapshot());for(let i=0;i<900;i++){const inp=[n({move:i<100?1:0,jump:i===140}),n({aim:Math.PI})];g.step(1/600,inp);h.step(1/600,inp);}A.deepEqual(g.snapshot(),h.snapshot());});
console.log(checks+' V4.2 feature groups passed');
