const {chromium}=require('C:/Users/Luiz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--allow-file-access-from-files']});
 const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.join(__dirname,'../outputs/um-corte.html')).href);
 await page.waitForFunction(()=>typeof window.duelSnapshot==='function');
 await page.screenshot({path:path.join(__dirname,'title.png')});
 await page.locator('#start').click();
 assert.equal((await page.evaluate(()=>duelSnapshot())).phase,'playing');
 await page.keyboard.down('KeyD');await page.waitForTimeout(420);await page.keyboard.up('KeyD');
 let snap=await page.evaluate(()=>duelSnapshot());assert.ok(snap.fighters[0].x>480);
 await page.keyboard.press('Shift');await page.waitForTimeout(90);snap=await page.evaluate(()=>duelSnapshot());assert.ok(snap.fighters[0].dashCooldown>0);
 await page.waitForTimeout(100);await page.keyboard.press('KeyJ');await page.waitForTimeout(40);snap=await page.evaluate(()=>duelSnapshot());assert.equal(snap.fighters[0].state,'startup');
 await page.screenshot({path:path.join(__dirname,'combat.png')});
 await page.keyboard.press('Escape');assert.equal((await page.evaluate(()=>duelSnapshot())).paused,true);
 const before=await page.evaluate(()=>duelSnapshot());await page.waitForTimeout(250);assert.deepEqual(await page.evaluate(()=>duelSnapshot()),before);
 await page.screenshot({path:path.join(__dirname,'pause.png')});
 await page.keyboard.press('Escape');assert.equal((await page.evaluate(()=>duelSnapshot())).paused,false);
 await page.locator('#sound').click();assert.equal(await page.locator('#sound-state').innerText(),'OFF');
 await page.waitForTimeout(1500);
 console.log('Snapshot after play',await page.evaluate(()=>duelSnapshot()));
 await page.screenshot({path:path.join(__dirname,'playing.png')});
 await page.setViewportSize({width:900,height:700});await page.screenshot({path:path.join(__dirname,'small.png')});
 await page.setViewportSize({width:390,height:844});await page.keyboard.press('Escape');await page.screenshot({path:path.join(__dirname,'mobile.png')});
 console.log('UI errors',errors);assert.deepEqual(errors,[]);
 await browser.close();console.log('Browser checks passed.');
})().catch(e=>{console.error(e);process.exit(1)});
