const fs=require('fs'),r='work/v6/';function edit(f,a,b){let s=fs.readFileSync(r+f,'utf8');if(!s.includes(a))throw Error(f+' missing '+a.slice(0,70));fs.writeFileSync(r+f,s.replace(a,b));}
edit('engine.js',"for(const k of['resetFighters','step','emit','finish','snapshot','loadSnapshot','adminApply'])v6original", "for(const k of['resetFighters','step','emit','finish','snapshot','loadSnapshot','adminApply','resolveCombat'])v6original");
edit('engine.js',"Game.prototype.step=function(dt,inputs){const active=this.phase==='playing'&&this.hitstop<=0;v6original.step.call(this,dt,inputs);if(active&&this.phase==='playing')this.touchProps();};", "Game.prototype.resolveCombat=function(){this.touchProps();return v6original.resolveCombat.call(this);};");
edit('admin.js',"this.send({action:'preview',id:+$('admin-preview-player').value,animation:b.dataset.adminPreview});", "if(this.send({action:'preview',id:+$('admin-preview-player').value,animation:b.dataset.adminPreview}))$('admin-console').classList.toggle('previewing',b.dataset.adminPreview!=='stop');");
edit('admin.js',"this.opened=true;this.draw();", "this.opened=true;$('admin-console').classList.remove('previewing');this.draw();");
edit('admin.html','data-admin-preview="stop">PARAR','data-admin-preview="stop">PARAR / PAINEL');
fs.appendFileSync(r+'v6.css','\n.admin-console.previewing{position:fixed;inset:auto 16px 16px auto;margin:0;width:360px;max-height:260px;padding:16px;background:#eee6d9ed}.admin-console.previewing::backdrop{background:transparent}.admin-console.previewing #admin-fields,.admin-console.previewing>.lab-buttons,.admin-console.previewing>p{display:none}.admin-console.previewing .admin-preview{margin:8px 0 0;padding:5px}\n');
edit('app.js',"function updateV5UI(drawn){", "function updateV5UI(drawn){for(const id of['preset-save','preset-load','preset-import','preset-accept'])$(id).disabled=configLocked();");
// Also allow cutting large menu headings without changing their click targets.
edit('app.js',"const menuFX=new DuelMenuFX", "for(const el of document.querySelectorAll('#menu h1,#menu h2,#pause h2,#match-title'))el.dataset.cut='';\nconst menuFX=new DuelMenuFX");
// Populate ambience immediately and draw irregular trees instead of rectangular poles.
edit('menu-fx.js',"this.objects=[];this.parts=[];", "this.objects=Array.from({length:40},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,size:3+Math.random()*6,vx:10+Math.random()*25,vy:20+Math.random()*35,angle:Math.random()*6,cut:false}));this.parts=[];");
edit('menu-fx.js',"for(let i=0;i<16;i++){c.fillRect(i*w/15,h*.15+(i%3)*50,7,h);}", "for(let layer=0;layer<2;layer++)for(let i=0;i<10;i++){const x=i*w/9+(layer?35:0),top=h*(.07+(i%3)*.035),base=x+Math.sin(i*9)*35;c.fillStyle=layer?'#0b1521':'#152733';c.beginPath();c.moveTo(base-12,h);c.lineTo(x-4,top);c.lineTo(x+5,top);c.lineTo(base+20,h);c.fill();c.strokeStyle=c.fillStyle;c.lineWidth=layer?6:3;for(let k=0;k<3;k++){const y=top+h*(.1+k*.12),sgn=(i+k)%2?1:-1;c.beginPath();c.moveTo(x,y+45);c.lineTo(x+sgn*50,y);c.lineTo(x+sgn*85,y-12);c.stroke();c.beginPath();c.ellipse(x+sgn*80,y-20,55,15,sgn*.2,0,7);c.fill();}} ");
