(function(){
const D=DuelCore,TAU=Math.PI*2;
DuelScenery.THEMES.bells={...DuelScenery.THEMES.tower,tag:'ECO DO ÚLTIMO GOLPE'};
DuelScenery.THEMES.rooftops={...DuelScenery.THEMES.bamboo,tag:'SOBRE OS TELHADOS'};
const sceneryDraw=DuelScenery.draw;
DuelScenery.draw=function(r,g,t){sceneryDraw.call(this,r,g,t);if(!['bells','rooftops'].includes(g.mapId))return;const c=r.ctx,off=(640-r.camera.x)*.055;c.save();if(g.mapId==='rooftops'){for(let layer=0;layer<3;layer++)for(let i=0;i<6;i++){const x=i*270-100+off*(layer+1),y=350+layer*100+(i%2)*24;c.fillStyle=['#17233b','#18273c','#142136'][layer];c.fillRect(x+20,y,195,720-y);r.path([[x-18,y],[x+117,y-62],[x+251,y],[x+213,y-5],[x+20,y-5]],'#101c30','#62728a33',2);for(let n=0;n<6;n++)r.line({x:x+n*42,y:y-2},{x:x+117+(n-3)*10,y:y-55},'#7794aa16',1);if(layer===1)for(let k=0;k<3;k++)c.fillStyle='#e9bb7935',c.fillRect(x+50+k*45,y+25,16,32);}}else{for(const x of[145,1110]){r.path([[x+off,565],[x+off+8,220],[x+off+36,220],[x+off+44,565]],'#192139aa');r.line({x:x+off-20,y:218},{x:x+off+70,y:218},'#927a9477',7);}r.path([[100+off,218],[182+off,175],[1125+off,175],[1198+off,218]],'#172037aa','#927a9450',2);for(const x of[425,855]){r.line({x:x+off,y:194},{x:x+off,y:350},'#b2a6c533',2);r.path([[x+off-3,220],[x+off+26,230],[x+off+22,345],[x+off+4,333]],'#96547144');}}c.restore();};
const rotate=(w,a)=>{const pivot=w.hand,at=p=>({x:pivot.x+(p.x-pivot.x)*Math.cos(a)-(p.y-pivot.y)*Math.sin(a),y:pivot.y+(p.x-pivot.x)*Math.sin(a)+(p.y-pivot.y)*Math.cos(a)});return{...w,angle:w.angle+a,a:at(w.a),b:at(w.b),segments:w.segments.map(s=>({a:at(s.a),b:at(s.b)})),shaft:w.shaft?{a:at(w.shaft.a),b:at(w.shaft.b)}:null};};
class DuelPresentation{
 static pose(r,f,w,t){r.idleHistory??=[];let h=r.idleHistory[f.id];if(!h||t<h.t||h.kind!==f.kind)h=r.idleHistory[f.id]={t,kind:f.kind,still:0,aim:f.aim,next:4+Math.random()*3,variant:0,gesture:-10};const dt=Math.min(.05,Math.max(0,t-h.t));h.t=t;const quiet=f.state==='idle'&&f.grounded&&Math.abs(f.vx)<5&&Math.abs(f.move||0)<.01&&Math.abs(f.aim-h.aim)<.012;h.still=quiet?h.still+dt:0;if(!quiet){h.next=4+Math.random()*3;h.gesture=-10;}h.aim=f.aim;let q={...f},a=0,dx=0,dy=0;const tense=r.gameView?.score.some(n=>n>=r.gameView.rules.winningScore-1);if(quiet&&tense){q.visualCrouch=3;q.visualLean=f.facing*2;a=Math.sin(t*3)*.018;}
 if(quiet&&!tense){if(h.still>=(h.next??4)){h.gesture=h.still;h.next=h.still+4+Math.random()*3;h.variant=1-(h.variant||0);}const phase=(h.still-(h.gesture??-10))/1.15;if(phase>=0&&phase<1){const v=Math.sin(phase*Math.PI),variant=h.variant;a=v*({knight:.16,lancer:.46,assassin:.7,swordsman:.2,reaper:.32,boxer:.12}[f.kind])*(variant?-1:1)*f.facing;q.visualLean=Math.sin(phase*TAU)*({boxer:4,assassin:2}[f.kind]||1.5);q.visualCrouch=v*(f.kind==='boxer'?3:1);dx=v*f.facing*({knight:-4,lancer:5,assassin:2,swordsman:-5,reaper:4,boxer:3}[f.kind]);dy=v*({knight:-5,lancer:4,assassin:-9,swordsman:8,reaper:5,boxer:-3}[f.kind]);if(f.kind==='assassin'&&variant)a=phase*TAU*f.facing;}}
 if(f.state==='parry'){const entry=1-D.clamp(f.stateTime/Math.min(.065,f.duration*.25||.065),0,1),exit=D.clamp((f.stateTime/f.duration-.85)/.15,0,1),amount={knight:.38,lancer:.7,assassin:.22,swordsman:.25,reaper:.5,boxer:.18}[f.kind];a=(-entry*amount+exit*.08)*f.guardFacing;q.visualLean=(1-entry)*f.guardFacing*3;q.visualCrouch=f.kind==='boxer'?5:2;dx=-entry*f.guardFacing*(f.kind==='lancer'?14:8);dy=entry*(f.guard==='high'?12:f.guard==='low'?-12:6);dx+=Math.sin(f.stateTime*18)*Math.exp(-f.stateTime*12)*f.guardFacing*2;}
 if(quiet&&r.gameView&&r.gameView.time-(f.lastPerfect??-100)<.24){const v=1-(r.gameView.time-f.lastPerfect)/.24;a+=Math.sin(v*Math.PI)*f.facing*.18;q.visualLean=-f.facing*v*2;}
 let visual=rotate(w,a);if(f.state==='parry'){const shoulder={x:f.x+f.facing*13*D.SCALE,y:f.y+(-85+(q.visualCrouch||0)+6)*D.SCALE},hx=visual.hand.x+dx-shoulder.x,hy=visual.hand.y+dy-shoulder.y,len=Math.hypot(hx,hy),limit=47*D.SCALE;if(len>limit){dx+=hx*(limit/len-1);dy+=hy*(limit/len-1);}}const shift=p=>({x:p.x+dx,y:p.y+dy});visual={...visual,hand:shift(visual.hand),a:shift(visual.a),b:shift(visual.b),segments:visual.segments.map(s=>({a:shift(s.a),b:shift(s.b)})),shaft:visual.shaft?{a:shift(visual.shaft.a),b:shift(visual.shaft.b)}:null};if(f.state==='parry')h.guardPose=visual;else if(f.state==='parryRecovery'&&h.guardPose){const k=D.clamp(f.stateTime/.14,0,1),blend=(a,b)=>({x:D.lerp(a.x,b.x,k),y:D.lerp(a.y,b.y,k)}),old=h.guardPose;visual={...visual,hand:blend(old.hand,visual.hand),angle:D.lerp(old.angle,visual.angle,k),a:blend(old.a,visual.a),b:blend(old.b,visual.b),segments:visual.segments.map((s,i)=>({a:blend(old.segments[i]?.a||s.a,s.a),b:blend(old.segments[i]?.b||s.b,s.b)})),shaft:visual.shaft&&old.shaft?{a:blend(old.shaft.a,visual.shaft.a),b:blend(old.shaft.b,visual.shaft.b)}:visual.shaft};}return{f:q,w:visual};}
 static prop(r,p,state,time,scale=1){const c=r.ctx,d=D.DECOR[p.type],age=Math.max(0,time-(state?.hitAt??-100)),hit=age<3,side=state?.side||1;c.save();c.translate(p.x*scale,p.y*scale);const sway=hit?Math.sin(age*9)*Math.exp(-age*1.3)*side*.3:0;
 if(state?.broken){if(p.type==='bamboo'){r.line({x:0,y:d.h-20},{x:0,y:d.h},'#688968',9);}if(age<.8){c.globalAlpha=1-age/.8;for(const s of[-1,1]){c.save();c.translate(s*age*40,age*age*140);c.rotate(s*age);c.fillStyle=p.type==='bamboo'?'#709b79':p.type==='lantern'?'#e5b17c':'#ac8275';c.fillRect(s<0?-d.w/2:0,0,d.w/2,d.h*.65);c.restore();}}c.restore();return;}
 c.rotate(sway);if(p.type==='bell'){r.line({x:0,y:-30},{x:0,y:0},'#a49376',3);r.path([[-25,8],[-20,0],[20,0],[25,8],[27,55],[35,65],[-35,65],[-27,55]],'#a88055','#252637',3);r.path([[-18,8],[-9,8],[-12,53],[-22,56]],'#d7b97d');r.line({x:-29,y:56},{x:29,y:56},'#3b3440',4);r.ellipse(0,68,8,5,'#e2bb79');if(hit){c.globalAlpha=Math.exp(-age*2)*.4;c.strokeStyle='#ffe9b0';c.lineWidth=1;for(const s of[-1,1]){c.beginPath();c.ellipse(s*(40+age*14),35,10+age*8,28+age*7,0,s<0?1.8:-1.3,s<0?4.5:1.3);c.stroke();}}}
 else if(p.type==='lantern'){r.line({x:0,y:-20},{x:0,y:0},'#303746',2);r.lighting?.glow(c,0,20,75,'#ffc587',.65);r.ellipse(0,19,12,18,'#e2a76b');r.line({x:-10,y:2},{x:10,y:2},'#55444d',4);r.line({x:-10,y:35},{x:10,y:35},'#55444d',4);r.line({x:0,y:3},{x:0,y:33},'#fff1bb',2);}
 else if(p.type==='bamboo'){r.line({x:0,y:0},{x:0,y:d.h},'#48725e',11);r.line({x:-3,y:0},{x:-3,y:d.h},'#94af81',2);for(let y=15;y<d.h;y+=25){r.line({x:-7,y},{x:7,y},'#bad39a',2);r.path([[0,y],[28,y-15],[12,y-5]],'#628f70');}}
 else if(p.type==='flag'){r.line({x:-5,y:-12},{x:-5,y:d.h},'#887a72',3);const wave=Math.sin(time*3+p.x)*5;r.path([[-3,0],[62,8+wave],[56,59+wave],[24,state&&state.hitAt>-99?30:62],[-3,55]],'#99576c','#2b3147',2);r.path([[3,5],[12,10],[10,47]],'#dba782');}
 else{r.path([[-10,0],[10,0],[8,10],[17,21],[12,41],[-12,41],[-17,21],[-8,10]],'#927b87','#293148',2);r.line({x:-12,y:20},{x:12,y:20},'#d6b596',3);}c.restore();}
 static props(r,g,t){for(let i=0;i<(g.map.decor||[]).length;i++)this.prop(r,g.map.decor[i],g.propStates?.[i],g.time,g.map.scale||1);const weather=g.map.weather;if(weather&&weather!=='none'&&!r.reduced){const c=r.ctx,count=r.lighting.settings.quality==='ultra'?75:r.lighting.settings.quality==='low'?12:32;c.save();for(let i=0;i<count;i++){const x=(i*193+t*(weather==='rain'?-40:10))%g.map.width,y=(i*127+t*(weather==='rain'?480:weather==='embers'?-30:30)+g.map.height*100)%g.map.height;c.globalAlpha=weather==='rain'?.16:.33;c.fillStyle=weather==='embers'?'#ffc279':weather==='petals'?'#eab7b3':'#c8e2df';if(weather==='rain'){r.line({x,y},{x:x-7,y:y+24},'#b2d0e6',1);}else c.fillRect(x,y,3,weather==='snow'?3:2);}c.restore();}}
 static ultra(r,g,t){if(r.lighting.settings.quality!=='ultra')return;const c=r.ctx;for(const l of r.lighting.lights||[]){const v=c.createLinearGradient(l.x,l.y,l.x,l.ground);v.addColorStop(0,l.color+'30');v.addColorStop(1,l.color+'02');r.path([[l.x-5,l.y],[l.x+5,l.y],[l.x+120,l.ground],[l.x-120,l.ground]],v);r.lighting.glow(c,l.x,l.y,270,l.color,.4);for(let i=0;i<5;i++){const y=l.ground+10+i*7;c.globalAlpha=.2-i*.03;r.line({x:l.x-14-i*6+Math.sin(t*2+i)*3,y},{x:l.x+14+i*6,y},l.color,2);}c.globalAlpha=1;}}
 static finale(r,e){const p=e.preview?.animation==='finisher'?{...e.preview,age:(performance.now()-e.preview.start)/1000,finisher:true}:e.fatal;if(!p?.finisher||p.age>1.1)return;
 const c=r.ctx,age=p.age,u=D.clamp((age-.025)/.24,0,1),fade=D.clamp((1.1-age)/.5,0,1),kind=p.kind||'knight',color={knight:'#ffe3ae',lancer:'#ffcda0',assassin:'#ffd8cf',swordsman:'#cddfff',reaper:'#e3c1ff',boxer:'#bffff0'}[kind],x=D.clamp(((p.x||r.camera.x)-r.camera.x)*r.camera.zoom+640,260,1020),y=D.clamp(((p.y||r.camera.y)-r.camera.y)*r.camera.zoom+360,180,490);
 c.save();c.setTransform(r.scale,0,0,r.scale,r.ox,r.oy);c.fillStyle='#050c1d';c.globalAlpha=.18*fade;c.fillRect(0,0,1280,720);c.globalAlpha=.65*fade;c.fillRect(0,0,1280,16);c.fillRect(0,704,1280,16);c.translate(x,y);c.globalAlpha=fade;const len=(kind==='assassin'?135:kind==='swordsman'?560:kind==='lancer'?720:400)*Math.sin(u*Math.PI/2),width=kind==='assassin'?5:kind==='swordsman'?17:11;
 if(p.cause==='QUEDA'){c.strokeStyle=color;c.lineWidth=2;for(let i=0;i<5;i++){const yy=-120+u*240+i*17;c.globalAlpha=fade*(1-i*.15);c.beginPath();c.moveTo(-35+i*15,yy-70);c.lineTo(-35+i*15,yy);c.stroke();}}
 else if(kind==='reaper'){for(let i=0;i<5;i++){c.strokeStyle=i===0?'#fffaee':color;c.globalAlpha=fade*(1-i*.18);c.lineWidth=i===0?5:2;c.beginPath();c.arc(0,0,80+u*145+i*6,-2.6,-2.6+u*4.3);c.stroke();}}
 else if(kind==='boxer'){for(let i=0;i<3;i++){c.strokeStyle=i===0?'#f3fff5':color;c.globalAlpha=fade*(1-i*.3);c.lineWidth=i===0?4:1;c.beginPath();c.ellipse(0,0,25+u*(150+i*35),15+u*(85+i*22),0,0,TAU);c.stroke();}for(let i=0;i<8;i++){const angle=i*TAU/8;r.line({x:Math.cos(angle)*(35+u*80),y:Math.sin(angle)*(25+u*45)},{x:Math.cos(angle)*(55+u*180),y:Math.sin(angle)*(30+u*100)},color,1);}}
 else{c.rotate(kind==='lancer'?0:kind==='knight'?-.6:kind==='swordsman'?-.35:.3);const grad=c.createLinearGradient(-len,0,len,0);grad.addColorStop(0,color+'00');grad.addColorStop(.3,color+'b0');grad.addColorStop(.53,'#fffdf5');grad.addColorStop(1,color+'00');r.path([[-len,0],[-len*.18,-width],[len,0],[len*.12,width*.45]],grad);r.line({x:-len,y:0},{x:len,y:0},'#fff9e9',1.5);c.globalAlpha=fade*.4;for(let i=0;i<3;i++)r.line({x:-len*.7+i*12,y:width+4+i*4},{x:len*.8-i*60,y:width+4+i*4},color,1);}
 c.setTransform(r.scale,0,0,r.scale,r.ox,r.oy);c.globalAlpha=fade;c.fillStyle='#f5e1b9';c.font='11px monospace';c.textAlign='center';c.fillText(p.cause==='QUEDA'?'A ÚLTIMA QUEDA':'O ÚLTIMO CORTE',640,590);c.restore();}

}
const draw=DuelRenderer.prototype.render,fighter=DuelRenderer.prototype.fighter,env=DuelLighting.prototype.environment,shadow=DuelLighting.prototype.shadow;
DuelLighting.prototype.environment=function(r,g,t){env.call(this,r,g,t);DuelPresentation.ultra(r,g,t);DuelPresentation.props(r,g,t);};
DuelLighting.prototype.shadow=function(r,g,f){if(this.settings.quality==='ultra'&&this.settings.shadows&&f.grounded){r.ctx.save();r.ctx.filter='blur(4px)';r.ellipse(f.x+12,f.y+8,39,8,'#02061770');r.ctx.restore();}shadow.call(this,r,g,f);};
DuelRenderer.prototype.fighter=function(f,t,w,portrait=false){if(portrait)return fighter.call(this,f,t,w,true);const e=this.effects?.preview;if(e&&e.id===f.id&&e.animation!=='stop'){const age=(performance.now()-e.start)/1000;if(age<3){f={...f,state:e.animation==='guard'?'parry':'idle',stateTime:age%1,duration:1,vx:0,move:0,grounded:true,aim:f.aim,guard:D.guardSector(f.aim,f.grounded),guardFacing:f.facing};t+=age;if(e.animation==='idle'){this.idleHistory??=[];this.idleHistory[f.id]={kind:f.kind,t,still:4+age%1.2,aim:f.aim,next:100,gesture:4,variant:0};}if(e.animation==='tense')f.visualCrouch=4;w=D.blade(f);}}
 const pose=DuelPresentation.pose(this,f,w,t);fighter.call(this,pose.f,t,pose.w,false);if(this.lighting.settings.quality==='ultra'&&f.grounded&&!f.dead&&this.actorCanvas){const c=this.ctx;c.save();c.beginPath();c.rect(f.x-90,f.y+5,180,36);c.clip();c.globalAlpha=.10;c.translate(f.x,f.y+6);c.scale(1,-.25);c.drawImage(this.actorCanvas,-280*D.SCALE,-360*D.SCALE,560*D.SCALE,560*D.SCALE);c.restore();}};
DuelRenderer.prototype.render=function(g,e,t){this.gameView=g;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches||!!this.lighting.settings.reduced;draw.call(this,g,e,t);if(this.lighting.settings.quality==='ultra'){this.post??=new DuelPostFX();this.post.draw(this);}DuelPresentation.finale(this,e);if(e.perfect>0){const c=this.ctx;c.save();c.setTransform(this.scale,0,0,this.scale,this.ox,this.oy);c.globalAlpha=Math.min(1,e.perfect*5);c.textAlign='center';c.font='bold 15px monospace';c.fillStyle='#c9f4ff';c.shadowColor='#183455';c.shadowBlur=6;c.fillText('PERFECT PARRY',640,155);c.restore();}};
window.DuelPresentation=DuelPresentation;
})();
