const fs=require('fs');let s=fs.readFileSync('work/v6/presentation.js','utf8'),a=s.indexOf(' static finale('),b=s.indexOf('\n}\nconst draw=',a);
if(a<0||b<0)throw Error('finale markers');s=s.slice(0,a)+` static finale(r,e){const p=e.preview?.animation==='finisher'?{...e.preview,age:(performance.now()-e.preview.start)/1000,finisher:true}:e.fatal;if(!p?.finisher||p.age>1.1)return;
 const c=r.ctx,age=p.age,u=D.clamp((age-.025)/.24,0,1),fade=D.clamp((1.1-age)/.5,0,1),kind=p.kind||'knight',color={knight:'#ffe3ae',lancer:'#ffcda0',assassin:'#ffd8cf',swordsman:'#cddfff',reaper:'#e3c1ff',boxer:'#bffff0'}[kind],x=D.clamp(((p.x||r.camera.x)-r.camera.x)*r.camera.zoom+640,260,1020),y=D.clamp(((p.y||r.camera.y)-r.camera.y)*r.camera.zoom+360,180,490);
 c.save();c.setTransform(r.scale,0,0,r.scale,r.ox,r.oy);c.fillStyle='#050c1d';c.globalAlpha=.18*fade;c.fillRect(0,0,1280,720);c.globalAlpha=.65*fade;c.fillRect(0,0,1280,16);c.fillRect(0,704,1280,16);c.translate(x,y);c.globalAlpha=fade;const len=(kind==='assassin'?135:kind==='swordsman'?560:kind==='lancer'?720:400)*Math.sin(u*Math.PI/2),width=kind==='assassin'?5:kind==='swordsman'?17:11;
 if(p.cause==='QUEDA'){c.strokeStyle=color;c.lineWidth=2;for(let i=0;i<5;i++){const yy=-120+u*240+i*17;c.globalAlpha=fade*(1-i*.15);c.beginPath();c.moveTo(-35+i*15,yy-70);c.lineTo(-35+i*15,yy);c.stroke();}}
 else if(kind==='reaper'){for(let i=0;i<5;i++){c.strokeStyle=i===0?'#fffaee':color;c.globalAlpha=fade*(1-i*.18);c.lineWidth=i===0?5:2;c.beginPath();c.arc(0,0,80+u*145+i*6,-2.6,-2.6+u*4.3);c.stroke();}}
 else if(kind==='boxer'){for(let i=0;i<3;i++){c.strokeStyle=i===0?'#f3fff5':color;c.globalAlpha=fade*(1-i*.3);c.lineWidth=i===0?4:1;c.beginPath();c.ellipse(0,0,25+u*(150+i*35),15+u*(85+i*22),0,0,TAU);c.stroke();}for(let i=0;i<8;i++){const angle=i*TAU/8;r.line({x:Math.cos(angle)*(35+u*80),y:Math.sin(angle)*(25+u*45)},{x:Math.cos(angle)*(55+u*180),y:Math.sin(angle)*(30+u*100)},color,1);}}
 else{c.rotate(kind==='lancer'?0:kind==='knight'?-.6:kind==='swordsman'?-.35:.3);const grad=c.createLinearGradient(-len,0,len,0);grad.addColorStop(0,color+'00');grad.addColorStop(.3,color+'b0');grad.addColorStop(.53,'#fffdf5');grad.addColorStop(1,color+'00');r.path([[-len,0],[-len*.18,-width],[len,0],[len*.12,width*.45]],grad);r.line({x:-len,y:0},{x:len,y:0},'#fff9e9',1.5);c.globalAlpha=fade*.4;for(let i=0;i<3;i++)r.line({x:-len*.7+i*12,y:width+4+i*4},{x:len*.8-i*60,y:width+4+i*4},color,1);}
 c.setTransform(r.scale,0,0,r.scale,r.ox,r.oy);c.globalAlpha=fade;c.fillStyle='#f5e1b9';c.font='11px monospace';c.textAlign='center';c.fillText(p.cause==='QUEDA'?'A ÚLTIMA QUEDA':'O ÚLTIMO CORTE',640,590);c.restore();}
`+s.slice(b);fs.writeFileSync('work/v6/presentation.js',s);
fs.appendFileSync('work/v6/v6.css','\n#title-screen,[data-cut],.cut-letter{user-select:none;-webkit-user-select:none}.admin-console.previewing,.admin-console.previewing .lab-heading strong,.admin-console.previewing .text-button{color:#284249}\n');
// Carry UI test fixes into the real network regression harness.
s=fs.readFileSync('work/v5/online-check.cjs','utf8').replaceAll('v5','v6');s=s.replace("await h.click('#rules-details summary');","await Promise.all(pages.map(p=>p.click('#title-play')));await both(()=>!duelSnapshot().titleOpen);await h.click('#rules-details summary');");
// A guest admin can preview an animation on both clients without touching a single game field.
s=s.replace("await sync();await owner.selectOption('#admin-map','bamboo');", "const frozen=await sync();await owner.click('[data-admin-preview=\"guard\"]');await both(()=>duelSnapshot().preview?.animation==='guard');let visual=await sync();A.deepEqual(visual[0].fighters,frozen[0].fighters);A.deepEqual(visual[0].metrics,frozen[0].metrics);await owner.click('[data-admin-preview=\"perfect\"]');await both(()=>duelSnapshot().preview?.animation==='perfect');await owner.click('[data-admin-preview=\"stop\"]');await both(()=>!duelSnapshot().preview);await sync();console.log('PASS synchronized ADMIN visual previews, no score/physics/stats change');await owner.selectOption('#admin-map','bamboo');");
fs.writeFileSync('work/v6/online-check.cjs',s);
