(function(){
'use strict';
const $=id=>document.getElementById(id),{Game,CLASSES,COLORS,MAPS,RULES,DEFAULT_RULES,DIFFICULTIES,neutral,cleanRules,guardSector}=DuelCore;
const canvas=$('game'),renderer=new DuelRenderer(canvas),selected={mode:'pve',difficulty:'normal',characters:['knight','lancer'],colors:['jade','coral'],mapId:'dojo',rules:cleanRules(),source:'keyboard'};
let game=new Game(selected),inMenu=true,paused=false,countdown=0,accumulator=0,last=0,clock=0,muted=false,audio=null,net=null,lobby=null,seat=0,onlineSession=null,sessionCounter=0,roomBusy=false,connectionError='',buffers=[neutral(),neutral()];
const effects={particles:[],cuts:[],shake:0,flash:0,eventText:'',eventLife:0},reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const input=new DuelControls(canvas,{onPause:()=>{if(!$('settings').open)togglePause();},onDisconnect:()=>{if(!inMenu&&(selected.mode==='local'||selected.source==='pad')){if(selected.mode!=='online'){paused=true;showPause();}else input.clear();$('pause-note').textContent='Controle desconectado. Reconecte e pressione um botão para continuar.';}}});
function unlockAudio(){try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});}catch{}}
function tone(freq,time,vol,type='sine',end){if(!audio||muted)return;const t=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(end)o.frequency.exponentialRampToValueAtTime(end,t+time);g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.0001,t+time);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+time);}
function noise(time,vol,freq){if(!audio||muted)return;const n=audio.sampleRate*time,b=audio.createBuffer(1,n,audio.sampleRate),data=b.getChannelData(0);for(let i=0;i<n;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/n,2);const s=audio.createBufferSource(),g=audio.createGain(),f=audio.createBiquadFilter();s.buffer=b;f.type='bandpass';f.frequency.value=freq;f.Q.value=.65;g.gain.value=vol;s.connect(f);f.connect(g);g.connect(audio.destination);s.start();}
function sound(type){if(type==='swing')noise(.13,.18,1800);else if(type==='dash')noise(.12,.11,550);else if(type==='jump')noise(.08,.07,420);else if(type==='parry'||type==='clash'){for(const[f,v]of[[790,.1],[1183,.075],[2111,.05],[3457,.025]])tone(f,type==='parry'?.4:.25,v);noise(.05,.13,4500);}else if(type==='kill'){tone(92,.23,.3,'sine',35);tone(176,.12,.08,'triangle',50);noise(.20,.4,1300);}else if(type==='start'||type==='round'){tone(480,.15,.04);tone(722,.3,.025);}}
function burst(x,y,count,color,power=1){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,v=(70+Math.random()*310)*power,life=.18+Math.random()*.36;effects.particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v-30,life,maxLife:life,color,size:1+Math.random()*2});}}
function resetEffects(){effects.particles=[];effects.cuts=[];effects.shake=effects.flash=effects.eventLife=0;$('round-feedback').classList.remove('visible');renderer.previousBlades=[[],[]];}
function clearInputs(){input.clear();buffers=[neutral(),neutral()];}
function ownLocked(){return!!lobby?.players[seat]?.ready;}
function configLocked(){return!!lobby&&(seat!==0||lobby.players.some(p=>p.ready));}
function validPlayer(p){return p&&!!CLASSES[p.kind]&&!!COLORS[p.color]&&typeof p.ready==='boolean';}
function ruleValue(key,value){return key==='parryWindow'?Math.round(value*150)+' ms':value.toFixed(1)+'×';}
function config(){return{mapId:selected.mapId,rules:cleanRules(selected.rules)};}
function updateControlsText(){const k=a=>input.label('keyboard',a);$('menu-controls').textContent=k('left')+' / '+k('right')+' mover · '+k('jump')+' pular · mouse mirar. '+k('attack')+' atacar · '+k('parry')+' parry · '+k('dash')+' dash.';$('dash-key').textContent=input.label(selected.source,'dash').split(' / ')[0];$('parry-key').textContent=input.label(selected.source,'parry').split(' / ')[0];}
function drawCharacters(){for(let side=0;side<2;side++){const parent=$(side?'opponent-characters':'player-characters');parent.replaceChildren();for(const[k,s]of Object.entries(CLASSES)){const b=document.createElement('button');b.className='character'+(selected.characters[side]===k?' selected':'');b.dataset.kind=k;b.setAttribute('aria-pressed',String(selected.characters[side]===k));b.setAttribute('aria-label',s.name+', '+s.description);b.disabled=ownLocked();const c=document.createElement('canvas');c.width=160;c.height=160;c.setAttribute('aria-hidden','true');const name=document.createElement('strong');name.textContent=s.name;const weapon=document.createElement('small');weapon.textContent=s.weapon;b.append(c,name,weapon);b.onclick=()=>{selected.characters[side]=k;selectionChanged();};parent.append(b);renderer.drawPortrait(c,k,side,selected.colors[side]==='random'?'coral':selected.colors[side]);}
 const colors=$(side?'opponent-colors':'player-colors');colors.replaceChildren();for(const[k,v]of Object.entries(COLORS)){const b=document.createElement('button');b.className='swatch'+(selected.colors[side]===k?' chosen':'');b.style.setProperty('--color',v.hex);b.title=v.name;b.setAttribute('aria-label',v.name);b.setAttribute('aria-pressed',String(selected.colors[side]===k));b.dataset.color=k;b.disabled=ownLocked()||(selected.mode!=='online'&&selected.colors[1-side]===k);b.onclick=()=>{selected.colors[side]=k;selectionChanged();};colors.append(b);}if(side&&selected.mode==='pve'){const b=document.createElement('button');b.className='random-color'+(selected.colors[1]==='random'?' chosen':'');b.textContent='ALEATÓRIA';b.onclick=()=>{selected.colors[1]='random';selectionChanged();};colors.append(b);}}
 $('player-description').textContent=CLASSES[selected.characters[0]].description;$('opponent-description').textContent=CLASSES[selected.characters[1]].description;$('your-color-name').textContent=COLORS[selected.colors[0]].name;$('enemy-color-name').textContent=COLORS[selected.colors[1]]?.name||'Aleatória';}
function renderMaps(){const parent=$('map-choices');parent.replaceChildren();for(const[k,m]of Object.entries(MAPS)){const b=document.createElement('button');b.className='map-choice'+(selected.mapId===k?' selected':'');b.dataset.map=k;b.dataset.theme=k;b.setAttribute('aria-pressed',String(selected.mapId===k));b.disabled=configLocked();const preview=document.createElement('span');preview.className='map-preview';const theme=DuelScenery.THEMES[k];preview.style.background='linear-gradient('+theme.sky[0]+','+theme.sky[1]+')';preview.style.setProperty('--map-edge',theme.edge);preview.style.setProperty('--map-stone',theme.surface);const orb=document.createElement('b');orb.className='map-orb';preview.append(orb);for(const p of m.platforms){const bar=document.createElement('i');bar.style.cssText='left:'+p.x/12.8+'%;top:'+(p.y-220)/5+'%;width:'+p.w/12.8+'%;height:'+(p.solid?9:4)+'px';preview.append(bar);}const title=document.createElement('strong');title.textContent=m.name;const tag=document.createElement('em');tag.textContent=theme.tag;title.append(tag);const desc=document.createElement('small');desc.textContent=m.description;b.append(preview,title,desc);b.onclick=()=>{selected.mapId=k;rulesChanged();};parent.append(b);}}
function renderRules(){
 const parent=$('rules-grid');parent.replaceChildren();
 for(const[k,r]of Object.entries(RULES)){
  const label=document.createElement('label');label.textContent=r.name;label.htmlFor='rule-'+k;const out=document.createElement('output');out.textContent=ruleValue(k,selected.rules[k]);out.id='value-'+k;
  const el=document.createElement('input');el.type='range';el.min=r.min;el.max=r.max;el.step=r.step;el.value=selected.rules[k];el.id='rule-'+k;el.disabled=configLocked();el.setAttribute('aria-valuetext',ruleValue(k,selected.rules[k]));
  el.oninput=()=>{out.textContent=ruleValue(k,+el.value);el.setAttribute('aria-valuetext',out.textContent);};el.onchange=()=>{selected.rules[k]=+el.value;rulesChanged();};label.append(out,el);parent.append(label);
 }
 const presets=$('parry-presets');presets.replaceChildren();for(const[value,name]of[[1,'Preciso'],[2,'Confortável'],[4,'Longo'],[8,'Estendido']]){const b=document.createElement('button');b.type='button';b.className='parry-preset'+(selected.rules.parryWindow===value?' selected':'');b.dataset.parry=value;b.disabled=configLocked();b.setAttribute('aria-pressed',String(selected.rules.parryWindow===value));const title=document.createElement('strong');title.textContent=name;const time=document.createElement('span');time.textContent=ruleValue('parryWindow',value);b.append(title,time);b.onclick=()=>{selected.rules.parryWindow=value;rulesChanged();};presets.append(b);}
 $('air-dash').checked=selected.rules.airDash;$('air-dash').disabled=configLocked();$('reset-rules').disabled=configLocked();const count=Object.keys(DEFAULT_RULES).filter(k=>selected.rules[k]!==DEFAULT_RULES[k]).length;$('rules-summary').textContent=(count?count+' AJUSTES':'REGRAS PADRÃO')+' · PARRY '+ruleValue('parryWindow',selected.rules.parryWindow);$('host-note').textContent=lobby?'MAPA E REGRAS DO ANFITRIÃO':'SEIS ARENAS · SEIS ATMOSFERAS';
}
function preview(){if(!inMenu)return;const colors=[...selected.colors];if(colors[1]==='random'||colors[1]===colors[0])colors[1]=Object.keys(COLORS).find(c=>c!==colors[0]);game=new Game({...selected,colors});renderer.previousBlades=[[],[]];}
function refreshMenu(){document.querySelectorAll('[data-mode]').forEach(b=>{const active=b.dataset.mode===selected.mode;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});$('input-source').value=selected.source;$('opponent-side').hidden=selected.mode==='online';$('online-side').hidden=selected.mode!=='online';$('difficulty-area').hidden=selected.mode!=='pve';$('start').hidden=selected.mode==='online';$('input-source-wrap').hidden=selected.mode==='local';$('opponent-select-label').textContent=selected.mode==='local'?'JOGADOR 2 · CONTROLE':'ADVERSÁRIO';$('player-select-label').textContent=selected.mode==='local'?'JOGADOR 1 · TECLADO + MOUSE':'SEU PERSONAGEM';$('difficulty-description').textContent=DIFFICULTIES[selected.difficulty].description;drawCharacters();renderMaps();renderRules();renderLobby();updateControlsText();preview();}
function selectionChanged(){if(lobby){const player={kind:selected.characters[0],color:selected.colors[0],ready:false};if(seat===0){lobby.players[0]=player;invalidateLobby();}else sendRequired({type:'choice',...player});}refreshMenu();}
function rulesChanged(){if(lobby&&seat===0){lobby.config=config();invalidateLobby();}refreshMenu();}
function networkStatus(text,state){$('online-status').textContent=text;$('online-status').classList.toggle('error',state==='error');if(state==='error'&&!net?.connected){roomBusy=false;$('create-room').disabled=false;$('join-room').disabled=false;$('online-actions').hidden=false;$('room-waiting').hidden=true;}}
function sendRequired(msg){if(!net?.send(msg)){returnMenu('A conexão não conseguiu confirmar a ação. Criem uma nova sala.');return false;}return true;}
function broadcastLobby(){if(net?.connected)sendRequired({type:'lobby',lobby});}
function invalidateLobby(){lobby.revision++;lobby.players.forEach(p=>p.ready=false);broadcastLobby();}
function renderLobby(){const l=lobby;$('lobby-panel').hidden=!l;if(!l)return;$('lobby-players').replaceChildren();for(let i=0;i<2;i++){const p=l.players[i],row=document.createElement('div');row.className='lobby-player';const dot=document.createElement('i');dot.style.background=COLORS[p.color].hex;const name=document.createElement('span');name.textContent=(i===seat?'VOCÊ':'OPONENTE')+' · '+CLASSES[p.kind].name;const status=document.createElement('b');status.textContent=p.ready?'PRONTO':'ESCOLHENDO';row.append(dot,name,status);$('lobby-players').append(row);}
 const conflict=l.players[0].color===l.players[1].color;$('ready-button').textContent=l.players[seat].ready?'CANCELAR PRONTO':'CONFIRMAR E FICAR PRONTO';$('ready-button').disabled=conflict;$('lobby-rules').textContent=conflict?'As cores coincidem. Um jogador precisa escolher outra.':MAPS[l.config.mapId].name+' · '+(Object.keys(RULES).filter(k=>l.config.rules[k]!==1).map(k=>RULES[k].name+' '+ruleValue(k,l.config.rules[k])).join(' · ')||'Multiplicadores padrão')+' · Dash aéreo '+(l.config.rules.airDash?'ligado':'desligado')+'. Ao ficar pronto, você confirma estas regras.';}
function disconnect(){const previous=net;net=null;lobby=null;onlineSession=null;seat=0;roomBusy=false;previous?.close();$('create-room').disabled=$('join-room').disabled=false;$('online-actions').hidden=false;$('room-waiting').hidden=true;$('lobby-panel').hidden=true;}
function returnMenu(message=''){disconnect();inMenu=true;paused=false;countdown=0;accumulator=0;clearInputs();resetEffects();$('menu').hidden=false;$('arena').classList.add('menu-open');for(const id of['hud','match-meta','menu-button','pause','match','cooldowns','cooldowns-two','countdown','connection-status'])$(id).hidden=true;$('menu-error').textContent=message;refreshMenu();networkStatus(message,message?'error':'idle');}
function showGame(){inMenu=false;paused=false;clearInputs();accumulator=0;resetEffects();$('menu').hidden=true;$('arena').classList.remove('menu-open');for(const id of['hud','match-meta','menu-button','cooldowns'])$(id).hidden=false;for(const id of['match','pause'])$(id).hidden=true;$('cooldowns-two').hidden=selected.mode!=='local';$('connection-status').hidden=selected.mode!=='online';$('left-label').textContent=selected.mode==='local'?'JOGADOR 1':seat===0?'VOCÊ':'OPONENTE';$('right-label').textContent=selected.mode==='local'?'JOGADOR 2':selected.mode==='pve'?'RIVAL':seat===1?'VOCÊ':'OPONENTE';for(let i=0;i<2;i++){$(i?'right-class':'left-class').textContent=CLASSES[game.fighters[i].kind].name;$(i?'enemy-score':'player-score').style.color=COLORS[game.colors[i]].hex;}$('match-meta').textContent=MAPS[game.mapId].name+' · '+(selected.mode==='pve'?DIFFICULTIES[selected.difficulty].name:selected.mode==='local'?'LOCAL':'SALA '+net.roomCode);$('menu-button').textContent=selected.mode==='online'?'CONTROLES':'PAUSAR';$('rematch-status').textContent='';$('restart').disabled=false;updateControlsText();canvas.focus({preventScroll:true});}
function startOffline(){unlockAudio();if((selected.mode==='local'||selected.source==='pad')&&!input.pad){$('menu-error').textContent='Conecte um controle e pressione um botão antes de começar.';return;}disconnect();const colors=[...selected.colors];if(colors[1]==='random'){const choices=Object.keys(COLORS).filter(k=>k!==colors[0]);colors[1]=choices[Math.floor(Math.random()*choices.length)];}game=new Game({...selected,colors});game.start();countdown=1;showGame();}
function showPause(){$('pause').hidden=false;$('pause-label').textContent=selected.mode==='online'?'ONLINE EM ANDAMENTO':'DUELO PAUSADO';$('pause-note').textContent=selected.mode==='online'?'Este painel não pausa o duelo online.':'Um golpe mata. Dash não dá invencibilidade.';clearInputs();}
function togglePause(){if(inMenu)return;if(game.phase==='matchEnd')return;if(!$('pause').hidden){if((selected.mode==='local'||selected.source==='pad')&&!input.pad){$('pause-note').textContent='Reconecte o controle e pressione um botão para continuar.';return;}$('pause').hidden=true;paused=false;accumulator=0;clearInputs();canvas.focus({preventScroll:true});}else{paused=selected.mode!=='online';showPause();}}
function consumeEvents(){for(const ev of game.events.splice(0)){sound(ev.type);if(ev.type==='kill'){effects.shake=reduced?0:7;effects.flash=reduced?.025:.13;effects.cuts.push({x:ev.x,y:ev.y,life:.3,maxLife:.3});burst(ev.x,ev.y,22,'#eadeba',.75);const yours=ev.winner===seat;$('round-eyebrow').textContent=ev.trade?'EMPATE':selected.mode==='local'?'PONTO DO JOGADOR '+(ev.winner+1):yours?'SEU PONTO':'PONTO DO OPONENTE';$('round-title').textContent=ev.trade?'O mesmo instante.':yours?'Um corte.':'Uma abertura.';$('round-reason').textContent=ev.reason;$('round-feedback').classList.add('visible');}
 else if(ev.type==='parry'||ev.type==='clash'){effects.shake=reduced?0:4;effects.flash=reduced?0:.025;burst(ev.x,ev.y,25,'#fff2b6');effects.eventText=ev.type==='clash'?'CLASH':'PARRY · CONTRA-ATAQUE';effects.eventLife=.45;}else if(['dash','land','jump'].includes(ev.type)){const f=game.fighters[ev.id];burst(f.x,f.y,6,'#c5b48c',.22);}else if(ev.type==='round'){clearInputs();$('round-feedback').classList.remove('visible');effects.eventLife=0;}else if(ev.type==='matchEnd'){$('round-feedback').classList.remove('visible');$('pause').hidden=true;paused=false;$('match').hidden=false;$('match-title').textContent=selected.mode==='local'?'Jogador '+(ev.winner+1)+' venceu.':ev.winner===seat?'A vitória é sua.':'O oponente levou o duelo.';$('match-score').textContent=game.score.join(' — ');clearInputs();}}}
function updateEffects(dt){effects.shake=Math.max(0,effects.shake-dt*32);effects.flash=Math.max(0,effects.flash-dt);effects.eventLife=Math.max(0,effects.eventLife-dt);for(const p of effects.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=500*dt;}effects.particles=effects.particles.filter(p=>p.life>0);for(const c of effects.cuts)c.life-=dt;effects.cuts=effects.cuts.filter(c=>c.life>0);}
function sourceFor(id){return selected.mode==='local'?(id?'pad':'keyboard'):selected.source;}
function readInput(id,consume=true){if(countdown>0||!$('pause').hidden||$('settings').open||game.phase!=='playing')return neutral();return input.read(sourceFor(id),game.fighters[id],renderer,consume);}
function simulate(inputs){for(let id=0;id<2;id++){for(const k of['move','aim','jumpHeld','down'])buffers[id][k]=inputs[id][k];for(const k of['attack','parry','dash','jump'])buffers[id][k]||=inputs[id][k];}for(let sub=0;sub<10;sub++){const frozen=game.hitstop>0;game.step(1/600,buffers);if(!frozen)for(const b of buffers)b.attack=b.parry=b.dash=b.jump=false;}consumeEvents();}
function seeded(seed){let s=seed>>>0;return()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296;};}
function validInput(v){return v&&Number.isFinite(v.move)&&Math.abs(v.move)<=1&&Number.isFinite(v.aim)&&Math.abs(v.aim)<=Math.PI+.001&&['attack','parry','dash','jump','jumpHeld','down'].every(k=>typeof v[k]==='boolean');}
function validConfig(c){return c&&!!MAPS[c.mapId]&&c.rules&&typeof c.rules.airDash==='boolean'&&Object.keys(RULES).every(k=>Number.isFinite(c.rules[k])&&c.rules[k]>=RULES[k].min&&c.rules[k]<=RULES[k].max);}
function initSession(packet){if(!net?.connected||!packet||typeof packet.id!=='string'||packet.id.length>90||!Number.isInteger(packet.seed)||packet.delay!==6||!Array.isArray(packet.characters)||packet.characters.length!==2||packet.characters.some(k=>!CLASSES[k])||!Array.isArray(packet.colors)||packet.colors.length!==2||packet.colors.some(k=>!COLORS[k])||packet.colors[0]===packet.colors[1]||!validConfig(packet))return false;
 onlineSession={id:packet.id,frame:0,delay:6,local:new Map(),remote:new Map(),sampled:5,started:false,createdAt:performance.now(),stalledAt:0,hashes:new Map(),remoteHashes:new Map(),votes:[false,false],packet};for(let f=0;f<6;f++){onlineSession.local.set(f,neutral());onlineSession.remote.set(f,neutral());}game=new Game({...packet,mode:'online',ai:false,random:seeded(packet.seed)});game.start();countdown=2;showGame();return true;}
function hostNewMatch(){if(!net?.connected||net.role!=='host'||!lobby)return;const seed=new Uint32Array(1);crypto.getRandomValues(seed);const p={type:'start',id:net.roomCode+'-'+(++sessionCounter)+'-'+seed[0],seed:seed[0],characters:lobby.players.map(p=>p.kind),colors:lobby.players.map(p=>p.color),...lobby.config,delay:6};if(initSession(p))sendRequired(p);}
function stateHash(){const q=n=>Math.round(n*1e5);return JSON.stringify([game.phase,game.round,game.score,q(game.time),q(game.hitstop),q(game.roundTimer),q(game.fallTimer),game.fighters.map(f=>[f.kind,q(f.x),q(f.y),q(f.vx),q(f.vy),q(f.aim),f.state,q(f.stateTime),f.dead,f.facing,q(f.duration),f.attackId,f.attackHit,q(f.attackAim),f.grounded,f.airUsed,f.guard,f.guardFacing,q(f.dashX),q(f.dashY),q(f.dashCooldown),q(f.parryCooldown),q(f.dropTimer),q(f.coyote),q(f.jumpBuffer),f.jumping])]);}
function checkHash(f){const s=onlineSession;if(s?.hashes.has(f)&&s.remoteHashes.has(f)){if(s.hashes.get(f)!==s.remoteHashes.get(f))returnMenu('O duelo perdeu a sincronização. Criem uma nova sala.');else{s.hashes.delete(f);s.remoteHashes.delete(f);}}}
function onNetworkMessage(msg){if(!net?.connected||!msg)return;
 if(msg.type==='lobby'&&seat===1&&inMenu){const l=msg.lobby;if(!l||!Number.isInteger(l.revision)||!Array.isArray(l.players)||l.players.length!==2||!l.players.every(validPlayer)||!validConfig(l.config))return;const first=!lobby;lobby=l;selected.mapId=l.config.mapId;selected.rules=cleanRules(l.config.rules);if(first){sendRequired({type:'choice',kind:selected.characters[0],color:selected.colors[0],ready:false});}else{selected.characters[0]=l.players[1].kind;selected.colors[0]=l.players[1].color;}refreshMenu();return;}
 if(msg.type==='choice'&&seat===0&&lobby&&inMenu&&CLASSES[msg.kind]&&COLORS[msg.color]&&!lobby.players[1].ready){lobby.players[1]={kind:msg.kind,color:msg.color,ready:false};invalidateLobby();refreshMenu();return;}
 if(msg.type==='lobbyReady'&&seat===0&&inMenu&&lobby&&msg.revision===lobby.revision&&typeof msg.ready==='boolean'&&lobby.players[0].color!==lobby.players[1].color){lobby.players[1].ready=msg.ready;broadcastLobby();refreshMenu();if(lobby?.players.every(p=>p.ready))hostNewMatch();return;}
 if(msg.type==='start'&&seat===1){const configMatches=lobby&&JSON.stringify(msg.characters)===JSON.stringify(lobby.players.map(p=>p.kind))&&JSON.stringify(msg.colors)===JSON.stringify(lobby.players.map(p=>p.color))&&msg.mapId===lobby.config.mapId&&JSON.stringify(msg.rules)===JSON.stringify(lobby.config.rules);if(!configMatches||(!inMenu&&!(game.phase==='matchEnd'&&onlineSession?.votes.every(Boolean)))){returnMenu('Configuração alterada sem confirmação. Reabram a sala.');return;}if(!initSession(msg))returnMenu('V3 incompatível. Usem o mesmo arquivo do jogo.');else sendRequired({type:'ready',id:msg.id});return;}
 const s=onlineSession;if(!s||msg.id!==s.id)return;
 if(msg.type==='ready'&&seat===0&&!s.started){if(sendRequired({type:'go',id:s.id}))s.started=true;return;}if(msg.type==='go'&&seat===1){s.started=true;return;}
 if(msg.type==='input'){if(!Number.isInteger(msg.frame)||msg.frame<s.frame||msg.frame>s.frame+180||!validInput(msg.input))return;if(!s.remote.has(msg.frame))s.remote.set(msg.frame,msg.input);return;}
 if(msg.type==='hash'&&Number.isInteger(msg.frame)&&typeof msg.hash==='string'&&msg.hash.length<1800){if(msg.frame>s.frame-120&&msg.frame<s.frame+120){s.remoteHashes.set(msg.frame,msg.hash);checkHash(msg.frame);}return;}
 if(msg.type==='rematch'&&game.phase==='matchEnd'){s.votes[1-seat]=true;$('rematch-status').textContent='O oponente pediu revanche. Confirme para jogar novamente.';if(seat===0&&s.votes.every(Boolean))hostNewMatch();}
}
function onlineTick(dt){const s=onlineSession;if(!s||!net?.connected)return;if(!s.started){if(performance.now()-s.createdAt>12000)returnMenu('O início do duelo não foi confirmado. Criem outra sala.');return;}if(s.stalledAt&&performance.now()-s.stalledAt>10000){returnMenu('Sem novos comandos por 10 segundos. Mantenham as duas abas visíveis e criem outra sala.');return;}accumulator=Math.min(accumulator+dt,.1);let steps=0;while(accumulator>=1/60&&steps++<6){if(s.sampled<s.frame+s.delay){const target=s.frame+s.delay,command=readInput(seat,false);if(!net.send({type:'input',id:s.id,frame:target,input:command})){if(!s.stalledAt)s.stalledAt=performance.now();accumulator=Math.min(accumulator,.025);break;}input.consume(sourceFor(seat));s.local.set(target,command);s.sampled=target;}
 if(!s.local.has(s.frame)||!s.remote.has(s.frame)){if(!s.stalledAt)s.stalledAt=performance.now();accumulator=Math.min(accumulator,.025);break;}s.stalledAt=0;const commands=seat===0?[s.local.get(s.frame),s.remote.get(s.frame)]:[s.remote.get(s.frame),s.local.get(s.frame)];s.local.delete(s.frame);s.remote.delete(s.frame);countdown=Math.max(0,(120-s.frame)/60);if(!countdown)simulate(commands);s.frame++;accumulator-=1/60;if(s.frame%60===0){s.hashes.set(s.frame,stateHash());net.send({type:'hash',id:s.id,frame:s.frame,hash:s.hashes.get(s.frame)});checkHash(s.frame);for(const m of[s.hashes,s.remoteHashes])for(const f of m.keys())if(f<s.frame-120)m.delete(f);if(onlineSession!==s)return;}}
}
function createTransport(){disconnect();connectionError='';net=new DuelOnline({onStatus:networkStatus,onConnected(info){seat=info.seat;roomBusy=true;$('online-actions').hidden=true;$('room-waiting').hidden=false;$('room-display').textContent=net.roomCode;if(seat===0){lobby={revision:1,players:[{kind:selected.characters[0],color:selected.colors[0],ready:false},{kind:net.remoteCharacter,color:'coral',ready:false}],config:config()};broadcastLobby();refreshMenu();}networkStatus('Conectado. Escolham as cores e confirmem as regras.','connected');},onMessage:onNetworkMessage,onDisconnected(reason){connectionError=reason;returnMenu(reason);}});return net;}
async function createRoom(){unlockAudio();const n=createTransport();roomBusy=true;$('create-room').disabled=$('join-room').disabled=true;$('online-actions').hidden=true;$('room-waiting').hidden=false;$('room-display').textContent='······';try{const code=await n.createRoom(selected.characters[0]);if(net===n)$('room-display').textContent=code;}catch(e){if(net===n)networkStatus(e.message,'error');}}
async function joinRoom(){unlockAudio();const value=$('room-code').value,n=createTransport();roomBusy=true;$('create-room').disabled=$('join-room').disabled=true;try{await n.joinRoom(value,selected.characters[0]);}catch(e){if(net===n)networkStatus(e.message,'error');}}
function ready(){if(!lobby||lobby.players[0].color===lobby.players[1].color)return;if(seat===0){lobby.players[0].ready=!lobby.players[0].ready;broadcastLobby();refreshMenu();if(lobby?.players.every(p=>p.ready))hostNewMatch();}else sendRequired({type:'lobbyReady',revision:lobby.revision,ready:!lobby.players[1].ready});}
function requestRematch(){if(selected.mode!=='online'){startOffline();return;}if(!onlineSession||!net?.connected)return;if(!sendRequired({type:'rematch',id:onlineSession.id}))return;onlineSession.votes[seat]=true;$('restart').disabled=true;$('rematch-status').textContent='Aguardando o oponente confirmar…';if(seat===0&&onlineSession.votes.every(Boolean))hostNewMatch();}
function renderBindings(){const parent=$('bindings');parent.replaceChildren();for(const[a,name]of Object.entries(DuelControls.ACTIONS)){const row=document.createElement('div');row.className='binding-row';const label=document.createElement('span');label.textContent=name;row.append(label);for(const device of['keyboard','pad']){const b=document.createElement('button');b.className='secondary';b.dataset.action=a;b.dataset.device=device;b.textContent=input.label(device,a);b.onclick=()=>{input.beginCapture(device,a);$('binding-status').textContent='“'+name+'”: pressione '+(device==='pad'?'um botão do controle.':'uma tecla ou botão do mouse.');};row.append(b);}parent.append(row);}for(const key of['deadzone','sensitivity']){$(key).value=input.settings[key];$(key+'-value').textContent=input.settings[key].toFixed(2);}$('stick-layout').value=input.settings.moveAxis;}
function openSettings(){if(!inMenu&&selected.mode!=='online'){paused=true;showPause();}clearInputs();renderBindings();$('settings').showModal();}
input.onCapture=message=>{$('binding-status').textContent=message;renderBindings();updateControlsText();};
function frame(ms){const dt=Math.min((ms-(last||ms))/1000,.06);last=ms;input.enabled=!inMenu&&!$('settings').open;input.poll(dt);if(!paused&&game.hitstop<=0)clock+=dt;if(!inMenu&&!paused){if(selected.mode==='online')onlineTick(dt);else if(countdown>0){countdown=Math.max(0,countdown-dt);input.clear();}else{accumulator=Math.min(accumulator+dt,.08);while(accumulator>=1/60){simulate([readInput(0),selected.mode==='local'?readInput(1):neutral()]);accumulator-=1/60;}}updateEffects(dt);}renderer.render(game,effects,clock);
 $('player-score').textContent=game.score[0];$('enemy-score').textContent=game.score[1];for(const[id,suffix]of[[selected.mode==='online'?seat:0,''],[1,'-two']]){const f=game.fighters[id],s=DuelCore.stats(f);$('dash-fill'+suffix).style.transform='scaleX('+Math.max(0,1-f.dashCooldown/(s.dashCooldown*game.rules.dashCooldown))+')';$('parry-fill'+suffix).style.transform='scaleX('+Math.max(0,1-f.parryCooldown/(s.parry*game.rules.parryWindow+s.parryRecovery*game.rules.parryRecovery))+')';}const f=game.fighters[seat],g=guardSector(f.aim,f.grounded);$('guard-hint').textContent=g==='high'?'↑ ALTO':g==='low'?'↓ BAIXO':'↔ NORMAL';$('combat-event').textContent=effects.eventText;$('combat-event').classList.toggle('visible',effects.eventLife>0&&game.phase==='playing');$('countdown').hidden=inMenu||countdown<=0;$('countdown').textContent=countdown>1?String(Math.ceil(countdown)):'Em guarda';
 $('controller-status').textContent=input.pad?'Controle conectado · '+(input.pad.mapping==='standard'?'padrão reconhecido':'mapeie os botões em Controles'):(selected.mode==='local'||selected.source==='pad'?'Conecte um controle e pressione um botão.':'Controle opcional: conecte e pressione um botão.');if(selected.mode==='online'&&!inMenu){const stalled=onlineSession?.stalledAt&&performance.now()-onlineSession.stalledAt>250,ping=net?.latency;$('connection-status').textContent=stalled?'Aguardando oponente · mantenha a aba visível':(ping===null?'Sincronizando':ping+' ms')+' · '+(selected.source==='pad'&&!input.pad?'CONTROLE DESCONECTADO':'conexão direta');$('connection-status').classList.toggle('warning',!!stalled||ping>180);}requestAnimationFrame(frame);
}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{disconnect();selected.mode=b.dataset.mode;if(selected.mode!=='pve'&&selected.colors[1]==='random')selected.colors[1]=Object.keys(COLORS).find(k=>k!==selected.colors[0]);if(selected.mode==='local')selected.source='keyboard';$('menu-error').textContent='';refreshMenu();});$('difficulty').onchange=()=>{selected.difficulty=$('difficulty').value;refreshMenu();};$('air-dash').onchange=()=>{selected.rules.airDash=$('air-dash').checked;rulesChanged();};$('reset-rules').onclick=()=>{selected.rules=cleanRules();rulesChanged();};$('input-source').onchange=()=>{selected.source=$('input-source').value;input.padAim=seat?Math.PI:0;updateControlsText();};$('start').onclick=startOffline;$('restart').onclick=requestRematch;$('menu-button').onclick=togglePause;$('resume').onclick=togglePause;for(const id of['match-menu','pause-menu'])$(id).onclick=()=>returnMenu();$('create-room').onclick=createRoom;$('join-room').onclick=joinRoom;$('cancel-room').onclick=()=>{disconnect();refreshMenu();networkStatus('Sala encerrada.','idle');};$('ready-button').onclick=ready;$('room-code').onkeydown=e=>{if(e.key==='Enter')joinRoom();};$('copy-room').onclick=async()=>{try{await navigator.clipboard.writeText(net.roomCode);networkStatus('Código copiado. Envie ao seu amigo.','waiting');}catch{networkStatus('Selecione e copie o código acima.','waiting');}};
for(const id of['settings-button','pause-settings'])$(id).onclick=openSettings;$('close-settings').onclick=()=>{$('settings').close();input.capture=null;clearInputs();};$('settings').addEventListener('cancel',()=>{input.capture=null;clearInputs();});$('cancel-binding').onclick=()=>{input.capture=null;$('binding-status').textContent='Mapeamento cancelado.';};$('reset-controls').onclick=()=>{input.reset();renderBindings();updateControlsText();$('binding-status').textContent='Controles padrão restaurados.';};for(const key of['deadzone','sensitivity'])$(key).oninput=()=>{input.settings[key]=+$(key).value;input.save();$(key+'-value').textContent=input.settings[key].toFixed(2);};$('stick-layout').onchange=()=>{input.settings.moveAxis=+$('stick-layout').value;input.settings.aimAxis=input.settings.moveAxis===0?2:0;input.save();};$('sound').onclick=()=>{muted=!muted;unlockAudio();$('sound-state').textContent=muted?'OFF':'ON';$('sound').setAttribute('aria-pressed',String(!muted));};window.addEventListener('pointerdown',unlockAudio,{once:true});window.addEventListener('keydown',unlockAudio,{once:true});function lostFocus(){clearInputs();if(!inMenu&&selected.mode!=='online'&&game.phase!=='matchEnd'){paused=true;showPause();}}window.addEventListener('blur',lostFocus);document.addEventListener('visibilitychange',()=>{if(document.hidden)lostFocus();});window.addEventListener('pagehide',()=>net?.close());
window.duelSnapshot=()=>({version:3,release:'3.1',mode:selected.mode,difficulty:selected.difficulty,inMenu,paused,countdown,phase:game.phase,round:game.round,score:[...game.score],mapId:game.mapId,rules:{...game.rules},camera:{...renderer.camera},fighters:game.fighters.map(f=>({...f})),habits:{...game.habits},lobby:lobby?JSON.parse(JSON.stringify(lobby)):null,controller:!!input.pad,online:{connected:!!net?.connected,room:net?.roomCode||'',seat,frame:onlineSession?.frame||0,latency:net?.latency??null,error:connectionError},reason:game.lastReason});$('download').href=location.href;returnMenu();requestAnimationFrame(frame);
})();
