(function(){
'use strict';
const {clamp,lerp,COLORS,blade,stats}=DuelCore,TAU=Math.PI*2;
class DuelRenderer{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.camera={x:640,y:360,zoom:1};this.previousBlades=[[],[]];this.lastRound=0;this.lastTime=0;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;}
 resize(){const b=this.canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.round(b.width*d),h=Math.round(b.height*d);if(w!==this.canvas.width||h!==this.canvas.height){this.canvas.width=w;this.canvas.height=h;}this.scale=Math.min(w/1280,h/720);this.ox=(w-1280*this.scale)/2;this.oy=(h-720*this.scale)/2;this.dpr=d;}
 screenToWorld(x,y){const r=this.canvas.getBoundingClientRect();return{x:((x-r.left)*this.dpr-this.ox)/this.scale/this.camera.zoom+this.camera.x-640/this.camera.zoom,y:((y-r.top)*this.dpr-this.oy)/this.scale/this.camera.zoom+this.camera.y-360/this.camera.zoom};}
 line(a,b,color,width=1){const c=this.ctx;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.strokeStyle=color;c.lineWidth=width;c.stroke();}
 path(pts,fill,stroke,width=1){const c=this.ctx;c.beginPath();pts.forEach((p,i)=>i?c.lineTo(p[0],p[1]):c.moveTo(p[0],p[1]));if(fill){c.closePath();c.fillStyle=fill;c.fill();}if(stroke){c.strokeStyle=stroke;c.lineWidth=width;c.stroke();}}
 ellipse(x,y,rx,ry,color){const c=this.ctx;c.beginPath();c.ellipse(x,y,Math.max(.1,rx),Math.max(.1,ry),0,0,TAU);c.fillStyle=color;c.fill();}
 background(game,t){DuelScenery.draw(this,game,t);}
 platforms(game,t){DuelScenery.platforms(this,game,t);}
 fighter(f,time,w,portrait=false){const c=this.ctx,ink='#263a33',color=COLORS[f.color]?.hex||'#367f75',side=f.facing,bob=f.grounded&&Math.abs(f.vx)<20?Math.sin(time*2.8+f.id)*1.5:0,run=clamp(Math.abs(f.vx)/stats(f).speed,0,1),air=!f.grounded,lean=clamp(f.vx/47,-12,12)+(f.state==='active'?Math.sin(f.stateTime/f.duration*Math.PI)*f.facing*6:0),squat=(f.landing>0?Math.sin(f.landing/.15*Math.PI)*7:0)+(f.state==='dash'?10:0);
  c.save();if(DuelScenery.THEMES[this.lastTheme]?.dark&&!portrait){c.shadowColor='#c3ded088';c.shadowBlur=1.5;}if(f.dead){const p=clamp(f.deathTime/.5,0,1);c.translate(f.x+side*p*12,f.y);c.rotate(side*p*1.48);c.translate(-f.x,-f.y);c.globalAlpha=1-p*.3;}
  if(f.state==='dash'&&!this.reduced){for(let i=3;i>=1;i--){c.globalAlpha=.05+(4-i)*.025;this.path([[f.x-f.dashX*i*19-15,f.y-f.dashY*i*19-110],[f.x-f.dashX*i*19+15,f.y-f.dashY*i*19-110],[f.x-f.dashX*i*19+22,f.y-f.dashY*i*19-31],[f.x-f.dashX*i*19-20,f.y-f.dashY*i*19-31]],color);}c.globalAlpha=1;}
  if(f.grounded)this.ellipse(f.x,f.y+3,29,4,'#213f3326');const hip={x:f.x+lean*.6,y:f.y-46+squat},shoulder={x:f.x+lean,y:f.y-96+bob+squat},head={x:shoulder.x+side*2,y:shoulder.y-25},swing=Math.sin(f.anim),lift=Math.cos(f.anim),back=-side;
  const feet=air?[{x:f.x-15+clamp(f.vx/30,-9,9),y:f.y-13-clamp(-f.vy/30,0,16)},{x:f.x+16,y:f.y-6-clamp(f.vy/35,0,14)}]:[{x:f.x+swing*22*run-8,y:f.y-Math.max(0,lift)*10*run},{x:f.x-swing*22*run+8,y:f.y-Math.max(0,-lift)*10*run}];const cape=f.kind==='assassin'?56:f.kind==='reaper'?45:34,flutter=Math.sin(time*8+f.x*.02)*(3+run*3);
  this.path([[shoulder.x-back*3,shoulder.y-1],[shoulder.x+back*17,shoulder.y+4],[hip.x+back*(cape+run*19)+flutter,hip.y+13],[hip.x+back*12,hip.y-1]],color);this.path([[shoulder.x+back*9,shoulder.y+13],[hip.x+back*(cape*.6)+flutter,hip.y+4],[hip.x+back*6,hip.y-3]],'#263c343d');
  c.lineCap='round';for(let i=0;i<2;i++){const knee={x:lerp(hip.x,feet[i].x,.5)+(air?side*(i?13:-8):-side*3),y:lerp(hip.y,feet[i].y,.55)-squat};this.line(hip,knee,ink,13);this.line(knee,feet[i],ink,11);this.line({x:feet[i].x-4,y:feet[i].y},{x:feet[i].x+side*9,y:feet[i].y},ink,7);if(f.kind!=='assassin')this.line(knee,{x:lerp(knee.x,feet[i].x,.7),y:lerp(knee.y,feet[i].y,.7)},'#647065',5);}
  this.path([[shoulder.x-16,shoulder.y],[shoulder.x+16,shoulder.y],[hip.x+15,hip.y+6],[hip.x-15,hip.y+6]],ink);this.path([[shoulder.x-12,shoulder.y+4],[shoulder.x+12,shoulder.y+4],[hip.x+11,hip.y-3],[hip.x-11,hip.y-3]],color);
  if(f.kind==='knight'||f.kind==='swordsman'){this.path([[shoulder.x-10,shoulder.y+5],[shoulder.x+11,shoulder.y+6],[hip.x+9,hip.y-13],[hip.x,hip.y-7],[hip.x-10,hip.y-13]],'#9ca596');this.line({x:shoulder.x,y:shoulder.y+8},{x:hip.x,y:hip.y-14},'#c6cabb',2);this.ellipse(shoulder.x-side*13,shoulder.y+6,10,8,ink);this.ellipse(shoulder.x-side*13,shoulder.y+4,9,5,'#8b998e');}
  this.line({x:hip.x-14,y:hip.y-7},{x:hip.x+14,y:hip.y-7},'#dcc49a',4);const hand=w.hand,elbow={x:lerp(shoulder.x,hand.x,.5)-side*9,y:lerp(shoulder.y+8,hand.y,.5)+10};this.line({x:shoulder.x+side*9,y:shoulder.y+10},elbow,ink,12);this.line(elbow,hand,ink,10);this.line(elbow,{x:lerp(elbow.x,hand.x,.75),y:lerp(elbow.y,hand.y,.75)},color,6);this.ellipse(hand.x,hand.y,5,5,'#d3b590');
  if(['lancer','swordsman','reaper'].includes(f.kind)){const h={x:hand.x-Math.cos(w.angle)*16,y:hand.y-Math.sin(w.angle)*16},el={x:shoulder.x-side*18,y:shoulder.y+28};this.line({x:shoulder.x-side*10,y:shoulder.y+7},el,ink,9);this.line(el,h,ink,8);this.ellipse(h.x,h.y,4,4,'#d3b590');}
  this.line({x:shoulder.x,y:shoulder.y+3},{x:head.x,y:head.y+9},ink,10);this.ellipse(head.x,head.y,12,14,ink);if(f.kind==='knight'||f.kind==='swordsman'){this.path([[head.x-13,head.y-8],[head.x-7,head.y-17],[head.x+8,head.y-17],[head.x+14,head.y-6],[head.x+11,head.y+8],[head.x-12,head.y+8]],'#8e9d90');this.line({x:head.x+side*2,y:head.y-2},{x:head.x+side*12,y:head.y-2},ink,3);this.path([[head.x-4,head.y-17],[head.x+side*4,head.y-27],[head.x-side*17,head.y-21],[head.x-side*14,head.y-14]],color);}else if(f.kind==='assassin'||f.kind==='reaper'){this.path([[head.x-14,head.y+9],[head.x-12,head.y-12],[head.x+side*4,head.y-21],[head.x+14,head.y-8],[head.x+12,head.y+11]],color);this.line({x:head.x+side*1,y:head.y-1},{x:head.x+side*11,y:head.y-1},'#ecd7aa',3);this.line({x:head.x,y:head.y+4},{x:head.x+side*11,y:head.y+4},ink,6);}else{this.ellipse(head.x+side*4,head.y,9,11,'#c5ab85');this.path([[head.x-16,head.y-8],[head.x,head.y-20],[head.x+17,head.y-8]],ink);this.line({x:head.x-side*12,y:head.y-7},{x:head.x-side*28+flutter,y:head.y-2},color,4);}
  if(f.state==='startup'){const a=f.attackAim;this.line({x:f.x+Math.cos(a)*34,y:f.y-79+Math.sin(a)*34},{x:f.x+Math.cos(a)*48,y:f.y-79+Math.sin(a)*48},'#fff2c4',2.5);}if(f.state==='stunned'){c.strokeStyle='#e2b463';c.lineWidth=2;c.beginPath();c.ellipse(head.x,head.y-30,17,5,Math.sin(time*16)*.2,0,TAU);c.stroke();}c.restore();if(!f.dead&&!portrait){c.globalAlpha=.55;this.ellipse(f.x+Math.cos(f.aim)*53,f.y-79+Math.sin(f.aim)*53,2.2,2.2,color);c.globalAlpha=1;}
 }
 sword(f,w,t,portrait=false){DuelWeapons.draw(this,f,w,t,portrait);}
 render(game,effects,t){if(this.lastTheme!==game.mapId){this.lastTheme=game.mapId;if(this.canvas.parentElement){this.canvas.parentElement.dataset.theme=game.mapId;this.canvas.parentElement.classList.toggle('dark-arena',!!DuelScenery.THEMES[game.mapId]?.dark);}}this.resize();const c=this.ctx,dt=clamp(t-this.lastTime,0,.05);this.lastTime=t;if(this.lastRound!==game.round){this.previousBlades=[[],[]];this.lastRound=game.round;}const alive=game.fighters.filter(f=>!f.dead),fs=alive.length?alive:game.fighters,minX=Math.min(...fs.map(f=>f.x))-210,maxX=Math.max(...fs.map(f=>f.x))+210,minY=Math.min(...fs.map(f=>f.y))-235,maxY=Math.max(...fs.map(f=>f.y))+95,z=game.phase==='title'?1:clamp(Math.min(1280/(maxX-minX),720/(maxY-minY)),.5,1.12),tx=z<=1?640:clamp((minX+maxX)/2,640/z,1280-640/z),ty=Math.min(440,(minY+maxY)/2),smooth=1-Math.exp(-dt*5);this.camera.zoom=lerp(this.camera.zoom,z,smooth);this.camera.x=lerp(this.camera.x,tx,smooth);this.camera.y=lerp(this.camera.y,ty,smooth);
  c.setTransform(1,0,0,1,0,0);c.fillStyle='#d7ceba';c.fillRect(0,0,this.canvas.width,this.canvas.height);c.setTransform(this.scale,0,0,this.scale,this.ox,this.oy);this.background(game,t);c.save();c.beginPath();c.rect(0,0,1280,720);c.clip();const shake=this.reduced?0:effects.shake||0;c.translate(640+(Math.random()-.5)*shake,360+(Math.random()-.5)*shake);c.scale(this.camera.zoom,this.camera.zoom);c.translate(-this.camera.x,-this.camera.y);this.platforms(game,t);for(const f of game.fighters){if(!f.grounded&&!f.dead){const surfaces=game.map.platforms.filter(p=>p.y>=f.y&&f.x>=p.x&&f.x<=p.x+p.w).sort((a,b)=>a.y-b.y);if(surfaces.length){const ground=surfaces[0],height=ground.y-f.y;this.ellipse(f.x,ground.y+3,Math.max(9,27-height*.035),3,'#213f331d');}}const w=blade(f);this.fighter(f,t,w);this.sword(f,w,t);}for(const p of effects.particles||[]){c.globalAlpha=p.life/p.maxLife;this.line({x:p.x-p.vx*.015,y:p.y-p.vy*.015},p,p.color,p.size);}c.globalAlpha=1;for(const cut of effects.cuts||[]){c.globalAlpha=cut.life/cut.maxLife;this.line({x:cut.x-90,y:cut.y+60},{x:cut.x+90,y:cut.y-60},'#fff5d6',3);}c.globalAlpha=1;c.restore();if(effects.flash){c.fillStyle='#fff2d6';c.globalAlpha=Math.min(.4,effects.flash*2.5);c.fillRect(0,0,1280,720);c.globalAlpha=1;}}
 drawPortrait(canvas,kind,side=0,color){const old=this.ctx;this.ctx=canvas.getContext('2d');const c=this.ctx;c.clearRect(0,0,canvas.width,canvas.height);c.save();const f={id:side,kind,color:color||'jade',x:0,y:0,vx:0,vy:0,aim:-1.1,facing:1,attackAim:0,state:'idle',stateTime:0,duration:0,grounded:true,anim:0,landing:0,dead:false};const w=blade(f),pts=[{x:-65,y:-152},{x:35,y:7},...w.segments.flatMap(s=>[s.a,s.b]),...(w.shaft?[w.shaft.a,w.shaft.b]:[])],minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxY=Math.max(...pts.map(p=>p.y)),scale=Math.min((canvas.width-10)/(maxX-minX),(canvas.height-10)/(maxY-minY));c.translate(canvas.width/2-(minX+maxX)/2*scale,canvas.height-5-maxY*scale);c.scale(scale,scale);this.fighter(f,0,w,true);this.sword(f,w,0,true);c.restore();this.ctx=old;}
}
window.DuelRenderer=DuelRenderer;
})();
