(function () {
  'use strict';
  const $ = id => document.getElementById(id);
  const {Game, C, CLASSES, DIFFICULTIES} = DuelCore;
  const canvas=$('game'), renderer=new DuelRenderer(canvas);
  let game=new Game({mode:'pve',characters:['knight','lancer']});
  const selected={mode:'pve',difficulty:'normal',characters:['knight','lancer']};
  const keys=new Set(), freshInput=()=>({move:0,attack:false,parry:false,dash:false});
  let pending=[freshInput(),freshInput()], paused=false, inMenu=true, countdown=0, accumulator=0,last=0,clock=0;
  let muted=false,audio=null,net=null,roomBusy=false,seat=0,onlineSession=null,connectionError='',sessionCounter=0;
  const effects={particles:[],cuts:[],shake:0,flash:0,hitstop:0,eventText:'',eventLife:0};
  const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const weaponNames={knight:'ESPADA',lancer:'LANÇA',assassin:'ADAGA'};
  const difficultyText={easy:'Mais hesitação e erros. Tempo para aprender a distância.',normal:'Reações humanas, variação e punições por erros.',adaptive:'Aprende seus hábitos durante a partida e muda as decisões.',impossible:'Reflexos sobre-humanos e punição precisa. Mesmas armas e um golpe para morrer.'};

  function unlockAudio(){try{if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});}catch{}}
  function tone(freq,time,volume,type='sine',endFreq=0){if(!audio||muted)return;const t=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(endFreq)o.frequency.exponentialRampToValueAtTime(endFreq,t+time);g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.0001,t+time);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+time);}
  function noise(time,volume,frequency){if(!audio||muted)return;const n=audio.sampleRate*time,b=audio.createBuffer(1,n,audio.sampleRate),data=b.getChannelData(0);for(let i=0;i<n;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/n,2);const src=audio.createBufferSource(),g=audio.createGain(),f=audio.createBiquadFilter();src.buffer=b;f.type='bandpass';f.frequency.value=frequency;f.Q.value=.65;g.gain.value=volume;src.connect(f);f.connect(g);g.connect(audio.destination);src.start();}
  function sound(type){if(type==='swing')noise(.16,.18,1800);else if(type==='dash')noise(.12,.12,550);else if(type==='parry'||type==='clash'){for(const [f,v]of [[790,.12],[1183,.08],[2111,.055],[3457,.027]])tone(f,type==='parry'?.42:.26,v);noise(.06,.15,4500);}else if(type==='kill'){tone(92,.23,.32,'sine',35);tone(176,.12,.08,'triangle',50);noise(.22,.43,1300);}else if(type==='start'||type==='round'){tone(480,.15,.045);tone(722,.3,.028);}}
  function burst(x,y,count,color,power=1){for(let i=0;i<count;i++){const angle=Math.random()*Math.PI*2,speed=(70+Math.random()*310)*power,life=.18+Math.random()*.38;effects.particles.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed-30,life,maxLife:life,color,size:1+Math.random()*2});}}
  function clearInputs(){keys.clear();pending=[freshInput(),freshInput()];}
  function resetEffects(){effects.particles=[];effects.cuts=[];effects.shake=effects.flash=effects.eventLife=0;$('combat-event').classList.remove('visible');$('round-feedback').classList.remove('visible');}
  function characterName(kind){return CLASSES[kind]?.name||kind;}
  function controlsText(){return selected.mode==='local'?'P1 · A/D mover · F atacar · G parry · H dash\nP2 · ←/→ mover · J atacar · K parry · L dash':'A/D ou ←/→ mover · J ou clique esquerdo atacar\nK ou clique direito parry · Shift dash';}
  function updateControls(){const lines=controlsText().split('\n');$('menu-controls').textContent=lines.join('  |  ');$('footer-controls').textContent=inMenu?'UM GOLPE LIMPO. NENHUMA BARRA DE VIDA.':lines.join('   /   ');$('controls').replaceChildren(...lines.map(line=>{const el=document.createElement('div');el.textContent=line;return el;}));$('dash-key').textContent=selected.mode==='local'?'H':'SHIFT';$('parry-key').textContent=selected.mode==='local'?'G':'K';}
  function drawCharacters(){for(let side=0;side<2;side++){const parent=$(side?'opponent-characters':'player-characters');parent.replaceChildren();for(const kind of ['knight','lancer','assassin']){const button=document.createElement('button');button.type='button';button.className='character'+(selected.characters[side]===kind?' selected':'');button.dataset.kind=kind;button.setAttribute('aria-pressed',String(selected.characters[side]===kind));button.setAttribute('aria-label',characterName(kind)+', '+CLASSES[kind].description);button.disabled=roomBusy;const portrait=document.createElement('canvas');portrait.width=130;portrait.height=150;portrait.setAttribute('aria-hidden','true');const name=document.createElement('strong');name.textContent=characterName(kind);const weapon=document.createElement('small');weapon.textContent=weaponNames[kind];button.append(portrait,name,weapon);button.addEventListener('click',()=>{selected.characters[side]=kind;refreshMenu();});parent.append(button);renderer.drawPortrait(portrait,kind,side);}}
    $('player-description').textContent=CLASSES[selected.characters[0]].description;$('opponent-description').textContent=CLASSES[selected.characters[1]].description;
  }
  function refreshMenu(){
    document.querySelectorAll('[data-mode]').forEach(b=>{const active=b.dataset.mode===selected.mode;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});
    $('opponent-side').hidden=selected.mode==='online';$('online-side').hidden=selected.mode!=='online';$('difficulty-area').hidden=selected.mode!=='pve';$('start').hidden=selected.mode==='online';$('difficulty-description').textContent=difficultyText[selected.difficulty];$('opponent-select-label').textContent=selected.mode==='local'?'JOGADOR 2':'ADVERSÁRIO';$('player-select-label').textContent=selected.mode==='local'?'JOGADOR 1':'SEU PERSONAGEM';drawCharacters();updateControls();
    if(inMenu){game=new Game({mode:selected.mode,difficulty:selected.difficulty,characters:[...selected.characters]});renderer.previousBlades=[[],[]];}
  }
  function setBusy(value){roomBusy=value;$('create-room').disabled=value;$('join-room').disabled=value;$('room-code').disabled=value;document.querySelectorAll('#player-characters button').forEach(b=>b.disabled=value);}
  function networkStatus(text,state){$('online-status').textContent=text;$('online-status').classList.toggle('error',state==='error');if(state==='error'){setBusy(false);$('online-actions').hidden=false;$('room-waiting').hidden=true;}}
  function disconnect(showMessage=false){const previous=net;net=null;onlineSession=null;roomBusy=false;seat=0;if(previous)previous.close();setBusy(false);$('online-actions').hidden=false;$('room-waiting').hidden=true;$('connection-status').hidden=true;if(showMessage)networkStatus('Sala encerrada. Você pode criar outra.', 'idle');}
  function returnMenu(message=''){disconnect(false);inMenu=true;paused=false;countdown=0;accumulator=0;clearInputs();resetEffects();$('menu').hidden=false;$('arena').classList.add('menu-open');for(const id of ['hud','match-meta','menu-button','pause','match','cooldowns','cooldowns-two','countdown'])$(id).hidden=true;refreshMenu();if(message)networkStatus(message,'error');else $('online-status').textContent='';}
  function showGame(){inMenu=false;paused=false;clearInputs();accumulator=0;resetEffects();$('menu').hidden=true;$('arena').classList.remove('menu-open');$('hud').hidden=false;$('match-meta').hidden=false;$('menu-button').hidden=false;$('match').hidden=true;$('pause').hidden=true;$('cooldowns').hidden=false;$('cooldowns-two').hidden=selected.mode!=='local';$('connection-status').hidden=selected.mode!=='online';$('left-label').textContent=selected.mode==='local'?'JOGADOR 1':seat===0?'VOCÊ':'OPONENTE';$('right-label').textContent=selected.mode==='local'?'JOGADOR 2':selected.mode==='pve'?'RIVAL':seat===1?'VOCÊ':'OPONENTE';$('left-class').textContent=characterName(game.fighters[0].kind);$('right-class').textContent=characterName(game.fighters[1].kind);$('match-meta').textContent=selected.mode==='pve'?'PvE · '+(DIFFICULTIES[selected.difficulty]?.name||selected.difficulty):selected.mode==='local'?'LOCAL · 1 × 1':'ONLINE · '+(net?.roomCode||'');$('rematch-status').textContent='';$('restart').disabled=false;updateControls();canvas.focus({preventScroll:true});}
  function startOffline(){unlockAudio();disconnect();game=new Game({mode:selected.mode,difficulty:selected.difficulty,characters:[...selected.characters]});game.start();countdown=.85;showGame();}
  function togglePause(){if(inMenu){$('pause').hidden=!$('pause').hidden;$('pause-label').textContent='CONTROLES';$('resume').textContent='VOLTAR';$('pause-menu').hidden=true;$('online-pause-note').hidden=true;updateControls();return;}if(game.phase==='matchEnd')return;clearInputs();const opened=!$('pause').hidden;$('pause').hidden=opened;$('pause-label').textContent=selected.mode==='online'?'CONTROLES · PARTIDA EM ANDAMENTO':'DUELO PAUSADO';$('resume').textContent='VOLTAR AO DUELO';$('pause-menu').hidden=false;$('online-pause-note').hidden=selected.mode!=='online';paused=selected.mode==='online'?false:!opened;accumulator=0;if(!opened)$('resume').focus({preventScroll:true});else canvas.focus({preventScroll:true});}

  function consumeEvents(){
    for(const ev of game.events.splice(0)){sound(ev.type);
      if(ev.type==='kill'){effects.shake=reducedMotion?0:7;effects.flash=reducedMotion?.05:.16;effects.cuts.push({x:ev.x,y:ev.y,life:.35,maxLife:.35,angle:-.5});burst(ev.x,ev.y,22,'#eadeba',.75);burst(ev.x,ev.y,10,'#4b5147',.5);const yours=ev.winner===seat;$('round-eyebrow').textContent=ev.trade?'EMPATE':selected.mode==='local'?'PONTO DO JOGADOR '+(ev.winner+1):yours?'SEU PONTO':'PONTO DO OPONENTE';$('round-title').textContent=ev.trade?'O mesmo instante.':yours?'Um corte.':'Uma abertura.';$('round-reason').textContent=ev.reason;$('round-feedback').classList.add('visible');$('accessible-status').textContent=ev.reason+' Placar '+game.score.join(' a ');}
      else if(ev.type==='parry'||ev.type==='clash'){effects.shake=reducedMotion?0:ev.type==='parry'?4:3;effects.flash=reducedMotion?0:.035;burst(ev.x,ev.y,ev.type==='parry'?28:21,'#fff2b6');effects.eventText=ev.type==='clash'?'CLASH':selected.mode==='local'?'PARRY · JOGADOR '+(ev.id+1):ev.id===seat?'PARRY · CONTRA-ATAQUE':'PARRY DO OPONENTE';effects.eventLife=.5;}
      else if(ev.type==='dash'){const f=game.fighters[ev.id];burst(f.x,555,6,'#b7a27d',.25);}
      else if(ev.type==='round'){pending=[freshInput(),freshInput()];$('round-feedback').classList.remove('visible');effects.eventLife=0;}
      else if(ev.type==='matchEnd'){$('round-feedback').classList.remove('visible');$('pause').hidden=true;paused=false;$('match').hidden=false;$('match-title').textContent=selected.mode==='local'?'Jogador '+(ev.winner+1)+' venceu.':ev.winner===seat?'A vitória é sua.':'O oponente levou o duelo.';$('match-score').textContent=game.score.join(' — ');clearInputs();}
    }
  }
  function updateEffects(dt){effects.shake=Math.max(0,effects.shake-dt*32);effects.flash=Math.max(0,effects.flash-dt);effects.eventLife=Math.max(0,effects.eventLife-dt);for(const p of effects.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=500*dt;p.vx*=Math.pow(.96,dt*60);}effects.particles=effects.particles.filter(p=>p.life>0);for(const c of effects.cuts)c.life-=dt;effects.cuts=effects.cuts.filter(c=>c.life>0);effects.hitstop=game.hitstop;}
  function movement(id){if(selected.mode==='local')return id===0?(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0):(keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0);return(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0);}
  function readInput(id,consume=true){const result={...pending[id],move:movement(id)};if(consume)pending[id]=freshInput();if(countdown>0||!$('pause').hidden||game.phase!=='playing')return freshInput();return result;}

  // Online uses deterministic lockstep. Both PCs resolve the same two input frames;
  // when a frame is missing, both wait instead of disagreeing about a lethal contact.
  // Inputs are scheduled six frames ahead (~100 ms) to absorb ordinary network jitter.
  function seeded(seed){let s=seed>>>0;return()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296;};}
  function validInput(v){return v&&[-1,0,1].includes(v.move)&&['attack','parry','dash'].every(k=>typeof v[k]==='boolean');}
  function initSession(packet){
    if(!packet||typeof packet.id!=='string'||packet.id.length>90||!Array.isArray(packet.characters)||packet.characters.length!==2||packet.characters.some(k=>!CLASSES[k])||!Number.isInteger(packet.seed)||packet.delay!==6)return false;
    const role=net?.role;if(!role)return false;
    onlineSession={id:packet.id,frame:0,delay:6,local:new Map(),remote:new Map(),sampled:5,ready:false,started:false,createdAt:performance.now(),stalledAt:0,hashes:new Map(),remoteHashes:new Map(),votes:[false,false],buffers:[freshInput(),freshInput()]};
    for(let f=0;f<6;f++){onlineSession.local.set(f,freshInput());onlineSession.remote.set(f,freshInput());}
    game=new Game({mode:'online',ai:false,characters:packet.characters,random:seeded(packet.seed)});game.start();countdown=2;showGame();return true;
  }
  function hostNewMatch(){if(!net?.connected||net.role!=='host')return;const value=new Uint32Array(1);crypto.getRandomValues(value);const packet={type:'start',id:net.roomCode+'-'+(++sessionCounter)+'-'+value[0],seed:value[0],characters:[net.character,net.remoteCharacter],delay:6};initSession(packet);if(!net.send(packet))returnMenu('A conexão não conseguiu preparar o duelo. Criem uma nova sala.');}
  function stateHash(){const q=n=>Math.round(n*1e5);return JSON.stringify([game.phase,game.round,game.score,q(game.time),q(game.hitstop),q(game.roundTimer),game.fighters.map(f=>[f.kind,q(f.x),f.state,q(f.stateTime),f.dead,f.facing,q(f.duration),f.attackId,f.attackHit,f.dashDir,q(f.dashCooldown),q(f.parryCooldown)])]);}
  function checkHash(f){const s=onlineSession;if(s?.hashes.has(f)&&s.remoteHashes.has(f)){if(s.hashes.get(f)!==s.remoteHashes.get(f))returnMenu('A partida perdeu a sincronização. Nenhum resultado foi imposto. Criem uma nova sala.');else{s.hashes.delete(f);s.remoteHashes.delete(f);}}}
  function onNetworkMessage(msg){
    if(!net?.connected||!msg||typeof msg.type!=='string')return;
    if(msg.type==='start'&&net.role==='guest'){if(!initSession(msg))returnMenu('Configuração de duelo incompatível. Reabram a mesma versão.');else if(!net.send({type:'ready',id:msg.id}))returnMenu('A conexão não conseguiu confirmar o duelo. Criem uma nova sala.');return;}
    const s=onlineSession;if(!s||msg.id!==s.id)return;
    if(msg.type==='ready'&&net.role==='host'&&!s.started){if(!net.send({type:'go',id:s.id})){returnMenu('A conexão não conseguiu iniciar o duelo. Criem uma nova sala.');return;}s.ready=true;s.started=true;return;}
    if(msg.type==='go'&&net.role==='guest'){s.ready=true;s.started=true;return;}
    if(msg.type==='input'){if(!Number.isInteger(msg.frame)||msg.frame<s.frame||msg.frame>s.frame+180||!validInput(msg.input))return;if(!s.remote.has(msg.frame))s.remote.set(msg.frame,msg.input);return;}
    if(msg.type==='hash'&&Number.isInteger(msg.frame)&&typeof msg.hash==='string'&&msg.hash.length<1000){if(msg.frame>s.frame-120&&msg.frame<s.frame+120){s.remoteHashes.set(msg.frame,msg.hash);checkHash(msg.frame);}return;}
    if(msg.type==='rematch'&&game.phase==='matchEnd'){s.votes[1-seat]=true;$('rematch-status').textContent='O oponente pediu revanche. Confirme para jogar novamente.';if(net.role==='host'&&s.votes.every(Boolean))hostNewMatch();}
  }
  function onlineTick(dt){const s=onlineSession;if(!s||!net?.connected)return;if(!s.started){if(performance.now()-s.createdAt>12000)returnMenu('O início do duelo não foi confirmado. Criem uma nova sala.');return;}if(s.stalledAt&&performance.now()-s.stalledAt>10000){returnMenu('A partida ficou sem novos comandos por 10 segundos. Mantenham as duas abas visíveis e criem outra sala.');return;}accumulator=Math.min(accumulator+dt,.10);let steps=0;
    while(accumulator>=1/60&&steps++<6){
      if(s.sampled<s.frame+s.delay){const target=s.frame+s.delay;const input=readInput(seat,false);if(!net.send({type:'input',id:s.id,frame:target,input})){if(!s.stalledAt)s.stalledAt=performance.now();accumulator=Math.min(accumulator,.025);break;}pending[seat]=freshInput();s.local.set(target,input);s.sampled=target;}
      if(!s.local.has(s.frame)||!s.remote.has(s.frame)){if(!s.stalledAt)s.stalledAt=performance.now();accumulator=Math.min(accumulator,.025);break;}
      s.stalledAt=0;const inputs=seat===0?[s.local.get(s.frame),s.remote.get(s.frame)]:[s.remote.get(s.frame),s.local.get(s.frame)];s.local.delete(s.frame);s.remote.delete(s.frame);
      countdown=Math.max(0,(120-s.frame)/60);
      if(countdown===0){for(let id=0;id<2;id++){s.buffers[id].move=inputs[id].move;for(const key of ['attack','parry','dash'])s.buffers[id][key]||=inputs[id][key];}for(let sub=0;sub<10;sub++){const frozen=game.hitstop>0;game.step(1/600,s.buffers);if(!frozen)for(const b of s.buffers)b.attack=b.parry=b.dash=false;}consumeEvents();}
      s.frame++;accumulator-=1/60;
      if(s.frame%60===0){const hash=stateHash();s.hashes.set(s.frame,hash);net.send({type:'hash',id:s.id,frame:s.frame,hash});checkHash(s.frame);for(const map of [s.hashes,s.remoteHashes])for(const f of map.keys())if(f<s.frame-120)map.delete(f);if(onlineSession!==s)return;}
    }
  }
  function createTransport(){disconnect();connectionError='';net=new DuelOnline({onStatus:networkStatus,onConnected(info){seat=info.seat;setBusy(true);if(info.role==='host')hostNewMatch();else networkStatus('Conectado. Preparando duelo…','connected');},onMessage:onNetworkMessage,onDisconnected(reason){connectionError=reason;returnMenu(reason);}});return net;}
  async function createRoom(){unlockAudio();const n=createTransport();setBusy(true);$('online-actions').hidden=true;$('room-waiting').hidden=false;$('room-display').textContent='······';try{const code=await n.createRoom(selected.characters[0]);if(net===n)$('room-display').textContent=code;}catch(e){if(net===n){networkStatus(e.message,'error');setBusy(false);}}}
  async function joinRoom(){unlockAudio();const value=$('room-code').value;const n=createTransport();setBusy(true);try{await n.joinRoom(value,selected.characters[0]);}catch(e){if(net===n){networkStatus(e.message,'error');setBusy(false);}}}
  function requestRematch(){if(selected.mode!=='online'){startOffline();return;}if(!net?.connected||!onlineSession)return;if(!net.send({type:'rematch',id:onlineSession.id})){$('rematch-status').textContent='A conexão está ocupada. Clique novamente para confirmar a revanche.';return;}onlineSession.votes[seat]=true;$('restart').disabled=true;$('rematch-status').textContent='Aguardando o oponente confirmar a revanche…';if(net.role==='host'&&onlineSession.votes.every(Boolean))hostNewMatch();}

  function frame(ms){const dt=Math.min((ms-(last||ms))/1000,.06);last=ms;if(!paused&&game.hitstop<=0)clock+=dt;
    if(!inMenu&&!paused){if(selected.mode==='online')onlineTick(dt);else if(countdown>0){countdown=Math.max(0,countdown-dt);clearInputs();}else{accumulator=Math.min(accumulator+dt,.08);while(accumulator>=1/600){const frozen=game.hitstop>0;game.step(1/600,[readInput(0,!frozen),readInput(1,!frozen)]);accumulator-=1/600;consumeEvents();}}updateEffects(dt);}
    renderer.render(game,effects,clock);
    $('player-score').textContent=game.score[0];$('enemy-score').textContent=game.score[1];
    for(const [id,suffix]of [[selected.mode==='online'?seat:0,''],[1,'-two']]){const f=game.fighters[id],st=DuelCore.stats(f);$('dash-fill'+suffix).style.transform='scaleX('+Math.max(0,1-f.dashCooldown/st.dashCooldown)+')';$('parry-fill'+suffix).style.transform='scaleX('+Math.max(0,1-f.parryCooldown/st.parryCooldown)+')';}
    $('combat-event').textContent=effects.eventText;$('combat-event').classList.toggle('visible',effects.eventLife>0&&game.phase==='playing');$('countdown').hidden=inMenu||countdown<=0;$('countdown').textContent=countdown>1?String(Math.ceil(countdown)):'Em guarda';
    if(selected.mode==='online'&&!inMenu){const stalled=onlineSession?.stalledAt&&performance.now()-onlineSession.stalledAt>250;const ping=net?.latency;$('connection-status').textContent=stalled?'Aguardando o oponente · mantenham a aba visível':ping===null?'Conexão direta · sincronizando':'Conexão direta · '+ping+' ms'+(ping>180?' · conexão lenta':'');$('connection-status').classList.toggle('warning',!!stalled||ping>180);}
    requestAnimationFrame(frame);
  }

  const recognized=new Set(['KeyA','KeyD','ArrowLeft','ArrowRight','KeyF','KeyG','KeyH','KeyJ','KeyK','KeyL','ShiftLeft','ShiftRight','Escape','Enter','KeyM']);
  window.addEventListener('keydown',ev=>{if(ev.target instanceof HTMLInputElement||ev.target instanceof HTMLSelectElement||ev.ctrlKey||ev.altKey||ev.metaKey||!recognized.has(ev.code))return;if(ev.code==='Enter'&&ev.target instanceof HTMLButtonElement)return;ev.preventDefault();if(ev.repeat)return;unlockAudio();if(ev.code==='KeyM'){$('sound').click();return;}if(ev.code==='Escape'){togglePause();return;}if(ev.code==='Enter'){if(game.phase==='matchEnd'&&!inMenu)requestRematch();else if(inMenu&&selected.mode!=='online')startOffline();else if(!$('pause').hidden)togglePause();return;}if(inMenu||paused||!$('pause').hidden||countdown>0||game.phase!=='playing')return;keys.add(ev.code);if(selected.mode==='local'){if(ev.code==='KeyF')pending[0].attack=true;if(ev.code==='KeyG')pending[0].parry=true;if(ev.code==='KeyH')pending[0].dash=true;if(ev.code==='KeyJ')pending[1].attack=true;if(ev.code==='KeyK')pending[1].parry=true;if(ev.code==='KeyL')pending[1].dash=true;}else{if(ev.code==='KeyJ')pending[seat].attack=true;if(ev.code==='KeyK')pending[seat].parry=true;if(ev.code.startsWith('Shift'))pending[seat].dash=true;}});
  window.addEventListener('keyup',ev=>keys.delete(ev.code));canvas.addEventListener('contextmenu',ev=>ev.preventDefault());canvas.addEventListener('pointerdown',ev=>{ev.preventDefault();unlockAudio();canvas.focus({preventScroll:true});if(inMenu||paused||countdown>0||selected.mode==='local'||game.phase!=='playing')return;if(ev.button===0)pending[seat].attack=true;if(ev.button===2)pending[seat].parry=true;});
  function lostFocus(){clearInputs();if(!inMenu&&selected.mode!=='online'&&!paused&&game.phase!=='matchEnd'&&$('pause').hidden)togglePause();}window.addEventListener('blur',lostFocus);document.addEventListener('visibilitychange',()=>{if(document.hidden)lostFocus();});window.addEventListener('pagehide',()=>net?.close());
  document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{disconnect();selected.mode=b.dataset.mode;refreshMenu();$('online-status').textContent='';}));$('difficulty').addEventListener('change',()=>{selected.difficulty=$('difficulty').value;refreshMenu();});$('start').addEventListener('click',startOffline);$('restart').addEventListener('click',requestRematch);$('resume').addEventListener('click',togglePause);$('help').addEventListener('click',togglePause);for(const id of ['menu-button','match-menu','pause-menu'])$(id).addEventListener('click',()=>returnMenu());$('create-room').addEventListener('click',createRoom);$('join-room').addEventListener('click',joinRoom);$('cancel-room').addEventListener('click',()=>disconnect(true));$('room-code').addEventListener('keydown',e=>{if(e.key==='Enter')joinRoom();});$('copy-room').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(net.roomCode);networkStatus('Código copiado. Envie ao seu amigo.','waiting');}catch{networkStatus('Selecione e copie o código mostrado acima.','waiting');}});$('sound').addEventListener('click',()=>{muted=!muted;unlockAudio();$('sound-state').textContent=muted?'OFF':'ON';$('sound').setAttribute('aria-pressed',String(!muted));});
  window.duelSnapshot=()=>({version:2,mode:selected.mode,difficulty:selected.difficulty,inMenu,paused,countdown,phase:game.phase,round:game.round,score:[...game.score],fighters:game.fighters.map(f=>({kind:f.kind,x:f.x,state:f.state,dead:f.dead,dashCooldown:f.dashCooldown,parryCooldown:f.parryCooldown})),online:{connected:!!net?.connected,room:net?.roomCode||'',seat,frame:onlineSession?.frame||0,latency:net?.latency??null,error:connectionError},reason:game.lastReason});
  $('download').href=location.href;
  returnMenu();requestAnimationFrame(frame);
})();
