const {chromium}=require('C:/Users/Luiz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {pathToFileURL}=require('node:url'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--allow-file-access-from-files']});try{
 const page=await browser.newPage({viewport:{width:1366,height:850}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(__dirname,'../../outputs/um-corte-v2.html')).href);await page.waitForFunction(()=>typeof duelSnapshot==='function');
 await page.screenshot({path:path.join(__dirname,'menu.png')});
 assert.equal(await page.locator('#player-characters button').count(),3);assert.equal(await page.locator('#opponent-characters button').count(),3);
 for(const difficulty of ['easy','normal','adaptive','impossible']){await page.locator('#difficulty').selectOption(difficulty);assert.equal((await page.evaluate(()=>duelSnapshot())).difficulty,difficulty);}
 await page.locator('#difficulty').selectOption('easy');await page.locator('#player-characters [data-kind="assassin"]').click();await page.locator('#opponent-characters [data-kind="lancer"]').click();await page.locator('#start').click();await page.waitForFunction(()=>duelSnapshot().countdown===0);
 assert.deepEqual((await page.evaluate(()=>duelSnapshot())).fighters.map(f=>f.kind),['assassin','lancer']);await page.keyboard.down('KeyD');await page.waitForTimeout(300);await page.keyboard.up('KeyD');assert.ok((await page.evaluate(()=>duelSnapshot())).fighters[0].x>475);
 await page.keyboard.press('KeyJ');await page.waitForFunction(()=>duelSnapshot().fighters[0].state==='startup');await page.screenshot({path:path.join(__dirname,'pve.png')});
 await page.keyboard.press('Escape');assert.equal((await page.evaluate(()=>duelSnapshot())).paused,true);let snap=await page.evaluate(()=>duelSnapshot());await page.waitForTimeout(200);assert.deepEqual(await page.evaluate(()=>duelSnapshot()),snap);await page.locator('#resume').click();
 await page.locator('#menu-button').click();await page.locator('[data-mode="local"]').click();await page.locator('#player-characters [data-kind="knight"]').click();await page.locator('#opponent-characters [data-kind="assassin"]').click();await page.locator('#start').click();await page.waitForFunction(()=>duelSnapshot().countdown===0);
 await page.keyboard.down('KeyD');await page.keyboard.down('ArrowLeft');await page.waitForTimeout(300);await page.keyboard.up('KeyD');await page.keyboard.up('ArrowLeft');snap=await page.evaluate(()=>duelSnapshot());assert.ok(snap.fighters[0].x>470);assert.ok(snap.fighters[1].x<800);
 await page.keyboard.press('KeyF');await page.waitForFunction(()=>duelSnapshot().fighters[0].state==='startup');await page.keyboard.press('KeyK');await page.waitForFunction(()=>duelSnapshot().fighters[1].state==='parry');await page.screenshot({path:path.join(__dirname,'local.png')});await page.waitForTimeout(900);
 await page.keyboard.press('KeyL');await page.waitForFunction(()=>duelSnapshot().fighters[1].dashCooldown>0);await page.locator('#menu-button').click();await page.locator('[data-mode="online"]').click();await page.screenshot({path:path.join(__dirname,'online-menu.png')});await page.locator('#room-code').fill('bad');await page.locator('#join-room').click();await page.waitForFunction(()=>document.getElementById('online-status').classList.contains('error'));
 assert.equal((await page.evaluate(()=>duelSnapshot())).inMenu,true);await page.locator('[data-mode="pve"]').click();await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(__dirname,'mobile.png')});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);console.log('PASS UI: class selections, four difficulties, PvE movement/attack/pause, local independent keys/actions, online form and validation, narrow layout.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
