'use strict';
const assert=require('node:assert/strict');
const {Game,C,CLASSES,DIFFICULTIES,blade,stats,segmentDistance}=require('./engine.js');
const DT=1/600;let passed=0;
function test(name,fn){try{fn();passed++;console.log('PASS '+name);}catch(e){console.error('FAIL '+name);throw e;}}
function seeded(seed=12345){return()=>{seed=(Math.imul(1664525,seed)+1013904223)>>>0;return seed/4294967296;};}
function game(options={}){const g=new Game({mode:'local',random:seeded(),...options});g.start();g.events=[];return g;}
function run(g,seconds,input){for(let i=0;i<Math.ceil(seconds/DT);i++)g.step(DT,typeof input==='function'?input(i*DT):input||[{},{}]);}
function position(g,d){g.fighters[0].x=450;g.fighters[1].x=450+d;}
function active(g,id,progress=.60){const f=g.fighters[id];g.setState(f,'active',stats(f).active);f.stateTime=f.duration*progress;f.attackHit=false;}

test('three classes retain one-hit rules without health',()=>{assert.deepEqual(Object.keys(CLASSES),['knight','lancer','assassin']);for(const kind of Object.keys(CLASSES)){const g=game({characters:[kind,'knight']});position(g,{knight:120,lancer:195,assassin:75}[kind]);assert.equal('hp'in g.fighters[0],false);g.attack(0);run(g,.6);assert.equal(g.fighters[1].dead,true,kind);assert.deepEqual(g.score,[1,0]);}});
test('all nine weapon pairings can score a clean one-hit kill',()=>{for(const a of Object.keys(CLASSES))for(const b of Object.keys(CLASSES)){const g=game({characters:[a,b]});position(g,{knight:120,lancer:195,assassin:75}[a]);g.attack(0);run(g,.6);assert.equal(g.fighters[1].dead,true,a+' vs '+b);}});
test('local players have independent movement and action input',()=>{const g=game();g.step(DT,[{move:1},{move:-1}]);assert(g.fighters[0].x>436);assert(g.fighters[1].x<844);g.step(DT,[{attack:true},{parry:true}]);assert.equal(g.fighters[0].state,'startup');assert.equal(g.fighters[1].state,'parry');assert.equal(g.aiEnabled,false);});
test('player two can attack and win',()=>{const g=game({characters:['knight','assassin']});position(g,75);g.step(DT,[{},{attack:true}]);run(g,.4);assert.equal(g.fighters[0].dead,true);assert.deepEqual(g.score,[0,1]);});
test('legacy object input stays supported',()=>{const g=game();g.step(DT,{move:1,enemyMove:-1});assert(g.fighters[0].x>436);assert(g.fighters[1].x<844);});
test('startup and recovery prevent attack spam',()=>{const g=game();assert(g.attack(0));assert.equal(g.attack(0),false);run(g,.12);assert.equal(g.fighters[0].state,'startup');assert.equal(g.bodyContact(g.fighters[0],g.fighters[1]),false);run(g,.25);assert.equal(g.fighters[0].state,'recovery');assert.equal(g.attack(0),false);run(g,.4);assert.equal(g.attack(0),true);});
test('blade segment is finite: a distant opponent is safe',()=>{for(const kind of Object.keys(CLASSES)){const g=game({characters:[kind,'knight']});position(g,CLASSES[kind].reach+35);g.attack(0);run(g,.8);assert.equal(g.fighters[1].dead,false);assert.equal(g.habits.whiffs,1);}});
test('lance shaft has a genuine nonlethal close-range zone',()=>{const g=game({characters:['lancer','assassin']});position(g,75);g.attack(0);run(g,.72);assert.equal(g.fighters[1].dead,false);const b=blade(g.fighters[0]);assert(b.shaft);assert(Math.hypot(b.b.x-b.a.x,b.b.y-b.a.y)<40);});
test('parry interrupts attacker and permits a counterattack',()=>{const g=game();position(g,120);g.attack(0);run(g,.20);g.parry(1);run(g,.2);assert.equal(g.fighters[0].state,'stunned');assert.equal(g.fighters[1].dead,false);assert(g.events.some(e=>e.type==='parry'));assert(g.attack(1));run(g,.45);assert.equal(g.fighters[0].dead,true);assert.deepEqual(g.score,[0,1]);});
test('early parry leaves a punishable recovery',()=>{const g=game();position(g,120);g.parry(1);run(g,.2);assert.equal(g.fighters[1].state,'parryRecovery');g.attack(0);run(g,.35);assert.equal(g.fighters[1].dead,true);assert(g.lastReason.includes('Parry cedo'));});
test('parry has cooldown even after a successful block',()=>{const g=game();position(g,120);g.attack(0);run(g,.2);g.parry(1);run(g,.15);assert.equal(g.fighters[1].state,'idle');assert.equal(g.parry(1),false);});
test('simultaneous blade collision causes clash without a point',()=>{const g=game();position(g,200);g.step(DT,[{attack:true},{attack:true}]);run(g,.4);assert(g.events.some(e=>e.type==='clash'));assert.deepEqual(g.score,[0,0]);assert(g.fighters.every(f=>!f.dead));});
test('dash has no invincibility and bodies cannot cross',()=>{const g=game();position(g,120);active(g,0);g.dash(1,-1);g.resolveCombat();assert.equal(g.fighters[1].dead,true);const h=game();position(h,60);h.step(DT,[{dash:true,move:1},{dash:true,move:-1}]);run(h,.15);assert(h.fighters[1].x-h.fighters[0].x>=40-1e-6);assert.equal(h.dash(0),false);});
test('assassin movement is faster and lance recovery is longer',()=>{assert(CLASSES.assassin.speed>CLASSES.knight.speed);assert(CLASSES.knight.speed>CLASSES.lancer.speed);assert(CLASSES.lancer.recovery>CLASSES.knight.recovery);assert(CLASSES.assassin.startup<CLASSES.knight.startup);});
test('rounds restart and first to five ends the match',()=>{const g=game();for(let n=0;n<5;n++){g.defeat(g.fighters[1],g.fighters[0]);run(g,1.25);assert.equal(g.score[0],n+1);if(n<4){assert.equal(g.phase,'playing');assert(g.fighters.every(f=>!f.dead));}}assert.equal(g.phase,'matchEnd');g.start();assert.deepEqual(g.score,[0,0]);assert.equal(g.phase,'playing');});
test('snapshot serialization preserves online state and event payloads',()=>{const host=game({mode:'online',characters:['assassin','lancer']});run(host,.12,[{move:1},{move:-1}]);host.attack(1);const snapshot=JSON.parse(JSON.stringify(host.snapshot()));const guest=new Game();assert(guest.loadSnapshot(snapshot));assert.deepEqual(guest.snapshot(),snapshot);snapshot.fighters[0].x=0;assert.notEqual(guest.fighters[0].x,0);});
test('online deterministic copies resolve the same actions',()=>{const host=game({mode:'online',characters:['knight','lancer']});position(host,195);const guest=new Game();guest.loadSnapshot(JSON.parse(JSON.stringify(host.snapshot())));for(let i=0;i<500;i++){const inp=[{move:i<80?1:0,attack:i===90},{parry:i===210}];host.step(DT,inp);guest.step(DT,inp);}assert.deepEqual(host.snapshot(),guest.snapshot());});
test('adaptive mode learns attack and parry habits, resetting per match',()=>{const g=game({mode:'pve',difficulty:'adaptive'}),base=g.getAIPolicy();g.habits.attacks=12;g.habits.whiffs=8;const attacks=g.getAIPolicy();assert(attacks.parryChance>base.parryChance);assert(attacks.punishChance>base.punishChance);g.habits.attacks=0;g.habits.parries=12;assert(g.getAIPolicy().baitChance>base.baitChance);g.resetFighters();assert.equal(g.habits.parries,12);g.start();assert.equal(g.getAIPolicy().learned,false);});
test('impossible defends a visible close attack that easy misses',()=>{for(const difficulty of ['easy','impossible']){const g=game({mode:'pve',difficulty,random:()=>.5});position(g,120);g.ai.timer=100;g.ai.attackDelay=100;g.attack(0);run(g,.45);if(difficulty==='easy')assert(g.fighters[1].dead);else{assert.equal(g.fighters[1].dead,false);assert(g.events.some(e=>e.type==='parry'));}}});
test('difficulty does not alter weapons, damage, or cooldown durations',()=>{for(const difficulty of Object.keys(DIFFICULTIES)){const g=game({difficulty,characters:['lancer','assassin']});g.attack(0);assert.equal(g.fighters[0].duration,CLASSES.lancer.startup);g.dash(1);assert.equal(g.fighters[1].duration,CLASSES.assassin.dash);assert.equal(g.fighters[1].dashCooldown,CLASSES.assassin.dashCooldown);}});
test('PvE class and difficulty combinations finish rounds without invalid positions',()=>{for(const difficulty of Object.keys(DIFFICULTIES))for(const kind of Object.keys(CLASSES)){const g=game({mode:'pve',difficulty,characters:['knight',kind],random:seeded(41)});for(let i=0;i<600*35&&g.score[0]+g.score[1]===0;i++){g.step(DT,[{move:1,attack:i%380===0},{}]);for(const f of g.fighters)assert(Number.isFinite(f.x));}assert(g.score[0]+g.score[1]>0,difficulty+' '+kind);}});
console.log('\n'+passed+' engine tests passed.');
